---
output:
  html_document: default
  word_document: default
---
# Часть 1. Социальный маятник {-#chapter-1}

> И все, что я любил – я любил в одиночестве.
>
> --- Эдгар Аллан По

## 1{-#1} 

Забывшись тревожным сном, – антибиотики и неудавшаяся ночь давали о себе знать сильнее чем следовало – Элеонора невнятно выругалась и отвернулась к стене, однако мучения не прекращались, и вскоре девушка осознала, что толчки, которые её подсознание поначалу сочло результатом дуэта местных дорог и старого поезда, оказались всего лишь попытками её разбудить. Всё ещё не открывая глаз, девушка зевнула и потянулась (насколько это позволяли сделать убогие габариты спальной полки). Чьи-то пальцы упрямо продолжали сжимать её плечо и в итоге Нора сдалась.

Обернувшись, она увидела лупоглазое, испещрённое угрями лицо, что расположилось в пугающей близости, и инстинктивно подалась назад, от чего её голова тут же поцеловала вешалку для полотенец. Пожилая проводница сделала шаг назад и, теперь стояла со сложенными на груди руками вполне довольная проделанной работой.

– Як си кунялося? [^1]

Элеоноре, потирающей ушибленный затылок, понадобилось какое-то время, дабы понять, о чем её спрашивают. В итоге, девушка неуверенно заметила:

– Поезд всю ночь трясло.

Проводница угрюмо качнула головой.

– Ниська має бути файна штрика. [^2]

Нора медленно кивнула, не имея ни малейшего понятия о том, что бы это могло значить.

– Вы не подскажите, через скольк...

Где-то в другом конце вагона раздался звук бьющегося стекла, и голова женщины тут же исчезла в дверном проёме.

– Гузиця![^3]  – заявила она с таким видом, словно это слово многое объясняло, а затем уже более рассержено: – А шляк бы трафыв эту фіндюр...[^4] 

Конец фразы затерялся, так как проводница уже мельтешила по коридору, оставляя за собой шлейф неведомых ругательств. Нора, которая до этого утра думала, что владеет украинским в совершенстве, взглянула на часы. До момента прибытия оставалось ещё около двух часов.

За это время словарный запас нашей героини успешно дополнили ярчайшие образчики местного фольклора. Такие как *лайдак*, *шмаркатий*, *чмурик*, *алік*, *харлак*, *йолупега*, *гамазей*, а также особенно полюбившееся Элеоноре словечко, которое едва ли имело отношение к колоритной брани, но звучало гордо и неоднозначно – *нацицюрник*. 

– И на кой чёрт было будить меня в такую рань?

По ту сторону двери раздались шаги и мгновение спустя, похерив правила приличия, на пороге вновь объявилась проводница, словно почувствовавшая, что о ней вспоминают не в лучшем ключе.

– Сьорбать будеш, кобіто? [^5]

Девушка тут же кивнула головой, потому что и раньше слышала этот вопрос.

– Чашку чая, пожалуйста.

– Скільки?

– Простите?

– Скільки цукру? [^6]

– О нет, я пью чай без сахара.

Услыхав эту фразу, проводница выпучила свои и без того громадные зеньки [^7]. Выглядело это жутковато, и девушке почудилось, что глазные яблоки вот-вот вырвутся на свободу. Тем временем женщина окинула Элеонору ошарашенным взглядом, предназначавшимся по меньшей мере для представителей внеземной расы. В подобной ситуации Агата без лишних раздумий послала бы собеседника на хуй, – плевать, пуцка это, или пуцька [^8]  – но до знакомства с последней оставалось почти девять часов, так что Нора лишь сдержанно улыбнулась.

Проводница не удостоила этот жест ответом и удалилась.  

Нора нехотя вылезла из-под одеяла и принялась собирать постель. 

День начался как-то не очень. 

[^1]: Как спалось? (здесь и дальше – укр. диалект) 
[^2]: Сегодня дорога должна быть хорошей
[^3]: Задница!
[^4]: Да чтоб паралич разбил эту бл… (с польского наречия)
[^5]: Пить будешь, девушка?
[^6]: Сколько сахара?
[^7]: Глаза
[^8]: Варианты написания вышеупомянутого органа.

## 2 {-#2}

Девушка подвязала волосы и, укутавшись в шарф, вышла за пределы душного купе. Дело было не в отсутствии воздуха и даже не в абстинентном синдроме, который медленно, но уверенно подкрадывался к её организму, – просто Нора решила, что ещё одной встречи с курьером из ада, по каким-то странным и неведомым причинам выступающим здесь в роли проводницы, она не переживёт.

Продвигаясь по вагону, Элеонора бросила взгляд на проплывающий за окнами пейзаж и отметила про себя, что привлекательность картины за стеклом возрастает прямо пропорционально её отдалению от родного города. С этими мыслями она миновала последнее купе, туалет, открытая дверь которого демонстрировала всякому нуждающемуся малоприятное зрелище, и вышла из вагона.

С зажатой в пальцах сигаретой она стояла в крохотном продуваемом помещении, соединяющим седьмой и восьмой вагоны, прямиком под значком с изображением жирной линии, перечеркивающей сигарету и надписью "Не палити"[^9]. Как и в коридоре, пол здесь был непростительно грязным и от предыдущего его отличало лишь присутствие дюжины окурков – свидетелей того, что Элеонора была далеко не единственной, кто нарушал вышеуказанное правило. Несмотря на обещания проводницы, которых девушка всё равно не разобрала, поезд продолжало трясти, так что свободной рукой ей приходилось держаться за пыльные поручни.

Не лучшее место для аллергика.

Чай уже ждал на столике, когда Элеонора вернулась в своё купе. Слишком крепкий, но без сахара.

[^9]: Не курить!

## 3 {-#3}

– Виходок зачиняється![^10] – оповестила проводница.

Поезд прибыл по расписанию, чем немало удивил своих обитателей. В десять минут девятого Нора захлопнула книгу и внимательно осмотрела своё купе, не забыв заглянуть под спальную полку, где однажды оставила кошелёк. Плацкартные вагоны были забиты под завязку, но в вагоне номер восемь едва ли была занята четверть мест, посему девушка ехала одна, против чего она нисколько не возражала – загадочные спутники бывают только в старых романах; на деле же их роли обычно исполняют храпящие алкоголики и счастливые обладатели грязных носков, а то и оба варианта сразу.

Проведя в дороге более восемнадцати часов, Элеонора чувствовала себя выжатой, но вместе с тем понимала, что засиделась. Львов встретил её тихим утром и мокрым снегом. Ступив на перрон, девушка вдохнула свежий воздух и ощутила, что усталость начинает испаряться. При себе у неё была дамская сумочка и кожаный чемодан. Старомодный, он вполне тянул на ручную кладь.

Здание вокзала оказалось на удивление просторным и уютным. Выполненное в пастельных тонах, оно удачно вписывалось в представление девушки о новом месте жительства: воздух был пропитан запахами шоколада и свежесваренного кофе; с разных сторон доносились отрывки фраз, произнесённых, казалось, на всех языках мира. Выйдя на улицу, Элеонора задержалась на какое-то время, чтобы полюбоваться старинными фасадами здания. Онлайн-путеводитель гласил, что открытое в ноябре тысяча восемьсот шестьдесят первого года (возведенное в тысяча девятьсот четвёртом), строение это исторически было первым железнодорожным вокзалом на территории современной Украины. Она деловито кивнула и сделала сэлфи.      

Покончив с осмотром, девушка постояла ещё немного напротив здания вокзала, дожидаясь пока из кадра удалятся туристы, после чего сфотографировала его и направилась к нескольким десяткам такси, что выстроились в аккуратный ряд у самого бордюра.

До центра города простиралось всего два с половиной километра, но девушка решила взять такси, тем самым сохранив силы. По словам хозяйки, комната, насчёт которой она договорилась, будет готова только к пяти часам вечера, так что сегодня Норе предстояла долгая прогулка.

Она воткнула в уши любимые ракушки и окунулась в атмосферу декабрьского утра.

[^10]: Туалет закрывается!

## 4 {-#4}

Для начала Элеоноре хотелось подняться на самый верх пресловутой ратуши, дабы всецело ощутить вкус нового города, ну, и, конечно, ввиду очаровательной панорамы, которую она не единожды видела на чужих снимках. Однако, вскоре выяснилось, что ратуша находится в пешеходной части Львова, куда строго настрого запрещен въезд. Шофер – пожилой вуйко[^11] в бордовом берете и с усами щеточкой – высадил девушку на проспекте Свободы и подробно объяснил, как добраться до нужной ей точки.  

[^11]: Мужчина

Поблагодарив мужчину и выйдя из машины, Элеонора первым делом заметила хмурое каменное сооружение, возвышающееся в центре небольшого сквера. Его она также узнала. Сама фигура Тараса Шевченко ничем не отличалась от прочих памятников, увиденных Норой в других украинских городах: стандартной высоты, выполненная из бронзы, покоившаяся на гранитном постаменте, но было здесь ещё кое-что, заставляющее прохожих затаить дыхание. По левую сторону от поэта находилась двенадцатиметровая стела – так называемая «Волна национального возрождения», передняя сторона которой символически изображала историю страны со времен Киевской Руси до прошлого века, вместе с героями произведений Кобзаря; обратная же передавала всё тот же мотив, начиная с двадцатого века. Фигурные рельефы вызывали коктейль из тоски и благоговения, а разглядывать их можно было до захода солнца. И хотя это сооружение было далеко не в её вкусе, Нора провела у памятника с четверть часа, затем подкурила и перешла дорогу, направляясь в сторону вычурных зданий и бесконечных кофеен.

Ещё одной особенностью этого места были выложенные брусчаткой дороги: в совокупности с узкими улочками они создавали особую, домашнюю атмосферу. Свернув направо, девушка шагнула в заснеженный переулок и медленно зашагала вдоль трамвайных путей, что привели её к Доминиканскому собору.

Гуляя по старому городу, Нора ощущала родство с этим местом и на её губах вновь поселилась мечтательная улыбка. Приятно было наконец вырваться из приевшегося индустриального городка, единственной перспективой жизни в котором была возможность уехать.

Обойти центр не составляло труда – городок был небольшим, но каждый квадратный метр последнего являл собой произведение искусства, так что последующие два часа Элеонора провела за изучением местности, которая к её приятному удивлению оказалось премного богаче того, что предлагал путеводитель. Первым действительно полюбившимся ей местом стал Доминиканский монастырь: выполненная в камне, наружная часть собора, включающая в себя роскошные статуи, удивительно гармонировала с золотым интерьером. До этого момента девушке не доводилось видеть столь сдержанного барокко. 

Разглядывая алтарь, она заметила вошедшего в костёл мужчину, на руках у которого сидела белокурая девочка, бережно замотанная в пуховик. Увидев переливающиеся фасады, она протянула к ним ручки, после чего вдруг надула розовые губки и обиженно спросила:

– Почему я не могу здесь жить, папочка?

Последнее слово прозвучало особенно чётко, выдавая южный диалект, и Элеонора успела подумать, что она не единственная туристка, гуляющая по незнакомому городу ранним снежным утром. Однако, ответ последовал на местном украинском.

– Бо то э культурна пам'ятка, доце – лицо мужчины осветила улыбка. – Не реви, ушитко то добрі, бо дам тобі цуцлик.[^12]

[^12]: Потому, что это культурный памятник, доча. Не реви, все же хорошо, а то дам тебе соску.

– Я уже большая для цуцлика, – заявила девочка, но тем не менее расхохоталась.

Мужчина придал своему лицу наигранно задумчивое выражение.

– Хм... Большая кажеш?[^13] Тоді мабудь і лизанку купувати не варто...[^14]

[^13]: Говоришь
[^14]: Тогда, наверное, и леденец покупать не стоит…

Оказавшись истинной женщиной, малышка чмокнула отца в щёку, и по добродушному взгляду мужчины стало ясно, что он купит ей не один леденец.

«И почему я не могу здесь жить?» – подумала Элеонора, глядя на удаляющееся из собора семейство.

Забавно, но ближе к вечеру она с немалой долей иронии вспомнит эту мысль.

## 5 {-#5}

Навернув пару кругов по Старому городу, Нора вновь вышла на площадь Рынок и очень огорчилась тому, что не смогла попасть в ренессансную Чёрную каменицу, о которой она читала, что та получила свой цвет совершенно таинственным для прошедших столетий образом. Девушке нравился чёрный, (и об этом она также вспомнит грядущим вечером) а потому ей хотелось узнать, как зданице выглядит внутри.

Поражало её и удачное сочетание античности с повседневной жизнью города. Многое поражало.

Запечатлев ещё несколько строений и статуй, Нора поднялась по ступеням. Она очутилась около памятника Ивана Фёдорова, который, если верить путеводителю, был возведен в честь четырёхсотлетия книжной печати на украинской земле. Но заинтересовало девушку кое-что другое: всю площадь подле постамента занимал огромный букинистический рынок. Являвшаяся по своей эстетичной природе тем ещё графоманом, Элеонора с новыми силами взялась за изучения ассортимента и вскоре утяжелила свой багаж. Отрадно было и другое: здесь оказалось возможным найти не только редкие, давно снятие с продажи издания, но и старые пластинки. Девушка любила винил (это-то их с Агатой и объединило) и не пожалела бы на его покупку денег, будь у нее при себе проигрыватель.
Она покинула площадь, дав себе обещание обзавестись последним в скором времени.
На протяжении всего дня снег то усиливался, то затихал чтобы начаться вновь.

Следующей остановкой стала Ратуша. Девушка не была уверена в том, правильно ли она рассчитала свои силы, ведь по мере прогулки чемодан в её руке становился всё тяжелее, а лишенная сна ночь всплывала в памяти, но подойдя к интересовавшему её зданию Элеонора уже не сомневалась в том, что увидит волшебную панораму. Во-первых, в своих желаниях она была упряма, во-вторых, ратуша выглядела не такой уж и высокой. К тому же, девушка любила прогулки в одиночестве, особенно если альтернатива как таковая отсутствовала.

У входа в здание городского совета её традиционно приветствовал каменный лев. Внутри оказалось тепло и просторно. Быстрыми шагами Нора преодолела четыре этажа, время от времени выглядывая в окна. Иногда на её пути встречались работники администрации, что суетливо перескакивали из одного кабинета в другой. Следуя указателям, Элеонора очутилась в тесной комнатке – пропускном пункте, дальняя дверь которого служила выходом на крышу. Кабинка сторожа пустовала. Девушке не хотелось задерживаться, так что она просунула в окошко розовую купюру и направилась к двери.

Для начала её вниманием завладели огромные старинные часы, шестеренки которых, несмотря на свой возраст, продолжали вертеться. Обожающая стим-панк, Элеонора долгое время не могла отвести взгляд от механизма. Даже воздух этого места проникся минувшими столетиями, а тишина и пустынность придавали помещению загадочность. Девушке представилось, что она только что вошла в ТАРДИС, которая перенесла её в средину девятнадцатого века – такое неописуемое чувство единения с произведением искусства.

Впереди её ожидало чуть более четырёхсот деревянных ступеней и поначалу эта цифра не казалась Норе значительной, но, не пройдя и половины своего пути, девушка осознала, что покорение ратуши после насыщенного прогулками утра – идея не из лучших. Отдышавшись, она наклонилась через перила и взглянула вниз: идеальная симметрия раскинувшейся под ногами картины создавала иллюзию зеркал.

Чем выше Элеонора поднималась, тем уже становился проход, из квадратной лестница превращалась в спиральную, а перила и вовсе исчезли. Теперь идти приходилось медленно: земля то и дело уходила из-под ног. Один раз девушка даже споткнулась, не обошлось и без этого. Перед её глазами тут же предстала картина красочного падения.

Тем временем подъем стал настолько резким, что Нора уже не видела ничего кроме недавно побеленной стены по правую сторону от себя. Путь её занимал не более двадцати минут, но где-то на середине дороги Нора потеряла счет времени и не поверила своему счастью, когда за очередным поворотом вдруг наткнулась на приоткрытую дверь, из которой пробивался свежий ветер.

Элеонора с облегчением вздохнула и вышла на смотровую площадку. 

Снегопад усилился. На улице заметно похолодало. Одна снежинка упала прямиком на нос девушки, но охваченная открывающимся с ратуши видом она этого не заметила. Панорама оказалась воистину чудесной: в какую сторону не глянь, на глаза попадались неописуемые львовские красоты, будь то величественные храмы, или же разноцветные олдфэшеневые[^15] домики. Последние полюбились ей особенно сильно – аккуратные и в то же время хаотично разбросанные дворики, разделенные тонкими улочками; дома с покатыми крышами, схожие, но не идентичные; яркие верхушки, стены, выполненные в мягких тонах и бесчисленное количество кирпичных дымоходов. 

[^15]: Old-fashion (англ.) – старомодный   

Местами виднелись трамвайные пути, по которым лениво передвигался транспорт. Элеонора стояла у самого края и наблюдала за одним из трамваев до тех пор, пока тот не скрылся из виду, растворившись в зимней белизне. Она пожалела, что на крыше часовой башни до сих пор не открыли какую-нибудь кофейню. Конечно, нынешнее состояние ратуши максимально соответствовало прошлому, но теперешняя погода и очаровательные виды то и дело наводили девушку на мысли о домашнем уюте и горячих напитках.

Вспомнилось ей и другое – поднебесный чердак в старом доме, крохотное помещение, доверху заваленное книгами, сувенирами и флаконами сладких духов – место, где девушка провела большую часть своей лишь начинающей становиться взрослой жизни.

Нора тряхнула головой, словно отгоняя от себя неудавшиеся мысли. Так или иначе, для ностальгии было ещё слишком рано. 

## 6 {-#6}

С приходом холодов темнело в этих краях рано. К четырём часам Элеонора расправилась с обедом, а в начале пятого попросила принести ей ещё одну чашку заманчиво пахнущего латте.

Ближе к вечеру погода изменилась в лучшую сторону. Ветер поутих, и сидя в дальнем углу кофейни, девушка наблюдала за тем, как крупные хлопья снега плавно кружили в оранжевом свете фонарей, расположившихся вдоль бульвара. Нора обхватила рукой чашку с дымящимся напитком; второй она переворачивала неразлинованные страницы ежедневника, просматривая их содержимое. Прошлой ночью, в ожидании запаздывающего сна, девушка заполнила своим изящным почерком несколько листов. Поначалу это должны были быть всего лишь частички водоворота мыслей, кружащего в её голове, но постепенно стал вырисовываться сюжет.

А начиналось повествование со следующих слов.

> *Я всегда считаю секунды между молнией и громом, определяя таким образом расстояние на котором 'сверкает'. Этому в детстве научил меня отец, объяснив  разницу между скоростью света и скоростью звука. Я помню, как мы сидели летней ночью возле реки, он светил фонариком в небо и говорил, что этот свет долетит до ближайшей звезды через восемь лет. Мне тогда самой было около восьми, и этот срок казался огромным. Сейчас я подумала, что если кто-то на этой 'ближайшей звезде' получил наше послание, то вскоре мне стоит ждать ответа.*

Элеонора вычеркнула парочку не приглянувшихся ей слов и перевернула страницу.

> *Я шла по просторному нефу в полном одиночестве, мои шаги разносились гулким эхом и смешивались со звуком стучащих по стеклу капель дождя. Замедлив шаг, я подошла к широкому витражному окну, свет из которого в солнечные дни делил коридор на две равные части. Рассматривая узоры из цветного стекла, я остановила свой взгляд на розах, аккуратно составленных из угловатых алых осколков. Дождь тем временем прекратился и застывшие на лепестках прозрачных цветов капли, напоминали крупную росу, выступившую ранним утром после холодной ночи.*
>
> *Повернувшись на 180° я облокотилась на подоконник и начала рассматривать сводчатый потолок, возвышающийся в трёх метрах надо мной. Утончённые переходы и вычурные розетки не переставали поражать меня своей плавностью и точёностью, от них веяло стариной, и в моей голове уже начала разыгрываться история, сродни средневековым легендам, как вдруг в кармане пальто зазвонил телефон.*

Эта часть записей напоминала Элеоноре о давно минувшем лете, проведенном в Оксфорде. Несмотря на то, что дожди не прекращались, дни выдались удивительно жаркими, а вместе с тем не прекращался и наплыв туристов. Норе, которая предпочитала в уединении знакомиться с прекрасным, приходилось просыпаться с зарей: только так она могла гулять по городу, а не протискиваться сквозь толпу иностранцев, плевавших на историю и делающих сэлфи на фоне каждого столба.  

Какое-то время наша героиня разглядывала «точёность», размышляя, есть ли такое слово в принципе, и если нет, стоит ли его употреблять? В итоге решила пока оставить.

Далее в тексте следовал разговор, и если с описаниями, по её скромному мнению, у Норы проблем не возникало, то в плане диалогов девушка особой уверенности не чувствовала. Составляя их, она никак не могла отделаться от чувства наигранности.


> *...как вдруг в кармане пальто зазвонил телефон.*
>
> *– Привет, Имя, – произнесла я в трубку.*
>
> *– Добрый вечер, леди Имя. Когда вы наконец покинете свою башню и явитесь отужинать со мной? Убийство дракона возлагаю на вас.*
>
> *– Я как раз точу свой меч, чтобы с ним расправиться, – произнесла я в тон речам Имя.*
>
> *– Ещё не сдала?*
>
> *– Нет, брожу пока тут. Профессор должен освободиться к шести. *
> 
> *– Но мы же договаривались увидеться в шесть, – голос Имя прозвучал расстроено.*
> 
> *– Ну ты же знаешь, как это обычно бывает. Час задержки – это ещё не много. Хотя я сама рассчитывала, что сегодня всё пройдет быстро. Вечером тут обычно никого особо нет, но видимо у МакДоусона нашлись какие-то срочные дела, в которые моя скромная персона не входит.*
> 
> *– Слишком уж она у тебя скромна. Не можешь настоять на своём.*
> 
> *– Ты ведешь себя, как Имя, - Имя прыснул. - Давай перенесём на семь? Обещаю, что не задержусь ни на минуту.*
> 
> *– Ладно, договорились. Ровно в семь возле «Нью Эйдж», – Имя поставил особое ударение на слово 'ровно'.*
> 
> *– Когда приедешь, я уже промокну насквозь, дожидаясь тебя.*
> 
> *– Дождь закончился, так что тебе это в любом случае не удастся.*
> 
> *– Посмотрим.*
> 
> *Я отключилась, не дав Имя ответить и, мечтательно улыбаясь собственным мыслям о предстоящем вечере, снова повернулась к окну. На этот раз я смотрела сквозь стекло на нависшие над городом тучи, которые вдруг озарила тонкая сеть молний, и ровно через шесть секунд послышался приглушенный стенами гром.*

Элеонора вскинула бровь и нарисовала жирный вопросительный знак вдоль всего диалога. Фамилию профессора девушка подчеркнула дважды – во время написания чернового текста она старалась на фокусироваться на мелочах, а в выборе фамилии приставка 'Мак-' оказалась первым, что пришло ей в голову.

Она ещё не знала, будет это повесть, или целый роман, но метила на научную фантастику. Норе не терпелось закончить рукопись – такое призрачное ощущение чего-то великого появлялось каждый раз, когда сознание нашей героини посещала новая идея. В итоге, верхний ящик её прикроватного столика был переполнен неоконченными рукописями, и хотя некоторые из них выглядели довольно увесистыми, остановившись однажды, Нора никогда не возвращалась к старым историям.

Но в этот раз все обещало сложиться иначе.

Погруженная в изучение собственных записей, Нора совершенно забыла о времени. С неподдельным изумлением она уставилась своими зелеными глазами на часы, показывающие пять вечера, и попросила как можно скорее принести счет.

## 7 {-#7}

Объявление о предоставлении жилья Элеонора нашла незадолго до назначенного срока выезда. Совершенно случайно. Первоначально девушка собиралась поселиться в каком-нибудь небольшом хостеле и уже по ходу дела подыскать что-нибудь, удовлетворяющее её потребности, так как заселиться она собиралась на весьма длительный срок. Однако заметка, попавшаяся ей на глаза, тут же привлекла внимание Норы. 

Её будущая арендодатель писала на украинском. Перевод же объявления выглядел бы следующим образом.

> *На продолжительное время сдается этаж старинного здания с видом на культурные достопримечательности города. В апартаменты входят две спальни, одна из которых с балконом, ванная комната и просторная гостиная. Есть беспроводной интернет. Помещение расположено в тихом, безлюдном месте, десять минут ходьбы до трамвайной остановки.*

Ниже указывалась цена аренды, невероятно низкая для такой роскоши, и это окончательно убедило Нору зарезервировать новое жилье.

Элеонора не любила опаздывать, но делала это с завидной регулярностью.

«С видом на культурные достопримечательности,» – напомнила себе девушка с толикой облегчения.

Значило ли это, что пункт назначения находится вблизи от центра? Она полагала, что да. И так как сама Нора находилась в центре, немного времени на дорогу у неё всё ещё оставалось.

Девушка миновала Оперный театр, на ходу любуясь чарующей скульптурной композицией, отражающей радости и страдания жизни, что возвышалась над коринфскими ордерами в убаюкивающем свете тысячи огней: крылатые музы, олицетворяющие гениев Славы, Музыки и Трагедии. Чуть ниже располагалось несколько десятков античных фигурок, разбросанных по всему зданию. В вечернее время, за пеленой падающего снега казалось, что они пляшут на фасадах здания. Шагая по заснеженной аллее, Нора ощутила, как по её телу пробежали мурашки, вызванные увиденной картиной.

Вскоре ей на глаза попался крохотный туристический трамвайчик, разъезжающий вокруг площади и периодически останавливающийся у выдающихся мест, что располагались буквально на каждом углу. Девушка подошла к нему и назвала нужный ей адрес, поинтересовавшись, не проходит ли экскурсия мимо этого места.

– Перепрошую?[^16] – удивленный взгляд.

[^16]: Прошу прощения?

Элеонора повторила нужный ей адрес.

Водитель и его спутница переглянулись, после чего первый отрицательно покачал головой и поспешил вернуться к экскурсии, а Нора – чуть более чем обескураженная – продолжила свой путь. 

Трамвай подошел быстро и, видимо, ввиду погоды был абсолютно пуст. Прислонившись к стеклу, Элеонора слушала музыку и наслаждалась проплывающей за окном картиной. Казалось бы отдохнувшие в кофейне ноги заныли с новой силой; девушка уже в сотый раз прокляла свою любовь к каблукам. 

Спустя какое-то время снег перестал и теперь лишь изредка мелькал за окном. Старый город постепенно сменился пейзажами, которые мало чем отличались от предыдущего места жительства Элеоноры. Трамвай ехал слишком долго, и тень сомненья постепенно окутывала девушку. В итоге, она достала телефон и заглянула в электронную почту.

– Вот оно.

В своем заключительном письме Агата писала:

> *Вам нужен трамвайный маршрут №7, что проходит через проспект Свободы, в паре шагов от Оперного. Сойдите на улице Мечникова, (13737) это третья с конца остановка. Выйдя из трамвая, увидите врата под остроконечной каменной аркой. Входите. Сверните налево и идите прямо, пока не встретится памятник Франко.*

(Ответ также пришел на украинском, и в этом месте было написано «Франка», а не «Франку», но наша героиня то ли не заметила подмены, то ли попросту сочла ее случайной оговоркой.) 

> *Потом направо и вдоль сосновой аллеи, в конце которой Вы увидите высокое здание из черного камня. Оно здесь единственное, так что не спутаете. Если надумаете взять такси, адрес: Мечникова 33/8, или же попросите остановить у Лычаковского музея, Вас поймут.*
>
> *P.S. Пускай Вы и обещали быть в пять, напомню, что в ворота Вы должны зайти не позже шести вечера, иначе придется ждать утра.*
>
> <p align="left"><em>--- А.</em></p>

Ещё при первом прочтении письма постскриптум показался норе странным. Теперь же он выглядел тревожным, особенно с учетом того, что до указанного времени оставалось всего ничего. Девушка вздохнула и сделала музыку громче, изо всех сил стараясь взять верх над накатившей сонливостью.

## 8 {-#8}

Когда Элеонора сошла с трамвая, с шести часами вечера её отделяли всего три минуты. Батарейка в телефоне предательски сдохла. Будучи выходцем двадцать первого века, Нора не имела при себе фонарика. Незнакомая, пугающе пустынная улица была полностью покрыта тьмой и столь разительно отличалась от той части города, в которой девушка провела последние семь часов. К счастью, светлые каменные врата, о которых писала Агата, величественно выделялись во мраке, и Нора со всех ног поспешила к ним.

Открыты. 

Но вокруг – ни души. Какое-то время она простояла у входа, опрометчиво вглядываясь в темноту, а спустя несколько шагов в неопределенном направлении, всё-таки, заприметила танцующий лучик белого света, но тот был слишком далеко, да и к тому же находился по правую руку, тогда как девушке предстояло идти в противоположную сторону. 

И она пошла. 

На протяжении первой минуты все было в порядке, но мгновеньем спустя Элеонора наткнулась на какой-то высокий камень и во весь рост растянулась на земле.

– Фак! – вскрикнула девушка. 

Живя с не знающими английского языка родителями, в подобных ситуациях она привыкла изъясняться именно таким образом.

– Хренова бичара[^17]!

[^17]: Bitch! (англ.) – Сука! 
[^18]: Dick (англ. жарг.) – хуй.

И еще спустя пару секунд:

– Ну и дик[^18] с ним.

Холода она не чувствовала, а потому решила, что не тронется с места, пока глаза не привыкнут к темноте. 

Чемодан по-прежнему оставался в её руке.

Она не знала, как долго пролежала в сугробе, глядя на верхушки сосен, сужающиеся там, где по её мнению должно было быть небо, но не думала, что с момента падения прошло много времени. Наконец, зрение начало адаптироваться, и Элеонора поняла, что уже может различать тонкие очертания стволов. 

Хороший знак. Девушка понемногу начала подниматься.

Нора машинально взглянула на свой личный камень преткновения. Тут-то всё и прояснилось. Лычаковский – девушка вспомнила, где прежде слышала эту фамилию: всё в том же путеводителе.

Её преградой действительно был камень, надпись на котором гласила:

<p align=center>
<em>
Наталья В. Гробовец
</em>
</p>
<p align=center>
<em>
1809 – 1849
</em>
</p>

Она обнаружила, что находится на кладбище, вероятно, открытом для посещений до шести часов вечера.

## 9 {-#9}

До этого дня Элеонора никогда не замечала за собой койметрофобии[^19], но в сложившихся обстоятельствах вычурные старинные надгробия, расположившиеся по обе стороны её пути, выглядели зловещими. Никаких проблесков света, никакого ветра, или шума автомобилей. Последние пристанища мёртвых встречали и провожали её в кромешной тишине. Для полноты картины не хватало лишь густого тумана, плавно вытекающего из-под какой-нибудь могилы.

[^19]: Coimetrophobia – боязнь кладбищ.

Памятником Франка также оказалось надгробие писателя.

«И впрямь культурная достопримечательность,» – девушка нахмурила брови.

Сворачивая направо, она в полной мере не ожидала увидеть обещанное строение, выполненное из черного кирпича. Происходящее скорей напоминало хорошо продуманный розыгрыш. Но помимо всего прочего Нора была самым что ни на есть филантропом, а потому решила дать этой истории шанс и дойти до конца. К тому же, возможность вызвать такси отсутствовала, а пройти весь путь вновь не было сил. 

Нора испытала смесь удивления и облегчения, заприметив то самое здание. Ввиду своего цвета, оно в последний момент выпрыгнуло из темноты.

Возведенное в три этажа, строение служило прекрасным примером раннего барокко и словно вышло из-под руки самого Пёппельмана: утонченные, но в то же время сильные пилястры; идеально выдержанные пропорции изящно украшали статуи скорбящих атлантов, что притаились среди цветочных арабесок; те же орнаменты непринужденно свешивались вдоль колонн и полуколонн, венчая богатым узором центральный вход. Вместе с тем, здание имело каркасную систему строения, что придавало ему особенно мрачный вид, в несколько раз увеличивая реальный размер.     

Вывеска над парадным входом гласила:

<p align=center>
<em>
МАЯТНИК
</em>
</p>

И подпись ниже:

<p align=center>
<em>
Бюро ритуальных услуг
</em>
</p>

– И почему меня это не удивляет? – произнесла Нора и тут же вздрогнула от звука собственного голоса, предавшего тишине ещё большее могущество.

Девушка собрала последние силы в кулак и быстрыми шагами поднялась по высоким ступеням. На месте окон почивали высокие витражи, а аналогом звонка служила медная ручка-стучалка, традиционно выполненная в форме маятника и оказавшаяся чересчур увесистой. После третьего стука в одном из витражей зажегся свет. Послышались неспешные шаги и звук открывающихся замков.

Дверь отворилась, и на крыльцо вышла особа, прекрасно вписавшаяся во время и место действия: высокая, бледная, темноволосая фигура в свободном, покрывающем ступни чёрном платье; шляпка в тон одеждам натянута на затылок; достающие до бедер волосы были прямыми и скрывали треть лица; на шее – подвеска в виде маятника, но наиболее странным элементом оказались старомодные солнцезащитные очки, столь неуместные в это время суток.

«Должно быть, у нее проблемы с алкоголем,» – мелькнуло в голове Норы.  

Нельзя сказать, что она слишком уж ошиблась.

Определить возраст стоявшей на ступенях личности пока не представлялось возможным. 

– Значит, снег уже выпал… – произнесла та невероятно низким голосом, и тут же добавила: – Вы опоздали на 84 минуты. Это хорошо: не люблю просыпаться до наступления темноты.

– Вы Агата?

Хозяйка дома ничего не ответила, а лишь медленно кивнула и протянула девушке бледную руку. Внимание Элеоноры тут же привлек увесистый перстень в форме черепа, выглядевший на удивление женственным в сочетании с длинными ногтями-семечками.

Они обменялись рукопожатием.   

– Меня зовут Элеонора, но достаточно будет простого обращения «Нора».

Уголок рта арендодателя, если её все еще можно было считать таковой, странно дернулся. Лишь спустя сутки наша героиня узнала, что это движение означает улыбку. Элеонора не могла с точностью этого утверждать, но казалось, что Агата внимательно наблюдает за ней. 

– Рады видеть вас в бюро ритуальных услуг «Маятник», Элеонора, – изрекла Агата.

Она отступила в сторону, предлагая гостье войти.

## 10 {-#10}

Следуя тускло освещенными коридорами за хозяйкой бюро, Элеонора никак не могла отделаться от мыслей о том, что она добровольно собирается заселиться в украинскую версию замка Дракулы, (именно таким он представлялся девушке во время чтения романа, и, посетив в последствии с десяток «оригинальных поместий», она осталась более чем разочарованной) а экскурсию по дому ей проводила гранжевая версия Мартиссии Адамс.

«Тудудудум-пам-пам, тудудудум-пампам, тудудудум, тудудудум, тудудудум, пам-пам, – услышала она знакомый мотив в собственной голове, а вслед за ним: –  Дети ночи… Какую музыку они заводят!»

Нора прокашлялась, желая скрыть улыбку.

Она опустила взгляд и попыталась сосредоточиться на шумной картинке. Ноги шагающей впереди Агаты терялись в темноте касающегося пола платья, так что Норе чудилось, что её спутница не идет, а парит в парочке сантиметров над землей.

– У вас очень необычный дом, – вежливо заметила девушка. – Я бы сказала, выдающийся.

Ответа не последовало.

– Могу я узнать, как давно было построено бюро?

– Спустя год после снования кладбища, – ответила Агата, и, заметив на лице собеседницы замешательство, добавила: – В тысяча семисот восемьдесят восьмом.

Ступенька под ногой Норы устало скрипнула, словно подтверждая вышеназванную дату.

– Что ж, это… впечатляет.

Когда они преодолели первый лестничный пролет, хозяйка дома остановилась.

– Весь первый этаж занят под бюро ритуальных услуг, – она махнула рукой. – В правом крыле находится прощальный зал, а левое занято мои кабинетом и другими помещениями, о предназначении которых вам едва ли хочется слышать.

Проследив за этим движением, Нора увидела лишь темноту.

Девушка поёжилась.

– Здесь же находятся ваши апартаменты. Ну, а последний этаж мой и он мало чем отличается от этого.

Внутри было довольно свежо, но всё же лучше, чем на улице. Рука Агаты на мгновенье исчезла в темноте, нащупывая выключатель, и вскоре к огням холла присоединилось с десяток светильников. Стены были увешаны картинами, взятыми в витиеватые рамки всевозможных форм и размеров; мебели – совсем немного, казалось, она втрое старше нашей героини.  

Мысленно Элеонора отметила, что внутри здание выглядит куда меньше, несмотря на музейный интерьер, но ничего не сказала.

Агата подняла ладонь вверх и, медленно согнув тонкие пальцы, двинулась вдоль коридора, приглашая девушку следовать за ней. Последняя не заставила себя ждать. Сквозь пустующий дверной проём они проникли в просторную гостиную.

Первым объектом, завладевшим вниманием девушки, стал резной камин, в несколько раз превосходящий в размерах тот, что остался в её доме.

«Бывшем доме,» – напомнила себе Элеонора.

В конце комнаты виднелись двойные высокие двери, под стать потолкам. Хозяйка кивнула в сторону первых.

– Располагайтесь, – произнесла она, и Нора поняла, что ей никогда не удастся привыкнуть к этому загробному голосу. – Могу предложить кофе, хотя  ближе к ночи я предпочитаю вино. Это удобно, потому что в дневное время мне глаз не разомкнуть.

– Кофе был бы очень кстати.

Агата кивнула и вскоре исчезла за пределами комнаты.  

Мебель в первой спальне полностью повторяла обстановку гостиной: резная, дубовая и очень-очень старая. Единственным отличием стала двуспальная кровать с кованной спинкой, отбрасывающей причудливые тени на черного (а вы сомневались?) цвета стены. В гостиной же на её месте покоился диванчик из алого бархата.

Закрыв за собой дверь, Нора громко выдохнула и поспешила отделаться от изводивших её весь день туфель. Спустя долю секунды те уже летели в одному богу известном направлении.

От дубленки девушка избавилась в более мягкой манере, но тоже без особой любви. Следом отправились свитер и джинсы. Чемодан временно прилег под кроватью – сил на раскладывание вещей у девушки уже не было.

Она улыбнулась сложившейся ситуации и растянулась поперек ложа.

## 11 {-#11}

Элеонора прикрыла глаза и направила душ в свою сторону, с облегчением почувствовав, как поток тёплой воды смывает с её лица остатки утреннего макияжа. Усилием воли она заставила свою задницу, а вместе с ней и другие части тела, покинуть пределы кровати. Теперь тёплая, практически горячая струя ласкала кожу, вгоняя девушку в ещё большую сонливость.

Ванная комната примыкала ко второй спальне – очередное просторное помещение. Выполненное в кофейных тонах и обставленное элементами современной мебели, оно разительно отличалось от предыдущих комнат. Впервые ощутив этот контраст, девушка вновь подумала о ТАРДИС.  

Вымотанная, уставшая до невозможности, она откисала под душем, лениво наблюдая за тем, как тонкие струйки воды стекали по запотевшему стеклу кабинки. Время от времени, Нора мысленно корила себя за неосмотрительность: это же каким надо обладать легкомыслием, чтобы мало того, что в последний момент взяться за поиски жилья, так ещё и не удосужиться проверить место его нахождения, и это при том, что в расположении человечества уже лет десять имеется такая крутая штука как Гугл-поиск.

– Расслабься, – раздраженно бросила девушка. – Выспись для начала, а завтра уже подыщешь что-нибудь адекватное.

– А-д-е-к-в-а-т-н-о-е, – спустя полминуты повторила Элеонора.

Да уж, это точно не о её новых апартаментах.

Нора широко зевнула и потянулась за полотенцем.

Душ определённо не предавал бодрости.


<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Норе думалось, что в ванной комнате она провела от силы десять минут, но на деле оказалось, что процесс этот занял втрое больше времени. Возможно, в какой-то момент она просто отключилась, ведь такое случалось и прежде. Так или иначе, когда девушка вошла в гостиную, сжимая в руках сумочку, дожидавшийся её напиток уже успел остыть.  

– Как вам здесь нравится? – осведомился низкий хрипловатый голос.

Элеонора непроизвольно взглянула на его источник. Агата раскинулась поперек одного из кожаных кресел, перебросив ноги через подлокотник, и выглядела слегка поддатой. В левой руке та держала бокал-тюльпан, наполненный бардовой жидкостью, напоминавшей вино; в правой – дымилась сигарета. Шляпа исчезла, (в мягком свете раскачивающейся над их головами люстры, Нора видела, как пряди волос гоздині[^20] переливались янтарным цветом) но очки по-прежнему были на месте.

[^20]: Хозяйки

Силясь отыскать вежливый ответ, девушка еще раз взглянула на собеседницу. Голова Агаты была чуть повернута, но зеркальная поверхность очков не позволяла определить траекторию взгляда последней.

Нора дружелюбно улыбнулась. На всякий случай.

– Ваш дом напоминает мне Дрезденскую Цитадель Пёппельмана.

Тишина.

– Вы ведь знаете, о чем я?

Агата медленно кивнула.  

Однако, весь её внешний вид кричал о том, что женщине – или девушке, Нора всё ещё не могла определить возраст своей новой знакомки, так что решила пока думать о ней как о даме – было совершенно наплевать на происходящее вокруг.

– Присаживайтесь, – наконец, отозвалась Агата, и Нора вдруг осознала, что до сих пор стоит посреди комнаты.

Приземлившись на диванчик, который был не столь мягок, каким казался при первом взгляде, Элеонора заметила, что на ногах так-себе-собеседницы надеты ни то криперы, ни то мартина – в общем, какие-то глянцевые говнодавы неизменного чёрного цвета. 

«Ноги есть, – подумала Нора. – Это уже хорошо».

– Агата?

Бледное лицо, вернее та его часть, что не была скрыта очками, повернулась в сторону Норы. Плавно и неторопливо. Девушку уже понемногу начинала раздражать эта медлительность, вызванная то ли алкоголем, то ли чёрт его знает чем ещё.

Но девушка всё-таки решилась задать кипящий в её голове вопрос.

– Но почему вы не написали, что дом находится на кладбище? – мягко спросила она, и увидела бровь, выглянувшую из-под очков так-себе-собеседницы. – То есть... Я хочу сказать, вы, конечно, написали 'Лычаковского', но...

– Я ведь упомянула памятник Франка, – безразлично заметила Агата. – Имей я ввиду статую, а не надгробие, я бы написала 'Франку'. Элементарная грамматика украинского языка. 

Теперь уже Нора молчала.

– К тому же, много ли вы знаете здешних достопримечательностей, которые бы могли сравниться с некрополем?

«Тысячу и одно,» – подумала Элеонора, но, как любой филантроп, говорить она этого, естественно не стала.

Тем временем Агата осушила свой бокал, выбралась из кресла и направилась в другой конец гостиной.

Девушка откинулась назад и принялась разглядывать окружающую её обстановку: стены были увешаны картинами, практически все – портреты, и хотя девушка видела их впервые, работы показались ей, как она бы сказала, весьма выдающимися.  

Несмотря на предвкушение грядущих странностей, Нора ощущала дискомфорт, сидя в тишине, нарушаемой лишь завываниями внезапно разыгравшегося на улице ветра. Она отхлебнула холодного кофе, который – о чудо! – оказался без сахара и предприняла новую попытку завязать беседу.

– Как давно вы здесь живете?

– Вы действительно хотите это знать? – вновь подняла брови Агата.

Она уже вернулась с новым, до краев наполненным бокалом, в придачу к которому, решив не мелочиться, прихватила и бутылку, этикетки на которой не было

– Люди часто задают вопросы, которые их не интересуют, чтобы потом получить ответы, которые, в свою очередь, интересуют их ещё меньше, – изрекла Агата, заметив следы замешательства на лице гостьи. – А делается этот ритуал ради какой-то мифической вежливости. Конечно, можете рассказать, чем вы занимаетесь, например, но, бога ради, не заставляйте меня участвовать в этом утомительном процессе! – так-себе-собеседница наигранно отмахнулась. – Но полагаю, приятней будет просто пропустить бокальчик-другой. Вино и музыка – вот лучшие собеседники.

Не дожидаясь ответа, она протянула Норе бокал, а сама приложилась к бутылке.

– Берите-берите. Кофе ваш уже, поди, давно остыл.

Всё ещё удивленная внезапным монологом хозяйки дома, Нора взяла бокал. Она отхлебнула вина (то оказалось сладким, с примесью чайной розы) и, сама не зная отчего, принялась рассказывать о своей деятельности.

Агата ухмыльнулась, но перебивать не стала.

– По образованию я менеджер по управлению проектами...

Девушка поднялась со своего места и, выудив из сумочки пластиковую визитку, протянула последнюю Агате, которая уже успела плюхнуться обратно в кресло. Та молча взяла карточку.

–... Пару лет работала в одной крупной компании, расположившейся в моем родном городе, но южные индустриальные пейзажи мне, мягко говоря, чужды, так что я дала себе слово покинуть город при первой же возможности. Прошлось во многом себе отказывать, но, тем не менее, мне удалось собрать подходящую сумму для того, чтобы пару лет безбедно жить и заниматься тем, к чему лежит душа.

Агата не спросила, откуда родом её гостья, и Нору это вполне устраивало.

Она взглянула на так-себе-собеседницу. Полулежа, та беззаботно потягивала вино и без особого интереса вертела меж тонких пальцев визитную карточку. Норе уже было невмоготу наблюдать эту навевающую сонливость меланхолию и она поспешно переключила свое внимание на висящие перед ней портреты.

Одну из картин Элеонора, все-таки, узнала. Эта была «Женщина дождя»: высокая утонченная фигура, облаченная в черные одежды; поверх мертвенно бледного лица виднелась широкая бесформенная шляпа, с полей которой стекали дождевые капли; на поджатых губах играла знакомая ухмылка – сходство с хозяйкой дома сразу же бросалось в глаза. Картина вызывало противоречивые чувства тревоги и умиротворения, но первым делом завораживал отсутствующий взгляд, лучащийся из-под опущенных ресниц рисованной девушки. Глаза были белыми.

«А что если она носит очки потому, что...?» – Элеонора нахмурилась и тут же отогнала от себя эту глупую мысль.

Она сделала жадный глоток вина.

– А душа у меня лежит к писательству, – девушка застенчиво улыбнулась, отчего на щеках проступили очаровательные ямочки. –  Вот только проблема в том, что за всё время мне не удалось закончить ни одной рукописи. Потому я и выбрала Львов – маленький старый город, идеальное место для писателя.

Ещё глоток.

– Знаете, в идеале мне хотелось бы открыть своё издательство. Пускай небольшое, но... 

Нора вздрогнула и замолчала. На долю секунды девушка увидела, как «Женщина дождя» подняла веки и взглянула прямиком на неё своими белоснежными глазами. Элеонора испуганно моргнула, а когда вновь взглянула на картину, увидела, что изображенная на ней особа по-прежнему смотрит куда-то вниз.       

«Твою-то мать, вроде не горилку пью, а привидится же такое!»

Нора также заметила, что хозяйка дома прекратила вертеть в руках карточку и теперь с интересом наблюдала за ней.

– Что с вами? 

– Вино ударило в голову, – тихо произнесла Элеонора. – Должно быть, я переутомилась.

– Возьмите сигарету.

– Ох, у меня есть...

Девушка принялась рыться в сумочке, ей внезапно захотелось перекурить.

Агата вновь поднялась, но на этот раз не за вином. Она направилась к стоявшему позади Норы серванту и на протяжении нескольких минут была занята чем-то вне поля зрения нашей героини. Вскоре в гостиной разлились сладкие звуки музыки, ставшие мёдом для ушей Элеоноры.

– Винил! – восхищенно вскрикнула она и обернулась. – Шестьдесят третий год?

– Шестьдесят первый, – небрежно ответила Агата, но холода на лице так-себе-собеседницы заметно поубавилось.

«Возможно, мне стоит задержаться здесь ещё ненадолго», – расслаблено подумала Элеонора.

К тому же, в её телефоне собралось более сотни фотографий, которые сами себя не обработают и в социальные сети на опубликуют.

## 12 {-#12}

Дело близилось к полуночи. 

Элеонора беспокойно ерзала в постели. Она ощущала себя уставшей и изношенной, но окунуться в сон никак не удавалось. Виной всему была давящая тишина, создаваемая то ли локацией, то ли предназначением похоронного бюро. Нора понятия не имела, находились ли в здании так называемые клиенты Агаты, и всеми силами старалась об этом не думать.

Какое-то время до её ушей еще доносились свинговые мотивы, льющиеся из гостиной, но вскоре они исчезли: вероятно, Агата поднялась в свои апартаменты. Нора пролежала в тишине больше часа. В итоге она выскользнула из постели и направилась к высокому окну. Она приподняла раму и достала из шкафа запасное одеяло. Тишина сменилась завыванием ветра. Холод и внезапно разыгравшаяся вьюга не добавляли уюта, но, всё же, были лучше мёртвого затишья.

«Я лежу в огромном здании, которое находится посреди старого кладбища. В кромешной темноте. Поблизости ни души, лишь покойники. Последние, возможно, находятся ближе чем я думаю... – Нора вздрогнула и натянуло одеяло до самых глаз. – Прекрати! Сейчас же переключи ход мыслей».

– Погода в этих краях так непостоянна, – заплетающимся языком произнесла девушка и наконец провалилась в тревожный сон.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Девушке снилось, что она бродит по кладбищу, не в силах отыскать выход. В какую сторону не глянь, ей улыбались призрачные очертания надгробий, сверкающие в лунном свете. Откуда-то издалека лилась музыка – смесь виолончели и контрабаса – прекрасная, но вместе с тем зловещая в сложившихся обстоятельствах. Снега и в помине не было, зато слышались шаги. Их слегка приглушенный звук эхом отдавался в темноте и Нора никак не могла понять, где находится её преследователь.

Вдруг она почувствовала на плече чьи-то цепкие пальцы, обернулась и ...

Показанные в кино пробуждения после кошмаров обычно сопровождаются криками и резким поднятием, однако в случай нашей героини был вовсе не из этих. Элеонора распахнула глаза и медленно перевернулась на бок, но с подушки не подорвалась; дыханье её оставалось ровным.

«Склеп, вот что мне напоминает этот чёртов дом».

Она вновь сомкнула веки, но тут же с ужасом прислушалась: шаги не исчезали. Казалось, кто-то бродит в стенах... Шаги смолкли, а затем вновь раздались прямиком за её спиной, но это было невозможно, ведь спинка кровати примыкала к наружной стене второго этажа.

Девушка с трудом отогнала эти мысли и вынудила себя прекратить прислушиваться.

«Ко мне в гости пожаловал сонный паралич, оттуда и тревожность, – сказала себе Нора. – Все логично, я же гуляла целый день».

Она шевельнула кистью, убежденная, что ничего не выйдет. Увы, девичьи пальцы послушно коснулись ладони.

Шаги тем временем раздавались то тут то там, заставляя шуршать половицы. После очередного такого скрипа Элеонора сдалась. Она нащупала телефон и включила на всю громкость «El Pintor». На середине третьей песни Нора почувствовала, что проваливается в сон. 

Она не знала, в котором часу проснулась, но решила, что прошло как минимум 30 минут, потому что музыка в её ушах смолкла. Видимо, альбом закончился.

Из сна её опять вырвали шаги.

На этот раз Элеонора лежала неподвижно с едва приоткрытыми веками, боясь пошевельнуться. Нет, кто-то определенно точно только что пробежал в полуметре от нее... Вот только там была стена, смотрящая на кладбище.

Шаги раздавались уже у окна, а затем исчезли так же внезапно как и появились. По коже Элеоноры скользнул холод, когда она увидела картину, заставившую сердце забиться где-то на уровне горла: большую часть витража заслонил вытянутый силуэт, вырисовавшийся буквально из неоткуда. Сутулый, со свисающими вдоль тела руками, он был на голову, а то и больше, выше хозяйки дома.  

Силуэт стоял неподвижно, повернутый в сторону кровати. Девушка чувствовала на себе его взгляд, а когда незваный гость сделал шаг в её направлении, Нора выпрыгнула из постели и метнулась в сторону выхода – именно там находился выключатель (вот вам первый минус больших комнат). Бежала она секунд десять, слыша лишь свое истерически бьющееся сердце, но успела заметить, что силуэт взмахнул руками.

Дальше классика жанра: когда напуганная до усрачки Нора обернулась, комната была пуста. На неё смотрели лишь три пары портретных глаз.

В ту ночь девушка спала с включенным светом.

## 13 {-#13}

Элеонора вынырнула из сна за час до полудня. За окном блестело пушкинское утро: стекла были исписаны ледяными узорами, редкие снежинки мерно парили за окном в лучах зимнего солнца. Утро впрямь оказалось мудренее вечера и, как всегда бывает в подобных историях, Нора сочла произошедшее ночью дурным сном.

Как и все герои этих самых историй, она ошибалась.

Девушка сладко потянулась и поплелась в гостиную. Таким славным утром дом выглядел куда гостеприимней – даже компанию «Женщины дождя» Нора сочла приятной.

На камине её ждала записка.

> *В погребе уйма вина, но о завтраке придется заботиться самой. Через дорогу от кладбища есть парочка киосков, но в них вряд ли найдется что-нибудь пригодное для употребления. Ближайший известный мне супермаркет находится по адресу Соборная площадь 14. Добраться туда можно все тем же трамваем №7.*
>
> *P.S. До темноты на третий этаж не ходите. Можете, конечно, рискнуть, но, говорят, я избиваю людей, помешавших моему сну, а потом этого даже не помню.*
>
> <p align=right><em>--- А.</em></p>

На этой веселой ноте Элеонора наскоро оделась и отправилась по указанному адресу. Хотя она и предпочла трамвай прогулке, путь всё равно был неблизким, и, заняв одиночное место у окна, девушка написала ещё несколько страниц то ли грядущего романа, то ли повести.

Действие разыгрывалось в нескором будущем. Смесь древней архитектуры и космических технологий увлекала Нору, так что за описания она бралась с нескрываемым восторгом. Да и диалоги теперь вызывали меньше подозрения. В старый город наша героиня вернулась довольная проделанной работой.

Времени до наступления темноты оставалось более чем достаточно. Прежде чем отправиться за продуктами, Нора задержалась, чтобы позавтракать в одной из милых  кофеен, мостившихся на каждом шагу. 

«Світ Кави» находилась около Каплиці Боїмів, и девушка с разочарованием подумала, что нет в русском языке слова, которое с точностью могло бы передать суть этого сакрального здания. На ум приходила лишь «часовня», но это совсем не туда.

Заведение примыкало к светлому жилому зданию. Вход украшали каменные вазоны, в которых росла желтая ветреница, и пускай до Нового года оставался практически месяц, веранда была увешана множеством гирлянд. Такую обстановку наша героиня обычно величала «ламповой».

«Должно быть, вечером здесь особенно уютно…» – подумала Нора и вошла в кофейню.

Несмотря на ранее время, все места были заняты. Официант предложил девушке плед и, сделав заказ, та уселась в одно из плетеных кресел под навесом. На улице Элеоноре нравилось гораздо больше: она считала, что в большинстве своем работа писателя заключается в наблюдении, поиске различных типажей характера и их изучении, а потому, ожидая заказ, увлеченно наблюдала за оживленной улицей.

## 14 {-#14}

Над кладбищем сгущались поздние сумерки. Снег эволюционировал в дождь; ветер гонял над надгробиями капли воды. Вытянувшись во весь рост, Агата Рахманинова лежала поверх небрежно застеленной кровати с доживающей свой век сигаретой в зубах; её босые ноги практически доставали до конца ложа. Граммофон извергал из себя второй и последний альбом Джой Дивижн. На прикроватном столике, соседствующий с солнцезащитными очками, её дожидался томик Ремарка, заложенный на середине двадцатигривневой купюрой.  

По правую сторону от себя Агата услышала шаги и тут же потянулась за очками, но опустила руку, когда увидела представшую посреди комнаты фигуру.

– Владислав, – произнесла она, выдыхая сигаретный дым. – Тебе нужно чаще попадаться мне на глаза, иначе я всё время забываю о твоём присутствии.

Девушка отложила сигарету и села на кровати.

Фигура угрюмо развела руками и опустилась рядом. Это был широкоплечий альбинос, ростом под два метра, немногим старше самой Агаты.

– Видел уже нашу гостью?

Владислав коротко кивнул.

– И что думаешь?

– Человек, – изрек Ласло с таким выражением лица, словно говорил о крайне мерзких вещах. – Но красивая.

– Не думаешь, что пора нанести ей визит? – предложила Агата и похлопала приятеля по плечу. – Я имею в виду, нормальный визит.

Девушка сделала яркий акцент на предпоследнем слове.

– Я постараюсь, – пообещал Ласло.

Его голос сквозил неуверенностью.

Из приоткрытого окна до них донесся звук захлопнувшейся двери.

– Вернулась, – произнесла Агата и бросила взгляд на часы в форме черепа, украшавшие восточную стену. – Без двух минут шесть. Снова в последний момент.  

Она ухмыльнулась, а в случае Агаты это означало самую что ни на есть улыбку.    

– Пойду я.

Владислав поднялся и быстрым темпом зашагал в конец комнаты. Еще мгновенье, и он растворился в очертаниях стены.

– Возвращайся к ужину! – крикнула, Агата, надевая очки. – Сыграем в карты.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

В дверь тихонько постучали. В привычной скупой манере Агата предложила гостье войти. На пороге тут же возникла Элеонора. Её раскрасневшееся от холода лицо смотрело на хозяйку похоронного бюро извиняющимся взглядом.

– Я услышала музыку, и решила, что вы не спите…

Агата махнула рукой, приглашая девушку присесть. Она успела натянуть очки незадолго до прихода последней, и теперь на лице шатенки сияла прежняя безмятежность.

Нора освободилась от шарфа и присела напротив так-себе-собеседницы.

– Хотите кофе? – предложила она. – Я также купила кое-какие продукты, но не решилась искать кухню без вас. 

Агата вопросительно подняла бровь.

– Боялась наткнуться на какого-нибудь покойника, – объяснила Нора и виновато улыбнулась. – Кстати, вам самой не жутко здесь находиться?

– Что вы имеете в виду?

Нора немного замялась, боясь оскорбить чувства собеседницы, которой царившая здесь атмосфера, казалось, пришлась по душе.

– Одной, посреди кладбища…

– Я абсолютный мизантроп, – невозмутимо изрекла та, – и меж двух зол предпочитаю компанию мёртвых. К тому же, где вы весь день гуляли, Элеонора?

Девушку удивил такой вопрос. Она решила, что Агата пытается перевести тему, и пускай с так-себе-собеседницей Нора была знакома лишь второй день, это не было на неё похоже.

– Гуляла по Старому городу.

– Конкретней?

– Прошлась по центру, позавтракала в «Світе Кави», том что находится около Часовни Бомоив…

– Во-о-от, – протянула Агата и Нора непонимающе поглядела на неё. – Долго вы находились около часовни?

– Часа два, если не больше, но почему вам это интересно?

– Вот вам интересный факт на сегодня: каплиця была возведена в начале семнадцатого века на территории городского кладбища того времени. Конечно, сейчас старый город старательно вымощен брусчаткой, но вы ведь понимаете, что сегодня успешно позавтракали в компании многовековых захоронений?

– Вы серьезно?

Агата медленно кивнула и ухмыльнулась.

– Мертвые приносят гораздо меньше хлопот, как видите. Всё зависит от визуального восприятия. С ранних лет меня привлекают кладбища. Зовется этот подарок судьбы тафофилией – почитайте на досуге, если хотите.

Тем временем потусторонний голос Кёртиса в последний раз пропел «Where have they been?»[^21], и проигрыватель умолк.

[^21]: «Где они были?» – повторяющаяся строка из композиции «Decades» группы Joy Division.

– Пойдемте, – поднимаясь, произнесла Агата. – Покажу вам кухню. 

## 15 {-#15}

На протяжении оставшихся до наступления следующего года недель, Элеонора уяснила одну вещь о хозяйке «Маятника» – неизменно оставаясь темной лошадкой, Агата никогда не распространялась о своём прошлом, но с неумолимым интересом поддерживала две темы: литература и смерть. Избегая последнего, можно было скоротать приятный вечер у камина и, хотя в бытовых вещах её сожительница по-прежнему была так-себе-собеседницей, интерес Элеоноры постепенно возрастал. 

Уже тогда она начинала задумываться, что из Агаты вышел бы неплохой антагонист для её грядущего романа… 

Однако, тем вечером Элеонору ожидало ещё одно открытие.

Кухня оказалась расположенной в противоположном крыле третьего этажа. Как и ванная комната, она была оборудована в стиле двухтысячных и выглядела неуместной на фоне остального интерьера бюро ритуальных услуг.  

После кратковременной дискуссии, во время которой Агата с безразличным видом опустошала первый за этот вечер бокал, дамы сошлись на том, что ужином (а кому завтраком) им послужит пицца, и вскоре принялись за готовку. Вернее, готовила Нора, в то время как её сожительница разглагольствовала о хемингуэевских героинях и лениво потягивала вино.

– …выходит, что среди перечисленных барышень нет ни одного сильного характера, что слегка удручает.

– А как же Пилар? – бросила Нора, которая пропустила большую часть монолога.

Она покончила с укладкой ингредиентов на корж и с облегчением сунула противень в духовку.

– Пилар скорее исключение из общего правила. Плюс, говорю же, она и близко не является возлюбленной главного героя, а посему я делаю вывод, что Хем концентрируется исключительно на силе духа своих мужских персонажей, чего не скажешь о Ремарке. Взять хотя бы его Элизабет.        

Элеонора устало опустилась на высокий стульчак и плеснула себе воды. Прикончившая третий бокал Агата взглянула на эту картину крайне неодобрительно, но ввиду тёмных очков жест этот остался незамеченным.

Нора не знала, в чем скрывался секрет внезапной болтливости её собеседницы: в вине, или подходящей теме, но решила непременно воспользоваться ситуацией.  

– Послушайте, – начала она, – сегодня вечером, поднявшись на третий этаж, я слышала не только музыку… Мне кажется я слышала голоса.

Агата ничего не ответила.

– Я бы не стала спрашивать просто так, но прошлой ночью произошло кое-что странное.

– Вот как?

– Долгое время я не могла уснуть, а когда удалось, меня разбудили шаги. Я понимаю, как это звучит… Кто-то буквально бродил в стенах, но! Это ещё не самое стрёмное: в какой-то момент у моей кровати появилась высокая фигура, возникшая словно из неоткуда.

Договорив, Нора в ожидании посмотрела на так-себе-собеседницу.

«Сейчас она решит, что я свихнулась, и попросит съехать в ближайшем будущем, – пронеслось в голове девушки. – Возможно, это не худший вариант».

Последовавший вопрос более чем удивил Нору. 

– В это время вы часом не слушали музыку? 

Девушка робко кивнула.

– Пост-панк? – спокойно уточнила Агата? – Что это было: Кьюр, Джой Дивижн? Или, может быть, что-нибудь поновее, Бон Ивер, скажем?

– Интерпол, – тихо ответила Нора, пораженная до глубины души.

– Тем более!

Губы Агаты изогнулись в подобии улыбки.

– Да будет вам, – произнесла она, завидев побелевшее личико Норы.

– Почему вы спросили о музыке? – только и нашлась девушка.

Агата осушила свой бокал.

– Потому что только так можно выманить Владислава из его окопов. 

Нора удивленно приоткрыла губы.

– С ударением на «и», – между тем заметила Агата.

## 16 {-#16}

Владислав Мирославский был местным таксидермистом…

– Таксидермистом? – с недоверием переспросила Элеонора.

Агата задумчиво кивнула.

– Некоторые клиенты бюро прибегают к подобного рода услугам, – объяснила она, и Нора брезгливо поёжилась. – Но чаще всего Ласло выступает в роли визажиста. Знаете, старается приукрасить трупики, чтобы те не выглядели очень уж плачевно.

Так вот, Владислав Мирославский был местным таксидермистом, а по совместительству и ярым социофобом, что лишь укрепляло их дружбу с Агатой: руководствуясь разными причинами, оба всё же не питали любви к человечеству и старательно избирали круг общения. Однако, если Агата могла находится в компании незнакомцев, о Владиславе никак нельзя было сказать того же. С годами боязнь общества, поселившаяся в голове последнего, лишь укрепилась и, так как работа в бюро («К моему глубочайшему сожалению,» – заметила Агата) ритуальных услуг отчасти подразумевала периодическое присутствие в здании живых людей, друзьям пришлось искать компромисс. 

Как выяснилось, Владислава не пугали люди, которые не могли его увидеть, так что вскоре Агата нашла выход. После долгих лет, проведенных в старом здании, ей были известны все тайные ходы, комнаты и лестницы, скрытые от посторонних глаз, а таковых в доме оказалось не меньше комнат. В большинстве своем, ходы представляли незамысловатую оптическую иллюзию: они тянулись промеж толстых каменных стен и оканчивались у наружной стороны какой-нибудь спальни; стена в том месте переходила в двойную, но из-за однотонных черных обоев, которыми стены были обклеены с обеих сторон, этого никак нельзя было заметить невооруженным взглядом.

С помощью таких коридоров Владислав мог свободно перемещаться по дому, без страха быть замеченным. Жил он, кстати, в одной из тайных комнат, находившейся на последнем этаже.

Хозяйка дома отвела Нору в дальнюю гостевую спальню и велела ей стать в то самое место, где минувшей ночью девушка видела испугавший её силуэт.

– Здесь, – произнесла Элеонора, остановившись в метре от окна. – Но я ничего не вижу.

Агата отрицательно покачала головой.

– Вплотную к окну.

Нора послушно сделала два шага вперед.

Справа от неё все так же была черная стена. Руководствуясь рассказом Агаты, девушка вытянула руку и ахнула: кончики пальцев скрылись к темноте. Она бросила вопросительный взгляд в сторону Агаты. 

Та кивнула, и Нора сделала еще несколько шагов в темноту, а когда наткнулась на стену, интуитивно свернула влево. Вскоре лица коснулось что-то гладкое и лёгкое. Этим чем-то оказалась чёрная как смоль занавесь, откинув которую, Элеоноре открылся узкий, но хорошо освещенный каменный коридор. Она ещё какое-то время заинтересованно разглядывала это место, после чего вернулась в спальню.

– Надо же! – восхищенно выпалила девушка. – Как тонко продумано! Выдающееся изобретение!

Агата довольно кивнула.

– Шторку я сама повесила. Остальное шло в комплекте с домом.

– А картины? – вспомнила Элеонора. – Вчера мне показалось, что «Женщина дождя» взглянула прямиком на меня.

Агата вновь кивнула.

– Бюро украшает около ста пятидесяти портретов, но резать эту мне было сложней всего. «Женщина дождя» – моя любимая. К счастью, Владислав проделал всё очень осторожно.

Они уже практически достигли кухни, когда послышался равномерный гудок – пицца была готова.

Однако, у Норы оставался ещё один вопрос.

– Но почему вы не сказали мне раньше? 

– О Владиславе?

– Да.

– Понимаете, – ухмыльнулась Агата, поправляя очки, – порой я и сама о нем забываю.

## 17 {-#17}

– Раз уж вы благополучно пережили встречу с Ласло и не сбежали, предлагаю перейти на «ты», – Агата отправила в рот кусок пиццы и поспешно залила это дело вином.

Она проделывала сей ритуал с каждый куском, и Норе не удалось скрыть своего удивления.

– Когда много пьешь, любая еда становится пресной, – добавила Агата. – Так что скажите?

– Всеми руками «за»! – весело ответила Элеонора. Её лицо осветила широкая улыбка. – В таком случае, позволено ли мне спрашивать, откуда у тебя столько вина?

Дама устремила бледное лицо в стороны Норы.

– Я так понимаю, ты не спускалась в винный погреб?

– Нет, а что там?

Очки помешали миру увидеть очередной саркастичный взгляд Агаты Рахманиновой. 

– Вино.

– А я думала мексиканцы, – таким же безразличным тоном заметила Элеонора.

Агата прекратила жевать, отставила бокал и… расхохоталась.

– Тарантиновские диалоги, – отдышавшись, сказала она. – Мои любимые. 

Девушка улыбнулась в ответ, ожидая продолжения. 

– Вино я произвожу сама, за домом есть крохотный виноградник.

– Правда? 

Агата ответила утвердительно и в этот раз наполнила два бокала. 

– Бартендер, художник, арендодатель и владелица бюро ритуальных услуг, – перечислила Агата. – Временами выступаю в роли пост-мортем фотографа.

– Так значит похоронное бюро не твой основной род деятельности?

Дама в чёрном пожала плечами.

– В последние годы дела в бюро идут не то чтобы очень, потому я и решила сдавать пустующий этаж. Наверное, здесь всё дело в моей харизме.

– А что с ней?

– Она отсутствует.

За стеной послышались приглушенные шаги.

«Крадется, паразит!» – подумала Элеонора.

Обе девушки взглянули в сторону единственной картины, висящей в отведенной под кухню комнате – гротескного портрета Гоголя, выполненного в красно-синих тонах.

Глаза Николая Васильевича оставались на месте и вскоре шаги начали отдаляться.

– Передумал, – разочарованно произнесла Агата.

Она потянулась к бутылке, как вдруг недовольно вскрикнула.

– Вот чёрт?

– Что случилось? – встревожилась Нора.

– Винишко, – печально произнесла Агата. – Оно закончилось. 

## 18 {-#18}

Солнцезащитные очки особы по имени Агата Рахманинова имели зеркальное покрытие и едва ли применялись по назначению. Будучи натурой компанейской, Элеонора как могла пыталась подстраиваться под мэнсоновский режим[^22], так что уже на третий день пребывания в "Маятнике" собственное отражение являлось Элеоноре чаще чем солнечный свет.

[^22]: Имеется в виду распорядок дня Мэрлина Мэнсона: музыкант как-то признался, что предпочитает бодрствовать по ночам.

Девушка просыпалась задолго после полудня с твердым намерением не сомкнуть глаз до двух, а то и трёх часов ночи. Обычно она проводила в постели ещё какое-то время: читала и бороздила просторы всемирной паутины. Затем отправлялась на кухню, где с грациозностью шанхайского рыцаря варганила поздний завтрак, остерегаясь преждевременного пробуждения хозяйки дома. Светлыми днями, распрощавшись с голодом, Нора отправлялась гулять по городу, и каждый раз открывала для себя новые, приятные сердцу места, что удивительно, учитывая масштабы Львова. Если же погода оставляла желать лучшего, девушка возвращалась на свой этаж, чтобы почитать новости и укрепить графоманию.  

Одним таким дождливым днем, Нора сидела у окна гостиной, наблюдая за тем, как зимнее солнце плавно опускается за горизонт. Паркет в радиусе метра от неё был усыпан скомканными страницами – работа над рукописью продвигалась ужасно медленно. 

Избавившись от очередного листа и крепко выругавшись, девушка, наконец, задействовала эффект болта и спустилась в винный погреб, решив как следует набраться по этому поводу.

Когда вино обратилось мёдом, а до встречи с дном бутылки оставалось всего ничего, Нора услышала приближающиеся шаги. Наивно решив, что сегодня Агата поднялась раньше, девушка обернулась. Естественно, она никого не увидела.

«Владислав, чёртов ты засранец!» – мелькнуло в голове.

Изредка она слышала льющиеся за стенами шаги, так что уже не предавала этому особого значения.

«А у него хороший вкус», – улыбнулась девушка: в тот вечер она слушала Колдплей.

Следующая мысль поразила Нору не своим контекстом, но тем фактом, что она раньше не задала себе этот вопрос.

«Почему он просто сам не ставит музыку?» – поразительно, как временами хмельное сознание рождает трезвые мысли.

Позже Агата объяснила, что Владислав старается не нарушать тишину из-за страха быть услышанным.

– Радуйся, что дела обстоят именно так, – ухмыльнулась гоздиня. – В отсутствии гостей он завывает как кретин и сутки напролет может слушать одну и ту же песню.

– Ты преувеличиваешь, – вежливо заметила Элеонора, думая о том, что предмет их обсуждения, возможно, сидит за ближайшей стеной, внимательно вслушиваясь в диалог.

– Вовсе нет. Достаточно просто изучить его профиль на ласт.фм. Там всё задокументировано.

Так вот, услышав шаги и определив их источник, Нора продолжила играть в Хемингуэйа и вскоре её унесла сладкая дрёма. 

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

– Ну, надо же, – раздался знакомый потусторонний голос.

Нора медленно выплыла из глубин сна. 

Открыв глаза, она первым делом встретилась со своим залипшим личиком – ухмыляющаяся Агата склонилась над ней. Высокая, в траурных одеждах, она походила на предвестника смерти, кем, в общем-то, и являлась. В руках дама держала пустую бутылку, которую Нора выронила аккурат перед тем, как провалиться в сон.

– Мне ещё рано, – простонала Элеонора.

На лице Агаты проступило недоумение.

Она хмыкнула, уселась напротив плохо соображающей девушки и закурила.

– Есть вопрос, – произнесла Нора, когда ход её мыслей вернулся в прежнее русло.

Агата подождала, пока собеседница откашляется, и протянула ей бокал.

– Ой, нет! – запротестовала девушка, заметив в нем вино.

Она хотела спросить о предназначении очков, но в последнюю секунду передумала, вспомнив вчерашний разговор. Каждый раз, когда Элеонора пыталась затронуть относительно личные темы, так-себе-собеседница превращалась в генератор рандомных фактов, так или иначе связанных со смертью. Так она узнала, что урной для изобретателя пачки Принглс послужило его же детище – банка-тубус, а еще – что на японском и китайском языках число четыре созвучно слову "смерть".

– Почему ты решила открыть бюро? 

– Однажды я сказала своей матери, что если она и может меня за что-то судить, так это за оказание ритуальных услуг без лицензии, – прозвучал ответ.

Нора облегченно вздохнула. Она и не подозревала, что это была ссылка на очередную увлекательную историю[^23].

[^23]: «Единственное, за что Вы меня можете осудить, так это за оказание ритуальных услуг без лицензии» – слова Джона Уэйна Гейтси, американского серийного убийцы прошлого века, также известного как «убийца-клоун» благодаря своим выступлениям на детских праздниках.  

И слава богу.

– На самом деле, "Маятник" был здесь ещё задолго до моего рождения. Похоронный дом, так он тогда назывался. Видела дома, стоящие по ту сторону кладбища? – тонкая рука вынырнула из моря чёрных складок, указывая в правую сторону. 

– Многоэтажки?

Агата кивнула.

– В тёплую пору года моё детство проходило далеко отсюда, но всё остальное время я жила в одном из этих домов, – чёртово гетто с прекрасным видом на некрополь. Последний с детства служил мне парком и игровой площадкой, за неимением других вариантов. Чудом окончила школу, никого не убив, а спустя несколько лет, когда дом дал трещину и жить в нём стало совсем невмоготу, стала подыскивать альтернативу. Денег было чуть менее чем ничего, а потому приличное жилье в районе Старого города мне едва ли удалось бы арендовать. Я даже задумывалась, а не поселиться ли на улице Джона Леннона, но название оказалось её единственным плюсом.

Словом, ситуация вырисовывалась плачевная. Уже тогда я начала предпринимать первые попытки виноделия. Как-то вечером стояла у окна с полным бокалом новехонького вина. Аромат напиток имел превосходный, но при более близком знакомстве выяснилось, что употреблять его невозможно. Быстро и много пить я умела уже тогда и, сделав это по неосторожности, поняла, что меня вот-вот вывернет наизнанку. На путешествие в ванную времени не оставалось, и я выблевала всё в окно. Детище моё оказалось воистину убийственным: трясло минут пятнадцать, и наконец разогнувшись, я почувствовала себя Энди Дюфрейном, выбравшимся из Шоушенка. Никогда ещё воздух не казался мне столь сладким, а закат не виделся таким прекрасным. Глубоко и прерывисто дыша, я задержалась у окна, пытаясь насладиться видом и заодно придти в себя. Тогда-то взгляд и задержался на «Маятнике». Я вспомнила, что уже с полжизни не видела, чтобы в нем проводились церемонии прощания и следующим утром связалась с нужными людьми.

Выяснилось, что владелец похоронного дома давно покинул этот бренным мир, не оставив после себя наследников. В итоге здание перешло в руки внука троюродной тетки покойного, который к тому времени жил в Одессе и не имел ни малейшего желания заниматься подобного рода бизнесом. Юноша даже не пытался продать бюро, которое с момента смерти хозяина стояло нетронутым. Услышав моё предложение, он первым же поездом примчался во Львов для оформления документов. Вероятно, боялся, что я передумаю.

Но я не передумала. Здание полюбилось мне с первого взгляда, да и район был подходящий, учитывая моё отношение к социуму. Ласло сказал, что это судьба.

– Владислав?

Агата кивнула.

– Мы и тогда были соседями. 

К этому моменту Элеонора уже окончательно оправилась от алкогольного сна. Она попросила подкурить, после чего спросила:

– И ты тут же возобновила работу бюро?

Привычная ухмылка.

– За кого ты меня держишь? Первые полтора месяца я просто жила здесь на деньги, оставшиеся с суммы компенсации старой квартиры, но в скорости и они закончились. Тогда я решила возобновить работу «Маятника». А почему, собственно нет? Всего-то требовалось получить лицензию и наладить торговые связи. Остальное и так было при мне.

– И ты жила здесь одна всё то время? – поинтересовалась Нора.

Агата помрачнела, если это выражение вообще подходит для описания дамы в стиле Эдгара По. Она нервно провела пальцами по оправе очков. Губы слегка вздрогнули.

– Владислав въехал позже, – уклончиво ответила Агата. – После открытия бюро.

Она предпочла превратиться в так-себе-собеседницу и Норе не удалось вытянуть из нее что-нибудь существенное. Не считая историй о смерти, разумеется.  

Тем вечером Агата впервые удалилась в спальню раньше Элеоноры.

«Возможно, она просто плохо спала,» – с надеждой подумала девушка.

Однако, глубокой ночью, поднимаясь на кухню за новой порцией бодрящего кофе, (она не оставляла попыток справиться с рукописью) Нора слышала печальную музыку, льющуюся из апартаментов хозяйки дома. 

## 19 {-#19}

Первая неделя пребывания в «Маятнике» подходила к концу.

Элеонора все так же не виделась с ночным призраком, но время от времени слышала как Владислав бродит по своим каменным коридорам.

После каждых ночных посиделок таинственная владелица похоронного бюро нравилась ей все больше: вопреки своей отстраненности (наследственной, или приобретенной – Нора не знала) Агата обладала неким шармом. Загадочность, вот что влекло девушку. Она уже знала, что Агате известно о смерти и теперь хотела выяснить, что же та знает о жизни. 

При взгляде, брошенном со стороны, создавалось впечатление, что Агата прошла через несколько столетий, и плевать хотела на каждое из них. Но так ли это было на самом деле? Возможно, она и вовсе не покидала пределов родного города.

– О жизни, о смерти… – скользнуло в голове, и Элеонора мигом просияла: она вдруг поняла, как завоевать внимание Агаты грядущим вечером.

Относительно новой приятельницы её интересовали как минимум две вещи. Во-первых, Элеонора никак не могла определиться с возрастом Агаты. Вблизи та выглядела молодой, если не сказать юной: лицо и руки были матовыми, нетронутую морщинами кожу нарушали лишь едва заметная морщина на лбу и складка у левого уголка губ. Результат любимых жестов Агаты, решила девушка, ухмылки и вздергивания бровей.

Однако, голос Агаты звучал довольно взросло, а иронично-саркастичные нотки, граничащие с безразличием, только добавляли лет.  

Тогда Элеонора решила записать всё то, что узнала об Агате за прошедшую неделю. К тому же, с зажатой между пальцев ручкой девушке всегда думалось гораздо проще.

> *Агата как-то упомянула, что она возобновила работу «Маятника» почти шесть лет назад… Или четыре? Я всегда путала эти числа.*

Нора закусила губу. Ей также не составляло труда принять оранжевый цвет за зеленый и наоборот, но к счастью это не имело отношения к делу.

Перечислив все, что она смогла вспомнить о хозяйке дома, Нора в недоумении уставилась на свою записную книгу: подобные подвиги должны занять лет эдак сорок.

«Окей, – решила девушка. – Оставим пока цифры».

В конце концов о возрасте Агаты она могла узнать и от Владислава, и хотя на сегодняшний день контакт с последним казался немыслимым, Элеонора с робкой надеждой верила, что однажды ей удастся провести вечер в компании своего призрака, когда оба будут по одну и ту же сторону стены.

Куда больше Элеонору интересовало предназначение солнцезащитных очков на лице подруги.

«Подруги?»

Она на мгновенье задумалась, вспомнив относительно недавний диалог с хозяйкой дома.

В тот вечер девушка намеревалась позвонить домой, желая справиться о делах, и в ходе разговора рассказать о пребывании в новом городе, естественно, опустив все траурные подробности.

– Маме приятно будет услышать, что я завела друга в свою первую неделю во Львове, – поделилась Нора.

Агата нахмурилась.

– Я не завожу друзей, – заметила та.

Девушка с недоверием взглянула на свою собеседницу.

– А что насчет Владислава?

Привычная ухмылка.

– Ласло был рядом задолго до того, как я узнала о предназначении дырки между ног.

«По всей видимости, здесь не поспоришь», – с грустью подумала Элеонора, но вопреки этому начала все чаще воспринимать Агату как друга.

Она вернулась к записям.

> *Сначала я решила, что причина очков кроется в алкоголизме, но уже следующим утром заметила, что Агата носит их и до того, как взяться за выпивку. К тому же, у нее, похоже, не бывает похмелья.*
> 
> *Слепота сразу отпадает: временами мы читали в гостиной по очереди.*
>
> *Возможно, это астигматические очки, затемненные лишь с одной стороны? В выборе цвета Агата не отличается особой оригинальностью, так что я не удивилась бы, окажись моё предположение верным.*
> 
> *Светобоязнь – самая логичная причина, но ведь (даже если забить на то, что она вообще не бодрствует в светлое время суток, а кстати, почему?) я опять-таки видела Агату в очках чуть ли не в кромешной тьме. Допустим, светобоязнь может быть симптомом какой-то другой болезни, а предмет моих размышлений уже настолько сросся с очками, что снимает их только перед сном?*
> 
> *А, может, они наоборот – с подсветкой?*

Нора улыбнулась, довольная собой. Последний вариант уж точно ни к селу ни к городу, но тот, что был до него действительно виделся девушке наиболее реалистичным.

> *В таком случае, нет ничего дурного в том, чтобы поинтересоваться предназначением очков.*

На этой одушевляющей нотке девушка захлопнула блокнот и отправилась в гостиную, дабы проверить, не появилась ли Агата. Нора провела там всего несколько минут – задержалась, чтобы поставить музыку и немного повозилась с проигрывателем. 

Агата ещё не проснулась, но по возвращении в спальню Элеонору ожидал сюрприз. Записная книга, о которой девушка точно помнила, что захлопнула, лежала там же, где её оставили, только вот открытая на последней записи, к которой чужая рука бережно добавила лишь одно предложение низким, закругленным почерком.

> *Не стоит это делать.*

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

– Не стоит это делать, – медленно произнесла Элеонора, словно хотела попробовать фразу на вкус.

Никаких подписей, объяснений, или иных инструкций; даже восклицательный знак отсутствовал. Только «не стоит это делать». Под стать владелице дома, Владислав умел быть таинственным.

«Тогда расскажи сам», – чуть ниже написала Нора. 

Девушка покинула пределы спальни, оставив блокнот открытым.

Она проголодалась и устала дожидаться Агату.

## 20 {-#20}

– Gnaghi! – сказал Франческо Делламоре.

– Шикарно! – сказала Агата.

– Есть такое, – согласилась Элеонора.

– Определенно мой любимый фильм, – продолжала дама. – Расставляет все по полочкам, создавая при этом ещё больший бардак в голове.

– Вообще-то, я надеялась, что ты его не видела.

Нора смущенно улыбнулась.

Ответом послужила широкая бровь, традиционно выглядывающая из-под очков.

– Считаешь, вы похожи?

Агата не ответила.

– Я имею ввиду, тебе действительно нравится жить на окраине кладбища? – добавила Нора. – Не многим пришлось бы это по душе.

– Тебе действительно нравиться пить чай без сахара? – прозвучал бесстрастный ответ.

Элеонора задумалась, после чего улыбнулась.

– Я тебя поняла.

Агата кивнула.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Ожидания оказались напрасными: Владислав больше ни слова не сказал. Даже на бумаге.

– Как продвигается работа над книгой? – внезапно спросила Агата.

Расположившись в своем кресле, она несколько часов просидела с книгой в руках не проронив и слова, а потому успевшая забыть о её присутствии Нора непроизвольно вздрогнула, услышав низкий потусторонний голос.

За это время девушке удалось выдавить из себя не более пяти страниц, и хотя по сравнению со вчерашними результатами этот явно был достижением, Нора осталась недовольна. 

Ближе к ночи холода вновь решили напомнить о себе. Ветер скользил за окном, лаская ветви деревьев, и те время от времени касались витражей. Элеонора сидела в постели, бесцельно перебирая волосы: несмотря на то, что часы уже оповестили о наступлении трёх ночи, спать не хотелось. Параллельно девушка штудировала интернет, подыскивая достойный внимания фильм. Она в который раз отметила про себя, как странно техника сочетается с убранством её апартаментов.

Спустя минут десять таких поисков Элеонора услышала топот. Кто-то вновь прогуливался по стенам. Шаги тем временем приближались, на сей раз звуча гораздо четче: казалось их обладатель не пытался скрывать своего присутствия. Остановились они у самого окна.     

По ту сторону стены раздался стук.

– Войдите? – нерешительно произнесла Элеонора.

Как и в прошлый раз, силуэт возник из ниоткуда. Сначала показалась бледная рука, затем плечо и, наконец, спрятавшееся за очками лицо: на этот раз Нору навестила гостья, а не гость.

Перед ней выросла Агата. Поверх траурных одежд было накинуто пальто соответствующего цвета.

– Я вижу, ты не спишь, – произнесла дама и указала на стену. – Слышимость отличная, если находишься внутри.

– Сна ни в одном глазу, – только и нашлась Нора.

С её лица не сходило удивление, заметив которое, Агата объяснила:

– Так быстрее.

– Ты откуда, или куда? – поинтересовалась девушка.

Агата сдвинула шляпку на затылок и застегнула пальто.

– Собираюсь прогуляться, хочешь присоединиться?

Нора отложила телефон.

## 21 {-#21}

К тому времени как дамы вышли на улицу ветер разгулялся не на шутку, и вскоре Норе открылось, что её загадочная спутница по совместительству является ругательницей высшего класса: шляпку Агаты несколько раз уносило в ночь.

Элеонора же, будучи уроженкой городка, который она не стала бы называть и при самых критических обстоятельствах, к шторму привыкла, а потому шляпок не носила. В паре метров от входа в бюро находилась парочка изредка работающих фонарей. На удивление, той ночью они были исправны. Нора стояла на гранитной тропинке, дожидаясь пока Агата возьмет верх над ветром в битве за любимый головной убор. Девушка чувствовала как по коже гуляют ледяные порывы дыхания ночи; в глазах отражался свет уличных фонарей, превращая их из зеленых в медовые – поворачивать назад совсем не хотелось.

Погода навеивала воспоминания о доме. Перед глазами всплывали ветреные вечера: пустынные грязные улицы, объятые лишь серой чередой бесконечных многоэтажек.

Нет, поворачивать назад совсем не хотелось.

– Графиня в метаньях, – сквозь пелену воспоминаний прозвучал голос Агаты.

Судя по звуку, дама уже отвоевала шляпку и теперь находилась в паре метров от Элеоноры, но вне площади озаренной желтым светом фонарей.

– Что?

– Спрашиваю, идёшь ли ты? Я здесь уже пару минут стою.

Нора старательно всмотрелась в темноту и, наконец, увидела собеседницу. Последнюю выдавали лишь огоньки света, плавно отражающиеся в стёклах очков.

– Прости, – ответила Нора. Она сделала пару шагов в направлении Агаты. – Ничерта не вижу. Ты гармонируешь с ночью.

Девушка не могла утверждать наверняка, но она буквально почувствовала, как подруга ухмыльнулась.

– И темнота вокруг неё шумела, словно прибой сумрачного моря, – изрекла Агата. 

– Ремарк?

– Ремарк.

Нора улыбнулась: высказывание её понравилось.

– Вообще-то он говорил о дереве, – добавила Агата, – но кому какое дело, когда речь заходит о поэтике. 

– Это вполне в твоём стиле.

Агата остановилась и взглянула на Нору, которая, наконец, начала различать в темноте очертания предметов.

– У меня есть стиль? – озадаченно поинтересовалась Агата.

Нора бросила в её сторону удивленный взгляд.

– Шутишь?

Дама покачала головой.

Элеоноре понадобилось секунд десять на размышления.

– Мрачный винтаж, – с уверенностью произнесла она.

– Хм… А мне нравится.

Агата расхохоталась.

– Ещё бы, – вторила присоединившаяся к ней девушка.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

– Не то чтобы я была сильно удивлена, – спустя дюжину метров заметила Элеонора, – но где-то в глубине моей души все же таилась робкая надежда на то, что мы погуляем вне кладбища.

Ответа не последовало.

– Просто я по-прежнему едва ли вижу в темноте, так что, если у тебя в очках не спрятаны фонари дальнего виденья, в чем я немножко сомневаюсь, близок час моего падения в…

– Погоди, – спокойно сказала Агата.

– Да?

– Просто погоди.

Нора непроизвольно закатила глаза.

– Ладно. А куда идти-то?

Агата приоткрыла рот и тут же клацнула языком. Так, словно собиралась указать девушке нужное направление, но в последний момент передумала. Нора, в свою очередь, без особого труда догадалась, какой пункт назначения ей хотели предложить, а посему решила повременить с расспросами.

Удалось ей это так себе.

– На днях я размышляла…

– Это полезно. Продолжай в том же духе.

Филантроп-Элеонора с лёгкостью проигнорировала этот ответ, как поступала и со всеми последующими колкими фразочками, слетевшими с уст владелицы похоронного бюро.

– …я размышляла и заметила странную штуку…

«Далеко не одну, – подумала Нора, – но, говорят, надо начинать с мелочей».

– Только одну? – словно прочитав её мысли, переспросила Агата, и Нора сказала собеседнице то же, что говорила себе минуту назад.

– Я слушаю.

– Как тебе удается заниматься прощальными церемониями, если те традиционно проходят в дополуденное время, когда ты видишь десятый сон? – на одном дыхании спросила девушка.

– С большим трудом и нечеловеческими усилиями.

Нора с недоверием взглянула на Агату.

– Ты ведь не оставляешь родственников усопшего предоставленными самим себе?

– Было пару раз, – последовал ответ. – На самом деле, я уже месяцев пять не занималась работой. Потому и подала объявление о сдаче этажа.

– Ясно.

Шли они с четверть часа.

Ветер продолжал играть с одеждой и волосами. Вчерашний снег обратился тонким льдом, создавая для девушки особенно травматические условия. Ориентироваться в пространстве было непросто. Приложив усилия, Нора заключила, что они сделали крюк вокруг бюро и теперь продвигались вглубь кладбища.

– Ещё один поворот, – Агата нарушила тишину неожиданно жизнерадостным голосом.

Девушка с радостью преодолела этот самый поворот. 

Открывшийся вид заставил Элеонору остановиться и медленно выдохнуть ночной воздух. Перед ней простиралась аллея склепов, усеянная множеством белых огоньков. Первой мыслью, пришедшей в голову девушки были светлячки. Однако, откуда им взяться в разгар декабря, да еще и на Западе Украины?

– Солнечные лампы, – догадалась Нора.

С их помощью кладбище выглядело очаровательным и совсем не страшным. Каменные, увенчанные соснами аллеи скорее походили на задний дворик какого-нибудь загородного дома, нежели на обитель мёртвых. Для получения полной картины, добавьте к этому всеобъемлющую тишину, нарушаемую лишь мерным шепотом веток.

– Выглядит – не побоюсь этого слова – уютно, – зачарованным голосом произнесла девушка. – Это ты сделала?

Агата согласно кивнула головой.

– Что же, должна признать на этот раз ты меня действительно поразила!

– Я сделала это и для себя, но в первую очередь для Ласло. В канун прошлого нового года этот любитель безлюдных мест подвернул ногу вон у того склепа и еще часа четыре провел в сугробе.

Агата извлекла из внутреннего кармана пальто портсигар, (в белом свете фонариков Нора увидела надпись: «Восемь из десяти курильщиков умирают. Двое оставшихся, видимо, живут вечно») и подкурила. Нора проделала то же самое.

Со свойственной ей меланхолией, Агата склонилась над одним из склепов и принялась поджигать толстую свечу, стоящую на постаменте.

– Зачем ты это делаешь? – удивилась Нора.

– Родственники усопших регулярно просят меня зажигать свечи на могилах их близких. Считают, что таким образом духи мёртвых находят покой.

– И ты с ними согласна?

– Мне за это платят, – просто ответила Агата. – К тому же, процесс не занимает много времени.

– А у меня он вот едва ли вызывает доверие.

Агата откинула с лица прядь волос и направилась к следующему склепу.

– Полноте, – сказала она. – Индонезийцы вот вообще любители подвешивать на скалах гробы со свеженькими покойниками, а затем дружно отмечать это д    ело. 

– Это еще для чего?

– Ну, они верят, что горы являются проводниками между земным и небесным мирами, или что-то вроде того. А вот младенцев они хоронят в дуплах, но только тех, у кого еще не прорезались зубы.

Лицо Норы выражало сомнения, смешанные с удивлением.

– Только не говори, что дерево здесь выступает проводником душ этих несчастных…

– Именно.

Девушка хмыкнула. Она подошла к соседнему склепу и вскоре зажгла тамошнюю свечу.  

– А ты сама что об этом думаешь? – поинтересовалась Элеонора.

– Слишком долгий выйдет рассказ, – произнесла Агата, не отрываясь от дела. – Но детей я в дуплах не прячу, можешь быть спокойна на этот счет.

– У меня есть время.

Какое-то мгновенье Агата смотрела на свою спутницу, вероятно, раздумывая над её вопросом. Затем дама согласно кивнула.

– Мне хочется думать, что умирая мы не исчезаем бесследно, но начинаем новую жизнь, всё ещё овеянные привкусом предыдущей. Сами того не подозревая, круг за кругом как Роланд[^24] идём к своей Башне, преследуя схожие цели. Пускай каждый раз новый, он, всё же, зависит от предыдущего, что может проявляться в мельчайших деталях.

[^24]: Роланд Дискейн – основной персонаж «Темной башни», цикла романов Стивена Кинга.

К примеру, мне представляется как в конце века в мои руки совершенно случайно попадет бутылка вина, сделанного некой Агатой Рахманиновой в далёком двух тысячи пятнадцатом. Наслаждаясь совершенным вкусом напитка, я буду удивляться тому, что человек, живший и усопший столетия назад, обладал алкогольными предпочтениями, идентичными моим. Быть может, с первым глотком меня настигнет дежавю, но чувство это будет столь мимолётным, что ощутить я его смогу лишь глубоко в подсознании.

Возможно, распитие такого вина натолкнет меня на верную мысль, или заставит совершить поступок, который в будущем приблизит меня к цели, а, возможно, тем вечером мне просто удастся славно надраться – оба варианта более чем приемлемы.

Или, допустим, ты. Вообрази, как однажды будешь держать книгу, над которой сейчас работаешь, и осознавать неописуемое родство с автором. Со мной такое часто случается. 

Ещё  мне хочется верить, что за пределами одной жизни мы снова и снова встречаем своих людей. Понимаешь, тех самых, кто ускользнул в этом варианте бытия, но это уже совсем банальные мысли. 

Нора слушала с широко распахнутыми глазами.

– Это хорошие мысли, – подытожила она, когда монолог Агаты подошел к концу. 

Агата улыбнулась, но как-то невесело. 

Норе тут же вспомнилась строка из стихотворения любимого поэта её сожительницы, которую последняя озвучивала по поводу и без: «Луна улыбалась, но мне показалась улыбка её неживой»[^25].

[^25]: Цитата из стихотворения Э.А. По под названием «Вечерняя звезда». 

– Так хочет думать моё сердце. Однако, – Агата коснулась виска указательным пальцем, – всё находится здесь. Это досталось мне вместе с интеллектом.

– Что всё?

Агата вновь улыбнулась. На этот раз гораздо мягче.

– Атеизм.   

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

До рассвета было не менее трёх часов. Погода по-прежнему оставляла желать лучшего, когда наши героини достигли конца аллеи склепов. 

Агата зажгла последнюю свечу и плотнее запахнула полы пальто. Она взглянула на свою спутницу.

– Пожалуй, пора возвращаться, – с готовностью произнесла Нора, стуча зубами.

– Пожалуй, пора, потому что я продрогла настолько, что сейчас с радостью бы поменялась местами с Ярославом Олеговичем, – заметила дама.

– С кем? 

Агата молча указала на склеп, расположенный за спиной её собеседницы, и, обернувшись, Нора прочла надпись:

<p align=center>
<em>
Сплавинский
</em>
</p>

<p align=center>
<em>
Ярослав Олегович
</em>
</p>

<p align=center>
<em>
1836 – 1917
</em>
</p>

## 22 {-#22}

Агата оказалась не единственным художником в доме – рисование являлось ещё одном талантом Элеоноры. В своих портретах ей удавалось удивительно сочетать реализм с абстракционизмом, и, как и каждый художник, девушка уделяла особое внимание работе над изображением глаз.

Нора запаслась кофейно-ромовым коктейлем, к которому её приучила Агата и теперь сидела на крыльце, периодически кутаясь в плед. На дворе стояло позднее утро вторника. С неба просеивался мелкий дождик. Хотя над кладбищем царил хмурый штиль, Нора чувствовала, что грозы этой ночью не миновать, и была совсем не против – осенне-зимняя свежесть ей нравилась. Но не так сильно, как горячий коктейль, конечно.

Нора сделала глоток бодрящего напитка и слегка улыбнулась – возможность напиваться с утреца была ещё очередной славной особенностью львовской жизни: планировка города явно не располагала к вождению автомобиля, от чего девушка, проведшая за рулем последние три года, (очень трезвые три года) получала особое наслаждение. 

На коленях покоилась новая записная книга, что разнилась от предыдущей лишь увеличенным форматом: правая рука Норы уже около часа бесцельно вращала карандаш. Девушка призвала на помощь всё, что только смогла отыскать в своей светлой головушке: воображение, интуицию и прекрасную память на лица. 

Безрезультатно. Лежащий перед ней портрет оставался незавершенным. Не хватало лишь глаз, в остальном сходство с оригиналом было безупречным: шелковые локоны, которым в перспективе предстояло принять цвет молочного шоколада, ниспадали с невысокого лба и струились далеко за пределы рисунка; темные брови правильной формы, (левая, как всегда, более изогнута, над правой виднелась родинка) под вздернутым носом располагался аккуратный рот. Сложенные бантиком губы терялись в сравнении с кончиком носа, посему первые их обладательница подводила темной помадой. Схожим образом Агата старалась выделить практически отсутствующие скулы. Всё это Норе удалось передать с завидной точностью.

Но глаза…

Их девушка не смогла увидеть даже в своем воображении.

Когда время близилось к трём после полудня, а попытки изобразить свою таинственную сожительницу Элеонора уже давно променяла на занятия графоманией, которая тем днем продвигалась как нельзя кстати, на противоположном конце аллеи, ведущей к дому, показалась фигура. Ею оказался плохо одетый мальчишка двенадцати, или тринадцати лет от роду. Тощий, облаченный в потускневшую фуфайку и затёртые до дых брюки, (которые, к тому же, выглядели размеров на пять больше нужного) он приветливо помахал рукой. Поверх копны грязных волос не хватало лишь соломенной шляпы – ну точно персонаж, сошедший со страниц романов Марка Твена.

Элеонора не могла похвастаться опытом общения с детьми, но при вступлении в диалог с братьями нашими меньшими придерживалась всего двух верных правил: всегда улыбаться и никогда не сюсюкаться.

– Цієї ночі трафилось дещо важливе[^26], – заявил мальчик, опуская приветствия.

[^26]: Этой ночью произошло кое-что важное.

Он достиг крыльца и держался так, словно знал девушку не первый год.

– Хорошее, или напротив? – поинтересовалась Нора.

Малец усмехнулся и клацнул языком, напоминая хозяйку «Маятника».

– Та хіба ж буваюсь в світі речі, вийнятково гарні чи злі?[^27] – с задумчивостью древнегреческого философа произнес он.

[^27]: Да разве бывают в мире вещи, исключительно хорошие или плохие?

Нора полагала, что бывают, но спорить не стала: самоуверенность ребенка забавно разбавляла хмурый день.

– У кия два кінці,[^28] – мальчишеская улыбка продемонстрировала зубы заядлого курильщика. – Зрештою, як не живеш, а труни не минеш, та й годі![^29]

[^28]: Палка о двух концах.
[^29]: Как не живешь, гроба не избежишь, и ладно!

Девушка помолчала, не зная, чем ответствовать этому потоку народной мудрости.

– А жіночка в чорному ще почиває?[^30] – наконец, осведомился юный философ.

[^30]: А женщина в чёрном еще отдыхает? 

Элеонора мельком глянула на часы.

– Можешь быть уверен.

Малец в свою очередь внимательно оглядел сидящую перед ним девушку.

– Кола під очима, розтягнутий светр, байдужість до макіяжу та ще й зошит на колінах… Ти, напевно, письменниця![^31]

[^31]: Круги под глазами, растянутый свитер, безразличие к макияжу, да еще и тетрадь на коленках… Ты, должно быть, писатель?

Элеонора смущенно улыбнулась.

– Але з тих, хто тільки починає. Та не дивуйся ти так! Сором’язливість тебе видає: сама ще не знаєш, чи гідна цим займатися, – лицо мальчика растаяло в довольной улыбке. – Я файно знаюся в людях.[^32]

[^32]: Но из тех, кто только начинает. Да не удивляйся ты так! Застенчивость тебя выдает: сама еще не уверена, достойна ли этим заниматься. Я хорошо разбираюсь в людях.

– Багато часу проводиш у суспільстві?[^33] – Нора и сама не заметила, как переключилась на украинский.

[^33]: Много времени проводишь в обществе? 

– Бач чого захотіла! – ребенок оказался хохотуном в десятом поколении. – Господь милував – багацько читаю.[^34]

[^34]: Ишь чего захотела! Бог миловал – много читаю. 

– Так я до чого хилю, – продолжил тот по окончании театральной паузы. – Може даси мені якогось свого зуба?[^35]

[^35]: Так я к чему веду. Может, дашь мне какой-нибудь из своих зубов?

– Даруй?[^36]

[^36]: Прости?

– Ну, зуба, чи щось таке.

– Нащо воно тобі?[^37]

[^37]: Зачем тебе это?

– На випадок успіху твоїх творів, звісно! Якось одна мізковита жіночка вилучила двадцять дві тищи за різець Джона Леннона. І це у євро! Так-то справи й робляться![^38]

[^38]: На случай успеха твоих произведений, конечно! Как-то одна умная женщинка получила двадцать две тысячи за резец Джона Леннона. И это в евро! Так-то дела и делаются! 

Нора залилась смехом.

– Ну то як, ми домовилися?[^39] – спросил малец с лукавой улыбкой, что ни на минуту не сходила с его лица.

[^39]: Ну так что, мы договорились?

– Я подумаю, – уклончиво ответила Нора.

Этому её научила Агата, сама того не ведая.

Малец пожал плечами.

– Піймав не піймав, а поганятися можна.[^40]

[^40]: Попытка не пытка.

Он расстегнул фуфайку и принялся исследовать содержимое карманов, в следствии чего девушка увидела леденец, надкушенный коржик, горсть монет, коробок спичек, моток ржавой проволоки и странного рода предмет, походивший на железную рогатку о четырёх концах.

«Он же не собирается торговаться за мой зуб?» – с сомненьем подумала Элеонора.

Тем временем юный предприниматель нашел что искал, и протянул девушке квадратный конверт бордового цвета.

– Передаси це жінці в чорному.[^41]

[^41]: Передашь это женщине в чёрном.

Нора осмотрела предмет: на лицевой стороне конверта красовалось знакомое изображение маятника, на обратной лермонтовским почерком вывели:

*Агате Р.*

*Отправитель: Валерий С.*

Завершивший свою миссию приверженец английских традиций уже удалялся из поля зрения. 

– Постой! – крикнула ему вслед Нора. – Что мне сказать Агате?

Малец ответил не оборачиваясь.

– Скажи, що заскочив Гек. Вона зрозуміє.[^42]

[^42]: Скажи, Гек забегал. Она поймет.

«Гек, – улыбнулась Нора. – И как я сама не догадалась?»

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Вечер не задался с первого акта.

Часы пробили начало девятого. Вошедшая в гостиную комнату Агата сообщила, что не выспалась. Нора же, в свою очередь, впервые увидела приятельницу в домашней одежде – помимо очков на Агате виднелся лишь халат, само собой черный; волосы растрепались до невозможности и непослушными прядями вились вокруг лица, аля Дженис Джоплин. 

Дама прикрыла рукой зевок и плюхнулась в кресло.    

– Ты проспала больше четырнадцати часов, – в недоумении произнесла Элеонора.

– У меня нет проблем с простейшими вычислениями, – сухо заметила Агата и, помедлив, добавила: – Чего нельзя сказать о сне.

– Это уж точно.

– Не сплю сутками, чтобы затем спать сутками, а, проснувшись, вновь не спать сутками… Винишка ради, спрячь этот жалостливый взгляд!

Нора повиновалась.

– И так было всегда? – спросила она.

– Нет. Но другой жизни я не помню.

У девушки сложилось впечатление, что ещё немного и Агата вновь обратится так- себе-собеседницей, так что она поспешно подкурила и с превеликим интересом взялась изучать собственные ногти.

Агата потягивала излюбленный напиток и наблюдала за этой картиной со свойственным ей безразличием.

Выждав несколько минут, Нора решила сменить тему.

– До Нового года менее двух недель, – начала она. – Может, пора заняться украшением дома? Я могла бы хоть завтра съездить за ёлкой, если ты не против.

– Я против.

Элеонора нахмурилась.

– Ну чего ты? – произнесла девушка как можно мягче.

– Не люблю праздники. Их приближение слишком переоценено и зачастую предзнаменует одни грядущие неприятности, так что никаких ёлок, но в подсобке найдётся парочка сосновых гробов. Разрешаю тебе нарядить их.

Нора бросила недоверчивый взгляд в сторону говорившей, но та то ли проигнорировала, то ли и вовсе не заметила этот жест.

– Шутишь?

– Вовсе нет. Подсобка слева от лестницы первого этажа, – спокойно ответила Агата.

Нора вздохнула, всеми силами стараясь не изображать Роберта Дауни младшего.[^43]

[^43]:  Т.е. не закатывать глаз.

– Я говорю о твоем отношении к праздникам, – произнесла она, про себя добавив: «саркастичная ты бестолочь», а затем: – Тебе не кажется, что здесь слишком много предрассудков?

Агата покачала головой.

– В общем-то, нет.

– Послушай, – не сдавалась Нора. – Позволь мне обустроить все? Хотя бы в гостиной и холе. Обещаю, проблем не будет!

Агата не ответила. Её внимание привлёк конверт, лежащий на кофейном столике.

– Ах да, Гек заходил, – вспомнила Нора, проследив за взглядом подруги. – Странный малый…

Агата приподнялась и нехотя потянулась за посланием. Лицо её помрачнело еще до того как конверт был вскрыт.

– Понеслась, – невесело бросила Агата.

## 23 {-#23}

Элеонора распахнула глаза задолго до официального наступления утра. Пространство вокруг поглотила привычная тьма, под воздействием которой в комнатах девушки, несмотря на их богатое убранство, царило лишь два цвета: черный и серый. От этой мысли сразу делалось как-то одиноко. 

Она лежала на правом боку и разглядывала свои ноги, гадая почему часы перед рассветом – самые холодные в сутках. Говорят, именно это время является для гробовщиков наиболее плодотворным потому, что большинство потенциальных покойников умирает незадолго до восхода солнца. «Отходят» – так принято говорить в больницах, постояльцы которых прекрасно осведомлены о вырисовывающейся статистике, отчего не скрывают своего страха перед предрассветными часами. Многие не хотят оставаться в одиночестве и башляют последние, предназначавшиеся для поездки в солнечную Испанию или обустройства  загородного дома сбережения ночным сиделкам. 

Часы в гостиной пробили четыре утра. Эхо разнеслось по всему этажу, если не зданию. Девушка подумала об умирающих. Сотни тысяч одиноких душ, разбросанных по всему миру, которые бессонно лежали в своих постелях, готовясь расстаться с жизнью. 

Нора выдохнула и медленно подняла голову, словно только пробудилась ото сна. Она лениво направилась в душ и, прежде чем включить воду, замерла, прислушиваясь к стенам, надеясь услышать шаги, или звуки музыки. Однако, немногие постояльцы «Маятника» еще спали в своих постелях. Тишину не нарушало ничего, кроме разыгрывающейся на улице вьюги.

Душ не занял много времени. По крайней мере, Норе хотелось на это надеяться. 

Нужно было выдвигаться. День обещал быть тяжелым и, судя по всему, очень долгим.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Дорога, по которой она шла, казалась девушке чьим-то неудачным наброском. Солнце по-прежнему таилось за горизонтом, посему и голые кроны деревьев, объятые инеем, и сугробы с выглядывающими из них надгробиями, и даже бесконечное количество снежинок, что кружили вокруг – все было серым. Элеоноре на мгновенье подумалось, что она попала в старый черно-белый снимок. Один из тех, которые за гривну можно приобрести в любой букинистической лавке. Только никто бы не стал покупать фотографию кладбищенской дороги, кроме, разве что, Агаты. Ради нее-то Нора и поднялась в такую рань.

На половине пути Элеонора обернулась. Похоронное бюро чёрнело в конце тропы, сливаясь с темнотой, но отнюдь не это привлекло внимание нашей героини. Девушка ожидала увидеть собственные следы, оставленные на снежном покрове. Их не было. Снежный поток бесцеремонно скрыл улики еще до того, как Нора успела достигнуть нужного места. Теперь все выглядело так, словно она никогда не была в «Маятнике», не входила в него минувшим вечером, не сидела на крыльце со своим альбомом в руках и не выходила этим утром. Да и самого здания, судя по открывающемуся виду, там никогда не было. Конечно, Нора оставалась в своем уме и прекрасно знала, что «Маятник» на месте, дожидается наступления рассвета, дабы выплыть из темноты и возвыситься над нарядившемся в белое некрополем, как Башня Роланда возвышается над полем роз. 

Тем не менее, девушку не покидали странные мысли. Нора продолжила свой путь и теперь складывалось ощущение, что она не идет, а парит над землей, едва ли касаясь снежного покрова. В голове пронеслись старые строки, повествующие одновременно о печальной и комической ситуации, вырванные из «Морфия».

> *Какая пустыня. Ни звука ни шороха… И вот я вижу, от речки по склону летит ко мне быстро, и ножками не перебирает под своей пёстрой юбкой колоколом, старушонка с желтыми волосами… В первую минуту я её не понял и даже не испугался. Старушонка как старушонка. Странно – почему на холоде старушонка простоволосая и в одной кофточке?.. А потом: откуда старушонка? Какая?.. на десять верст кругом – никого. Туманцы, болотца, леса! А потом вдруг пот холодный потёк у меня по спине – понял! Старушонка не бежит, а именно летит, не касаясь земли. Хорошо? Но не это вырвало у меня крик, а то, что в руках у старушонка – вилы.*

Нора не то чтобы призирала наркоманов, но искренне надеялась, что сцена эта является вымышленной, хотя в глубине души знала, что это не так: творчество Михаила Афанасьевича всегда оставалось более чем автобиографичным.

Она осознала, что пытается разглядеть снежинку, застывшую на кончике носа, и ускорила шаг.

Временами пропитанный недостатком сна разум выдает крайне странные мысли. Поразительный долбоебизм.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Мальчишка, назвавшийся Геком, поджидал девушку сразу за поворотом. На нем была всё та же фуфайка, на этот раз застегнутая. Примостившись на могильной плите известного украинского поэта, малец вальяжно курил самокрутку. Исходя из его внешнего вида, парнишка едва ли мог позволить себе покупку табака. Нора бросила взгляд на самодельную сигарету, гадая, что же скрывается за газетным обрывком. 

Она вспомнила, как лет эдак тринадцать назад соседские дети мастерили нечто подобное. Желая казаться взрослыми, они пытались курить сено, чайные и лавровые листы… Словом, все, что смогли разыскать дома, а один парнишка, чьё имя не стоит упоминать во избежание конфликта, клялся, что курил лобковые волосы своего деда, (у самого-то они ещё не выросли) которые срезал поздним вечером, когда последний задремал у телевизора. Дурбецало этот божился, что на вкус его самокрутка неотличима от табака. Спорить никто не стал, но и пробовать тоже.    

Элеонора ещё раз пристально оглядела самокрутку Гека и решила не развивать эту мысль.

– Здоровенькі були[^44], – промямлил Гек. Из-за зажатой в зубах самокрутки это прозвучало как «Сдовенькы буы».

[^44]:  Приветствие.

– И тебе не хворать, – машинально ответила Нора.

Рядом с легко одетым мальчиком она – закутанная в чёрную шубку и как минимум три шарфа – чувствовала себя гребанной матрешкой. Ещё обиднее оказался тот факт, что несмотря на все старания Элеонора по-прежнему ощущала холод.

Для поездки на трамвае час выдался слишком ранним. Гек, явившийся в некрополь пешком, заявил, что на дорогу им потребуется около двух часов. То же время уйдет на ожидание трамвая, который вряд ли появится раньше рассвета. Нора взглянула на мальчика: от длительного пребывания на холоде на его щеках расцвели розы, а само лицо, казалось, вот-вот покроется инеем.

– Почему бы нам просто не взять такси?

Гек просиял искренней детской улыбкой, открывавшей миру умилительные ямочки на щеках, и признался, что никогда не ездил на такси.

– Точніше, було крапаль, та я не певен, чи то можна взагалі рахувати, адже я не мав грошей, а тому вилетів в автівки на останньому світлофорі та згинув у невідомому напрямку.[^45]

[^45]: Точнее, немного было, но я не уверен, можно ли это вообще учитывать, ведь у меня не было денег, а потому я вылетел из автомобиля на последнем светофоре, чтобы исчезнуть в неизвестном направлении.

Это предложение малец выпалил на одном дыхании. Он тут же закашлялся. Норе понадобилось приложить усилия, дабы подавить желание оповестить своего спутника о вреде курения. Во-первых, в этом не было нужды, так как Гек (как и любой здравомыслящий человек) был осведомлен о последствиях курения табака – если это вообще был табак – чуть более, чем полностью. Во-вторых, Элеонора, начавшая курить в пятнадцать, и сама успела пригубить парочку сигарет с момента пробуждения. В конце концов, какая разница, во сколько начинать курить: годом раньше, двумя годами позже – раковые палочки всегда остаются раковыми палочками, и раз уж речь зашла об этом, то лучше и вовсе не курить. Но люди любят то, что их убивает.

– Стівен Кінг писав, що табак може бути корисним для сформувавшихся легенів[^46], – произнес мальчик, заметив как Элеонора поглядывает на его самокрутку.

[^46]:  Стивен Кинг писал, что табак может быть полезен для сформировавшихся легких.

Девушка подняла бровь и с интересом перевела взгляд на собеседника.         

– Ты читал «Тёмную Башню»?

Лицо Гека сделалось таким серьезным, словно он собирался заявить, что не просто прочитал, но и собственноручно написал этот цикл. Вместо этого малец лишь многозначительно кивнул.

– Я багацько читав. У Валерія.[^47]

[^47]:  Я много читал. У Валерия.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Валерий был крёстным отцом Агаты. Неофициально, разумеется, ибо последнюю никогда не крестили. Он держал магазинчик антикварных вещичек под названием «Ретроспектива», войдя в который, Элеонора мигом сообразила, откуда в похоронном бюро все эти пластинки, патефоны и многое другое добро, включающее в себя также серебряные готические подсвечники и первое полное русскоязычное собрание работ Хемингуэя.

Внутри лавки яблоку негде было упасть. Она представляла собой три до блеска вычищенные комнаты, доверху заставленные товарами на любой вкус и цвет, начав перечисление которых, рискуешь сыграть в «Гаргантюа и Пантагрюэль».[^48] Пахло здесь так, как пахнет старый чердак уютным августовским вечером. 

[^48]: Сатирический роман в пяти книгах французского писателя Франсуа Рабле, в котором поразительно много лишних деталей, а перечисление таких вещей как содержимое банкетного стола может занимать далеко не одну страницу.

Протискиваясь вслед за своим юным проводником промеж стеклянных витрин и книжных стендов, Нора то и дело останавливалась, завидев очередную заворожившую её вещь.

– Хутчіш![^49] – бросил через плечо Гек с нетерпением, свойственным всем детям. – Матимеш ще гору часу на екскурсію.[^50]

[^49]: Поторапливайся! 
[^50]: У тебя еще будет море времени на экскурсию

Нора в последний раз взглянула на удивительную печатную машинку средины прошлого века, стараясь запомнить, где та лежит, и шагнула вслед за мальчишкой в дальнюю комнату.

Из-за прикрытой дубовой двери доносилась бодрая на первый взгляд мелодия, которую девушка незамедлительно узнала. Это был Дел Шеннон, чей лирический герой гулял под дождем и думал всякие думы. Преимущественно невесёлые.

Преимущественно о любви.

Отворив дверь, Элеонора немало удивилась, обнаружив, что в комнате нет никого кроме неё, Гека и вот этого орущего паренька с пластинки.

Перехватив её взгляд, малец загадочно улыбнулся. Так, словно они с Норой хранили какой-то до ужаса важный секрет.          

– Та це я кімнати обжив і поставив платівку незадовго до відправлення на зустріч із тобою. Не хотів, аби крамниця зустріла тебе похмурим обличчям, бо тобі, мабуть, і «Маятника» вистачає, – Элеонора с облегчением отметила, что сегодня её новый друг не сыпал афоризмами. – До того ж, мені і самому якось моторошно лишаться тут наодинці.[^51]

[^51]: Так это я комнаты обжил и пластинку поставил незадолго до отправления на встречу с тобой. Не хотел, чтобы лавка встретила тебя хмурым лицом, ведь тебе, наверное, и «Маятника» хватает. К тому же мне и самому как-то жутковато оставаться тут в одиночестве.  

– Розумію[^52], – кивнула она и продолжила уже на русском: – Ты здесь живешь?

[^52]: Понимаю.

– Раніше іноді перебивався, а тепер так, певно що живу. Взагалі-то, це дядін кабінет[^53], – последнее утверждение Гек произнес с едва заметным смущением.

[^53]:  Раньше иногда перебивался, а теперь да, наверное, живу. Вообще-то, это кабинет дяди.

Движением руки он предложил Элеоноре присесть, а сам устремился в дальний конец комнаты, обещая вернуться с домашним горячим шоколадом, равного которому не сыщешь на всем белом свете. Ожидая такси, девушка изрядно подмёрзла и горло уже начинало побаливать. 

Однако, лицо таксиста, завидевшего молодых людей, карабкающихся по забору закрытого кладбища в половине пятого утра и грациозно летящих в направлении сугроба… – оно того стоило.

Конечно, не только это привело нашу героиню в «Ретроспективу».

Нора ощутила резкий перепад температур и поспешила избавиться от верхней одежды.

Дальняя комната служила Валерию квартирой, которая хоть и являла просторное помещение, совмещающее спальню, кабинет и кухню, выглядела практически пустой, по сравнению с предыдущими залами. Высокие окна с деревянной обделкой открывали вид на отрывок старого города.

Элеонора умостилась за широким письменным столом. Тот был вплотную приставлен к северной стене, вдоль которой имелась полка, доверху заставленная фотографиями в рамках, соседствующими с различной дребеденью. Снимки виднелись и под полкой, булавками приколотые к чёрным обоям. Девушка обернулась: Гек возился с чайниками у комода напротив окна, которое само по себе походило на тускнеющий снимок.  

Нора откинула с лица пепельно-черные волосы и с нескрываемым интересом принялась разглядывать фотографии.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

На многих снимках была Агата. Без очков и улыбающаяся если не во все зубы, то хотя бы вполовину – Нора не сразу её узнала. Что-то в этой улыбке показалось девушке знакмым, но ощущение это промелькнуло так быстро и неясно, как чувство дежавю во сне.

«В конце концов, все подвыпившие улыбаются одинаково», – подумала Нора и напрочь забыла об этом.

Даже на снимках, запечатлевших Агату в более поздний период (Нора тут же заметила шляпу с широкими полями и траурные одежды, столь характерные для ее сожительницы) дамочка не носила очков и Нора смогла разглядеть тёмно карие, практически черные глаза, края которых были по-кошачьи изогнуты. Наша героиня сочла этот взгляд слишком очаровательным, дабы скрывать его за зеркальной перегородкой, но решила повременить с расспросами. 

Если и имелось время для поднятия таковой темы, это определённо было не оно.  

Размышления прервал голос мальчишки.

– Вуаля! – радостно воскликнул Гек, протягивая дымящуюся кружку.

Нора тут же приложилась к напитку. Шоколад оказался слишком редким и скорей походил на неумело приготовленное какао. Мальчик, заподозрив неладное, с надеждой взглянул на новообращённого дегустатора. 

– Очень вкусно, – улыбнулась Нора.

Гек ответил незамедлительно, словно ожидал появления этой фразы. Элеонора подумала, что именно так дела и обстояли.

– Дядя мене навчив. Агата каже, що то лайно собаче, проте дядя запевнив колись, що я можу й краще. Тож я практикуюсь. Іноді.[^54]

[^54]:  Дядя меня научил. Агата говорит, что это дерьмо собачье, но дядя как-то убедил, что я могу и лучше. Так что я практикуюсь. Иногда.

Гек указал на один из снимков, которые девушка и без того продолжала рассматривать, сделанных, судя по всему, в каком-то баре. В центре композиции (на фоне барной стойки, за которой Агата что-то усердно смешивала в французском шейкере) улыбался мужчина средних лет. Как несправедливо бывает в отношении сильного пола, возраст лишь придавал ему привлекательности: высокие скулы, копна непослушных волос и невероятно яркие синие глаза первым делом приковывали взгляд. Морщинок – всего ничего. Парочка тёмных локонов падала на высокий лоб. Немалого роста и крепкого телосложения, без малейших признаков обвисшего брюшка.

«Прямо-таки герой советского кино», – мелькнула мысль в голове девушки.

– Дяді тут п’ятьдесят шість,[^55] – сообщил Гек.

[^55]:  Дяде тут пятьдесят шесть.

Элеонора круто вскинула брови и дважды моргнула, недоверчиво, но в то же время заинтересованно, поглядывая на собеседника.

– Сколько?!

Малец, вероятно, давно уже привыкший к подобной реакции, спокойно закончил мысль. 

– Саме тоді ми й познайомились. Ну, не в барі, звісно.[^56]

[^56]:  Как раз тогда мы и познакомились. Ну, не в баре, конечно.

## 24 {-#24}

Гек, чье настоящее имя, как выяснилось, было Дармедонт (Нора дважды сдавлено хихикнула и одарила мальчика извиняющимся взглядом) оказался большим любителем вести повествование. Делал он это совершенно непринужденно и, можно даже сказать, беспристрастно. Так, словно пересказывал сюжет хорошо знакомого фильма, а не отрывок собственной жизни. Элеоноре это даже нравилось: по своей натуре она была сентиментальной девушкой и даже реклама растворимого кофе порой могла вызвать слезы на прекрасном аристократическом личике. В эти минуты Норе думалось о том, как же хорошо, что сожительница её оказалась куда менее эмоциональной дамочкой, ибо двум таким нюням пришлось бы несладко в одной гостиной.     

Уже позже ей открылось, что Агата, которая при первом, а также парочке последующих взглядов напоминает закоренелого дудаиста, по сути куда более эмоциональна. Нет, она не ревела над сопливыми романтическими комедиями и никогда не умилялась детишкам, но поразительная чувствительность владелицы «Маятника» проявлялась в куда более странных вещах. Бывало, в момент разговора, или же просто занимаясь каким-нибудь привычным делом, вроде чтения, Агата вдруг застывала и, не шевелясь, смотрела куда-то перед собой. В такие моменты выражение лица дамы было олицетворением тоски, а наличие тонированных очков делало такую картину ещё более непонятной. Если в момент подобного происшествия в руке Агаты была зажата сигарета она могла спокойно догореть, обжигая при этом пальцы владелицы, да так, что та ничего и не замечала. 

Случались и другие ситуации, когда эмоциональная палитра Агаты состояла лишь из злости и всех оттенков раздражения в сторону вещей, которые, по мнению нашей героини, вовсе не стоили таких нервов. Агата была чертовски свободолюбива и даже такая ерунда как разлинованные блокноты была способна тут же вызвать ярость на лице, казалось бы, безразличной ко всему особы, особенно смущало Элеонору: привычные плавные движения контрастировали с резкими нотками в голосе, что угрожали обратиться неконтролируемыми приступами ярости, вызванными чёрт его знает чем. Тогда Агата казалась девушке воображаемой героиней какой-нибудь экспрессивной пьесы и Нора даже ловила себя на мысли, что буквально может предсказать следующее действие своей подруги.

Однако, все это имело место быть позже.

Сейчас же Элеонора сидела за столом дальней комнатки «Ретроспективы» и, подложив ладони под голову, с неподдельным интересом слушала рассказ Гека.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Дело было не в том, что у Гека не было семьи. 

Хотя, ладно, дело было именно в этом, но не в том смысле, в котором общество привыкло воспринимать эту фразу. Малец ни разу не был в приюте и, до поры до времени, не скитался холодными улицами в поисках ночлежки. Фактически он был частью полноценной семьи среднего достатка – по крайней мере так значилось в документах. Отец зарабатывал на жизнь тем, что по шестнадцать часов в день торчал в местном филиале одной невхеренной канадской it-компании, (которая отказывалась облагать налогом своих сотрудников, создавая последним немало хлопот) где довольствовался почетной должностью офисного планктона и безуспешно пытался избавиться от красноречивого акцента во время мастерски отрепетированных шаблонных ответов на вопросы обескураженных клиентов. Любимыми выражениями папаши Гека были «Please clarify your question»[^57] и «Have you tried to turn off and turn on?»[^58], хотя последнее всё ещё давалось ему с трудом. 

[^57]:  Пожалуйста, уточните свой запрос.(англ.)
[^58]:  Вы пробовали включить и выключить? (англ.)

Дело свое мужчина любил, пускай оно и состояло из беспрекословного выполнения обезьяньей работы, обсуждения политики с коллегами и, конечно же, того, чтобы вставлять please[^59] и kindly[^60] в каждую сводобную дырку диалога с арабами, которые ждали, что за десять баксов в месяц теподдержка вдоль и поперек будет вылизывать им задницы.

[^59]:  Пожалуйста (англ.)
[^60]:  Будьте добры (англ.)

На самом деле рабочий день был девятичасовым, но за оувертаймы[^61] приплачивали в полтора, а по праздникам (вы, блядь, не поверите!) – в два раза больше. Лаврентий не выходил на работу лишь по воскресеньям и в день Рождества Христова. Причиной последнего послужил тот случай, когда в разгар этого самого праздника мужчина попытался отчаянно впустить Иисуса в сердце не менее радикально настроенного клиента-мусульманина.          

[^61]: Overtime (англ.) – переработка. 

Итак, всё бы ничего, если бы оставшееся от лишенной смысла работы время Лаврентий проводил не с божьим сыном, а со своим собственным, но Геку удавалось поболтать с отцом от силы пару раз в неделю. К тому же, подобные разговоры всегда сводились к одной и той же фразе: «А как бы на твоем месте поступил Иисус?»

В четыре года Гек понял, что Иисуса отец любит премного больше, чем его самого. В шесть пообещал себе, что непременно разобьет нос этому бородатому всеми любимому мужику в платье, – было это задолго до явления миру Кончитты Вурст, вы не подумайте – ну а в восемь… На девятом году жизни Гек осознал, что бороться за отцовскую любовь в принципе бессмысленно, а уж тем более с мифическим зомби, так что ранним весенним утром он, как всегда, ушел в школу чтобы уже никогда не вернуться в отчий дом.

Мать Гека была той еще штучкой. Днем она скиталась по улицам, уговаривая прохожих протестировать на себе пробники убогой косметической марки, представителем которой она являлась, а по вечерам продолжала распространять эту идею в интернете. 

У мальчика также был старший брат, о котором достаточно сказать, что лучше бы его не было.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

В календаре наступило третье марта, но погода и не думала сворачивать на весну. Дождь лил без устали уже вторые сутки, делая улицы не только грязными, но и пустынными. Сумерки в такие дни наступали рано. Мальчик знал это, а потому заставил шагать быстрее свои непривыкшие к подобным нагрузкам ноги. В пути он провёл уже около тридцати двух часов, из которых спал всего шесть в одном заброшенном сарае, удачно встретившемся посреди голого поля. Теперь же нехватка сна и здоровой еды с лихвой сказывалась на растущем организме, и Гек чувствовал не просто усталость: шагая, он ощущал каждую ноющую мышцу. Болели не только ноги, руки почему-то сделались слишком тяжелыми и, свисая вдоль тела, заставляли мальчика упасть на холодную землю. Время от времени тот закладывал их за голову, но и это не могло помочь надолго. Спина также давала знать об изнуренности и буквально кричала мольбами о помощи, которые наш герой так умело игнорировал. Он был готов к чему угодно, – сколиозу, бронхиту и даже мифическому гепатиту, которым так любили пугать в школе, – но только не возвратиться домой. 

К началу второго дня пути Гек решил обратить всё в игру. Ему хотелось знать, сколько может пройти его тело без каких-либо остановок. Так мальчик приноровился выполнять на ходу многие вещи: есть, пить, просматривать карты и, конечно, справлять малую нужду. Последнее он находил особенно забавным, если не забывал повернуться к ветру спиной. 

Малец также делал на ходу различные упражнения – все, что только мог припомнить с занятий физической культурой и это помогало, но, опять-таки, лишь на какое-то время. Однако, хуже всего дела обстояли с шеей. Казалось, что её несколько раз обернули вокруг оси.  

Несмотря на физическую изнеможенность, морально Гек был на высоте. Происходящее казалось первой совершенной им вещью, пускай и сложной, но, наконец-то, имевшей смысл. Когда серое небо принялось тускнеть ещё сильнее, извещая о приближении темноты, мальчик понял, что едва ли успеет отыскать для ночлега новое заброшенное сооружение. За прошедшие часы пейзаж перед глазами едва ли изменился: пустынная дорога полна грязи и выбоин, в которых уже успело накопиться немало дождевой воды; вдоль обеих сторон трассы тянутся бесконечные ряды тополей. Утратившие листву деревья выглядели мертвыми. Ветер то и дело заставлял их ветки тянуться вниз, создавая тем самым весьма удручающую картину. Далее были поля. Холодные голые поля и ни одного, черт бы его побрал, сооружения. 

Тогда Гек представлял, как однажды напишет рассказ, а может и целую повесть, о парнишке, который день за днем вынужден идти только вперед, не имея возможности остановиться, – это было до того, как Гек всерьез увлекся литературой и с удивлением обнаружил, что такая книга существует уже не одно десятилетие.  

Темнота накрыла мальчика в считанные минуты, но, дождавшись, пока глаза к ней привыкнут, Гек заставил себя прошагать ещё полтора часа. Периодически ему попадались мелкие тропинки, уходящие в глубь поля. Возможно, на конце одной из них мальчика и ждала деревушка с парочкой заброшенных хат, но с трассы края тропинок видно не было, к тому же, наш герой уже твердо решил не сходить с главной дороги. 

Взошла луна и дождь вдруг резко прекратился. В то же время ветер задул сильнее, заиграл тощими ветвями и загудел среди пустошей. Пришлось признать, что сегодня ночевать доведется под открытым небом. Гек вздохнул, сошёл с трассы и, сделав пару неуверенных шагов в темноту, вдруг провалился в кювет. Он здорово ушиб локоть и разревелся. Не столько от боли, сколько от усталости и беспощадного осознания того, что он один в целом мире. Конечно, малец понимал это и прежде, но узнать разницу между понятиями «одинок» и «один» можно лишь прочувствовав последнее.

Ручейки слез продолжали испещрять его лицо, когда, шмыгнув носом, Гек осознал, что в кювете ветер чувствуется не так сильно. Он вытер рукавом нос, подложил под голову рюкзак и тут же забылся тревожным сном.

## 25 {-#25}

Очнулся Гек от собственного кашля. До рассвета было далеко, так что он позволил себе ещё какое-то время полежать, разглядывая ветви деревьев, возвышающихся на фоне ночного неба. Потянувшись, Гек сморщился от резкой боли, пронявшей спину и нехотя сел. Во рту раскинулась настоящая Сахара, но жажда уступала место голоду. Он вывалил содержимое пищевого контейнера на колени и с жадностью принялся поглощать бутерброды. Дышать было как-то тяжело, и наш герой с горечью осознал, что нос его заложен со вчерашнего вечера.   

Проблема восьмилетних мальчиков, устраивающих побеги из дому, по большей части заключается в том, что они понятия не имеют, как устроен быт, так что их познания в данном вопросе более чем отличаются от реального положения вещей. Гек был смышлен и, ввиду своего вынужденного одиночества, гораздо самостоятельнее сверстников, однако, он по-прежнему оставался ребёнком и многое не мог предусмотреть. Время, проведённое в компании телевизора, сказывалось на нём, в общем-то, положительно: мальчик знал о насилии больше, чем стоило, а потому, собираясь в путь, не забыл и о средствах самообороны. Оружия в их доме отродясь не водилось, как и газовых баллончиков, но, пораскинув мозгами, Гек пришел к выводу, что последнее с лёгкостью можно заменить. Теперь в боковом кармане его рюкзака хранился новенький флакон лака для волос. Мать разозлится, заметив пропажу, – тут Гек не сомневался, как не сомневался и в том, что исчезновение лака мать заметит гораздо раньше, чем отсутствие его самого – но оно того стоило.

Так вот, Гек был смышленым малым. Он прихватил с собой компас, карты, фонарик со сменной батареей, кое-какую одежду и прочие полезные мелочи, которые по его (и, в принципе, правильному) мнению могли понадобиться в пути, но мальчик не позаботился о главном. Он совершенно забыл про дождевой плащ, но, что ещё хуже – не вспомнил о лекарствах. Оно и понятно: стоило Геку приболеть, таблетки, сиропы и порошки от кашля заведомо ждали в аптечке над раковиной. Мальчику не приходилось покупать их самому, так что в последний момент он попросту не вспомнил о лекарствах. 

Наличные, что Гек имел при себе, были его собственными сбережениями за последние несколько лет, и представляли собой суму, лишь немного превышающую среднюю заработную плату. Этого хватило бы на оплату пары дней в отеле и покупку билета на поезд в оба конца, но Гек понимал, что денег у него всего ничего, а потому надо их беречь. К тому же, без документов билет бы ему не продали, а рисковать мальчик не хотел.            

К обеду пейзаж по обе стороны дороги начал меняться. Поля смешались с лесопосадками, поначалу редкими, а затем более широкими. Кое-где вдали начинали проступать домики. Сверившись с картами и своими записями, мальчик решил, что, если не будет останавливаться, достигнет областного центра с наступлением следующего рассвета. В городе он купит еды, отыщет автовокзал и обзаведётся билетом на утренний автобус в любой конец страны. Конечно, Гек мог провернуть это в своем собственном городишке и в таком случае уже был бы в тепле и далеко от грязной трассы, но кое-что здесь, всё же, останавливало. Он понимал, что спустя пару дней полиция начнет его искать, то есть опрашивать горожан, и был уверен, что окажется единственным восьмилетним мальчиком, покупающим билет на первый автобус. Его описание узнают и вскоре отыщут даже в новом городе.

А больше всего на свете Гек не хотел быть пойманным. Сперва он решил незаметно покинуть район, в котором жил, и удалиться как можно дальше от города. Даже в этой глуши по мокрой от дождя дороге иногда проезжали машины. Завидев их приближение, мальчик тут же прятался в овраге или среди деревьев. Дом он покинул в школьной форме и надетой поверх неё куртке, которые вскоре спрятал в одной из полевых ям для компоста, и переоделся в широкую толстовку с капюшоном и заношенную фуфайку. Эти вещи он нашёл в гараже. Отец не носил их уже много лет, так что вряд ли станет искать, отчего шансы быть неузнанным у мальчика увеличивались. 

Около семи вечера Гек сошел с трассы: вдали показался свет от чьих-то фар. Мальчик зашёлся ревущим кашлем, пытаясь углубиться в посадку и параллельно надеясь, что в автомобиле работает радио. Наш герой справился с кашлем и теперь тяжело дышал, пытаясь взять себя в руки. Его трясло уже второй час. Голова кружилась, а ноги путались на ходу, периодически увлекая лицо своего владельца прямиком в лужи. Гек взялся за ствол какого-то широкого дерева и попытался вернуться на дорогу. Его усилия были напрасными. С трассой его разделяло каких-то двадцать метров, но преодолевал их Гек бесконечно долго, чтобы в итоге обнаружить, что так и не сдвинулся с места. Определенно, за этот день дела его сделались гораздо хуже. Котелок совсем не варил, но страшнее всего было другое – толстяк в костюме клоуна.

Клоун преследовал его с наступления темноты. Точнее сказать было сложно: мальчик совершенно потерялся во времени. Минуты казались ему часами, а часы вдруг проскальзывали как пара секунд. Иногда мальчик оглядывался по сторонам и не мог вспомнить, как попал сюда. Некоторые отрезки времени просто исчезали. Но клоун вот не спешил исчезнуть, он держался на небольшом расстоянии от мальчика, словно выжидая, пока тот упадет без сил. 

Впервые Гек заметил силуэт среди деревьев, когда остановился, пытаясь прочистить нос, и вдруг обнаружил, что весь мокрый. Холода больше не чувствовалось, только жара – невыносимая жара и жажда теплились в голове мальчика. Он поднял тяжелые веки и обратил взгляд в сторону деревьев, пытаясь понять, есть ли ветер. Деревья медленно покачивались, оставляя за собой расплывающиеся следы. Воздух перед глазами сгустился и поплыл, дышать было невозможно. В голове мальчика пронеслась отдалённая мысль о том, что он под водой. И все это под водой. Холод, темнота и бесконечная влага только подтверждали эту мысль.

Мальчику сделалось страшно. Он обхватил себя руками, но сразу опустил их, изнывая от жары. По щекам потекли слезы и тут же смешались с ручейками пота, заполнившими всё лицо.

ПЛЫВИ.

Голос в голове. Чужой голос говорил ему, что дышать вовсе и не нужно. *Под водой никто не дышит, глупенький.*

ПЛЫВИ.

МЫ ВСЕ ЗДЕСЬ ПЛАВАЕМ. СКОРО И ТЫ ПОПЛЫВЕШЬ.

Гек замер. Последняя фраза окончательно вогнала его в ступор. Поплывешь? Он сказал «поплывешь»? Или он сказал… *Полетишь?*

Шея болела пуще прежнего. Мальчик осознал, что всё ещё смотрит на верхушки деревьев и медленно опустил голову. В нескольких шагах от него стояла высокая фигура, в руках которой были…

«Не шарики, пожалуйста, только не…»

Да, это были воздушные шарики. Шарики, которые совсем не раскачивались на ветру. Фигура ослабила хватку и парочку шаров устремились в небо.

Гек вскрикнул.

Вернее, попытался, но его измученное горло издало лишь хриплый стон.

Фигура сделала шаг по направлению к мальчику. Ещё несколько шаров вылетело из рук существа.

МЫ ВСЕ ЗДЕСЬ ЛЕТАЕМ.

Гек никогда не слышал этого голоса, но узнал бы его где угодно. Он знал эти шарики. Он знал эту фразу лучше чего бы то ни было. В темноте сложно было разглядеть детали внешности этого существа, но Геку не особо-то и хотелось. Он знал, кто это, знал его имя. Пеннивайз[^62] – единственный детский страх, так никогда и не покидавший Гека.

[^62]: Танцующий клоун Пеннивайз – главный антагонист  в романе Стивена Кинга «Оно», зло, являющееся нашему миру в различных образах, основным из которых является вид ужасного клоуна с охапкой ярких шаров в руках. 

По всей видимости, не напрасно. 

Клоун вытянул вперед руку, отпуская в небо оставшиеся шары и сделал шаг в сторону мальчика. Тот широко раскрыл глаза и, издав новый скрипучий стон, бросился прочь. Он выскочил в центр дороги и бездумно несся вперед.

Но не долго. 

Ватные ноги запутались, и Гек нырнул лицом в одну из глубоких луж, раскинувшихся посреди трассы. Боли от падения он совсем не почувствовал, зато было кое-что другое. От ледяной воды его мысли мгновенно прояснились. Жар слегка сошел и мальчик растерянно обернулся.

Клоуна нигде не было. Ещё бы, его и не могло здесь быть: персонажи Стивена Кинга не преследуют маленьких мальчиков на пустынных трассах. По крайней мере, вне штата Мэн.[^63]

[^63]:  Именно там разворачивается действие большинства историй автора.

Гек на удивление быстро забыл о странном происшествии, как это всегда случается с дурными снами, и продолжил свой путь, мечтая о чашке – нет, целом чайнике – горячего чая. 

Увы, просветление длилось недолго.

Пеннивайз преследовал его, вновь и вновь появляясь в разных местах. Вот он бредёт позади мальчика, а вот вдруг бледная рука в клоунском облачении появляется из темноты всего в паре метров от нашего героя. Гек не понимал, как существу удаётся перемещаться с такой скоростью, но времени на подобные размышления у него всё равно не было. На улице вновь сделалось холодно, да так холодно, что никакой чай бы не помог. Геку было страшно и невыносимо плохо. Он не помнил, когда в последний раз его так лихорадило.

И вот теперь, спустя неизвестное ему количество времени, Гек стоял во тьме, держась за ствол мокрого дерева и силясь вернуться на трассу. Он пробыл здесь так долго, что вдалеке замелькали фары следующей машины. Гек тяжело вздохнул и беспомощно опустился наземь. 

Секундой позже мальчик удивленно вскинул брови и улыбнулся. Из зарослей по другую сторону появилась собака. Мохнатая и крохотная, невероятно походившая на плюшевую игрушку, она была щенком лайки. Тем самым, о котором всегда так мечтал Гек. В свете луны белоснежная шерстка отливала синевой, придавая щенку ещё большее сходство с игрушкой. Полные доверия глазки-пуговки смотрели на Гека с восторгом. Мальчик не мог поверить своему счастью. Если следом не покажутся хозяева лайки, он сможет оставить щенка себе и тогда они будут вместе путешествовать по стране.

Гек знал, что сможет следить за собакой. Он мечтал о ней с пяти лет и успел за это время прочесть уйму сопутствующей информации. Удивительно, что именно сейчас удача повернулась к нему лицом, ведь деньги, которые мальчику пришлось взять с собой, изначально предназначались именно для приобретения пушистого друга.

Его размышления прервал глухой звук удара. Улыбка застыла на лице Гека, медленно искажаясь и обращаясь гримасой боли. Он закричал. На этот раз по-настоящему. К тому моменту щенок уже успел добраться до середины дороги, когда пролетевший мимо автомобиль размазал по асфальту его крохотное тельце. 

Мальчик закрыл лицо руками и зарыдал. Хуже быть просто не могло.

Но было хуже.

Пеннивайз вернулся. Он вышел из темноты и опустился на колени рядом с тем местом, где ещё мгновение назад, виляя хвостом, стоял щенок. Сейчас же там виднелись только пятна крови и разорванные внутренности, что казались черными под покровом ночи. Теперь Гек имел возможность рассмотреть своего преследователя. Стоило мальчику подумать, что улыбка на лице существа выглядит как-то иначе, как клоун тут же её снял. Вернее, снял то, что оказалось небольшой маской, скрывающей часть лица, и мальчик понял, что у клоуна нет нижней челюсти. На ёе месте виднелись едва ли зажившие кровавые ошмётки. 

Тем временем существо старательно соскребло с земли остатки бедного животного и с неумолимой легкостью принялось поглощать добычу. В страхе и отвращении, наш герой попытался отползти назад, но тело его не слушалось. Оставалось только следить за ужасной картиной.

Клоун покончил с трапезой. Он поднял голову и резко повернул её в ту сторону, где прятался мальчик. Затем сделал то, что парой секунд позже Гек интерпретировал как самую страшную улыбку на всем белом свете. Рот… Вернее сказать, то, что от него осталось, не шевелился, но Гек услышал, как из его собственной головы звучит голос существа. 

МЫ ВСЕ ЗДЕСЬ ЛЕТАЕМ.[^64]

[^64]:  «Мы все здесь летаем», – известная фраза вышеупомянутого персонажа. 

ОН ПОЛЕТЕЛ. Я ЧУВСТВУЮ, КАК ОН ЛЕТИТ.

ТЫ ТОЖЕ ПОЛЕТИШЬ.

В глазах у Гека потемнело. Тело мальчика упало на прелую листву. Он потерял сознание.

## 26 {-#26}

После этих слов последовала драматическая пауза. Приличия ради Элеонора выждала пару секунд, после чего как бы невзначай взглянула на часы. Особой надобности в этом не было. Девушка и так знала, что опаздывает.

– Впечатляющая история… – заметила она. 

– Це ще навіть й не четвертушка![^65] – тут же парировал Гек.

[^65]:  И это ещё даже не четвертая часть!

– … но я не думала, что она настолько длинная. Я с удовольствием послушаю, или прочту продолжение, но, боюсь, Агата уже ждёт меня. 

Мальчик слегка нахмурился. Казалось, рассказ слишком увлёк его, позволяя на время забыть о реальности.

– Ты ведь уже записал это? – тут же спросила Нора, стараясь напомнить мальцу о его писательских порывах.

Тот покачал головой.

Гек убрал со стола пустые чашки и выдвинул верхний ящик. Его содержимое оказалось потрепанной картонной папкой. Мальчик взглянул на неё лишь на мгновенье, но этого хватило, дабы Нора заметила бесконечную скорбь на лице Гека, которую тот так умело пытался скрыть.

– Тут я зібрав усі документи та долучив декілька карток на випадок, якщо Агата загубила свої.[^66]

[^66]: Тут я собрал все документы и добавил несколько фотографий на случай, если Агата потеряла свои.


Элеонора кивнула.

– Я приєднаюсь до вас разом з усіма, а потім розповім тобі ще частину своєї історії, якщо захочеш.[^67]

[^67]: Я присоединюсь к вам вместе со всеми, а потом расскажу тебе ещё часть своей истории, если захочешь. 

– Конечно.

Девушка отложила папку и принялась надевать верхнюю одежду.

– Скажи только, – произнесла она, шагая в сторону выхода, – у тебя в ту ночь прыгала температура?

Малец ухмыльнулся, тут же сделавшись прежним Геком.

– Ще б пак! – гордо сказал он. – Падала до тридцяти п’яти, а потім стрибала до сорока и знову те саме. Бачила колись таке?[^68]

[^68]: Еще бы! Падала до тридцати пяти, а потом прыгала до срока и снова то же самое. Видала когда-нибудь такое? 

## 27 {-#27}

Дабы подготовиться к церемонии, Агата поднялась на рассвете, как и обещала. Возможно, что и раньше: вернувшись домой, Элеонора видела её из окна своей спальни, плывущую средь могильных плит. Фигуру Агаты окутывал туман, скрывая края платья – столь густым слоем он стелился над землёй.

Наступившим утром хозяйка «Маятника» выглядела совсем скверно: ссутулившаяся и обхватившая себя руками, она держалась неуверенно, хотя была в одиночестве. Глядя на эту походку, Нора задалась вопросом: спала ли сегодня её подруга?

Девушка принялась укладывать волосы, изредка поглядывая на кладбище, где Агата бесцельно бродила взад-вперед, периодически исчезая в тумане. Нора поняла, что все ещё не согрелась и отправилась принять горячий душ, а когда вернулась в спальню траурная дамочка скрылась за пределами открывающегося из неё вида. Девушка простояла у окна ещё пару минут, надеясь, что та покажется, после чего пожала плечами.

– Наверное, ушла вглубь кладбища, – произнесла Нора, обращаясь к самой себе.

Она взяла с подоконника чашки, оставшиеся после минувшего вечера. Пора заняться завтраком. Обернувшись, Нора вздрогнула; посуда чудом осталась в руках. У изголовья её кровати неподвижно сидела Агата. Закинув ногу на ногу, она спокойно смотрела на девушку.

– Давно здесь сидишь? – только и нашлась Элеонора.

– Не то чтобы очень.

Агата не шелохнулась. Сотканная из бледной кожи, в тусклом свете торшера она напоминала восковую фигуру.

– А ты давно за мной наблюдаешь?

– Не то чтобы очень.

Завтрак получился американским – яичница с беконом, большую часть которой Агата отправила в мусорное ведро. Как девушка и подозревала, прошлой ночью её компаньонка не сомкнула глаз и теперь один за другим опустошала бокалы с таким рвением, словно пьянство могло компенсировать отсутствие сна.

Расправившись с завтраком, Нора бегло осмотрела комнату и, не обнаружив никаких следов присутствия Владислава, нахмурилась: находится в тишине больше не было сил. Она буквально ощущала облако скорби, тяготившее над Агатой. 

В итоге девушка остановила внимание на портрете, украшавшем противоположную стену. Нора указала на личико Николая Васильевича.

– Не твоих ли рук дело?

Агата кивнула не глядя.

– А что насчет Гинзберга?

Еще один кивок.

– Булгаков, Есенин, Бродский, Гоголь, Гинзберг, Берроуз, Томпсон, Уэлш, Буковски, Кинг, Хилл, Стокер, Коллинз, По, Лавкрафт, Хемингуэй, Ремарк – всего девятнадцать, среди которых три Эдгара, – произнесла Агата измученным голосом.

– Я знала, что они одного авторства! – с запалом вскрикнула Нора, которая всегда хотела разбираться в искусстве. – Эти мрачные контрасты, гротескная подача с вкраплениями сюрреализма… Много времени ушло на эту серию?

– Лет семь.

Элеонора не оставляла попытки разговорить Агату, тускнеющую на глазах.

– Ты изображаешь только любимых авторов?

– Ты наблюдательна.

Никакой ухмылки.

– И кто на очереди?

– Кристи. Пишу её уже четвертый месяц, но выходит слишком много деталей и это раздражает.

Следующая фраза Элеонора стала внезапной даже для неё самой.

– Хотелось бы мне оказаться в этом списке.

– Заверши рукопись, – серьёзно напомнила Агата.

– Я о каждой так говорю, но эту непременно закончу. Ещё немного и выйдет две третьих. 

Агата одобрительно кивнула.

Или просто кивнула. Кто её разберет.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Стрелка часов медленно ползла в сторону восьмерки. Этой ночью владельцы похоронного бюро постарались на славу: внизу всё было готово ещё до восхода солнца. Элеонора не знала, каким образом её соседям удалось уговорить представителей морга доставить тело глухой ночью, но подозревала, что инициатива исходила от Агаты. 

Девушке представилось ночное кладбище, каким, благодаря Агата, она прекрасно помнила это место; теряющиеся в тумане силуэты, несущие гроб по направлению к «Маятнику»… Или в гроб покойного клали уже здесь? В любом случае, картинка вырисовывалась не из самых воодушевляющих.

За неполный месяц, проведенный в «Маятнике», Нора ни разу не осматривала первый этаж, (не считая крестовых походов в винный погреб) видимо, не располагая подходящим траурным настроением. Этим утром ей представилась такая возможность.

Со слов Агаты девушке было известно, что правое крыло занимали кабинеты Рахманиновой и Мирославского; левое же было отведено под зал прощаний. Туда Нора и отправилась первым делом.

Зал прощаний представлял собой огромное помещение, по сравнению с которым терялся простор гостиных комнат. Убранное в красно-золотые тона оно больше походило на холл какого-нибудь театра: потолки подпирали мраморные горгульи, со всех сторон виднелись выступающие образы львов. Помимо настенной иллюминации, здесь имелись старинные колыхающиеся люстры со свечами вместо ламп – они-то и придавали комнате сакральное очарование, создавая атмосферу уединения. Высокие витиеватые подсвечники возвышались и вдоль всего зала.

Две третьих помещения занимали бархатные стулья, (какие прежде Элеонора видела лишь во дворцах-музеях) насчитывалось их более двух сотен. У дальней стены стоял гроб с усопшим. Тени от свечей мягко падали на лицо Валерия, придавая его чертам умиротворение. За свою жизнь девушка видела покойников раз пять, но впервые подошла так близко, не чувствуя при этом и толики страха – с атмосферой Агата не прогадала.

– Словно он прилег отдохнуть, – глухо произнесла Агата. Она вновь бесшумно выплыла из-за спины девушки. – Хотя так, пожалуй, говорят обо всех покойниках.

– Он будто улыбается…

– Видишь две эти тусклые линии? Вдоль скулы и у края губ. Их сложно заметить в желтом свете, но всё дело в тенях.

– Твоих рук дело?

– Освещение – да, однако для взаимодействия с тенями холст должен быть идеален, а это уже заботы Ласло.

– Вот как…

– Знаешь, они никогда не встречались, – туманно произнесла Агата, - по крайней мере, в нормальном понимании этого слова, но в своём письме Крёстный просил заняться… привести его в порядок именно в «Маятнике».

Нора внимательно оглядела свою собеседницу, раздумывая, стоит ли задать следующий вопрос.

– Раз уж речь зашла об этом, могу я задать ещё пару вопросов? – решилась она.

– Почему нет?

– С твоих слов и не скажешь, что Валерий был при смерти. Он умер от патологии? 

– Нет. Тромб оборвался. Это было внезапно для всех, включая его сердце, так что, к счастью, Крёстный ничего не заметил.

– А письмо?

Агата улыбнулась.

– Он написал его, сидя в моем кабинете лет эдак пять назад. Тем днём мы начинали подготовку к открытию бюро. Утром привезли фирменные конверты, одним из которых Валерий и воспользовался. Скорее шутки ради, но письмо он, всё же, сохранил. Вместе с этим, – она указала на безымянный палец левой руки, на котором переливался чёрно-синий агат. – Вообще, в отношении смерти Крёстный владел уникальной философией – вудиалленовской – предпочитал не иметь ложных надежд и воспринимал уход как нечто более приятное. Возможность сократить свои расходы, например.   

Нора хохотнула и озадачено взглянула на Агату, испугавшись собственного невежества, но та лишь одобрительно кивнула.

– Всё так, – произнесла дама в чёрном. – Он предлагал смеяться над всем, и смерть не стала исключением. В последней строке своего прощального письма крёстный спрашивает, а не называет ли мой друг, Владислав, трупиков пёсиками?

Девушка в недоумении подняла брови.

– Потому что у них холодные носики, – объяснила Агата.

Нора вновь рассмеялась.

– А он называет? – отдышавшись, уточнила девушка.

Уголок рта хозяйки «Маятника» дёрнулся.

– Не исключено.

## 28 {-#28}

Очередной проигрыватель расположился у входа в церемониальную комнату. В отличие от гостиных, пластинок здесь было куда меньше.

Пришедшие проститься с Валерием горожане начинали понемногу подтягиваться, и пускай подавляющее большинство последних облачилось в чёрное, ни один из них не мог тягаться с Агатой в количестве излучаемого траура.

Наши героини стояли по обе стороны дверной арки, помогая гостям рассаживаться. Воздух переполняли цветочные запахи, излучаемые букетами, что были уложены вокруг гроба. С каждой минутой их становилось всё больше. Вскоре цветы уже заполнили треть помещения, и Нора – едва ли счастливая обладательница аллергии, набирающей обороты с приходом тепла, – возблагодарила Валерия за решение покинуть этот бренный мир туманным декабрьским утром.

Тогда девушка и подумать не могла, чем обернётся сегодняшняя церемония.

Гости тем временем всё прибывали. «Утром, в полдень» зал впитал свыше четырёх сотен душ, что вдвое превышало количество стульев. Некоторые выражали хозяйке «Маятника» свои соболезнования, но большинство явившихся попросту не замечало Агату, (что её более чем устраивало) они сбивались в кучки и шумно продвигались в конец зала, не забывая при этом жалостливо всхлипывать.

Мальчишка по прозвищу Гек тоже был здесь. Нора видела как тот прикладывал к лицу платок, насквозь промокший от слёз. Заприметив девушку, Гек учтиво кивнул – от бывалой смешливости не осталось и следа. 

(Элеонору это не удивило: боль утраты зачастую чувствуется не сразу, уступая дорогу шоку, к тому же, несмотря на свою самостоятельность, Гек по-прежнему оставался ребёнком.) 

Девушка ответила тем же. 

Элеонора слыла натурой впечатлительной, а потому обычно избегала присутствия на похоронах, или свадьбах, находя эти события одинаково печальными. Вот и сейчас в её горле поселился мерзкий ком, а на глазах проступили слёзы.

– Полагаю, время начинать, – бесстрастно произнесла Агата. Её взгляд упал на Нору. – Даже не думай. От слёз твой тонкий аристократический носик превратится в деревенское рыло. 

Что есть, то есть. 

Нора попыталась выдавить из себя улыбку. Кое-как удалось.

– Как это у вас происходит? – тихо спросила она.

– Владислав, как и копатели, не церемонии не присутствует. Он тепло относился к Валерию, но Ласло как-никак таксидермист-визажист, о чем гостям хорошо известно. Людям больно видеть очередное напоминание о смерти их близкого, а Владу это только на руку, потому церемонию я провожу одна, но Ласло…

– Он всегда рядом, – Нора провела пальцами по двойной стене.

– Именно.

– И с чего начинается церемония?

Агата ответила не сразу. Она уже сосредоточенно рылась в пластинках. Тонкие пальцы, наконец, выхватили нужную вещь, и дама вернулась к беседе.

– Процесс до неприличия банален: я ставлю тоскливую мелодию – никаких «Аве Марий» в моём доме! – красивую лирическую мелодию, приглушаю свет и на протяжении последующего часа эти окаянные, – Агата махнула рукой в сторону зала, – ревут, содрогаясь в обоюдных конвульсиях, периодически сдабривая это дело фразочками вроде: «На кого ж ти мене залиииишииииив?!»[^69]

[^69]:  Кому же ты меня оставил?!

Не считая чарующего убранства зала, картина в точности повторяла похоронные церемонии, на которых Норе всё же довелось присутствовать в своём родном городе. Однако, от Агаты она ожидала большего.

– А дальше?

– А дальше покойника выносят во двор и придают земле, тем самым сопутствуя процессам разложения.

Лицо Элеоноры в удивлении подалось назад, от чего на шее мелькнула тень от несуществующего второго подбородка.

– Не может быть, – озадаченно произнесла Нора и, предвидя намечающийся рассказ Агаты о четырёх стадиях естественного разложения трупа, поспешила добавить: – Но кто-нибудь же произносит речи?

Агата вздохнула.

– Ты набралась этого из зарубежных фильмов, – заявила она и поднесла к виску указательный палец. – Вот где прощаются с близкими и произносят речи. Сюда же приходят исключительно с целью выплакаться.

– Ты так спокойно это воспринимаешь…

– О нет, – она резко выставила вперед правую руку, – всхлипывания меня раздражают. Обычно я стою у самого проигрывателя, пытаясь заглушить их.

Агата поставила пластинку, и зал окунулся в отчаянно прекрасную мелодию, к счастью оказавшуюся не первородным пост-панком, от которого девушка уже изрядно подустала.

Она узнала мелодию.

– Думаешь, это подходящая песня? – с сомнением протянула Нора.

Агата вновь не спешила с ответом: она принялась задергивать шторы.

– Композиция, конечно, замечательная…

– Естественно.

– …но, мне кажется, её лучше слушать… когда всё живы.

Адам Хёрт тем временем пророчил неизбежное:

<p align=center>
<em>
From the moment you start up this miserable life
</em>
</p>

<p align=center>
<em>
You should know that it's only a matter of time
</em>
</p>

<p align=center>
<em>
'Till you die
</em>
</p>

<p align=center>
<em>
'Cause we're all gonna die
</em>
</p>

<p align=center>
<em>
Start saying goodbye![^70]
</em>
</p>

[^70]:  Текст композиции Hurt под названием Flowers: (англ.) с того момента, как ты начал эту жалкую жизнь, ты должен понимать, что это только дело времени – когда ты умрёшь. Потому что мы все умрём. Начинай говорить «до свидания».  

Покончив с окном, Агата повернулась к залу и застыла со сложенными на груди руками. Улучив момент, Нора окинула её взглядом: она всё ждала, что подруга вот-вот заплачет, слишком уж подозрительным казалось её спокойствие. Но дама стояла ровно, с высоко поднятой головой и, кажется, даже подпевала. Утренняя рассеянность вконец развеялась.  

(Лишь позже Норе открылось, что слабой Агата бывает лишь наедине с собой.)

<p align=center>
<em>
And sarcastic song writers
</em>
</p>

<p align=center>
<em>
Guys with tattoos, drummers and bassists and engineers too
</em>
</p>

<p align=center>
<em>
And every last person that sang in this room
</em>
</p>

<p align=center>
<em>
They will die
</em>
</p>

<p align=center>
<em>
'Cause we're all gonna die…[^71]
</em>
</p>

[^71]: (англ.) И авторы саркастических песен, ребята в татуировках, барабанщики, басисты и инженеры тоже, и все до последнего, кто подпевает в этой комнате – они умрут, потому что мы все умрём…   

Звуки музыки близились к своему лирическому завершению.

– Однако… – начала Агата.

Нора с интересом взглянула на неё.

– Сегодняшний случай не стоит приписывать к повседневным. Это и моя боль тоже. У них было четыре минуты и тридцать восемь секунд для слёз, так что пора сворачивать эту драму. Элеонора?

– Да?

– Будь добра…

– Чем смогу?

Агата вновь запустила пальцы в виниловую стопку.

– Поставь её через тридцать секунд, – произнесла Агата и тут же исчезла в толпе.

Нора взглянула на полученную пластинку и удивленно вскинула брови.

«Ну, женщина в чёрном, надеюсь, ты ничего не напутала…»

## 29 {-#29}

Знаете, говорят, что жизнь не похожа на кино. Да, она в корне отличается от сопливых романтических комедий, кишащих неправдоподобными хэппи-эндами, или, скажем, идеальной рекламы кофе, но это уж точно не относится к душевным фильмам. Большинство в кино на такие не ходит, предпочитая им шумные блокбастеры, где все куда-то бегут, однако Элеонора как раз таки относилась к тому самому меньшинству. Тем днём, стоя в отведенном под церемонии прощанья зале, девушка зачарованно впитывала разыгравшуюся перед ней трагикомедию, в которой каждый шаг, каждое движение главной героини напоминали любимые киноленты.

Вопреки всему вышесказанному, происходящее вокруг Нора находила вполне реальным и пропитанным жизнью, с какой бы иронией это не звучало в сложившихся обстоятельствах. Именно тогда Агата перестала быть для неё лишь красивым картонным образом.

Пластинка транслировала одушевляющие нотки, кричащие об идеальной жизни. Уверенным шагом Агата поднялась на возвышение и с безмятежностью прислонилась к дальней стене. Музыка Моби вызвала в толпе неодобрение, но героине нашей было на это более чем наплевать.

Вот она потянула железную цепочку и за гробом с усопшим появился огромный белоснежный экран. Невидимый проектор, которым, вероятнее всего, руководит Владислав, начинает транслировать мерно всплывающие фотографии.   

Нора не была поклонницей слайд-шоу, считая их признаком дурного вкуса, но это было весёлым исключением. Вместо привычных фотографий вроде «наш парень в школе», «наш парень окончил университет» и «наш парень женился», гостям показывались совершенно иные воспоминания, идеально гармонирующие с музыкальным сопровождением.

Подобно персонажу Лиама Нисона, Агата мягко улыбнулась залу и начала показ. Нора видела как дрожат губы её подруги. Вскоре из-под очков показались слезинки, но Агата плавно смела их, продолжая улыбаться. На экране один за другим всплывали снимки.

> *Вот Валерий сидит в плетёном кресле посреди гостиной второго этажа. Он курит трубку с гротескной серьезностью, а за его спиной виднеются пятки убегающего Владислава.*
> 
> *Вот он стоит перед парадным входом «Маятника» с лопатой в руках; на мужчине рабочая одежда и огромная соломенная шляпа, в зубах – всё та же трубка. Здание выглядит заброшенным, так что Нора думает, что это первые дни возобновления бюро. Рядом, обхватив Крёстного за шею, Агата демонстрирует ровные зубы. На вид девушке около двадцати, волосы едва ли касаются плеч; на Агате надет пуловер со звездами и старомодный рваный комбинезон – никаких траурных одежд.*
>
> *Вот Валерий закинул Агату на плечо и дикаприевской походкой шагает вдоль кладбища, по-прежнему держа трубку в свободной руке.*     
> 
> *Вот он обнимает целый галлон вина, обмотанный подарочной лентой. На лице проступает невиданное блаженство.*
>
> *Вот мужчина обнимается с унитазом, показывая в камеру средним палец: вероятно, в те дни Агата ещё не до конца обучилась виноделию.*
> 
> *Вот Валерий самоотверженно пытается выбраться из свеженькой могильной ямы, в которую угодил по собственной неосмотрительности. Он делает вид, что злится, однако глаза – синее синего – выдают улыбку.*
> 
> *На следующем кадре  погода изменилась. С широкой улыбкой на глазах Валерий стоит на четвереньках посреди центрального катка; на ногах виднеются коньки, он боится стоять на льду.*
> 
> *Вот Валерий вновь курит, но на этот раз не трубку. В его ладонях зажат новенький бульбулятор. Комната заполнена плотным дымом. Поблизости валяется Владислав, которому, кажется, наплевать на собственную социофобию.*
> 
> *Вот Валерий испуганно смотрит на пустую стену, обхватив руками горло.*
>
> *Вот одурманенный он мчится по коридору, тогда как не менее обкуренная Агата пытается остановить Крёстного.*
> 
> *Вот Валерий выпал из окна и довольно растянулся на крыльце. К счастью, это был первый этаж.*

Тем временем Агата склонилась над гробом, всматриваясь в лицо усопшего и напоминая Элеоноре персонажа Блума.

– Она думает, в действительности ли он улыбается, – вслух произнесла девушка, чем приковала к себе парочку и без того негодующих взглядов. 

– КУРВА СКАЖЕНА![^72] – крикнул кто-то по соседству.

[^72]:  Сука бешенная! 

– Я почти уверена, что за очками скрывается безмятежность, – ответила Нора.    

> *Вот Валерий в одних плавках стоит на траве. Рядом уже практически принявшая свой привычный вид Агата, а около неё тот самый андерграундный молодой человек. Валерий смеется и держит на тыльной стороне ладони горящую свечу.*
>
> *Вот Агата горит, а молодой человек снимает с себя блейзер, умирая от смеха.*
> 
> *Вот Валерий в своем магазинчике…*

Снимки продолжали исчезать и появляться. Агата зажала в зубах сигарету и нервно шарила по карманам в поисках огонька. Вдруг из ниоткуда появилась мужская рука, держащая включенную зажигалку. До ушей доносилось:

<p align=center><em>
Oh,
</em></p>

<p align=center><em>
We close our eyes...
</em></p>

<p align=center><em>
The perfect life, life
</em></p>

<p align=center><em>
Is all we need.[^73]
</em></p>

[^73]:  Текст песни Moby под названием Perfect life: (англ.) ох, мы закроем свои глаза… Идеальная жизнь – вот все, что нам нужно.

Агата подкурила, но рука Владислава не исчезла. Огонёк вдруг начал колыхаться в такт музыке. Агата улыбнулась и принялась подпевать. Завидев эту картину, Нора разразилась смехом.

Она услышала недовольный шум толпы и тут же сделала музыку громче.

Тем временем Агата избавилась от сигареты не совсем корректным способом, швырнув её в вазу с цветами. Дама склонилась над покойником, крепко поцеловав его в обе щеки, и закрыла крышку гроба, отчего публика начала негодовать сильнее. Самая отважная старушенция, которая твердо вознамерилась скорбеть не менее часа, в гневе бросилась на Агату. Роста в последней – полтора метра с кепкой, так что дама без труда её остановила. Однако, неудержимая бабуля решила нанести ещё один удар.

Музыка продолжала литься. Где-то в паре метров от гроба, виляя бёдрами, танцевал Ласло, периодически натыкаясь на стены.

– Не смей меня, блядь, трогать! – крикнула Агата.

Вот непослушная бабуля уже летела в направлении вышеупомянутой вазы. 

«Хоть бы она никого не сожгла…» – пронеслось в голове Элеоноры.

Девушка не сразу осознала, откуда такие мысли, но следующее действие всё прояснило.

Подставка для гроба оказалась ничем иным, как стальным прозекторским столом, скрытым под бархатными тканями. Агата нашла ручку и принялась катить гроб к выходу. Толпа охала и, естественно, ахала. Никто не аплодировал и не двигался в такт музыке, как это бывает в глупых фильмах, но никто также не осмелился остановить хозяйку «Маятника».

На средине пути к Агате присоединился заплаканный Гек. Лицо мальчика отражало благодарность и глубочайшую скорбь, тогда как выражение физиономии самой дамы было сложно охарактеризовать: она была серьёзна, но в то же время безмятежна и абсолютно точно уверена в том, что делает.

«Это же Хешер!» – ликующе подумала Элеонора. 

Вот девушка уже обнаружила себя расталкивающей буйствующих гостей. Увидела, как прорывается к гробу и становится частью истории. Сама того не ведая, Нора плакала: очень уж она впечатлительна.

Втроем им удалось преодолеть зал как раз к концу мелодии. Шагали наши персонажи спокойно и неспешно, так, словно везли Валерия прогуляться. Мелькающие со всех сторон лица – разгневанные и озадаченные – казались им лишь размытым фоном.


<p align=center><em>
The perfect life. The perfect life. The perfect life.
</em></p>


Лица соприкоснулись со свежим ветром. Они вышли во двор.

– Дамы и господа, – торжественно произнесла Агата. – Объявляю первую за всю историю существования «Маятника» десятиминутную церемонию прощанья оконченной.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Да, жизнь это кино. Независимое авторское кино, разумеется.  

























