---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Часть II. Гром и Молния {-#chapter-2}

<div align=right>

  *(Девушка, указывая на забор кладбища:)*

  *– А зачем вам колючая проволока? По ночам сюда залезают?*

  *(Гробовщик безразлично:)*

  *– По ночам отсюда вылезают.* 

  *к/ф Влюбленный гробовщик*

</div>

## 30 {-#30}

Широкая полоса леса раскинулась под небесным сводом. Морозный воздух покрывал щёки девушки колючими поцелуями. Погода обещала быть бодрящей: термометр показывал шесть градусов ниже нуля. 

В это время года рассвет наступал не ранее семи утра. Агата подкурила очередную сигарету. Сегодня солнце за её спиной поднялось лишь без четверти восемь. Столетние сосны, туи и ели тянулись густой стеной, конца которой было не видать. Верхушки деревьев ещё сохранили на себе остатки вечернего снега и теперь вовсю переливались под лучами холодного солнца.

Ветра не было и перед глазами девушки застыла неподвижная картина, единственным изменением в которой была игра света. Ни одна ветка не шелохнулась пока солнце медленно поднималось над лесом, так что открывшийся вид скорее напоминал фотоснимок, которому постепенно предавали теплые тона. Последнее навело Агату на мысль о социальных сетях, а те, в свою очередь, напомнили о Норе.

Лесной пейзаж всегда действовал на владелицу «Маятника» умиротворяющее, и пускай она не была здесь более десяти лет, мысли девушки частенько возвращались к тихим полянам и одиноким тропинкам, усеянным сухими иголками и пожелтевшей листвой. Стоило Агате почувствовать, что руки опускаются, а измученное тоской сердце колотится так, словно вот-вот выскочит из груди, предвещая нервный срыв, она тут же закрывала глаза и переносилось в это чарующее место. Порой девушке приходилось облачиться в наушники, забраться в постель и некоторое время провести так, погрузившись в воспоминания о днях, когда в её мире не было места печали, а жизнь была полны покоя, изучения литературы и прогулок по волшебным тропинкам, ведущим к излюбленным местам. 

Сейчас, стоя на одной из тех самых дорог и купаясь в холодных рассветных лучах, Агата Рахманинова с едва уловимым удивлением осознала, сколь многое она забыла. Естественно, стирать детские вспоминания – привычное дело для человеческого сознания, особенно когда речь идет о мелочах, которым в мире взрослых не принято придавать большого значения. Но значение у них всё-таки было. Прошлое казалось ей размытой плёнкой, годами пылившейся в дальнем углу воспоминаний, но стоило Агате вернуться в родные места, как кто-то в её голове взялся за старый ящик и принялся старательно проявлять снимки, постепенно придавая им чёткости. 

Тогда она поняла, что уже давно не помнила, как старательно вырисовывала контур леса, сидя на этом самом месте; не помнила, как кузен бродил во сне и однажды чуть не потерялся в чаще; не помнила, как в канун Ивана Купалы сама гуляла по ночному лесу в поисках цветущего папоротника, дарующего бесконечную силу (включающую ясновиденье и власть над нечистым духом); не помнила, как лежала на печи, всматриваясь в крохотное окошко, открывающее лоскут звездного неба; не помнила, как неделями мастерила плот для покорения кристально чистых озер. Она осознала, что прожила последние годы, не зная, что однажды принимала у собаки роды; не знала, что когда-то забиралась на самую верхушку сосны в поисках мобильной связи; не знала, как прекрасен лес во время грозы; не знала, что именно здесь услышала свою первую андерграундную пластинку; больше не знала, каким был у него почерк, не знала его отчества, не знала, почему Адам оставил её.

Агата закрыла глаза. Это были не те мысли. Она глубоко затянулась, а затем выдохнула, создавая перед собой облако из пара и сигаретного дыма. Подсознание вновь сыграло с ней злую шутку, и она знала, что всё дело в ассоциациях. Девушка распахнула успевшие покраснеть глаза. Поблизости не было ни одной живой души, так что очки ждали её в домике, что остался за спиной. Может, оно и к лучшему.

Нужно было двигаться, иначе эмоциональная волна могла повториться, нахлынув с новой силой. Агата избавилась от погасшей сигареты.

Она ступила на заснеженную тропу и вскоре исчезла под покровом леса. 

## 31 {-#31}

Над долиной царил на удивление холодный вечер. Ветер заставлял деревья перешептываться, лишь начиная снимать с них листву. В печи приветливо шуршали обугленные брёвна. Сегодня небо было как никогда звёздным – девочка наблюдала за ним, свесив с лежанки не знавшие загара ноги и глядя в окошко, что размещалось под самым потолком. По своим размерам последнее не превосходило тетрадного листа. 

Стояла середина сентября тысяча девятьсот девяносто седьмого года.

Девочка – Агата, как вы уже, должно быть, догадались – держала в руках кружку с практически остывшим чаем. Не отводя взгляда на протяжении вот уже четверти часа, она  старательно рассматривала ту часть неба, что была видна с печи. Вглядывалась  в мерцающие светила, перебирала в голове все известные ей созвездия, историю их названий и пыталась вспомнить расположение зодиаков на небесном атласе. Затем вновь возвращалась мыслями к картине перед глазами, стараясь распознать виднеющиеся созвездия. 

В шестилетнем возрасте Агата уже начинала страдать нарушением сна. Особых мучений по этому поводу девочка не испытывала. Дискомфорт сказывался лишь в тех случаях, когда её пытались переучить. Только лет восемь спустя стало ясно, что дело вовсе не в бессоннице: биоритмы Агаты действительно отличались от общепринятого режима сна, но по сути никаких нарушений не было. По никому не известным причинам, подобные опции обосновались в организме девочки еще до её рождения, соседствуя с мизантропией и пороком сердца. 

Наша героиня ещё несколько минут сверлила взглядом звездное небо, после чего сдалась. Она вспомнила  о чае и принялась жадно поглощать его. Ввиду специфики своего организма в людях Агата больше всего ценила – и с возрастом это совсем не изменилось – умение мириться с её привычками. Дедушка был ранней пташкой, даже слишком. Он просыпался в четыре утра, завтракал в шесть и к семи был уже у калитки, готовый совершить первую за день прогулку. Не смыкавшая глаз всю ночь Агата с радостью к нему присоединялась и вместе они неспешно бродили по лесным просторам в поисках грибов и новых, не виданных ранее, озер и полян, что так умело прятались в глубинках леса. Иногда они заходили так далеко, что попадали в берёзовую рощу, а бывало, наоборот, держались ближе к дому, собирая дрова и хворост.

Так или иначе, спать Агате хотелось лишь к обеду и именно то, что дедушка не только не мешал её сну с полудня до наступления вечера, но и принимал эту привычку, так радовало нашу героиню. Было кое-что ещё: за всю свою жизнь Агата ни одного «утра» не провела без того, чтобы отпить чёрного чая, к которому позже добавилась сигарета. Дедушка же начинал и заканчивал свой день чашкой очень крепкого кофе, но к моменту пробуждения на ступенях лежанки Агату всегда ждала огромная кружка чая. Обычно девочка вытягивала руку, опустошала половину чашки и лишь потом выползала из-под одеяла. 

С годами, кстати, мало что изменилось. 

Вернёмся же к звездам. Этот вечер с самого начала отличился от всех предыдущих, потому что, распахнув глаза, девочка и думать забыла о чае. Она резко подскочила и поспешно уставилась в окошко. Отсутствовало и привычное желание позвать Булю и ещё с часок поваляться на теплых простынях, обнимая собаку. Агата слышала, что есть хороший способ быстро избавиться от дурного сна, а в тот день ей привиделся именно такой. Нужно было как можно скорее подойти к окну и стараться сконцентрировать своё внимание на открывающемся из него виде до тех пор, пока память не сотрет неприятные сновидения. Стоит сказать, что прежде данный способ действительно работал, но только не в этом случае.

Прошло минут двадцать, и Агате всё же пришлось это признать. Она опустошила кружку и начала спускаться с печи за новой. Девочка пыталась отвлечься от кошмара, погрузившись в книги, но мысли путались, так что ей приходилось по несколько раз перечитывать один и тот же абзац, что не могло не вызывать раздражения. Затем Агата опрометчиво силилась отвлечься с помощью ещё одного любимого занятия – рисования, но! Результат оставлял желать лучшего. Не потому, что картинка получилась так себе: Агата была совсем рёбенком и как все дети мнила себя великим художником. Результат оказался не очень как раз из-за того, что девочка изобразила именно то, что так сильно её напугало. Агата резко выдохнула и отшвырнула рисунок в корзину с макулатурой, надеясь, что следующим утром тот пойдет на растопку печи.

Она вдруг поняла, что вся дрожит и даже немного разозлилась на себя за это. Девочка не могла понять, почему увиденное во сне её так напугало. Она никогда не испытывала страха перед ведьмами, вампирами и прочей нечистью. Более того, Агата была поклонницей Гоголя, так что список её детских интересов составляли исключительно потусторонние и паранормальные темы. Это ещё сильнее пугало девочку: именно тот факт, что она испытывает странный, необъяснимый страх перед, казалось бы, безобидной детской фантазией, окончательно вогнал Агату в ступор. Она была настолько напугана, что ещё около часа не могла заставить себя покинуть пределы спальни. Чувство голода и тоски по любимому питомцу, всё же, возымело верх, и в итоге девочке пришлось отправиться на кухню, но, даже обнимая собаку, она не могла забыть странной картины, пригрезившейся ей накануне.

Сделать это не удалось и во время завтрака, который был для дедушки, скорее, ужином.   

## 32 {-#32}

Спустя тринадцать зим Агата с немалой грустью вновь обрела свое ненадолго утраченное одиночество. Алкоголь никогда не был в силах заглушить душевную боль девушки, а иногда и вовсе служил топливом для очага тоски в её сердце, так что владелица «Маятника» изо всех сил хваталась за спасательный круг, которым для неё служила литература. Правда крылась в том, что даже чтение не было способно заставить разбитое сердце забыть о пережитых горестях, но кое-что книги всё же меняли: они помогали заморозить мысли, отложить произошедшее, пускай и не в самый далёкий уголок сознания, и попросту тянуть время с надеждой на то, что когда девушке всё же придется вернуться к случившемуся, буря в её душе поутихнет. 

Конечно, тогда Агата и подумать не могла, что ждёт её дальше, а потому и не предполагала, что подобное состояние навсегда останется для неё единственным возможным.

В любом случае, девушка читала с неумолимой скоростью. Страницу за страницей и книгу за книгой, временами забывая о еде и отвлекаясь разве что на работу. Приносившее ей деньги дело отнюдь нельзя было назвать предсказуемым. Случались загруженные дни, но были и те, в которые никто почему-то не спешил умирать. Их Агата проводила не выбираясь из постели, а если девушка всё-таки решала покинуть её пределы, то лишь для того, чтобы обосноваться в старом кожаном кресле с привычной книгой в руках. Временами на неё накатывало внезапное тягостное вдохновение, и Агата бралась за кисти. Рисовала она чуть ли не в один присест: не могла уснуть, пока картина оставалась незавершенной, так что за мольбертом девушка проводила по несколько суток, но чаще всего её вечера занимала литература. Именно в один из таких мрачных и ничем не примечательных вечеров она взяла в руки бутылку Шато Шасс Сплин и «Призраков двадцатого века».[^74]

[^74]: «Призраки двадцатого века» – сборник рассказов американского писателя Джо Хилла.

Любимый напиток Байрона был приятным на вкус и практически оправдывал потраченную на него зарплату, но книга оказалась ещё лучше. К наступлению утра было прочитано двенадцать из четырнадцати рассказов. Пускай ни один из них не ввел Агату в состояние, хотя бы отдаленно напоминающее страх, местами она находила повествование не просто приятным, но и трогательным, вызывающим то самое трепещущее ощущение под ребрами и какой-то там ложечкой. Однако, ход событий резко переменился, когда пришло время для тринадцатого рассказа. История настораживала девушку с первых страниц, а вернее, со второго абзаца.

> *«За тобой гонятся карточные люди, – объяснила она, – дамы и короли. Они такие плоские, что могут проскальзывать под закрытыми дверями».*

Эти строки вызывали в душе девушки необъяснимую тревогу, что лишь усиливалась по мере развития сюжета. Агата не знала тому причин и, не прерывая чтения, всячески гнала от себя странные мысли. 

Безуспешно.

Повествование не было страшным. Оно было жутким. Под конец истории девушку всецело охватило чувство дежавю, смешавшееся с тревожным волнением. Она отложила книгу и какое-то время просидела, разглядывая то противоположную стену, то собственные руки, и пытаясь понять, чем вызван столь внезапный калейдоскоп эмоций. Естественно, чем больше Агата погружалась в мысли, тем быстрее от нее отдалялся ответ. В итоге, наша героиня уже не могла вспомнить, о чём думала минуту назад. Так всегда бывает с…

«С дурными снами», – произнесла про себя Агата.

Невнятная мысль промелькнула в её голове яркой вспышкой, чтобы исчезнуть прежде, чем девушка смогла что-либо понять. 

Внезапно захотелось рисовать.

Она растерянно взглянула на книгу и, не зная, что ещё делать, вернулась к чтению. Девушку не пугали события, что настигли главного персонажа в лесу, хотя они и включали в себя образ маленького призрачного мальчика, в одной пижаме разъезжающего на винтажного вида велосипеде. Настораживала скорее атмосфера и странное поведение героев рассказа. Конечно, было тут и кое-что ещё. Такое бледное и непритязательное, что Агата с трудом улавливала производившую этот шум волну, но вместе с тем понимала: именно та являлась истинным источником её тревоги. 

Покончив с книгой, девушка предприняла последнюю попытку найти причину ощущений, столь резко её охвативших. Агата чувствовала, что когда-то определенно знала ответ, но память стёрла эту информацию за ненадобностью. Понимала, что это что-то в действительности совершенно неважное, деталь, ни в чем не играющая роли, но, тем не менее, чувство страха, пугающее скорее своей внезапностью, не покидало девушку всё утро. 

К обеду она отдалась сну, а, очнувшись, начала новую книгу. 

С наступлением следующего дня Агата и думать забыла о случившемся. Она не вспоминала карточных людей на протяжении последующих пяти лет. До того самого момента, пока сердце и приближающийся нервный срыв не привели её обратно в лес.

## 33 {-#33}

Утро сменилось днем. Уютный слой перламутрового снега укрыл собой лес и долину, напоминая глазурь и превращая небольшие строения, – преобладающая часть которых пустовала уже долгие годы – разбросанные то тут, то там, в пряничные домики. За прошедшие часы температура воздуха поднялась до нуля. Ветра по-прежнему не было, и снежные хлопья сонно кружили в пространстве, играя солнечным светом. 

Ближайший домик располагался всего в сорока двух шагах от леса. Он был самым обычным деревянным жилищем с низкими потолками, но на фоне всеобъемлющей природы казался неким сказочным местом. Несмотря на то, что новогодние празднества остались позади, здесь царило волшебство.

И так было всегда.

Вскоре на конце тропинки показалась фигура, облаченная в траурные одежды. Она вышла из чащи и плавно двигалась по скрипучему снегу в сторону единственной виднеющейся тут калитки. 

Агата замерла в двух шагах от входа во двор и внимательно осмотрела дом. Он казался ещё меньше, чем запомнился ей из детства. Однако, вопреки звенящей тишине и тому факту, что при контакте с дверными проёмами дамочке теперь приходилось сгибаться в три погибели, (чувствуя себя Гендальфом, посетившим Шир) Агата ощущала, как при взгляде на знакомые ступени и заснеженные окошки, её тело наполняло поразительное спокойствие. 

В открывающемся пейзаже, казалось, чего-то не хватало. Всего на несколько секунд Агата прикрыла глаза, позволяя детским воспоминаниям выплыть наружу, а распахнув их, сразу же поняла, в чём дело. Отсутствовала главная деталь, превращающая домик в колыбель уюта – печь давно не топили, и, конечно же, из кирпичной трубы на крыше не валил пар.   

Агата слегка улыбнулась воспоминаниям и поспешила внутрь, намереваясь разогреть печь и искренне надеясь, что не забыла, как это делается.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Оказалось, забыла.

Дамочка залилась глубоким кашлем. Она бросилась к окнам и принялась открывать их одно за другим, сшибая на своем пути всякого рода хлам. Последнее мало заботило нашу героиню, хотя она в полной мере почувствовала упавший на её ногу тяжелый табурет.

Говорят, первый блин комом, но это ещё ничего. Чуть не лишить себя жизни в столь неподходящий для этого момент – куда неприятнее. Спальня и соседствующий с ней предбанник были заполнены чёрным дымом, который, вопреки стараниям, без остановки валил из печи. 

Как выяснилось позже, Агата поместила в печь слишком много поленьев, напрасно полила их керосином и недостаточно широко отодвинула створку дымохода, после чего благополучно погрузилась в сон, к счастью, не слишком глубокий, дабы пропустить нехватку кислорода.

Когда с устранением этого недоразумения было покончено и в комнате вновь сделалось возможным дышать, Агата умыла лицо и руки, покрытые слоем сажи, и вернулась в постель, с недоверием поглядывая на печь.

Спать совершенно расхотелось.

## 34 {-#34}

Темнота накрыла лес ещё до того, как часы успели пробить четыре. Слишком рано, даже для этих мест. Истосковавшаяся по сну Агата сидела у печи, зачарованно глядя на пламя и бесцельно перебирая старые стопки бумаги. Вскоре её взгляд застыл на одной точке, а лицо не выражало ничего, кроме еле уловимого отчаянья. Мыслями Агата была так далеко, что не сразу заметила, как её накрыло прежнее волнение, от которого она столь самонадеянно бежала сюда.

Хозяйка «Маятника» вздрогнула и, заметив, что пламя вот-вот погаснет, принялась бросать в него пожелтевшую от времени бумагу. Все ещё не в силах позабыть об угнетающих мыслях, то и дело всплывавших в её голове, Агата постаралась переключить внимание на что-нибудь другое. Вскоре она с немалой толикой безразличия разглядывала стопку бумаги, лежавшую у её ног. В основном там были древние журналы и газеты времен Советского Союза, но временами попадались старые дедушкины стихотворения. Девушка бережно отряхивала их от пыли и складывала на кофейном столике.

В какой-то момент Агата осознала, что жажда сна, наконец, взяла верх над её мрачными мыслями. Она облегченно вздохнула и, швырнув в огонь очередной выпуск «Вязания», уже предвкушала грядущие объятья Морфея, когда её рука замерла над стопкой, в глазах отразилась тревога, а из прикрытого рта вырвался резкий выдох, повторяя события многолетней давности.

На коленях девушки лежал детский рисунок. Пыльный, побледневший и местами порванный, при этом он был, всё же, узнаваем и запечатлел высокие тонкие силуэты, водившие хороводы внутри зеркала. Фигуры были изображены с помощью красной и черной красок, но Агата узнала бы их, даже будь они бесцветными.  

Карточные люди: короли, дамы и валеты из её сна! Карточные люди, которые отображались лишь по ту сторону зеркала. Тут-то Агате и вспомнилась «Маска моего отца»[^75], которая однажды навеяла на неё малопонятный ужас. Там были строки, поразительно напоминавшие детский кошмар, похороненный в недрах памяти.

[^75]: Рассказ из вышеупомянутого сборника Джо Хилла.

> *«Я отвел взгляд – не мог не отвести – и случайно посмотрел в зеркало на комоде. Покрывала слегка сдвинулись в сторону, и в отражении я увидел, что моего отца ласкает карточная женщина – пиковая дама. Её чернильные глаза устремлены вдаль, на теле – нарисованные одежды…»*

Конечно, в рассказе никто не водил хороводов. Странностей и без того хватало.

Агата же, в свою очередь, пришла к выводу, что в её сне происходила много больше событий, но сцена с жутким танцем оказалась единственным следом, отпечатавшимся в сознании. Большего ей знать и не хотелось. Подумать только, она каким-то образом смогла не только вспомнить сон, привидевшийся ей почти два десятилетия назад, но и испугаться таких воспоминаний! 

Девушка вопросительно подняла брови, сомневаясь в собственной вменяемости. Сложившуюся ситуацию она одновременно находила смешной и грустной. Агата загнала себя в глухой лес, желая успокоить нервы, но сейчас всё выглядело так, словно она в действительности страдает душевным расстройством. Меньше всего ей хотелось оказаться сумасшедшей, особенно… 

Нет, совсем не хотелось.

Агата отправила в огонь злополучный рисунок. Вслед за ним оправилась парочка новых поленьев.

Так закончился первый день в лесу.   

## 35 {-#35}

Гек не забыл о данном обещании и продолжил свой рассказ. Часть истории он поведал на следующий после похорон день. Это помогло разбавить гнетущую атмосферу, царившую в «Маятнике» после смерти Валерия. Мальчик говорил о том, как, мучаясь от безумных скачков температуры, провел несколько дней в состоянии трупа. Продвижение к цели сделалось для него мучительно медленным, и в один едва ли прекрасный момент Гек потерял сознание прямиком посреди трассы. 

Он пришёл в себя лишь когда над дорогой взошла полная луна, потревоженный вспышкой света, внезапно озарившей его лицо. Мальчику пригрезилось чудище с огромными жёлтыми глазами. Осознав, что перед ним автомобиль, Гек попытался отползти на обочину, но был слишком слаб для подобного рода действий.

Запоздалое везение всё же не подвело нашего героя. Спустя полчаса он очнулся на заднем сиденье машины со смутными воспоминаниями о предшествующих этому событиях. Водитель был мужчиной приятной наружности, немногим моложе Иисуса, и чем-то даже походил на последнего. Гек при всём желании не мог запомнить его имени. Спаситель уложил несчастного ребенка в автомобиль и без лишних раздумий помчался в город. Придя в себя, малец несколько раз поблагодарил спасителя, на что тот лишь встревожено улыбнулся и попросил ни о чем не беспокоиться. Затем сказал что-то о больнице, куда Геку ни за что нельзя было попадать. С таким же успехом он бы мог явиться прямиком в полицейский участок. Мальчик старался не терять контроля над телом, но периодически проваливался в сон. Проснувшись в очередной раз, он увидел, как сквозь запотевшие стекла переливались огни города. Геку удалось сбежать на ближайшем светофоре, оставив позади недоумевающего водителя.

Мальчик также поведал, как с трудом добрался до аптеки и, обзаведясь антибиотиками, отправился прямиком на вокзал, где и провел ту ночь. Утром выяснилось, что таблетки и какой-никакой, но, всё же, сон сделали своё дело и состояние больного улучшилось.

История, казалось бы, небольшая, но благодаря красноречию Гека и его любви к деталям, она заняла весь вечер. Мальчик начал рассказ во время ужина и закончил его, стоя рядом с Норой, наблюдавшей за тем, как хозяйка «Маятника» зажигала могильные огоньки.

– Найліпше мені ввижається та мить, коли я, ледве розплющивши беньки, поплентався до привокзального сортиру. Вперше за увесь час свого шляху я побачив власне відображення в люстерці і сказати, що побачене мене лишень вразило – не сказати нічого. Звичайно, в мене не з’явилась борода, чи ще щось навзнак мужності. Важко втелепати, що саме змінилось, але то був не я. З туалетного дзеркала у мене вдивлявся хтось інший.[^76]  

[^76]: Лучше всего мне видится тот момент, когда я, едва разлепив глаза, поплелся в привокзальный сортир. Впервые за всё время своего пути я увидел собственное отображение в зеркальце и сказать, что увиденное меня просто поразило – не сказать ничего. Конечно, бороды у меня не появилось, или ещё какого-нибудь признака мужества. Сложно смекнуть, что именно изменилось, но это был не я. Из туалетного зеркала на меня таращился кто-то другой.

Этими словами Гек закончил очередную порцию рассказа, и слегка поклонился в ответ на шутливый реверанс Элеоноры. Наблюдавшая эту картину Агата, вероятно, не единожды слышала вышеописанную историю. 

– Ты забыл свою любимую фразу, – без особых эмоций заметила она, зажигая новую свечу. 

Гек на мгновенье задумался, после чего просиял. 

– Трагічна жінка має рацію! – улыбаясь во все тридцать два, сказал малец. – Саме тоді я й став Геком.[^77]

[^77]: Трагическая женщина права. Именно тогда я и стал Геком!

## 36 {-#36}

В «Маятнике» наступление Нового года не отмечали, в традиционном понимании этого слова, как не отмечали Рождество, день всех влюбленных и любые другие праздники, связанные с убранством комнат. С большим трудом Элеоноре удалось получить разрешение развесить в гостиной парочку неоновых гирлянд.

– Бутылка хорошего вина послужит лучшим товарищем во время любого празднества, – произнесла Агата во время очередной попытки Норы убедить её хоть раз установить в доме ёлку.

– Но на твоем столе и так каждый вечер имеется бутылка, – с обидой пробормотала девушка.

– Значит, будет две, – отрезала Агата.

Она опустилась в кресло и раскрыла книгу на заложенном месте, давая понять, что обсуждение окончено.

Ещё какое-то время Элеонора посидела с надутыми губками, но вскоре поняла, что это едва ли принесет плоды, и поплелась в свою спальню. Девушка собиралась отправиться домой тридцатого числа. Как бы она ни презирала город, в котором волей судьбы ей пришлось расти, Нора находила крайне бессмысленным празднование нового года вне семейного круга. Дома её ждал вкусный обед, теплые объятья и, в конце концов, чертова ель.

Девушка убедилась, что дверь за ней закрылась, после чего отворила дверцу бездонного шкафа. Нора внимательно осмотрела находящийся перед ней предмет – новогодний подарок Агате.

Это был масштабный портрет и, возможно, лучшая вещь, из всех ею когда-либо нарисованных. Выполненная в холодных тонах картина с невообразимой точностью отображала внешние данные владелицы похоронного бюро. Единственное исключение составили глаза. На их месте Элеонора изобразила графики радиоимпульсов какого-то там пульсара, носившего невыносимо трудное название, словом, эмблему дебютного альбома Джой Дивижн. Надломленные линии горизонтально текли вдоль всего холста, предавая изображению некую абстрактность, создающую удачный контраст с реализмом общей картины. Этим Нора гордилась больше всего. 

Была у неё привычка, немало раздражавшая саму девушку: когда какая-нибудь из её картин вплотную подходила к логическому завершению и казалась Норе чудесной, в голове нашей героини вдруг зарождалось яростное желание продолжить рисунок. Как вы уже могли догадаться, в итоге, она перебарщивала с деталями, лишая собственное творение его первоначального шарма.

Вот и сейчас руки девушки предательски зачесались, умоляя добавить пару темных линий в-о-о-о-н в тот уголок, и Нора поспешно захлопнула дверцу шкафа.    

Из гостиной доносились отголоски незнакомой мелодии, вызывая в душе противоречивые чувства. Прихватив свою записную книжку, Элеонора уже отворила дверь спальни, намереваясь вернуться в отчужденную компанию, но так и застыла на месте. Среди музыки – пелось что-то о фотографиях и подходящих словах – девушка различала ещё один голос: тихий и лишенный эмоций он полностью соответствовал представлениям о своём владельце, таившихся в голове нашей героини.

Владислав продолжал говорить, но девушке так и не удалось разобрать ни слова. Она надеялась, что успеет понять что-нибудь в перерыве между песнями, но вот мелодия заиграла сначала, а таинственный голос и вовсе исчез. Нора вздохнула и вошла в гостиную.

– Что играет? – спросила она, желая избежать тягостного молчания соседки.

– The Cure, – не поднимая головы, произнесла Агата. – Музыка для тех, кто глубоко несчастен вместе с тем рад этому.     

Элеонора с недоверием взглянула на хозяйку «Маятника», пытаясь понять, не шутит ли она. Временами Агата говорила весьма странные и пафосные вещи, но делала это столь непринужденно, что сказанное начинало казаться забавным.

– Это как?

– Ну, для тех, кто ни жив, ни мёртв.

Девушка ещё с мгновенье постояла в дверях, дожидаясь более внятного объяснения, но его не последовало и Норе ничего не оставалось, кроме как опуститься на диван.

С чувством гнетущей подавленности, которое всегда сопровождало отсутствие вдохновения во время её литературных порывов, Элеонора принялась перечитывать рукопись. Написано было всего ничего, но девушке нравилось каждое слово и каждое событие её будущей книги. Своих персонажей Нора находила идеальными и прекрасно знала, как должен развиваться сюжет. У неё никогда не возникало проблем с облачением мыслей в слова. 

Именно это теперь и угнетало.

С каменным, как ей казалось, лицом Нора уже раз шесть перечитала ранее написанное, но так и не смогла выжать из себя и двух абзацев. Что бы ни приходило в голову, оно казалось девушке отталкивающе неуместным.

– Ну й чого ти журишся?[^78] – вдруг спросила Агата.

[^78]: Ну, и почему ты унываешь?

Нора вздрогнула. За время напряжённой работы мозга она успела позабыть о наличии в комнате кого и чего бы то ни было, кроме злополучной рукописи. Девушка в недоумении уставилась на подругу. Нора не могла с точностью сказать, что удивило её больше: внезапная смена Агатой языка, или тот факт, что та вообще заметила изменения в её настроении. 

– По-моему, мы все здесь сошлись во мнении, что это моя прерогатива – печалиться, – добавила Агата. 

На миг её лицо осветила улыбка, в которой проскальзывала едва уловимая печаль.

– Так что тебя омрачило? 

Нора осознала, что за всё время не промолвила ни слова. Подобное поведение казалось добродушной девушке невежливым, и та поспешила ответить.

– Книга. Она не пишется.

– Давно? – только и спросила Агата, хотя тон её был едва ли удивленным, превращая сказанное в утверждение.

Элеонора кивнула.

– Давно.

– Это всё персонажи, – опять не вопрос. – Они недостаточно живы.

Глаза нашей героини удивленно расширились. Агата говорила так уверенно, словно вдруг обрела способность к чтению мыслей.

– Я ведь… Не давала тебе прочесть рукопись? – медленно протянула Нора.

– Нет.

– И не рассказывала, о чём она?

– Нет.

– Тогда откуда..?

Агата вновь улыбнулась..

– Это и так ясно по тому, как ты выглядишь, когда пишешь.

– Что ты имеешь в виду?

– Я имею в виду что, что бы там не лежало в основе твоего сюжета, ты сама с натяжкой веришь в то, о чём пытаешься писать, – спокойно объяснила Агата. – Так всегда бывает с красивыми историями, авторы которых не испытывали держатся описываемых ощущений. Они понятия не имеют, о чём говорят, а потому подсознательно на расстоянии от персонажей. 

Девушка помедлила, удивленная обширностью ответа, а после выпалила всё, что таилось в её мыслях.

– Я работаю над романом меньше месяца, а в душе такое чувство, словно это тянется целую вечность. Искусство должно приносить радость, почему же тогда все мои амбиции обращаются мучениями? Фак, да мне просто хочется создать что-то прекрасное, но всё, за что я бы я ни взялась, оказывается пустым и в итоге у меня просто опускаются руки. Это невыносимо!

Агата отложила книгу и поднялась с места, дабы приглушить музыку.

– Твоя проблема, – начала она, – как раз кроется в убежденности в том, что искусство должно приносить радость. Да, порою это так, но! Оно приносит радость потребителю, но никак не автору, и уж тем более не во время самого процесса создания. Изливать душу чертовски сложно, а именно этим ты и должна заниматься и единственной радостью, которую ты получишь, станет облегчение – момент, когда понимаешь, что, наконец, сказал пером всё то, что хотел сказать. 

Владелица похоронного бюро помедлила, наблюдая за реакцией своей собеседницы, после чего с небывалой мягкостью в голосе задала вопрос.

– Ты вообще знаешь, что хочешь сказать своей книгой?

На этот раз Элеонора ответила без промедлений.

– Я хочу создать новый мир, прекрасный на первый взгляд…

– Нет, – прервала её Агата. – Я не спрашиваю тебя о сюжете. Идея – вот что должно теплиться в твоей голове на протяжении всей работы над романом. Ты можешь писать о будущем и прошлом, в котором никогда не жила, можешь вообразить новые миры и галактики, о которых ничего не знаешь и, изучив, или, опять-таки, придумав сопутствующую информацию клепать сюжет, облагораживая его красивыми деталями. При этом ты должна понимать, что всё вышесказанное – лишь декорации, окружающие твою идею. 

Представь, что повествование – это тесто, а детали, такие как место и время, придают ему форму, делают более привлекательным в чужих глазах, но никак не влияют на вкус. Ты не обязана отправляться на Луну, если хочешь сделать её местом действия своей истории, но ты должна пережить то, о чем пишешь, а вернее писать только о тех чувствах и эмоциях, которые ты в действительности пережила. В противном же случае твоё творение, (даже если ты заставишь себя его закончить) выльется одной лишь красивой картинкой, которая не будет цеплять никого, включая тебя саму.

Я не прошу тебя сейчас выбросить свой опус, хотя история о новом, на первый взгляд прекрасном мире, кажется мне более чем банальной в наши дни. Я прошу тебя прекратить вечерами напролет сверлить взглядом рукопись и попробовать разобраться в себе, понять, что ты уже успела пережить. Найди эти эмоции и извлеки на поверхность, вне зависимости от того, хорошие они или плохие.

Скажи мне, что ты чувствуешь?

– Растерянность, – угрюмо произнесла девушка.

Агата недовольно хмыкнула.

– Ой, да ну это и так ясно. А глубже?    

Элеонора развела руками. Выглядела она ещё более опечаленной, чем в начале разговора. Раздражение от неудачных творческих попыток исчезло, оставив лишь горечь и жалость к самой себе. 

– Боюсь, я ничего не чувствую, – с сожжением призналась Нора. – Моя жизнь не хорошая и не плохая, она совершенно обычная. Тут ты абсолютно права: я не знаю, что пытаюсь сказать своей книгой. Никогда об этом толком не думала. По-моему, во мне просто нет ничего такого глобального, и это заставляет меня чувствовать себя заурядной. И огорчает.

– Что ж, если это так, тебе стоит написать о человеке, который боится, что ему нечего сказать миру, – заметила Агата.

Следующая фраза, поразила девушку сильнее, чем сам разговор.

– Уверена, в тебе есть гораздо больше, чем ты способна себе представить.

Сейчас больше всего на свете Норе хотелось, чтобы её собеседница оказалась права, но, размышляя о двадцати прожитых годах, она не могла представить ничего, способного хоть немного затронуть чью-нибудь душу.  

– Почему ты так думаешь? – наконец спросила Элеонора.

– Копай глубже, – просто ответила Агата.

Она опустила голову и вновь углубилась в чтение. Разговор окончился так же внезапно как и начался.

## 37 {-#37}

Снег понемногу начинал таять. Ещё недавно обрамлявший деревья своим сверкающим кружевом иней постепенно исчезал, обнажая голые ветви. Вопреки стремительному приближению нового года, над Львовом повис ноябрь. 

Элеонора гуляла по кладбищу, пределы которого ей вовсе не хотелось покидать в такую погоду, как бы странно это не звучало. Она стала лучше понимать хозяйку «Маятника» и теперь воспринимала окрестности скорее как задний дворик, а не место скопления траура, или чего бы там ни было ещё. На улице было мерзко и холодно, периодически валил мокрый снег, что тут же исчезал при контакте с землей, так что отходить далеко от тепла Нора не желала, а кладбище – с его многочисленными холмами и аллеями – служило прекрасным аналогом парка, когда в девушке просыпалось желание размять ноги. 

Размышляя о странном, если не сказать душевном, разговоре с Агатой и своей жизни в целом, Элеонора немного взбодрилась, когда пришла к выводу о том, что то самое, переменчивое и захватывающее, о чём стоило бы рассказать читателю, происходит с ней прямо сейчас.

Луж в округе прибавилось и, спустившись с холма, наша героиня увидела небольшую табличку, что выглядывала из сугроба, успевшего значительно сдать в размерах за последние несколько дней. Надпись гласила:

<p align=center>
*«Червей не копать!»*
</p>

Девушка иронично улыбнулась этой находке и продолжила прогулку.

Ветер скользил меж надгробий, напевая понятный лишь ему одному мотив, когда, преодолев немалое расстояние, Элеонора решила вернуться в «Маятник». Сквозь небесную оболочку теперь просеивался мелкий дождик. Девушка уже миновала аллею склепов и, дрожа от холода, шагала под навесом массивных сосен Эллиота. Большие чёрные вороны сделались регулярными посетителями некрополя. Их крики разносились по всей территории и, сливаясь с атональным воем ветра, создавали атмосферу обречённости. Птицы виднелись на склепах, крестах и памятниках, голых ветвях и витиеватых калитках из тёмного метала, так что, уловив боковым зрением какое-то движение справа от себя, Нора сперва приняла его за компанию очередного ворона. Однако, поддавшись интуиции, она обернулась…

## 38 {-#38}

… чтобы увидеть высокого молодого человека, облачённого в чёрное пальто строгого покроя. Тот стоял подле одного из излюбленных надгробий Агаты, являвшего собой широкую каменную кровать, украшенную орлами с гордо расправленными крыльями; её изголовье служило ещё одним ложем, на котором, поместив головку на руку, вечным сном забылась каменная женщина. Черты лица и складки её одежд были столь искусно изготовлены, что при длительном взгляде на фигуру казалось, словно платья мерно вздымаются от вздохов дремлющей.

Именно это сейчас и делал незнакомец: не отводя глаз, рассматривал памятник, в то время как Нора разглядывала его. Несмотря на время и место, молодой человек выглядел так, будто ожидал старого друга.

Заметив чьё-то присутствие, незнакомец обернулся, и Нора поразилась тому, как он был красив. Тем временем молодой человек слегка улыбнулся и вскинул руку в приветственном жесте. Элеонора ответила тем же, и незнакомец вернулся к безмолвному изучению памятника.

Слегка растерянная, наша героиня продолжила идти в сторону похоронного бюро.

<p style="margin-top: 2em; margin-bottom: 2em">  
&ast;
</p>

Её поезд отходил в два часа и двадцать четыре минуты. За последние годы поезда стали на удивление пунктуальны. Они прибывали и отправлялись по расписанию в точности до секунды, так что Норе пришлось несколько раз свериться с билетом, дабы запомнить, что поезд отходит в четырнадцать двадцать четыре, а не в четырнадцать двадцать шесть – она не была рассеянной, но с детства путала цифры, составляющие в сумме число десять.

Каменное обрамленное колоннами крыльцо «Маятника» было усеяно воронами, как и сам дворик похоронного бюро. Птицы разгуливали по оккупированной территории размеренным шагом, перекрикиваясь скрипучими голосами и оставляя на талом снегу дорожки хрупких следов. Присутствие девушки их ничуть не смутило. Пернатые чувствовали себя полноправными хозяевами кладбища. Один ворон разместился в бесстрашной близости от входной двери, так что Норе пришлось отодвинуть упрямую птицу ногой, прежде чем войти внутрь. Та недовольно каркнула и отпрыгнула в сторону, чтобы мгновеньем позже вернуться на прежнее место.

Затворив за собой массивную дверь, Элеонора попала в знакомую атмосферу уюта. Внутри было блаженно тепло. Воздух пропитался сосной с тонкой ноткой кислинки, которой веяло из приоткрытой двери чулана, где содержимое медных чанов как раз проходило стадию мацерации. Откуда-то сверху доносились усыпляющие звуки музыки. 

Норе вдруг подумалось о том, как же приятно вернуться в «Маятник» с его высокими потолками, ветхой мебелью и вечной неизменностью. Девушка улыбнулась, дивуясь этим мыслям: она провела здесь только месяц, но теперь бюро  отзывалось в её душе приятными нотками ностальгии.   

Утро близилось к девяти часам. Нора ожидала найти Агату на привычном месте – дремлющей в кожаном кресле, но когда девушка принялась подниматься по широким ступеням, та выплыла из своего кабинета. По всей видимости, владелица бюро направлялась в сторону винного погреба. Вид у неё был довольно странный: скулы подведены, а губы пылают алым, очки на прежнем месте; на затылок сдвинута шляпа федора, из под которой старательно уложенные волосы волнами ниспадали на грудь, а ниже… Наспех накинутый халат и махровые тапочки, а между зубами зажата сигарета. Создавалось чувство, словно в спешке Агата успела привести себя в порядок лишь наполовину, или наоборот – ещё не до конца подготовилась к сну, сложно было сказать наверняка, учитывая режим дамочки.

Та остановилась, заметив присутствие Элеоноры, после чего медленно кивнула. Вопреки комичному внешнему виду, выражение лица Агаты выдавало в ней мастера похоронного дела.

– Кто-то умер? – поинтересовалась Нора и лишь затем поняла, как двусмысленно прозвучал вопрос.

– Моё светлое будущее.

Агата произнесла эту фразу тоном, лишенным каких бы то ни было эмоций, а затем вдруг разразилась странным, чуть ли ни нервным смехом. 

Не знавшая, что сказать, девушка изумленно застыла на лестнице. Агата поймала её взволнованный взгляд, и выражение лица хозяйки «Маятника» вновь сделалось непроницаемым.

– Не переживай, – произнесла она в привычной холодной манере. – Всего лишь ещё один заказ.

## 39 {-#39}

Под конец минувшего года произошло ещё кое-что занятное. Прежде чем покинуть бюро ритуальных услуг, чтобы сесть в лишенный комфортабельности поезд, Нора намеревалась вручить Агате её новогодний подарок. Ввиду распорядка дня последней, девушке пришлось сделать это поздним вечером, предшествующим дню отъезда. 

Очередная церемония прощанья закончилась много часов назад, но, войдя в гостиную, Элеонора отметила, что лицо владелицы «Маятника» по-прежнему сохраняло траурный вид.

– Мой поезд отправляется в четырнадцать двадцать шесть… – начала девушка.

– Четырнадцать двадцать четыре, – поправила её Агата.

Нора смущенно улыбнулась. Агата слегка склонила голову таким образом, что очки мешали понять, смотрит ли она в книгу, или на свою собеседницу. В любом случае, девушка продолжила.

– Думаю, к тому времени ты уже будешь видеть десятый сон, так что… – она помедлила, пытаясь понять, куда же всё-таки смотрит Агата.

Если та и заметила наличие свертка, который девушка держала в руках, то виду не подала.  

– Я хотела отдать тебе это прежде, чем отправиться в постель. 

Нора сделала пару шагов к креслу, в котором полулежала Агата, и протянула ей квадратный свёрток. Бледная рука скользнула в сторону наглухо запечатанного портрета. Её обладательница положила предмет на журнальный столик и после длительной паузы монотонно произнесла:

– Благодарю.

– Не хочешь узнать, что в нём? – спросила Нора.

Она продолжала улыбаться, не зная, что ещё делать.

– Позже.

Слегка разочарованная, Нора всё же сказала то, что собиралась.

– Знаешь, никогда бы ни подумала, что найду себе друга за столь короткое время. Откровенно говоря, я очень в этом сомневалась. Думала днями буду сидеть одна в чужом городе, не зная, куда себя деть, но теперь у меня такое чувство, словно мы знакомы вечность.

– Давай без реверансов, – ответила Агата.

– Ой, да не хмурься ты всё время! – воскликнула девушка.

Её лицо осветила широкая улыбка, а затем, поддавшись минутному порыву, Нора наклонилась и обняла подругу. Она указала на принесенный свёрток.

– Тебе понравится.

Тень улыбки скользнула на лице дамочки в чёрном.

– Не сомневаюсь.

Элеонора выпустила её объятий и зашагала к выходу. Она остановилась у самой двери.

– Мы увидимся через неделю, – пообещала девушка.

И нарушила обещание.

## 40 {-#40}

Следующим утром Элеонора вновь проснулась раньше, чем рассчитывала. До выхода оставалось больше двух часов, а то немногое, что она собиралась взять в дорогу, уже давно было сложено, так что девушка сидела на кухне с планшетом в руках, гуляя по социальным сетям. Вообще-то она собиралась выпить чашку кофе и провести первую половину дня скитаясь по городу, но, умостившись за столом, поняла, что в ближайшее время вряд ли захочет сдвинуться с места.

День обещал быть пасмурным. Ветер барабанил дождем в окна, а из старого радиоприемника раздавалась мелодия «Летнего места» Макса Штайнера, столь поразительно контрастирующая с погодой. Звуки музыки обволакивали девушку сладостными грёзами и заставляли чувствовать себя счастливой. Она не могла припомнить, когда в последний раз слышала эту мелодию, но вскоре добавила её в свой плейлист и, включив повтор, с головой окунулась в графоманию. 

Неожиданно для себя самой, Элеонора преодолела барьер в семь сотен слов. Воодушевленная музыкой, она продолжала писать, прерываясь лишь для того, чтобы подлить себе кофе и приближаясь к тысяче – заветному количеству исторгнутых на бумагу слов для всех начинающих авторов.

Наша героиня как раз собиралась отхлебнуть бодрящего напитка, когда атмосферу её душевного покоя внезапно нарушила Агата. Растрепанная, но с очками на привычном месте, она влетела на кухню в наспех запахнутом халате, из-под которого виднелись оборки белья. Конечно же, черного.

Определенный эффект произвело и то, что Агата буквально вышла из стены.

«Ещё один тайный ход», – подумала девушка.

Элеонора так и застыла с чашкой в одной руке и карандашом – в другой, вопросительно глядя на подругу. Та замедлила шаг и, подойдя к плите, повернула ручку. Только теперь Нора заметила, что духовка была включена.

– ДОВОЛЕН ТЕПЕРЬ? – крикнула Агата, обращаясь к стенам. Она повернулась к ошарашенной Норе и, пытаясь убавить злость в голосе, произнесла: – Это Ласло, кулинар хренов! Поставил в духовку свои блядские артишоки и съебался к чёртовой матери, завидев твоё приближение.

Норе понадобились силы, чтобы не расхохотаться. Она постаралась вспомнить что-нибудь печальное. В голову пришли кадры из «Землян»[^79] и это помогло. Девушка открыла рот, собираясь как-то успокоить подругу, но та тут же выставила вперед руку, демонстрирующую фарфоровую кожу.

[^79]: «Земляне» – документальный фильм Шона Монсона о проблеме жестокой эксплуатации животных людьми для различных целей.  

– Нет! Не заговаривай со мной, даже не думай! Я безумно зла, если меня будят раньше времени, я же говорила тебе, когда мы…

Концовка фразы исчезла за пределами кухни вместе с Агатой прежде, чем Нора успела опомниться. 

Девушка пожала плечами. Мысль о том, что боязливый Владислав к тому же знатный кулинар не могла не вызвать у неё смех.

«Такие дела!» – написала она, тем самым завершая отрезок текста размером в тысячу слов. 

## 41 {-#41}

Узнав о нелюбви подруги к интернет-общению и социальным сетям в целом, Нора сочла её странной и старомодной, но ни капельки не удивилась. Это привело к тому, что девушка проводила вечера за чтением и написанием электронных писем. Такое занятие пришлось ей по душе и Нора даже удивилась, почему никогда прежде не развивала свои писательские навыки подобным образом. 

Как и разговоры с Агатой, её послания по-прежнему не касались личных тем и пестрили различными фактами, но Элеонора с облегчением заметила, что теперь среди них встречались и те, что не имели отношения к тафофилии.

> ***Вчерашняя церемония и вовсе лишила меня последних сил. Хоронили какого-то цирюльника. Проститься явилось человек сорок, не более. Выполнив привычный ритуал «посмотрел-положил цветочки-поплакал», народец начал расходиться, и всё бы ничего, но осталась престарелая дамочка с пугающе высоким начёсом, которая никак не желала уходить. Ты ведь знаешь, как сложно мне бодрствовать после полудня! Я могу снести ещё часок-другой, а именно столько должна длиться церемония прощанья, но эта особа опустилась на колени у изголовья гроба и продолжала реветь даже когда поздние сумерки сменились кромешной темнотой. В подобной ситуации на Ласло полагаться не стоит, сама понимаешь, а я ведь не бармен, чтобы торчать здесь до последнего клиента! Наёмные ребята (я имею в виду, могильщиков) тоже замучались ждать и ушли домой ещё до заката, предложив этой плаксе самой нести гроб. ***
> 
> ***Короче говоря, я устала ждать пока ситуация прояснится. Поднялась в свои комнаты, но поняла, что уже не смогу сомкнуть глаз. Знаешь, как это бывает, когда бодрствуешь слишком долго – второе дыхание, или вроде того. Мертвецу, видимо, придётся провести под крышей «Маятника» ещё одну ночь, дожидаясь возвращения копателей. Они наотрез отказываются выносить гроб под покровом ночи. Говорят, это дурная примета… Странно, что прежде я слышала подобную ересь только в отношении мусора.***
> 
> ***Сейчас время близится к полуночи. Я сижу на кухне, наблюдая как Ласло возится с ужином и наполняю желудок кофе, пытаясь хоть как-то побороть усталость. Сквозь стены до моих ушей продолжает доноситься плачь этой полоумной. Кажется, никакой пост-панк не способен его заглушить.***
>
>
> <p style="margin-top: 2em; margin-bottom: 2em">&ast;</p>
>
>
> ***Эта женщина наконец ушла. Её стоны сменились шумом ветра. Всё ведет к тому, что над городом вот-вот разразится гроза. В голове у меня прояснилось и появилось резкое желание рисовать. Чувствую, что ещё не скоро смогу уснуть, но руки уже тянутся к кистям, так что вскоре я вынуждена буду прервать своё письмо. Только выпью ещё чашечку чего-нибудь горячего.***
>
> ***Кстати, ты знала, что первая чашка кофе была предложена европейцам в 1626-м году в Риме? Другие источники сообщают, что кофе был привезён в Европу в 1615-м году, а чай в 1610. Так или иначе, эта информация не приближает нас к ответу на мой вопрос: как люди вообще жили до этого, а главное – зачем?»*** >  
> <div align=end>***А.***</div>

На этой философской ноте и заканчивалось письмо Агаты. Нора представила её, рисующую свои вычурные полотна под грозовым покровом, ведущую соседство с покойником. Девушка рассмеялась подобному Арт Хаусу и взялась писать ответ. 

## 42 {-#42}

Минула неполная неделя с момента отъезда Элеоноры, так что в «Маятнике» её ждали со дня на день. Жизнь текла своим трагическим чередом, не привнося сюрпризов в будничность обитателей похоронного бюро, – как мёртвых, так и живых, – чем последние оставались, в общем-то, довольны.   

По крайней мере, внешне.

После недавнего возобновления работы «Маятник» стал местом проведения шестнадцати прощальных церемоний, что было прекрасным результатом, особенно во время зимних праздников. 

– Взгляни на них, – произнесла Агата, стоя у окна своей спальни.

На улице было сыро и ветрено. Шёл снег с дождем. На крыльцо бюро ритуальных услуг высыпалась группка людей. Вздрагивая и скорбно сгорбившись, они следовали за шестью мужчинами, что несли гроб. Агата наблюдала за этой картиной, пока похоронная процессия не обогнула дом и скрылась в недоступной взору части кладбища.

– Лица словно с обложки Sopor Aeternus[^80]. Разыгрывают трагедию, которой сами же верят. Я слышала, как одна из женщин за глаза порицала свою товарку за то, что её одежды недостаточно чёрные, а скорее тёмно синие… Смешно! Как будто это имеет значение.

[^80]: Sopor Aeternus & The Ensemble of Shadows (лат. Вечный сон и англ. Ансамбль теней) – немецкий проект, единственным участником которого является Анна-Варни Кантодеа, создающий композиции в таких жанрах как дарквэйв, неофолк и готик-рок с элементами средневековой музыки.

Владислав многозначительно кивнул.

Он оторвался от ноутбука и внимательно изучил выражение лица подруги. В последние дни Агата была слишком эмоциональной. Его это беспокоило. Ласло вёл общение с немногими, – да что там, их можно было пересчитать на пальцах одной руки – но! Он всегда разбирался в поведении своих близких. Чаще всего знал, что что-то гложет людей ещё до того, как они сами это осознавали. 

Агата сделалась нервной. Два дня назад ей вдруг не угодила лампа, которая годами стояла в кабинете, а вчера он нашел владелицу «Маятника» убирающей снег с крыльца, чего за той прежде никогда не наблюдалась. Агате не было особого дела до общества, но теперь она говорила о нём подозрительно часто.

– Все эти сегодняшние тренды! Патриархальная система питается за счёт продаж косметики и бритвенных станков, заставляя всех вокруг считать волосы на ногах чем-то постыдным. Выбрасываем время и деньги, а затем слегка калечим естественное состояние своего тела – вот что мы делаем, дабы соответствовать нынешним представлениям общества.

Очки Агата сняла как только вошла в спальню и сейчас Ласло мог видеть её глаза. Тщательно скрываемое ненавистью, в них всё же сквозило отчаянье.

– А смерть, – продолжала Агата. – Ты видел, что они сделали со смертью?!

Владислав отрицательно качнул головой, хотя этого, в сущности, и не требовалось: Агата тут же продолжила свой монолог.

– Человечество только начало подавать признаки здравого мышления, отходя от Библии, и адом нас не запугать, но нет! Теперь каждому встречному-поперечному напоминают о смерти! По телевиденью реклама станков для бритья чередуется с роликом, в котором зрителя просят позвонить своим старикам, ведь кто знает, когда пробьёт их час… А затем на экране, как бы невзначай, тут же появляется их новое средство для профилактики сосудочно-сердечных заболеваний. Чёрт, да смертью теперь торгуют!

Она замолчала и потянулась за сигаретой.

– Пойду приготовлю что-нибудь на ужин, – сказала Агата и скрылась в дверном проёме.

Владислав давненько не слышал, чтобы в одном разговоре поднималось такое количество глобальных вопросов, но последняя фраза и вовсе казалась тревожным звоночком. 

Он подхватил ноутбук и последовал за подругой.

## 43 {-#43}

> *Дорогая Агата,*
>  
> *Погода разыгралась не на шутку. Снег валит не прекращая уже который день, из-за чего света нет во всей округе. По вечерам я включаю генератор, чтобы зарядить технику и ненадолго почувствовать себя белым человеком, но тепла он практически не даёт. Дом теперь напоминает морозильную камеру и мне приходится напяливать по три свитера, чтобы не превратиться в айсберг.*
>  
> *Я уже упоминала, что мой коттедж находится в некотором отдалении от города. Так вот, дорога, что ведёт к трассе, превратилась в снежный тоннель, преодолеть который не в силах даже мой внедорожник. Если бы во мне и нашлось мужество пробраться сквозь ледяные заросли и подняться к трассе, шансы достигнуть городской черты едва ли утешительные – ввиду снегопада транспорт не ходит уже которые сутки, а садиться в кабину к дальнобойщику я пока не готова.*
>
> *В первые дни заточения меня тешила мысль о том, что подобное уединение – у камина и при свечах – лучшая атмосфера для творчества. Увы! Я по-прежнему не написала ни одной достойной строчки, не считая этих писем. По большей части я разбираю старые вещи, валяюсь с собаками и читаю книги, а по вечерам смотрю что-нибудь. Ты скажешь, что это прокрастинация, но я <u>действительно</u> не могу ничего написать. То есть, я пробую всё время, но каждый раз натыкаюсь на глухую стену, чей рост прямо пропорционален моим попыткам. Кажется, чем сильнее я стараюсь, тем менее живыми становятся мои собственные персонажи. Я больше не вижу их так ясно, как видела тем вечером в поезде, когда впервые взялась за книгу. Эта проблема преследует мои писательские амбиции на протяжении всех тех лет, которые я пытаюсь творить.*
>  
> *Скажи, что ты об этом думаешь?*     
> 
> *С любовью,*
> 
> *Нора*

Элеонора отправила письмо. Она обвела печальным взглядом свою комнатку с низким скошенным потолком: весь пол был устлан скомканной бумагой, яростно отброшенной в стену – её неудавшимися попытками.

В голове мелькнула мысль: а не поджечь ли эти рукописи прямо здесь, не подбирая их с ковра? Девушка тут же прикинула, как долго до её дома будет добираться пожарная машина, в такую-то погоду, подумала о своих собаках и поднялась, чтобы разогреть ужин. Она удивилась, услышав звук, сопровождающий прибитые нового письма.

Ещё больше она удивилась, развернув входящее сообщение: приветствия были опущены, как и подпись, а само послание содержало лишь одну фразу:

> ***«Твои персонажи ругаются матом?»***

– Чё? – произнесла Нора, вскинув брови.

От кого, от кого, но от Агаты она ожидала большего красноречия. Ну, или хотя бы очередной истории о каком-нибудь покойнике. Девушка вскинула брови, с недоумением глядя на эту фразу.

Тем не менее, она взялась писать ответ.

> *Нет, мои персонажи не ругаются матом. По крайней мере на страницах романа, но почему ты спрашиваешь? Откровенно говоря, я ожидала от тебя большего красноречия, ведь это ты у нас любительница старомодных посланий. &#128522;*

Ответ не заставил себя долго ждать.

> ***Пошути так ещё раз и получишь современное послание по всем известному адресу. Если тебе от этого станет легче, можешь представить, что я крайне озабочена твоими писательскими проблемами, а потому весь вечер сижу на почте и телеграфирую тебе незамедлительно.***
>
> ***Теперь перейдем к сути. Говоришь, твои персонажи не ругаются матом? Тогда, боюсь, у них никогда не было прыщей и волос на ногах, а походы в туалет этим несчастным вообще строго-настрого запрещены. Я веду к тому, что ты пытаешься идеализировать своих героев и выбрала для этого самый идиотский способ: ты идеализируешь их в собственных глазах. Пускай страницы твоей книги и не будут усыпаны первосортными ругательствами, – не каждому из нас дано стать Буковски и ты правильно делаешь, что боишься опошлить этим свою историю – но в мыслях-то ты должна понимать, что пишешь о людях, а не о сказочных героях. О людях, которые ссорятся, ругаются матом, мастурбируют, выдергивают волоски над верхней губой и опорожняют по утрам свои желудки.***
> 
> ***Применяй это где и сколько посчитаешь нужным, но не игнорируй.***

Это послание Нора перечитала несколько раз и, каким бы смешным в своей серьёзности не казался текст, девушка пришла к выводу, что в нём и впрямь есть смысл. Сама мысль о том, что Ричард (к тому времени она уже определилась с именем главного персонажа) подтирает задницу прежде чем отправиться завтракать, смущала её и никогда прежде не приходила в голову.

> *Думаю, здесь ты права. Я воспользуюсь твоим советом, чтобы придать своим персонажам более… живой вид, что ли, но я так и не знаю, как взяться за перо с прежним энтузиазмом. Я имею в виду, как вообще отыскать нужные мысли и построить сюжет, когда в моей голове вдруг простираются бесплодные земли?*

> ***Ты спрашиваешь у меня совета потому, что я много читаю? Это не совсем логично, дорогуша. В литературе я всего лишь наблюдатель. Потребитель, если угодно. Я многое беру, но ничего не возвращаю обратно. Мои советы – лишь взгляд со стороны, подкрепленный мнениями различных авторов, чьи эссе я читала прежде. Мне и сочинение в школе никогда не удавалось написать таким, каким его хотели видеть. Не думаю, что сама я смогла бы написать хотя бы треть книги. Стиль, сюжет, тема, предыстория, завязка, кульминация, развязка, цель, вывод – слишком много рамок, в которые приходится вгонять свои мысли. Мне это не по душе.***
> 
> ***Я могу сказать, что не так в твоей книге, выступая в роли читателя. Однако, если тебя интересует сам процесс создания – это не ко мне. Ознакомься с эссе По или Уайльда, в них ты найдешь много полезного, но для начала прочти первое, что должно бросаться в глаза другим авторам при виде библиографии Стивена Кинга, а именно ‘Как писать книги’.***

## 44 {-#44} 

Возможно ли, чтобы человек сгорал от душевных терзаний, но вместе с тем был смиренней покойника? Владислав старался не сводить глаз с подруги и чем пристальнее он наблюдай за Агатой, тем сильнее убеждался в том, что буря не за горами. 

Бюро ритуальных услуг пришлось возобновить работу в день смерти Валерия, вне зависимости от того, хотели ли этого его обитатели: вопрос и не поднимался. Однако, с виду Агата была не против. По утрам она беседовала с клиентами, сидя у изголовья массивного стола красного дуба, а в полдень обычно открывала церемонию прощанья. Её движения были плавными, голос практически загробным в своем спокойствии, а лицо не выражало ровным счётом ничего. 

И всё же, такие мелочи как внезапное упоминание в разговоре давно забытых тем, или расчистка снега на крыльце, зарождали в голове Владислава подозрения, удерживая его в напряжении. 

Агата никогда не пыталась стать душей компании, постоянно витала в свих собственных готических облаках и даже не пыталась скрыть этого, но в начале второй недели января набиравшая силу рассеянность стала пугать. Стоило хозяйке «Маятника» взять в руки кисти, и она не могла сомкнуть глаз, пока картина не была завершена. Исключение составлял разве что портрет Кристи, с которым Агата не могла справиться уже который год. Ей удалось не думать о картине и вернуть себе сон, но теперь дамочка изображала иные сюжеты: радостные моменты в мрачных тонах – отрывки из прошлой жизни, которые Ласло с трудом мог вспомнить. 

В отличие от Агаты. 

Лишившаяся сна и пребывающая в океане тревог, понятных лишь ей одной, Агата писала ночами и работала днем. Подобное состояние омрачало её и без того безрадостный вид и вскоре хозяйка похоронного бюро начала напоминать собственных клиентов. Несколько раз Владислав находил её с чашкой чая в руках, бесцельно смотрящую в окно, или стену. Последнее не играло роли, ибо взгляд девушки был более чем отсутствующий. Она забывала затушить сигарету и не замечала этого, даже когда окурок обжигал хрупкие пальцы. Одним пасмурным утром Агата позабыла надеть очки, спускаясь вниз для проведения очередной церемонии, и поняла это лишь вечером, по привычке собравшись их снять. 

В сущности, Владислава можно было назвать невероятно глупым и одновременно невероятно мудрым человеком. Он долгое время изучал поведение подруги, пытаясь понять, что здесь предпринять. 

Продолжая размышлять над этим вопросом, Ласло сидел в своём стенном укрытии и наблюдал за тем, как Агата рисует чьи-то глаза на лиловом фоне. Так прошло несколько часов, когда девушка вдруг отложила кисти и сделала несколько шагов назад, желая осмотреть полученный результат. 

– Так, что же мне делать? – спокойно произнесла Агата.

Она и головы не повернула, но вопрос прозвучал так, словно все это время друг находился подле неё и они болтали без умолку. Ласло помедлил с ответом, предположив, что Агата беседует сама с собой, что было бы не впервой, но, та позвала его по имени. Причем использовала полную версию – очередной тревожный звоночек.

– Ничего, – ответил Ласло, и вышел из укрытия, слегка пристыженный внезапным разоблачением. 

– Мы должны прекратить это, Ласло. Иначе я просто сойду с ума. Так не может продолжаться, неужели ты не понимаешь, к чему всё идет?

Агата повернулась к собеседнику, и тот мог видеть, что её шея и лицо перепачканы краской. Она глубоко вздохнула и добавила:

– Снова.

– Ничего не предпринимай, – повторил Владислав. – Иначе всё разрушишь…

– Но я больше не могу жить этим днём сурка! 

– …как той весной.

Агата вздрогнула. 

Упоминание «той весны» мигом охладило её пыл. Девушка обхватила себя руками и с тоской посмотрела на Владислава.

– Ты прав, – тихо сказала она.

Ласло положил руку на плечо подруги, и та накрыла её своей ладонью. Так – подавленные и отчаянные – они простояли несколько минут, не проронив ни слова.

– Пойду, – сказала Агата.

Она открыла рот, собираясь ещё что-то добавить, но, видимо, передумала.

Владислав кивнул.

– Ты привыкнешь, – пообещал он. – Я же привык. В конце концов, это тянется не первый год.

Агата медленно покачала головой.

– Это неправильно, – вновь заметила она, обращаясь, скорее, к себе самой, после чего вышла из мастерской.

Владислав продолжил стоять в средине комнаты, разглядывая пятна краски, отпечатавшиеся на полу и стенах, эскизы и художественные инструменты – ему нравилось находиться в здешнем творческом хаосе. Ласло понимал, почему подруга стала проводить свои вечера за мольбертом: царившая в мастерской атмосфера действовала на него умиротворяющее.

Взгляд Ласло остановился на картине, над которой Агата только что трудилась. Местами краска не успела высохнуть, отчего изображение казалось слишком ярким, но Владиславу оно всё равно нравилось. С картины, полные доброты и терпения, на него смотрели изумрудные глаза.

Это были глаза Элеоноры.

## 45 {-#45}

Двумя днями позже уставшая и сонная Агата плюхнулась в любимое кресло, намереваясь провести вечер в компании музыки и бутылочки красного полусладкого. Ладно, двух бутылочек и ещё одной полной лишь на треть, оставшейся со вчерашнего вечера. 

В любом случае, наша героиня наскоро расправилась с вчерашней бутылкой и тут же переключилась на новый запас. Она нехотя взяла в руки ноутбук и принялась набирать письмо, параллельно потягивая винишко и сокрушаясь о временах славной совиной почты.

> ***Элеонора,***
>
> ***Сегодня мне, наконец, удалось поспать. Проснувшись, я вдруг поняла, что от тебя не было вестей уже несколько дней, которые пролетели для меня как одни сутки… Так или иначе, надеюсь, твои пальцы не отмерзли и не были съедены в этом снежном заточении. Не то, чтобы я осуждала подобный ход событий, просто тебе явно будет удобней писать ответ, имея как минимум по три пальца на каждой руке.***
>
> ***Ты когда-нибудь слышала о 4D стимуляторе смерти?***
>
> ***Сомневаюсь.**
>
> ***Дело в том, что я внезапно осознала, что мне наскучило будничное однообразие. В своё время я перепробовала не одну профессию и лишь в «Маятнике» почувствовала, что нахожусь на своём месте, но даже занятие любимым делом не гарантирует увлекательного существования. Я полагаю, для поддержания духа человеку всё время нужно развиваться. Именно поэтому я решила что-нибудь изменить, взяться за новый проект. Учитывая специфику моего дела, это едва ли кажется возможным, но, поверь мне, в смерти порою кроется гораздо больше, чем в самой жизни. Вернее сказать, последнюю зачастую познают через первую, что открывает передо мной множество дверей.***
>
> ***Вернемся же к предмету разговора. В Китае уже не первый год успешно работает 4D стимулятор смерти. Формально, это проект, созданный для смертельно больных и всех тех, кто хочет испытать на себе воздействие летального исхода, вернув тем самым вкус к жизни. Эта штука позиционируется как игра, позволяющая почувствовать каково это – быть кремированным и вновь родившемся в матке. Если вкратце, участников помещают в безопасный гроб, а затем в печь, где благодаря сочетанию света, горячего воздуха и умению разработчиков создаётся подлинное ощущение горения. Затем клиентам открывается реалистичная проекция матки, сопровождаемая биением сердца. Им является яркий свет, представляющий собой тоннель, по которому они должны ползти, осуществляя перерождение.***
>
> ***Нет, я не собираюсь открывать нечто подобное, хотя занятие увлекательное, ты не находишь?***
>
> ***Я всё же намерена начать обдумывать проект на смертельную тематику, пускай и не требующий подобных технологий. Ты как никто другой знаешь, как много мне известно о смерти, ведь я не только знакома со всеми её атрибутами, но и с психологической стороной вопроса. Посему я хотела бы вести семинары. Прямо здесь, в «Маятнике», я располагаю идеальной атмосферой для того, чтобы беседовать о смерти, раскрывая не только поэтические аспекты упокоения.***
>
> ***Естественно, мои ученики будут делать надписи на собственных надгробиях, писать прощальные письма, выбирать для себя погребальные одежды, воссоздавать пост-мортем фото и подбирать дизайн гроба, в котором потом должны будут пролежать несколько часов. Однако, вместе с тем я расскажу о вскрытии, разложении и прочих радостях посмертных приключений тела.***
>
> ***Вот как я это вижу.***
>
> ***Даже если откинуть первоначальную идею о том, что оное занятие призвано напомнить о радостях жизни… Глупо нести в себе столько информации и не делиться ею с другими. Хотя…***
> 
> ***С другой стороны, может мне просто расширить границы своего виноделия?***
>
> ***Возвращайся скорее.***
>
> <p align=end>***А.***</p>

## 46 {-#46}

Спустя две чашки чая и бутылку вина Агата захлопнула книгу. Она заметно взбодрилась, обнаружив, что её ждет новое письмо.

> *Дорогая Агата,* 
>
> *Не знаю, возможно ли это, но, кажется, снегопад стал ещё сильнее. Боюсь, в ближайшие дни я не смогу тебе писать. Генератор вот-вот опустеет, а использовать оставшийся в машине бензин я пока не готова, надеясь, что вскоре снежная буря утихнет и я смогу выбраться из своего ледяного дворца.*
>
> *Без света здесь жутко. Особенно по ночам. Я подхватила простуду, так что всё время лежу под тремя одеялами, слушаю завывание ветра, которое не в силах заглушить даже накрепко закрытые металлопластиковые окна. Высокая температура заставляет меня дремать практически весь день, но сон этот едва ли можно назвать здоровым: я просыпаюсь каждый час. Если не от кашля, то от холода.*
>
> *Ночами я лежу без сна. Слушаю вьюгу за окном и чувствую себя Боггартом как в этом сериале, помнишь? Буквально слышу у себя в голове голос Рэдклиффа с его шикарным британским акцентом, который все время повторяет всего два слова: CAN’T SLEEP*[^81].
>
> [^81]: Нора говорит о сцене из мини-сериала «Дневник юного доктора», основанного на одноименном романе Михаила Булгакова.
>
> *Хорошо, еды в доме хватит на месяц вперед.*
>
> *Касательно твоих внезапных лекторских порывов, предлагаю обсудить это лично, но пока лучше сосредоточься на вине.*
>
> *Ты знаешь, я прочла ту книгу Кинга. В общем-то мне понравилось,  но и в противном случае я бы не рискнула тебе говорить обратное – мало мне проблем что ли? 	
&#128522; *
>
> *Так вот, я не совсем понимаю, как именно это должно мне помочь? Первая половина книги состоит из его воспоминаний, местами довольно…своеобразных; вторая – это сборник лингвистических советов, едва ли применимых к русскому языку в принципе.*
> 
> *Объяснишь?*
> 
> *С наилучшими пожеланиями,*
>
> <p align=end>*Нора*</p>

На этот раз ответ Агаты вновь явился незамедлительно.

> ***Согласна относительно вина. Сейчас как раз занимаюсь тестированием.***
>
> ***Боггарт – это привидение из «Гарри Поттера», хотя в свете последних событий я бы не удивилась, узнав, что ты чувствуешь себя именно им, а того доктора звали Бомгард.***
> 
> ***Что касается книги, обрати внимание на первую половину. Воспоминания Кинга – прекрасный образец осознания череды событий, которая сделала его самим собой и привела к занятию литературой в принципе. Я уже говорила тебе это: перебери в голове свою жизнь, углубись в воспоминания, разложи их по полочкам и пойми, зачем вообще ты хочешь писать. И ситуация прояснится.***
>
> ***Признаюсь, меня слегка беспокоит твоя ситуация. Выздоравливай, а затем убирайся к чёрту из этой глуши. Как можно скорее.***
>
> <p align=end>***А.***</p>

Агата несколько раз удостоверилась, что сообщение доставлено, но ответа не последовало.

– Должно быть спит, – предположил Владислав, с тревогой наблюдавший за тем, как подруга ежеминутно проверяет почту.

Агата одарила его красноречивым взглядом, выражавшим посыл по тому самому хорошо известному адресу и Ласло, который буквально избегал конфликтных ситуаций, поспешно ретировался на свой этаж.

К рассвету хозяйка «Маятника» опустошила последнюю бутылку.

Ответа от Норы по-прежнему не было.

<p style="margin-top: 2em; margin-bottom: 2em">&ast;</p>

Не было его и следующим утром. 

И днем позже.

## 47 {-#47}

Моросил мелкий дождь. Небеса объединяли в себе палитру сине-серых оттенков, переходящих в насыщено лиловый, и теперь походили на огромный синяк, охватывающий город. 

Дело шло к закату, когда мальчик вышел из здания вокзала. Он вновь проспал весь день и теперь с интересом разглядывал новое место. Это уже превратилось в своего рода традицию: сойдя с автобуса или электрички, Гек отсыпался в зале ожидания, а затем проводил целые сутки, гуляя по новому городу. Подобные прогулки приносили нашему герою духовный подъём, но вместе с тем и подавленность – неотъемлемую спутницу одиночества. Гек понимал, что ведёт себя крайне расточительно, но ничего не мог с собой поделать. Куда бы он ни ступил – мальчик не чувствовал, что находится на своём месте, а потому продолжал колесить по стране. 

Одиннадцать городов спустя Гек обнаружил, что от его начальных запасов осталось чуть больше десятой части, и начал ездить зайцем. Автобусы для такого не годились, а вот электрички – вполне. К тому же это оказалось ещё веселей, не надо было думать, какой город окажется следующим: садишься в первом вагоне и просто покидаешь электричку на той станции, где входит контролер. Однажды Гек не успел выйти до начала движения, и ему даже пришлось прятаться от проверяющего на крыше электрички. 

Такое вот веселье.   

– Серьезно, – сказала Агата. – Хватит.

Гек прервал свой рассказ и вопросительно взглянул на молчаливую собеседницу.

– Я миллион раз слышала эту историю. И каждый раз всплывают новые детали, в достоверности которых я очень сомневаюсь. Дай мне нормально выпить.

– Щас девять утра.

– Вот именно. Скоро придут клиенты.

Мальчик театрально закатил глаза.

– Ну што ты начинаешь. Хотя бы дослушай до того момента, где я говорю, какого цвета были сумерки в мой первый день во Львове…

– Пепельно бледные. 

Жест с глазами повторился. Затем Гек печально вздохнул.

– Тебе просто нужна новая история, – мягко произнесла Агата.

– Та мабудь.[^82] 

[^82]: Да, наверное.

– Ну, так иди и твори её. И дай мне, наконец, спокойно выпить.

– Думаешь, мне есть про што рассказывать? – спросил мальчик, пропуская мимо ушел последнюю фразу Агаты. – Нора всегда слушает мои истории. Но только старые. Ей они правда нравяца.

– Ей понравятся и новые. Кстати, а почему ты разговариваешь с Элеонорой исключительно на украинском?

– Ну, во-первых, это красиво, – с улыбкой начал Гек.

– А во-вторых?

– А во-вторых мне нравица её реакция. Кажеца, она не всё понимает, но очень стараеца этого не показывать. 

Агата ухмыльнулась винному бокалу.

Мальчик не унимался.

– Но… Думаешь, мне ещё найдеца про што рассказать?

Теперь пришла очередь Агаты вздыхать. Она поправила очки и воспользовалась этой возможностью.

– Тебе только двенадцать.

Мальчик ничего не ответил. Он вытащил из кармана старый портсигар Валерия и принялся сосредоточенно лепить самокрутки. 

Минут десять спустя, когда Агата уже решила, что может отдохнуть от бесконечной болтовни своего юного друга, тот вновь поднял голову и нарушил долгожданную тишину.

– Двенадцать лет – это так скучно, – сказал Гек и затянулся.

## 48 {-#48}

Владелица «Маятника» стояла у входа, наблюдая за тем, как люди (один в гробу, остальные своим ходом) покидают похоронное бюро. С гостиной второго этажа доносилась спокойная музыка, и Агата пыталась понять, что же всё-таки удивляет её больше: внезапное наличие джаза в этих стенах, или то, что Владислав вдруг обнаружил своё присутствие, не дождавшись пока дом опустеет.

Она решила, что склоняется к последнему варианту и в смятении поднялась по ступеням.

Гостиная была окутана теплом, излучаемым камином, который растопили впервые в этом году. Журнальный столик оказался уставленным узкими винными бутылками: по две каждого сорта. Рядом виднелась стопка шоколадных плиток.

Агата ещё раз обвела взглядом открывшуюся картину.

– Тааак? – протянула она.

Владислав стоял спиной к входу и, склонившись над проигрывателем, тщательно перебирал пластинки. Он обернулся, и Агата увидела, что друг держит в руках аптечку. Не ту, которую можно было найти в ванной комнате – её собственную, обычно спрятанную под кроватью.

Это насторожило девушку больше всего.

Агата мало что понимала в происходящем. Она смотрела на друга, разрываясь между недоумением и желанием рассмеяться. Ласло, видимо, испытывал нечто похожее, потому что с минуту они стояли молча.

Первой заговорила Агата.

– В чём тут дело? – полуулыбаясь спросила она.

Владислав не отвечал. Склонив голову, он блуждал взглядом по комнате. Так прошла ещё минута.

– Присядь, – наконец, выдавил из себя Владислав.

Он вновь притих. Агата знала, как временами бывает сложно заставить Владислава говорить. Как-то он молчал почти две недели, а одним утром просто вошёл в гостиную и сказал, что ему нравится игравшая там песня. Со стороны Агаты прозвучал вполне логичный вопрос «Почему ты молчал все это время?», на что Ласло ответил: «Потому что только в тишине вселенная даёт ответ!»

В общем, Агата не стала спорить и послушно опустилась в кресло. Владислав вручил ей аптечку, сел рядом и открыл ноутбук.

– Тебе это не понравится, – предупредил он.

Агата вопросительно вскинула брови.

– Тут пришло письмо…

– И?

Ласло ничего не ответил. Он лишь повернул компьютер так, чтобы подруге был виден текст письма.

Письмо оказалось от Норы. Короткое, написанное впопыхах, оно заставило Агату содрогнуться даже при повторном прочтении.

> *так темно и холодно. а хуже всего пустынно*
>
> *я ничего не вижу вчера я слышала шаги но здесь никого нет и не было*
>
> *кроме как за дверью*
> 
> *точнее, в дверном проёме*
> 
> *давно*
> 
> *голоса вокруг везде они а потом снова белая тишина*
> 
> *не думаю что здесь когда нибудь вообще был дом слишком сыро*
> 
> *холодн я видела так много*
> 
> *сколько тебе лет7 снова.каждый раз*
>
> *неужели я никогда не закончу свою книгу?*

## 49 {-#49}

Над «Маятником» повисла напряженная атмосфера. Казалось, даже солнце спешило скрыться за горизонтом. Пламя в камине погасло, а свет в гостиной так никто и не включил, так что теперь комната медленно погружалась в полумрак, наполняясь серыми оттенками. 

«Рапсодия в чёрно-голубых тонах» началась сначала. Комната виделась девушке отрывком из чёрно-белой ленты, и звучание мелодии  лишь усиливало это впечатление. Агата съежилась и тряхнула головой, пытаясь отделаться от гнетущих мыслей. Она подумала о прошлом и о тускнеющих со временем фотографиях.

Но прошлое не было выцветшим. Набирая яркости, оно в этот самый момент разливалось вокруг неё красками, заставляя сердце учащенно биться.

Оправившись от потрясения, Агата написала ответ, состоящий всего из двух слов:

> <p align=center>***Где ты?***</p>

Она не раз пыталась звонить, но, по всей видимости, телефон девушки давно разрядился. 

Голова раскалывалась до такой степени, что находиться в собственном теле было некомфортно. Иных вариантов, к сожалению, не предлагалось. Агата коснулась лба рукой, посидела так какое-то время, затем сняла очки и зажгла читальную лампу. 

Владислав увидел её пропитанное болью лицо и чуть было не отшатнулся. Такая обстановка угнетала его, вызывая желание выбежать из гостиной и укрыться в другом, менее скорбном месте. 

Агата не обратила на это никакого внимания. Она машинально потянулась к бутылке. Погруженный в молчание, Ласло тем не менее подоспел вовремя, чтобы откупорить сосуд. Он извлек из кармана нож сомелье и вскоре протянул девушке наполненный вином бокал. Та взяла его, но, к удивлению своего друга, не сделала ни глотка. 

Плечи Агаты поникли. Прикрыв глаза, она сплела изящные пальцы вокруг тонкой ножки бокала и сидела в застывшем состоянии, пребывая где-то вне комнаты. 

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Решив, что подруга уснула, Владислав осторожно взял из её руки бокал. Ему и самому давно хотелось спать, так что он убедился, что вино и прочие успокоительные меры находятся вблизи от Агаты, и вскоре поднялся на свой этаж…

## 50 {-#50}

…а когда проснулся, Агаты уже не было.

Вместе с ней пропал чемодан и несколько бутылок. В холе Владислава ждала записка, оставленная тонким почерком, понять который были в состоянии лишь избранные сего мира.

> ***Ласло!***
> 
> ***Проснувшись, я обнаружила, что сижу в одном из кресел церемониального зала. Не помню, как и для чего спустилась вниз. Однажды я проснулась на краю платформы от света, что исходил от приближающегося поезда. В ту ночь мои руки тряслись так же, как и сейчас.***
> 
> ***Думаю, мне нужно как можно скорее убраться из этих стен, иначе я просто утону в пучине безумия, да ещё и тебя прихвачу с собой. Говорят, собаки уходят из дома в преддверье смерти, а мне всегда нравились пёсики, ты знаешь. Однако, я просто собираюсь привести себя в порядок.***
> 
> ***Не переживай, я отменила ближайшие заказы, так что тебе никто не должен докучать. Умрут как-нибудь в другой раз.*** 
> 
> ***Я не намерена отсутствовать долго, но ты уж присмотри там за вином. И Элеонорой, если она вдруг даст о себе знать до моего возвращения. ***
> 
> ***Я должна держать себя в руках, если хочу ей помочь.***
> 
> <p align=end>***А.***</p>

Владислав развел руками и отправился в погреб.

Плакал его кулинарный конкурс.

## 51 {-#51}

Все это возвращает нас к тому моменту, когда печальная и обеспокоенная Агата нашла себя стоящей перед полосой бесконечного леса, купающегося в первых лучах рассвета.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Последнее утро в лесу выдалось настолько пасмурным, что, открыв глаза, Агата не сразу поняла, в каком времени суток она очутилась. Дни здесь протекали плавно. Преисполненные покоя и заснеженных тропинок, они погружали нашу героиню в долгожданный покой, уводя от реальности, как это бывает подвластно вину, или хорошей книге.

Девушка приподнялась на локтях и выскользнула из постели. Будущее по-прежнему виделось ей туманным и сумрачным, но одно Агата знала наверняка: она была готова вернуться в «Маятник», и если ситуация не прояснилась, собиралась всецело погрузиться в работу. К счастью, хоть с этим проблем не возникнет: всегда кто-нибудь да умирал. 

– В виденьях темноты ночной, – Агата услышала собственный голос, – мне снились радости, что были; но грезы жизни, сон денной мне сжали сердце – и разбили.[^83]

[^83]: Цитата из стихотворения Эдгара Аллана По под названием «Сон» в переводе Валерия Брюсова.

Агата выглянула в окно, продолжая повторять четверостишье в своей голове. Отрывки когда-то прочитанных фраз периодически бессознательно выплывают из памяти, когда литература является неизменным спутником твоей жизни – это была одна из многочисленных странностей Агаты, привычек, которые раздражали только её саму 

– В виденьях темноты ночной… – прошептала девушка и скривилась, осознав, что говорит вслух. 

Из окна на неё смотрела зима. В уголках стекло взялось морозом и походило на новогоднюю раму, обрамлявшую старую открытку: снег по-прежнему покрывал лес и долину, но за ночь над ними сгустились тучи, делая пейзаж неестественным. 

Впечатление было такое, словно над домиком застыл вечер, хотя солнце встало не более часа назад. Все вокруг предвещало ливень, если не грозу. Наблюдая за погодой, Агата лишь на мгновение усомнилась в своих намереньях прогуляться по лесу. Она любила лес во время грозы, пускай и не вспоминала об этом на протяжении долгих лет.

В сознании яркими вспышками пронеслись воспоминания и в голове вроде как прояснилось. 

– В виденьях темноты… Да ну вашу ж мать!

Агата наспех натянула на себя одежду и покинула дом, опустив привычную чайную церемонию.  

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

О последнем она пожалела сразу же, стоило лишь ступить под холодное январское небо. 

Быстрым шагом Агата шла по нетронутому снегу. Тонкие прутики ветвей переплетали друг друга, образуя над ней изящную арку. Вблизи гулял ветер. Девушка ощущала его присутствие, но не чувствовала особого холода, словно замерзшие деревья могли укрыть её от мороза.  

Под ногами хрустел снег, и это вызывало в душе нашей героини настойчивое, почти детское желание обойти как можно больше пустующих полян. Ей хотелось весь день только и заниматься тем, что оставлять следы своих ботинок на блестящем белом покрытии. Чувство это возникло спонтанно и, по сути, было таким же бессмысленным, как лопанье пузырьков на оберточной бумаге, когда не совсем понимаешь, зачем это делаешь, но просто не можешь остановиться.

Так прошло около часа, а может и двух: Агата не особо задумывалась о времени. Мысли девушки занимало другое – воспоминания, которые, подобно костям домино, обрушивались на неё, приводя в движение остальные частички чётко выстроенной линии. Но это были хорошие воспоминания, так что девушка не возражала и позволила себе полностью погрузиться в мысли.

Однако, зачастую проблема воспоминаний как раз и состоит в том, что это счастливые моменты, о которых говорят только в прошедшем времени.

## 52 {-#52}

Как уже упоминалось, за минувшие годы наша траурная героиня успела позабыть, как сильно любила лес во время грозы. В детстве она неизменно заполняла плетеную корзину рисовальными принадлежностями, покрывалом, термосом (а иногда и двумя: с чаем и кофе) и целым самодельным пирогом. Последний был всего лишь покупными вафельными коржами, щедро перемазанными вареной сгущенкой, но это отнюдь не делало его менее вкусным. Весь этот походный набор Агата брала с собой, отправляясь на длительную прогулку сквозь леса, луга и рощи.

Она обожала дни напролет бродить окрестностями: природа сделалась для неё не только источником неисчерпаемого вдохновения, но и тем, что время от времени даровало девочке уйму новых приятных мест.

Находить никем не тронутые кусочки леса нравилось Агате ничуть не меньше рисования. В такие моменты, обнаружив очередной чарующий дикий уголок, девочка чувствовала себя так же прекрасно, как и по завершению картины – ощущала превосходство. Не над другими, но над самой собой.

Так вот, однажды Агата набрела на тихое лесное озеро,  расположенное на поляне, что была в самой чаще. Едва ли это место и впрямь можно было назвать нетронутым: на берегу виднелась деревянная беседка, сколоченная чьими-то заботливыми руками, хотя действие это, судя по виду сооружения, производилось несколько десятков лет назад.

В тот день она вернулась из лесу гораздо позже обычного, чем немало напугала дедушку. Сидела под навесом и смотрела, как первые капли дождя соприкасаются с гладкой поверхностью кристально чистого озера, а затем лежала, наблюдая сквозь просветы в крыше беседки за тем, как над лесом разыгрывается настоящая гроза. Подобное зрелище внушало девочке благоговейный трепет и, вместе с тем, создавало некое чувство уюта, понятного лишь ей одной. Перед могуществом природы, а также ввиду уединения, Агата чувствовала себя совсем крошечной и вовсе не была против этого. Открывшееся ей зрелище словно несло в себе первозданную тайну, более никому не доступную.

Пожалуй, на самом деле всё обстояло не совсем так. Повзрослевшая Агата не полностью позабыла вещи, которые когда-то очень любила. Она просто вспоминала о них лишь в счастливые моменты своей жизни, о которых нельзя сказать, что их было много. Мысли о лесе возродились в душе девушки в тот самый момент, когда она засыпала в сладких объятьях Адама, и Агате безумно захотелось, чтобы они оба очутились в её детском воспоминании – старой беседке, спрятанной у лесного озера.    

И вот, в последний день её пребывания в лесу, заснеженная тропинка привела Агату к тому самому месту. Не без сожаления она увидела, что озеро давно высохло и то, что когда-то было тихим водоёмом, сделалось теперь всего лишь одинокой ямой, доверху засыпанной ветками и мусором.

Озера не было, Адама тоже, да и сама она  больше не была той мечтательной девочкой и думала о себе исключительно как о владелице бюро ритуальных услуг, которая время от времени не против пригубить стаканчик-другой.

«Как метафорично», – мысленно произнесла Агата, спустившись на дно ямы.

Она с грустью взглянула на останки бывшего озера, думая о том, что некоторые воспоминания лучше не пытаться воскресить, и подняла голову, разглядывая небеса, которые к тому моменту уже начинали светлеть. Слегка раздосадованная увиденным, наша героиня посетила ещё несколько уголков, где, как она помнила, должны были серебриться другие озера. Однако, и здесь ничего хорошего её не ожидало. Вероятно, что-то произошло с почвой, потому как на привычных глазу местах теперь простирались лишь высохшие ямы.

В конце концов, тоскующая по ушедшим временам Агата повернула в обратную сторону. Спустя два с лишним часа она прошла по собственным следам в том месте, где сквозь заснеженные ветви елей проглядывалась черепичная крыша небольшого дедушкиного домика, но Агата не замедлила шаг.

Было в этих краях местечко, которое, в противовес пропавшим озерам, уж точно оставалось неизменным. В детстве и года отрочества наша героиня не единожды гуляла вдоль этого отрезка земли – крохотного кладбища, раскинувшегося на окраине леса, что за последние годы заметно расширилось.

Благодаря расположению кладбища, да ещё и потому, что с каждым годом численность жилых домов в деревушке всё сокращалось, (а это не могло не нагонять ужас на оставшихся в ней обитателей) никто здесь не прибегал к употреблению хорошо известного глагола «умирать». О покойниках в этих краях говаривали, что их унесли под сосны.

«Хорошо, хоть что-то остаётся на прежнем месте», – подумалось Агате, когда она остановилась у резного железного креста – по всей видимости, первой могилы, положившей начало лесному кладбищу.

Пора было возвращаться.

Гроза тем днём так и не показалась.

## 53 {-#53}

Дорога, примыкающая к станции, оказалась насквозь истоптана и представляла собой болотистое месиво, некогда бывшее снегом – поразительный контраст с лесными тропинками, так прекрасно характеризующий итог всего, к чему прикасаются люди.

Полоса облысевших тополей, что тянулась вдоль коричневой дороги, показалась Агате чуть ли не прекраснейшим из городских пейзажей: утонченные пики деревьев устремляли свои конечности к небу; последнее было ослепительно белым, отчего сотни ветвей, испещряющих его края, казались следами карандаша, которые кто-то оставил на листе бумаги во внезапном порыве задумчивости, как бывает при затянувшихся телефонных разговорах. 

– И одиночеством всегдашним полно всё в сердце и природе[^84], – не отдавая себе в этом особого отчета, произнесла Агата.

[^84]: Цитата из стихотворения Бориса Пастернака под названием «Осень». 

Девушка свернула за угол и её ботинок оказался в непосредственной близости с бездомным мужчиной, спящим под стенами вокзального здания. Будучи привыкшей к подобным подаркам судьбы, Агата вовремя увернулась и успела удержаться на ногах. 

Она сверилась с часами – пятнадцать тридцать восемь. В ту же минуту громкоговоритель откашлялся и объявил, что с первого пути отбывает её поезд. Очень вовремя – Агата как раз ставила ногу на его выдвижную лесенку. Она не выносила ожидание, а потому никогда не опаздывала, но всегда приходила исключительно в последний момент, секунда в секунду.

Девушка нырнула вглубь вагона и вскоре оказалась в своем купе. Внутри было холоднее, чем на улице, но её это ничуть не удивило. Здесь всегда было предлагалось только два варианта: вагоны либо отапливались как последний круг ада, либо не отапливались вообще – привычное дело для украинских поездов. 

Пальто Агата снимать не стала. Она повесила шляпу на сомнительного вида крючок и, поплотнее укутавшись в шарф, надела наушники. 

Поезд тронулся. 

Агата бросила прощальный взгляд на проплывающие мимо деревья. Над ними, кружась, парили снежинки.

– И одиночеством всегдашним полно всё в сердце и в природе.

– И шо вы хочтэ цим сказать?

Агата перевела взгляд и увидела пожилую проводницу, вероятно, явившуюся для проверки билета. Женщина была натуральной блондинкой и, хотя лоснящиеся фиолетовые пятна на переносице и в уголках глаз отлично подчеркивали бледно фиалковые глаза, она по всем показателям попадала в группу риска людей, наиболее подверженных заболеванию раком кожи – такой была первая мысль Агаты. 

Вместе с тем девушка уже в который раз отметила, как же жители глубинок любят коверкать два прекрасных языка, образуя из них раздражающее нечто, причем в каждом регионе делают это по-своему. 

«Пожалуй, проведя с месяцок в поезде, можно с легкостью написать книгу под названием «100 и 1 способ извратить язык вашего города», подумала Агата, протягивая проводнице билет, но вслух сказала:

– Несите чай.        

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

По мере её приближения к дому падавшие с небес хлопья снега становились всё реже, пока окончательно не превратились в дождь. Прислонившись к окну, Агата лениво наблюдала пейзажи, проносившиеся по ту сторону стекла. У них был цвет сухой травы и опавших листьев. 

Потому как преимущественно это и была сухая трава да опавшие листья.

Открывающаяся глазу картина напоминала те самые шотландские равнины, что на весь мир славятся своей почвой для соложеного виски.

Агата отложила книгу и прибавила звук. Она слушала Боба Дилана – в дороге все слушают Дилана, и это всегда казалось ей самой естественной вещью на свете.

Дождь обратился ливнем. 

Часом позже Агата сошла с поезда.

## 54 {-#54}

Что ж, наша героиня получила свою грозу, правда с опозданием на сутки.

Погода разыгралась над Львовом с той же беспощадностью, с которой таксист, что вёз Агату в домой, устанавливал цены на свои услуги. Однако, особого выбора здесь не предоставлялось. 

Она без устали ёрзала на заднем сиденье автомобиля, слишком тесном для ног человека, имевшего рост выше среднего. За залитым дождевой водой окном с трудом можно было различить родные улочки, что, ввиду грозы, были неестественно пустынными как для послеобеденного времени. Местами попадались одинокие трамваи, брошенные мокнуть посреди своего пути; никто не выходил из бесконечных бутиков и кофеен, а мерцающие огни витрин и вовсе исчезли – казалось, мир вокруг забылся коллективным дождливым сном.

Агата без особого интереса отметила, что за всю дорогу ей не встретился ни один пешеход. Светофоры тоже были отключены. 

Единственным светом оказалась молния. Её серебристые полосы то и дело пронзали сгустившиеся тучи, и на несколько ослепительных мгновений возвращали городу его прежний вид. 

Водитель сунул в рот сигарету и рискнул приоткрыть окно, но спустя пару секунд окатил себя содержимым ближайшей лужи. Он чертыхнулся и избавился от теперь уже мокрой никотиновой палочки. Приподняв бровь, Агата наблюдала эту занимательную картину из-под своих очков. Последние, кстати, никак не давали водителю покоя: он то и дело нервно поглядывал в зеркало дальнего вида. 

Девушку едва ли это волновало. Малознакомые люди вообще частенько удостаивали её любопытными, а то и подозрительными взглядами и причиной тому не всегда были очки.

Мужчина вновь поднял голову, так что Агата увидела пару заинтересованных глаз, неотрывно следивших за ней на протяжении нескольких секунд, что, учитывая погоду и неработающие светофоры, было весьма рискованным действием.   

Подумав об этом, Агата ухмыльнулась: она знала статистику дорожных смертей и, в отличие от своего спутника, воспользовалась ремнём безопасности. Как это чаще всего и бывало, кривая улыбка сделала своё дело. Водитель моргнул и вернул внимание трассе.

Желая избежать внезапно возникшей неловкости, он вспомнил о музыке и включил радио. Вернее, попытался это сделать, но ни одна из радиостанций не хотела толком работать. Проигрыватель болезненно извергал из себя отрывки каких-то песен, более напоминающих эффект зажеванной пленки, которые тут же поглощались белым шумом. 

Последние звуки вышли особенно угнетающими. Такие обычно сопровождают в фильмах различные паранормальные явления.   

«А может и не только в фильмах», – подумалось Агате.

Мысль показалась ей настолько уместной и нелепой одновременно, что девушка расхохоталась. Затем поняла, что не считая одноразовой ухмылки, на протяжении всей дороги молчала с каменным лицом.

Эта мысль, подкрепленная ошалелым взглядом водителя, вызвала у неё новый приступ смеха. Агата догадывалась, что тут, наверное, кроется что-то нервное, но решила, что смеяться всё же лучше, чем пускать слёзы, а потому даже не пыталась себя сдерживать.

Несчастный мужчина (а был он таким ещё с того самого момента, когда услышал о пункте назначения) ничего не сказал. Он сжал руль с такой силой, что на пальцах побледнели фаланги. 

Водитель не сразу вспомнил о том, что нужно выключить радио и какую-то часть пути хохот дамочки в чёрном сопровождался звенящим белым шумом, изредка перекрываемым раскатами грома.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Облегченно вздохнув, таксист дал газу и вскоре скрылся за пеленой дождя.

Агату окатило холодной водой, и она тут же перестала смеяться.

«Точно нервное», – решила девушка и неспешно зашагала ко входу на кладбище. Спешить было некуда: она и так насквозь промокла за считанные секунды. Сухой оставалась лишь та часть головы, что пряталась под шляпой – и то, надолго ли?

Шагая сквозь ливень, наша героиня думала о том, как же всё-таки приятно возвращаться домой. Стило лишь увидеть знакомые очертания памятников, и на душе тут же стало легче. Бюро ритуальных услуг всегда было её крепостью. Откуда бы Агата не возвращалась и какое бы дерьмо не переживала, в «Маятнике» всё было на своих местах: пластинка в граммофоне, вино в погребе, Ласло на чердаке, ну и какой-нибудь покойник в зале прощаний.

Пропитанная этими мыслями, девушка чуть ли не с любовью наблюдала за тем, как дождь поглаживал многолетние надгробия. Вскоре из темноты выросли очертания похоронного дома. За спиной полыхнула молния и Агате показалось, что она видит чье-то бледное лицо в окне собственной спальни, но, моргнув, поняла, что за стеклом темно и пусто.

Молния ударила с новой силой. Последующих восьми секунд девушке хватило, дабы подняться по непростительно скользким ступеням. Она отворила дверь, и в тот самый момент над кладбищем разнесся оглушительный раскат грома.

Такое вот эффектное появление.

## 55 {-#55}

Ещё одна вспышка небесного света мелькнула прежде, чем девушка закрыла за собой дверь, и она успела увидеть пустующий холл. Светильники не работали. Вероятно, где-то замкнуло электричество, благодаря чему освещения лишился не один квартал.

Как выяснилось позже, в «Маятнике» её ждали все, включая Нору, вернувшуюся накануне, и парочку новых клиентов, ныне покойных. С последними Агата решила разобраться утром, полагая, что им уже всё равно.

Звук закрывающейся двери отдался эхом. Прислушавшись, Агата уловила резкое движение: кто-то (кто бы это мог быть?) пронесся сначала в одну, затем в другую сторону. Внутри оказалось слишком темно, дабы хорошо различать силуэты вокруг, но девушка не сомневалась в источнике шума – такой глухой звук издавали лишь половицы стенных тоннелей. 

Значит, Владислав был дома.

Первым делом она поднялась на третий этаж. Агата облегченно вздохнула при виде дюжины свечей, мягким светом озаряющих её собственную спальню. Сейчас ей меньше всего хотелось блуждать в потёмках.

Стена колыхнулась, и в комнату вошел Ласло. Он одарил подругу изучающим взглядом.

– Ну и видок у тебя, – заключил таксидермист, наблюдая за тем, как дождевая вода стремительно стекает с краев фетровой шляпки. – Прямиком из Трансильвании?

Агата не удостоила этот вопрос ответом. Вместо того девушка поспешно скинула с себя верхнюю одежду и упала на кровать.

Следующие реплики друзья произнесли одновременно.

– Света нет с самого утра…

– Вода хоть есть?

Они переглянулись.

– Да, – ответил Владислав, и, заметив, что девушка поглядывает в сторону ванной комнаты, вовремя добавил: – Холодная.

– Чёрт бы их побрал!

– Почему? Тебе разве не хватило?

Ласло ткнул пальцем в направлении окна.

– Попридержал бы ты эти шуточки для своих кулинарных конкурсов, – посоветовала Агата. – Если планируешь добраться туда живым.

Она стянула с лица очки и бережно поместила их на прикроватный столик.

– Я слишком устала.

– Очень жаль, – с каменным лицом заметил Ласло.

Владелица похоронного бюро подозрительно взглянула на друга, однако выражение его лица оставалось непроницаемым. 

– Это ещё почему? – не выдержала Агата.

Её собеседник улыбнулся.

– Нора вернулась.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Сонливость как рукой сняло. 

Наша героиня подскочила. Она тут же возвратила очки на привычное место, и сделала несколько шагов к выходу, но вдруг остановилась и взглянула на Владислава, который в свою очередь заинтересованно наблюдал за ней.

– Твою мать, – выдохнула Агата. – И как она выглядит?

Ласло – социофоб, гурман, таксидермист, косметолог для мертвецов и вообще веселый парень – сделал драматическую паузу, прежде чем ответить.

– Среднего роста, брюнетка, полноватая, на вид слегка за двадцать…

Агата несколько устала, к тому же, переволновалась, так что не сразу поняла, что происходит. 

– … глаза зелёные…

Когда до неё наконец дошёл смысл слов Владислава, девушка вяло подняла ладонь в останавливающем жесте.

– Знаешь, меня вот раньше напрягало твоё молчание, но я как-то передумала.

– Ой, да ну расслабься ты, – улыбнулся Ласло. – Она в порядке. Разве что немного простывшая.

– Как и я.  

## 56 {-#56}

В то время как Агата наблюдала за небом-матрицей сквозь разрушенную временем крышу лесной беседки, другая девушка теснилась в узком проходе поезда, готовясь сойти на следующей станции. 

Если верить расписанию, (а оно в последнее время было подозрительно правдивым)  висевшему на ободранной двери туалета, куда сквозь тонны грязи – ей хотелось думать, что это только грязь, но обоняние рисовало чуть менее утешительную картину – и изодранные клочья сероватой бумаги, уже был проложен путь самыми отважными пассажирами… 

Так вот, если верить расписанию, до Львова оставалось неполных десять минут. Элеонора провела на этом самом месте последний час. Нос девушки вёл себя странно: он уже который день был заложен, но всё же предательски различал самые отвратительные запахи. В купе с Норой ехал поношенного вида мужик, чей образ можно было описать всего одной фразой – дед в трусах, а также две тучные женщины с ребёнком, и если первый пациент всего лишь излучал всевозможные запахи немытого тела, (особого внимания, конечно, заслуживали ступни) то бабоньки оказались более оригинальными в выборе средств массового истребления. 

Во-первых, они всё время что-то ели. Жадно накинулись на еду ещё до того, как поезд впервые тронулся с места. Запасы провизии представляли собой разнообразие всех возможных салатов, содержащих немалую долю лука, а также целую связку домашней колбасы, и, казалось, были неиссякаемыми. Они мгновенно заполнили своими тошнотворными запахами и без того затхлое пространство, вмещающее к тому же пятерых человек.

Во-вторых, проблема была в ребенке. Будучи ещё дошкольником, он постоянно орал. Орал и ревел. Зачастую из-за того, что хотел есть, но, как и Нора, не выносил лука, так что основная часть пути могла бы стать отличным пособием для взращивания будущих чайлдфри,[^85] но! К сожалению, это было лишь полбеды. Главный сюрприз поездки открылся девушке чуть позже, когда ребёнок захотел в туалет.   

[^85]: Чайлдфри (с англ. child – ребёнок, free – свободный) – общее название для людей, осознанно не желающих иметь детей.

Мамаши, слишком заботливые, дабы позволить ему воспользоваться общественным толчком и, вероятно, слишком тупые, чтобы подумать об окружающих, имели при себе пластиковый горшок, больше походивший на больничную утку. Так или иначе, за те восемнадцать часов, что наша героиня провела в поезде, горшок наполнялся не один раз, (и не только жидкостью) но каждый раз, вместе с содержимым, убирался под стол, припасенный, видимо, до лучших времен.

Смешение вышеупомянутых запахов сводило Элеонору с ума. Она, вроде как, не была знакома с трупным зловонием, но всегда представляла себе его именно так. Под конец поездки девушку буквально начало мутить, и виной тому вряд ли были одни лишь красноречивые ассоциации. 

Никогда ещё Нора не жалела о своей вежливости так сильно, как тем злополучным днем. Она скучала по своему внедорожнику, что остался в холодном, заснеженном гараже её загородного домика.

Короче говоря, к утру находиться в купе вместе с тем, чтобы никого не убить, девушке просто не представлялось возможным. Единственным более-менее продуваемым местом оказался хвост вагона. Туда наша героиня и устремилась, прихватит чемоданы. 

За стеклом с завидной регулярностью мелькали придорожные столбы. Они упрямо не желали сменяться городским пейзажем. Элеонора смотрела в окно слишком долго, к тому же, не ела почти сутки, так что вскоре почувствовала опасное головокружение. Перспектива потерять сознание рядом с кучкой дерьма казалась ей не самой удачной, и Нора перевела взгляд.

Ей на глаза попалась перевернутая мусорная корзина, из середины которой на девушку грустно взирала одинокая прокладка.

«Представь, если бы мужчины испытывали к насилию такое же отвращение, какое испытывают к месячным…» – подумалось Норе.

Она не могла вспомнить, где слышала эту фразу. Возможно, в «Кэрри»?[^86] Хотя, читала она её слишком давно, чтобы сыпать цитатами, да и роман, кажется, освещал совсем другие проблемы.

[^86]: Первая опубликованная книга Стивена Кинга, в начале которой главная героиня с ужасом переживает появление первых критических дней.

Поезд тряхнуло. 

От резкого толчка девушку повело влево, но она успела устоять на ногах, схватившись за ручку туалета, чего бы никогда не сделала без крайней на то необходимости. 

За её спиной поочередно начали распахиваться дверцы купе. В коридор высыпали люди.

– Ну, слава тебе, господи! – произнесла Элеонора.

Она первой сошла с поезда.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Первые несколько минут, шагая прочь от здания вокзала, девушка была настолько счастлива очутиться на свежем воздухе, что даже не замечала, как с неба просеивался легкий дождик.

Однако, вскоре  капли принялись всё более настойчиво опускаться на её плечи, а несколько мокрых прядей волос тут же прилипло ко лбу. Дождь усилился, и игнорировать его сделалось не так-то просто. 

Пестрящие огни витрин игриво отражались на довольном, пускай и подмерзшем, лице девушки, когда та шагала в направлении трамвайной остановки. Единички ходили каждые пять минут.

Ещё немного, и она будет дома.  

## 57 {-#57}

Впервые за долгое время удача повернулась к Норе лицом, а не тем самым не требующим уточнения местом. Измученная, но счастливая, девушка вошла в похоронное бюро, двери которого оказались открытыми для всех желающих. Она успела подняться на свой этаж, выпила растворимый кофе и только, выйдя из горячего получасового душа, заметила разыгравшуюся за окнами грозу.

Свет предупреждающе мигнул. 

Нора усвоила предыдущий урок. Она зарядила телефон, планшет и три съемных аккумулятора до того, как в «Маятнике» исчезло электричество, после чего зарылась в сладко пахнущие одеяла, намереваясь немного почитать, но тут же отключилась и проспала целых четырнадцать часов.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Проснувшись, Нора почувствовала себя лучше и хуже одновременно. Такое частенько бывает с людьми, ещё не полностью оправившимися от болезни. 

За окнами царила темнота, как и в самом «Маятнике». Девушка зажгла свечи и прислушалась, стараясь уловить признаки чьего-либо присутствия. 

Их не было.

Войдя в похоронное бюро, наша героиня ничуть не удивилась, обнаружив, что дом объят тишиной. Агата в это время спала, а Владислав – если тот и был на месте – ни за что бы не обнаружил своего присутствия.

Теперь же над кладбищем стояла ночь и Элеонора ожидала найти подругу бодрствующей и с бокальчиком в руке. Той не оказалось ни в одной из гостиных комнат. Не было Агаты и в собственной спальне, и в кабинете, и даже в винном погребе. Войдя в кабинет Мирославского, Нора обнаружила какого-то обнаженного мужчину, спавшего посреди… стола? 

Ввиду плохого освещения, наша героиня не сразу поняла, что именно видит перед собой, а, разобравшись с положением вещей, решила, что на сегодня с поисками достаточно.

Она вернулась на свой этаж и позвонила Агате. Телефон той был вне зоне досягаемости.

Скорее разочарованная, чем напуганная, Нора вновь забралась в постель. Она включила очередную серию «Декстера», – благо 3G работал безотказно – и, лишь увидев заставку, поняла, как голодна. 


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Ближе к утру Нора осознала, что не одна в здании – кухня излучала умопомрачительные ароматы готовки – её это успокоило. Путем несложных умозаключений, девушка решила, что у плиты возится Владислав: она ни разу не заставала Агата за приготовлением ужина, да и подобная картина виделась ей нереалистической и чуть ли не гротескной, противоречащей всем законам физики и устройству современного мира в целом.

Темнота похоронного бюро девушку не пугала, – его владелица частенько приглушала свет – чего нельзя было сказать о тишине. Ниоткуда не доносилась музыка, и застывшее в воздухе молчание удручало даже больше, чем покойник, прикорнувший этажом ниже.

Наша героиня вытянулась на диване, (эту ночь она провела в своей гостиной) пытая понять, чего ей хочется больше: спать, или же есть. Она провела языком по обветренным губам и решила, что, во-первых, пить. Девушка берегла оставшееся в технике электричество, так что не стала пользоваться телефонным фонарем. Накануне она нашла в своем шкафу парочку газовых ламп, чему ничуть не удивилась, учитывая место действия, и теперь пробиралась к выходу из комнаты.

По мере её продвижения по коридору, мягкий свет лампы плавно выхватывал из темноты картины: всё те же портреты писателей, чередующиеся с кладбищенскими натюрмортами.

Тьма поглотила всё вокруг. В ней виднелась лишь горящая старинная лампа и очертания руки, что её держала. Это походило на интерфейс какой-нибудь мрачной бродилки.

Коридор перешёл в крохотный холл, укрывающий лестницу. Нора помедлила. Она знала, что в другом конце находятся ещё спальни. Те были заперты и, по всей видимости, пустовали. Девушка уже не впервые столкнулась с желанием проникнуть в них и осмотреться как следует. Прежде она отметала эту мысль, зная, что Агата непременно рассердится, застав её за этим делом. Она не понимала, откуда в ней такая уверенность, ведь это всего лишь комнаты… Просто знала.

Но сейчас Агаты не было в «Маятнике», а Владислав был полностью поглощен готовкой. Стоя у основания лестницы, девушка слышала слабые отголоски его веселого пения.

Нора глубоко вдохнула и сделала несколько неуверенных шагов. Вскоре перед нашей героиней оказалась массивная дверь черного дуба, мало чем отличавшаяся от той, что вела в её собственные спальни. Дверь была покрыта толстым слоем пыли, завидев который Нора инстинктивно зажала рот, опасаясь чихнуть и тем самым привлечь внимание Владислава. Затем она вспомнила, что за окном совсем не май месяц и с облегчением опустила руку. 

Единственным чистым местом оказалась дверная ручка.

«Кто-то открывал её не так уж давно», – подумала девушка и, поддавшись порыву любопытства, повернула дверную ручку.

Та скрипнула, но не поддалась. 

«Заперто! А чего ещё можно было ожидать?»

Девушка собиралась предпринять новую попытку, но её рука замерла в паре сантиметров от ручки. Нора инстинктивно попятилась назад, не совсем понимая, что именно её остановило. Лишь достигнув лестницы, девушка осознала это.

Доносившееся из кухни пение смолкло.

## 58 {-#58}

За свои неполных двадцать семь лет Владиславу пришлось от кое-чего отказаться. В основном из-за социофобии. Юноша ненавидел свою болезнь, но вместе с тем лелеял её как собственного ребенка. Он лишился вещей, которые веками радовали человечество, и перспектив, что были способны воодушевить кого угодно, но только не его самого. Для них Ласло оставлял в душе крохотный просвет. Он допускал вероятность того, что общение, а, быть может, даже влюбленность обладали способностью изменить его жизнь в лучшую сторону, – временами парень сокрушался о своем одиночестве и яростно желал от него избавиться – но зачастую старался не предавать этому особого внимания.

Коль на свете и были вещи, способные принести ему истинное, а главное мирное счастье, думал Владислав, так это самые банальные: музыка, хорошие драмы и, конечно же, кулинария. 

Впервые Владислав окунулся во вкусовые эксперименты более двадцати лет назад. Дело было поздней осенью. Тогда его семья жила в одном из этих жутких обшарпанных домов по ту сторону кладбища, которые, к тому же, ещё и плохо отапливались. Ближе к вечеру Влад сидел на кухне. На нем был спортивный костюм и две пары вязаных носков, но мальчик то и дело жался к батарее.

– Довго ще будеш знущатися над цією зупкую?[^87] – с улыбкой спросила девочка-подросток, которая уже допивала свой чай. 

[^87]:  Долго ещё будешь издеваться над этим супом?

Это была его старшая сестра. Красивая и спокойная, сколько Владик её помнил.

Мальчик искоса посмотрел на стол, где его ждала тарелка начавшего остывать супа. Он вроде как был голоден, но не выносил гороховый суп. Его вкус казался Владу каким-то… простоватым. 

Наш герой прошелся по поверхности стола взглядом, пытаясь отыскать что-нибудь съестное взамен противному супу. На глаза попалась лишь вазочка с красной смородиной. Её Влад тоже не то чтобы жаловал.  

Только прошлым утром мальчик слышал по телевизору о том, что минус на минус даёт плюс. Тогда это показалось ему логичным. Даже слишком логичным, чтобы рассказывать об этом из ящика. Естественно, что две прямые чёрточки, если их правильно совместить, образуют знак + с той же лёгкостью, с какой могут превратиться в знак равенства.

Влад перевёл взгляд на гороховый суп. Затем посмотрел на смородину. И снова на суп. Теперь мысль о минусах вдруг открылась ему в новом ключе.

– Сестра, – позвал он невероятно серьёзным голосом, а потом задумчиво потер подбородок, словно желая укрепить эту свою серьёзность. 

Девочка с интересом взглянула на брата. Большую часть времени тот говорил на русском. Её это совсем не удивляло. Влад не общался со сверстниками, да и вообще мало с кем общался без особой необходимости. Зато он частенько смотрел телевизор, откуда и перенимал манеру общения: дело было в девяностых и большинство фильмов по-прежнему транслировались на русском языке.

– Сестра, что будет, если бросить в суп ежевику? 

– Спробуй![^88] – весело ответила девочка, стараясь подавить смешок.

[^88]:  Попробуй!

Влад этого не заметил. С напыщенно серьёзным видом, что так плохо сочетался с фиолетовыми носочками, он взял у сестры чайную ложку и принялся кропотливо отсыпать ягоды в тарелку с супом. Мальчик оценивающе посмотрел на содержимое тарелки, решил, что ежевики уже достаточно, и попробовал ложечку. К его величайшему разочарованию, вкус супа совсем не изменился.

Поразмыслив над проблемой, Влад решил, что целиком брошенные в суп ягоды никак не повлияют на вкус – нужен их сок. Обрадовавшись новой идее, он принялся беспощадно давить ягоды, выбрал из тарелки кожуру и только тогда отважился вновь попробовать суп.

Увы, вышло не очень.

## 59 {-#59}

Во время отсутствия Агаты, Владиславу пришлось несладко. Первые дни ничего не предвещало беды, но под конец недели в бюро доставили не одного, а целых двух покойников. Вернее сказать, целым был лишь один из них, второй же оказался обезглавленной жертвой ДТП. 

Так или иначе, над обеими ребятками нужно было потрудиться и, будучи слишком нелюдимым, дабы отказать клиентам, Владислав принялся за работу. Он был свидетелем сотен церемоний прощанья, но с ужасом представлял, как будет проводить одну из них. Ласло не хотел тревожить подругу, (в конце концов, он уже не маленький) так что, работая над трупами, морально готовил себя к грядущему контакту с людьми, в тайне уповая на то, что сама Агата, всё же, вернется к назначенному сроку.

Он услышал, как Нора вошла в «Маятник» ещё до того, как девушка успела подняться в свои комнаты. У неё, конечно, был ключ, но, как бы ни был осторожен входящий, громоздкая дверь всегда давала о себе знать.

Элеонора застала Владислава как раз в разгар работы, и бедолаге не оставалось ничего, кроме как ретироваться на чердак в ожидании лучших времен. Девушка весь вечер кашляла. Услышав эти хриплые звуки, наш герой для начала надел медицинскую маску, (в отношении болезни, да и не только её, он был слегка параноиком) а уж потом вспомнил о просьбе Агаты присмотреть за Норой. Дождавшись, пока та уснет, Владислав решил приготовить ей куриный бульон, но, как это частенько с ним бывало, полностью погрузился в любимое дело и осознал это слишком поздно, чтобы останавливаться – он уже поливал пряным соусом золотистую телячью вырезку.

Ласло редко ужинал за кухонным столом. Это место представлялось ему лишь рабочей территорией, как и его прозекторский столик двумя этажами ниже. В лучших кулинарных традициях юноша сервировал свой посеребренный поднос, помещал туда новые изысканные блюда, (их никогда не бывало меньше трёх) не забывая при этом о стаканчиках с дижестивом и аперитивом. Завершив работу, Ласло накрывал поднос и нёс эту красоту на чердак. 

Находиться там ему нравилось больше всего. На чердаке было уютно. Лучше, чем на кухне и в любой их гостиных комнат. Владислав не мог этого знать, но во многом его обитель походила на старую спальню Элеоноры. 

У основания скошенной стены висел список фильмов и сериалов – по сути, его планы на вечер. В похоронном бюро Нора была далеко не единственной, кто умел экономить электричество. Владислав опустил поднос подле ноутбука и с любовью посмотрел на список. Сегодня он планировал взяться за «Красоту по-американски».

– Скоро вернусь, – пообещал он комнате.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Несмотря на то, что готовка уже с четверть часа как завершилась, кухня продолжала излучать пленительные ароматы, что бесстыдно рассеивались по всему дому, и Ласло бы не удивился, приведи они Нору наверх: насколько он мог судить, девушка не ела с самого приезда.

Сервируя стол для Элеоноры, Ласло напевал старую хипповую песенку, названия которой никак не мог вспомнить. Что-то про разнобой… или разные барабаны[^89], чёрт его знает. Тем не менее, наш герой всё время прислушивался и был готов в любую минуту покинуть зону риска. 

[^89]:  Имеется в виду песня «Different Drum» в исполнении The Stone Poneys. 

Владислав налил себе чаю, когда, наконец, услышал какие-то скрипы. Однако, никто не спешил подниматься на кухню.

– Если кто-то хочет есть, – мелодично пропел Ласло, – то может подняться на кухню через тридцать секунд.

В «Маятнике» вновь повисла тишина.

Желая удостовериться, что его услышали, Владислав повторил сказанное ещё разок. На лестнице раздались шаги. 

Довольный собой, наш герой задул свечи и мгновенно исчез в стенах, прихватив с собой чай.

Куда же без него.

## 60 {-#60}

Раскаты грома начинали понемногу стихать. Вскоре они и вовсе исчезнут, но лишь для того, чтобы, собравшись с новыми силами, разразиться наступившим днём. Насладившаяся ну очень ранним завтраком Элеонора развалилась за столом, лениво потягивая одну из медовых настоек Агаты. Она написала шеф-повару благодарственную записку, в конце которой спрашивала, куда же, ч`рт возьми, подевалась хозяйка бюро ритуальных услуг.  

Норе хотелось ещё немного побыть в тепле кухни. Здешние запахи нагоняли на девушку сонливость, против чего она ничуть не выступала. Нора сама не заметила, как уронила голову, прикрыла глаза…

<em>

(Сменяясь одна за другой, грезы проносились вихрем в её уставшем разуме. Они пестрили яркими клочками воспоминаний, большинство из которых наша героиня уже не помнила в момент пробуждения. Многие из них во сне казались совершенно реальными, остальные же играли роль того, что могло бы быть, и это совсем не казалось ей странным. 

Нора видела Агату, покупавшую медовуху в крохотной лавке, чьи размеры едва ли превосходили масштаб ванной комнаты. За всё время подруги ни разу не выбирались в город вдвоем, но сцена с настойкой повторилась, только теперь бутылка в руках хозяйки «Маятника» сменилась на вишневку. Это не было странным: Нора давно собиралась предложить Агате прогуляться по Львову.

В другой раз они шли по пустынному спуску. Воздух веял зимой, но снега и в помине не было. Плитку под ногами сплошь и рядом укрывал толстый слой льда. Запрокинув голову, Агата звонко смеялась и беззаботно скользила вниз с такой беспечностью, словно вместо ботинок на ней была пара коньков. Добравшись до самого низа, дамочка в чёрном схватилась рукой за фонарь и, повернувшись вокруг него, остановилась в ожидании подруги. Нора зачем-то надела каблуки, а потому продвигалась довольно медленно.

– Кто бросил здесь этот чертов окурок?! – кричала Агата, но на самом деле она заливалась смехом. 

– Это всё Павел Владимирович! – ответил приглушенный голос, звучащий где-то в стенах.

– На нем следы помады, – уже более спокойно произнесла Агата.

– Я не… – начала Нора.

Агата тут же отмахнулась от её объяснений, давая понять, что и не подозревает подругу.

Нора захихикала, не в силах больше скрывать улыбку.

Агата вынула остатки сигареты их гроба с покойным – с точностью Нора сказать не могла, но, кажется, Павел Владимирович при жизни был противником курения – и окинула взглядом церемониальную комнату.

– Начинаем через десять минут и чтобы больше никаких окурков!

Она слегка коснулась костяшками внутренней стены.

</em>

– Ты слышал, Ласло? 

*Был здесь и незнакомец, которого Элеонора встретила на кладбище незадолго до своего отъезда. Только во сне мужчина не был незнакомцем. Он откинулся на спинку кровати, перебирая гитарные струны, и…)*

…а распахнув их, увидела, что лампа уже погасла, а часть кухни, как это ни странно, заливал бледный серый свет, исходивший откуда-то из холла. Девушка осторожно поднялась и на не до конца очнувшихся ото сна ногах вышла на лестничную площадку. Тут призрачного света оказалось гораздо больше.

Элеонора повернула голову и выглянула в окно, чтобы лицом к лицу встретиться с виновником торжества: обрамленное венком из множества сухих ветвей над кладбищем поднималось холодное зимнее солнце.

## 61 {-#61}

Во время грозы темнело бессовестно рано, даже можно сказать: не светлело и вовсе. К пяти часам за окнами похоронного бюро вовсю простиралась послеобеденная ночь.

Норе что-то вновь нездоровилось. Сунув градусник подмышку, она пододвинулась к газовой лампе и, согнувшись в три погибели (а иначе она мало что могла увидеть) принялась приводить в порядок ногти. 

Боковым зрением девушка вдруг уловила яркую вспышку света. Она повернула голову и удивленно вглядывалась в темноту, когда из неё послышался подозрительный треск. Затем вспышка повторилась и всего на пару мгновений Нора увидела, что свет исходит от винтажного торшера – вероятно, единственной лампы, которую забыли выключить.

Дверь в гостиную отворилась без какого-либо предупреждения. Элеонора не успела толком предположить, кто за ней скрывается: обитатели похоронного бюро имели общую, временами пугающую привычку – передвигаться, не создавая при этом никакого шума.

У входа появилась Агата. Хозяйка «Маятника» держала в руках горящую свечу, и, раздвоившись, крохотные огоньки плясали, отражаясь в её очках. Агата переступила порог, направляясь к подруге, и та успела заметить, что лицо вошедшей – вернее, та его часть, которую не скрывали очки – было перепачкано кровавыми подтеками. 

Торшер вновь издал этот странный треск и зажегся в полную силу. Электричество вернулось и Нора, чьи глаза уже отвыкли от яркого искусственного освещения, почувствовала резкий укол головной боли. Она зажмурилась. 

Это возымело действие и боль в висках начала утихать. Спустя секунд шесть девушка осторожно открыла сначала один глаз, потом второй. Она удивленно выдохнула: Агаты не было на месте. Нора вспомнила о термометре. Тот показывал тридцать девять и два.

– Неужели померещилось? – прошептала девушка.

– Температуришь? 

Нора хрипло крикнула и обернулась. Агата оказалась на своем излюбленном месте. Одному богу известно, как девушка так быстро пересекла комнату, но теперь она восседала в кожаном кресле так, словно никогда и не вставала.

– Ты меня напугала, – призналась Нора.

Агата хотела извиниться, спросить, как у подруги дела и сказать, что безумно рада её возвращению, но вместо этого она произнесла всего три слова.

– Ты меня тоже.

Элеонора недоверчиво взглянула на собеседницу. При должном освещении полосы на её лице оказались всего лишь потревоженной дождем косметикой.

Правда была в том, что Агата не могла думать ни о чём другом кроме как…

– Письмо, – выпалила она.

Прозвучало это немного резче, чем того хотелось Агате, но теперь это едва ли её волновало.

– Письмо? – удивленно повторила Нора.

Агата кивнула.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Ей понадобилось какое-то время и собственный ноутбук, дабы прояснить ситуацию: в телефоне Элеоноры, как и в её планшете и, вероятно, любом другом устройстве, которым девушка могла бы воспользоваться для входа в почту, не было и намёка на злосчастное послание. 

– Наверное, чья-то шутка, – сказала Нора. Ей не нравилось выражение лица Агаты: никакие очки не могли скрыть тревоги. – Ящики частенько взламывают, особенно если ты пользуешься бесплатным доменом. А я пользуюсь. Обычно электронки ломают для банальной рассылки спама. Гек говорил, что его отец работал в отделе по борьбе с подобными взломами. Правда его быстро попросили – чувак отказывался блокировать религиозные рассылки.

Она вновь просмотрела текст письма.

> *так темно и холодно. а хуже всего пустынно*
>
> *я ничего не вижу вчера я слышала шаги но здесь никого нет и не было*
>
> *кроме как за дверью*
>
> *точнее, в дверном проёме*
>
> *давно*
> 
> *голоса вокруг везде они а потом снова белая тишина*
>
> *не думаю что здесь когда нибудь вообще был дом слишком сыро*
>
> *холодн я видела так много*
>
> *сколько тебе лет7 снова.каждый раз*
>
> *неужели я никогда не закончу свою книгу?*

– Звучит стрёмненько, – прокомментировала Нора, – хотя, вместе с тем смешно. Как будто читаешь дневник героинового наркомана, или смотришь одно из этих псевдопсиходелических видео.

За всё время Агата не проронила ни слова.

– Я понимаю твою тревогу, но это всего лишь чья-то глупая шутка, – заверила её Нора. – Я, конечно, приболела, но не бредила… Вот прямо чтоб настолько. И потом, у меня быстро закончились запасы электроэнергии. Не волнуйся, *бро*.

Последнее слово вырвалось у неё непроизвольно. Нора рассмеялась, но вовремя замолчала, увидев выражение лица собеседницы. Девушка в третий раз перечитала письмо.

– По всей видимости, они не поленились прочесть нашу переписку, потому что здесь есть о темноте и…

– Твоей книге, я вижу.

Нора улыбнулась, но губы владелицы похоронного бюро по-прежнему были плотно сжаты. 

– Хотела бы я знать, кто это написал, – произнесла Агата.

– Почему тебя это настолько беспокоит?

Дама в чёрном вздохнула и осмотрелась в поисках винишка. Бутылки нигде не было.

– Не нравится мне это, – только и нашлась Агата, не будучи уверена, идет ли речь о вине, или же том странном письме.

В итоге, она решила, что сгодятся оба варианта.   

## 62 {-#62}

Существует более ста способов того, как можно преподнести смерть. Вот самые популярные из них:

Перерождение, которое подвластно человеку лишь при условии, что на протяжении предыдущих жизней он накопил достаточно хороших эмоций, которые позволяют душе осуществлять любые внезапно возникшие желания, однако, в этом мире свершено отсутствует разнообразие, дающее возможность для развития, и когда вышеупомянутые положительные эмоции иссекают, душа возвращается в низшие миры, дабы вновь переродиться; 

Отделение души от тела, с дальнейшей навигацией на небеса, что отражают теологическую и метафизическую концепцию христианского царства, в котором бесполые ангелы имеют чины и в компании святых наслаждаются присутствием Бога, созерцая его деяния;

Остатки античности говорят нам о месте на краю земли, с прекрасным климатом и избытком сладких фруктов, где чистая душа, освобожденная от материи, а заодно и земных оков, находит долгожданный отдых;

Ацтеки так вообще придумали три рая, – ну, чтоб наверняка – в них уровень полученного комфорта, грубо говоря, соответствовал уровню просветления, до которого та, или иная личность успела прокачаться прежде, чем умерла;

Исходя из нордических традиций, жизнь после смерти не сильно-то и менялась: воины сражались дни напролет, а ночами только и делали, что пировали, так что не исключено, что многие из обитателей Валгаллы вообще не были в курсе того, что на днях умерли;

Если верить индейским племенам, окочурившись, ты будешь жить там, где заходит солнце и происходит удачная охота, что бы это ни значило;

Эскимосы вот временами видят образы своих усопших в лучах северного сияния, играющих с головой кита;

Есть ещё всевозможные вариации перехода в новый улучшенный мир, для которого наш является лишь прообразом.

Как ни странно, трактовок Ада ещё больше, но мы вернемся к реалистичной точке зрения – банальному увяданию, где смерть начинается в тот самый момент, когда мозг прекращает получать кислород, отчего жизненно важные органы просто не могут выполнять свои функции, проходит аутолиз, достигает анаэробного бактериального гидролиза и всё заканчивается трапезой братьев наших меньших.

Такого мнения и придерживалась Агата Рахманинова, составляя план своих лекций. Нора как раз предложила подруге уделять опарышам поменьше внимания, когда в кабинет просочился Гек. 

Он окинул взглядом владелицу «Маятника».

– Щось ти занадто бліда, жінко, та й наче схудла[^90], – заключил мальчик.

[^90]: Что-то ты слишком бледная, женщина, и вроде бы схуднула.

Переведя взгляд на Нору, он приподнял воображаемую шляпу, после чего быстренько пересек комнату и, (хотя в его распоряжении было ещё как минимум два обитых бархатом стула) умостился прямиком на стол.

Дама в чёрном ничего не ответила, а вот Элеонора мысленно согласилась с утверждением незваного гостя. Последние двадцать минут девушка искоса поглядывала на Агату, пытаясь отделаться от мысли, что та сейчас вот-вот утонет в своем громоздком кресле.

Мальчик принялся энергично мотать ногами, то ли выражая нетерпение, то ли отдавая дань Йену Кёртису[^91]. Агате, кажется, совершенно не мешало происходящее. Левую руку она изредка отнимала от ножки бокала, чтобы задумчиво провести кончиками пальцев по столешнице красного дуба; правой же Агата непрерывно водила над записной книгой, периодически что-то вычёркивая и дописывая.

[^91]: Йен Кёртис – вокалист и основатель пост-панк группы Джой Дивижн. Страдал эпилепсией и во время выступлений нередко исполнял свой фирменный танец, изображавший эту болезнь. 

– Выкладывай, – произнесла она, переворачивая страницу.

Гек, который уже успел приуныть от нехватки внимания, вмиг оживился.

– Привезли! – поспешил доложить он, и Нора вздрогнула, подумав об очередном покойнике, но, вопреки ожиданиям, следующая фраза мальчика вызвала у неё одно лишь недоумение. – На этот раз в глазных яблоках…

Во-первых, Гек вдруг заговорил на русском, и теперь речь его звучала странно и чуть ли не противоестественно. Во-вторых… *Что?*

Агата едва ли была поражена услышанным. Она вяло махнула рукой, так что на пальцах стали видны посиневшие вмятинки от длительного писания.

– Неинтересно. 

– Ти ж неначе як жартуєш?[^92]

[^92]: Ты не иначе как шутишь? 

Агата вздохнула.

– Я абсолютно серьезно, Гек, – она повернулась к другой девушке. – Так что думаешь, на втором этапе гниения труп лучше называть раздувшимся, или зрелым?

Нору застали врасплох: она как раз задумчиво переводила взгляд с мальчика на Агату, а затем обратно, и уж точно не предавалась размышлениям о стадиях разложения трупов, как и о любым другим, связанным с покойниками, думам, пускай временами это было и непросто, находясь в бюро ритуальных услуг.  

Девушка подвисла.

Агата подняла ручку, словно собираясь что-то записать, но затем повторила вопрос, вновь взглянув на собеседницу.

– Так, что думаешь? 

Та постаралась сосредоточиться и призвать на помощь всю свою вежливость.

– Эм-м-м…Да-а-а, – протянула Нора.

Гек предательски хохотнул.

– Что да? – Агата вопросительно подняла бровь. – Зрелый или раздувшийся?

– А как патологи называют? – наконец, нашлась Нора.

– И так, и так говорят.

– Я…Я думаю, тебе виднее.

Нора неуверенно взглянула на хозяйку «Маятника». Та плавно водила головой по сторонам, словно раздумывая, а не согласиться ли с собственными мыслями. Ответ, вероятно, оказался положительным, потому что Агата удовлетворенно хмыкнула и принялась увлеченно что-то вычёркивать.

Мальчик озадаченно следил за этим действом.

– Ну я піду?[^93] – произнес он, словно, ожидая, что Агата передумает.

[^93]: Ну, я пойду?

Однако, она лишь безразлично кивнула.

Близилось время обеда, что в «Маятнике» обычно имел место быть ближе к полуночи. Элеонора вспомнила об обещанной пицце и почувствовала, что кит в её животе вот-вот примется исполнять ночные серенады. Воспользовавшись ситуацией, девушка поднялась со своего места.

– Я тоже, – сказала она. – Засиделась что-то.

Еще один неопределенный кивок.

Вскоре дубовая дверь скрипнула и владелица «Маятника» вновь осталась одна в кабинете, едва ли это замечая.


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>


Несмотря на напускную обиду, которой так и сквозили глаза мальчика, (превратившие нашего героя обратно в ребёнка, каким его представляла Элеонора, слушая историю одного путешествия) и легкую растерянность ввиду отказа Агаты от чего бы там ни было, Гек не спешил покидать «Маятник», стоило ему лишь услышать пленительные запахи выпечки, коими, казалось, пропитался каждый камешек мрачного здания: как бы там ни было, малец никогда не был против вкусного обеда. Особенно халявного. 

– Тебе не кажется, что наша барышня чёт приуныла? – задала вопрос Нора, стоило им остаться наедине. – Ну, как в той странной песне, помнишь? Которая вовсе-то и не песня на самом деле.

Мальчик, который слишком много времени провел в компании Агаты и Валерия, был равнодушен к интернету, так что понятия не имел, о какой песне, или не песне идет речь, но мысль Элеоноры он понял, а потому многозначительно кивнул.

– Я за цим й зайшов.[^94]

[^94]: Я поэтому и зашел.

Гек заметил, что не помнит, дабы Агата хоть раз покидала «Маятник» с момента своего возвращения из лесу. Она, конечно, и до этого не то, чтобы часто выходила из так званой зоны комфорта, но прежде мальчик никогда не видел, чтобы она вообще всё время проводила в кабинете.

– Чи мені здеється?[^95] – малец с надеждой взглянул на собеседницу.

[^95]: Или мне кажется? 

Та попыталась припомнить какой-нибудь недавний относящийся к делу случай, но, увы, Нора вдруг осознала, что теперь её подруга даже не вспоминала о том, чтобы зажечь могильные фонари.

По всей видимости, лицо Элеоноры ответило на вопрос Гека раньше, чем это удалось сделать самой девушке. Малец в задумчивости клацнул языком и насупил брови, приняв в равной мере комичный и трогательный вид.

– Так я і думав…[^96]

[^96]: Так я и думал…

Нора и раньше догадывалась, что что-то не так, но в полной мере осознала это, лишь обретя единомышленника. Она беспомощно взглянула на последнего. Мальчик продолжал клацать языком, сосредоточенно глядя в темноту, за которой скрывался зал для проведения прощальных церемоний.       

Внезапно Гек смолк. Его взгляд возвратился к Норе.

– Не маєш бажання гульнути містом?[^97] – на лице мелькнула лукавая улыбка.

[^97]: Нет желания прогуляться по городу? 

Элеонора рефлекторно сверилась с часами: без трёх минут полночь – самое время размять ноги в минусовую температуру.

– Почему бы и нет, – ответила девушка. Она указала на лестницу. – Только сперва давай разбёремся с пиццей.

## 63 {-#63}

Вопреки настырному холоду, февральская ночь оказалась на удивление ясной: деревья то и дело пускались в пляс, сопровождаемый порывами ветра, а над ними золотился тонкий серп полумесяца, окруженный компанией ярко сияющих звёзд; воздух был свежим, на улицах буквально веяло зимой – всё это зачаровывало Элеонору, создавая запоздалую иллюзию Рождества.

Привыкшая путешествовать в одиночестве, наша героиня уже давно исследовала и досконально знала Старе Місто, а потому, усевшись в такси, тут же воодушевилась, услышав названный Геком адрес: улица Джона Леннона не входила в территорию, на которой обычно проходили её прогулки, и Нора была рада выбраться подальше от центра, который, несмотря на своё разнообразие, уже успел слегка наскучить.

Ехали они долго.

Однако, достигнув пункта назначения, девушка выглядела разочарованной. На мгновенье Норе подумалось, что она вдруг зачем-то вернулась в свой родной город, напрочь состоявший из такого вот пост-советского гетто, коим, несмотря на своё мелодичное название, оказалась вышеупомянутая улица.

Такси поспешило убраться вон, и наши персонажи остались стоять в окружении серых бетонных блоков, по ошибке именуемых домами. И вновь выражение лица Норы с лёгкостью выдало её мысли. Гек расхохотался.

– Стане тобі журитися![^98] – весело заметил он.

[^98]:  Будет тебе печалиться! 

Первым делом, говорил мальчик, когда они шагали сквозь ночь, в направлении одной из этих нагоняющих тоску мнгоэтажек, Норе следовало постараться расслабиться и спрятать этот виноватый взгляд – он и по жизни-то не сулит ничего хорошего, что уж говорить о грядущей встрече с дилером. Во-вторых, продолжал Гек, ни ей за что – ни при каких обстоятельствах – не стоило упоминать слова «пушка»! Таких парней это же-е-е-есть как бесит, ну, будто красной тряпкой перед быком помахать…

Всё это время Элеонора молча следовала за своим спутником. Мысленно она уже вовсю сокрушалась о том, что в принципе согласилась отправиться в это чёртово гетто. Нет, она любила Агату, а та, как уверял Гек, любила травку, но чем меньше расстояния оставалось до подъезда, тем сильнее наша героиня убеждалась в том, что игра не стоит свеч.

Слушая мальчика, она уже приоткрыла рот, собираясь сказать, что передумала, однако, была слишком вежливой, чтобы перебивать.

Ну, и последнее, спокойно излагал Гек, говорить будет он. Нора же, если кто вдруг спросит, является его сучкой, или как тут принято говорить… 

Тут малец не выдержал и расхохотался что есть мочи. Его смех эхом отдавался в бетонных стенах. Какой-то дед высунулся из окна соседнего дома и пропитым голосом предложил шумевшему веселиться в другом, более подходящем для этого, месте. Например, в заднице.

– Ты чего это? – прошептала девушка.

Её спутнику понадобилось время, чтобы успокоиться.

– Бачила б ти своє обличча…[^99] – не унимался Гек. – Ну просто кобітка-прихуїтка![^100]

[^99]: Видела бы ты свое лицо…

[^100]: Кобіта – девушка, тогда как второе слово не требует перевода. 

Элеонора остановилась. Она откинула с лица волосы и серьёзно взглянула на мальчика, чьё тело продолжало сотрясаться от смеха, что так и рвался наружу.

– Ой, не ображайся ти, – махнул рукой Гек. – Я ж лишень жартував, бо ти видавалась такою напруженою… Той Блискавка взагалі-то файний хлоп, тобі сподобається![^101]        

[^101]:  Ой, не обижайся ты. Я же всего лишь пошутил, а то ты казалась такой напряженной… Тот Молния вообще-то милый парень, тебе понравится!

Нора глубоко вздохнула.

Что ж, могло быть и хуже.

## 64 {-#64}

Выкурив парочку сигарет, девушка, казалось бы, успокоилась, но поняла, что это не так, когда разглядывала своё искаженное отражение в разбитом зеркале. Вскоре лифт за её спиной захлопнулся. Нора не была уверена в том, что собирается сказать: она не то хотела предложить своему спутнику уйти, не то просто собиралась попросить Гека ещё немного подождать… 

Как бы там ни было, взглянув на мальчика, наша героиня увидела, что тот уже приподнялся на носочках и коснулся кнопки звонка. Действие это отдалось чуть слышным щебетанием птиц, которые, скорее всего, уже давно умерли.

Нора не была поклонницей ни гонзо, ни пост-модернизма, но все же читала кое-что как из Томпсона[^102], так и из Берроуза[^103]. Короче говоря, она ожидала увидеть перед собой типичный образец угашенного в хлам наркомана. Однако, открывший дверь человек вовсе не имел безумный вид: на удивление, он оказался полностью одет, волосы – длинные, собраны в хвост, за исключением двух прядей, аристократично свисавших вдоль лица, которое вовсе не выражало негативных эмоций. Вместо ожидаемого шприца, зараженного сотнями вирусов, в руках дилера виднелась потрепанная книга, чью обложку не позволяло идентифицировать плохое освещение. 

[^102]: Хантер Томпсон – американский писатель и журналист, основатель гонзо-журналистики, автор автобиографических книг «Страх и отвращение в Лас-Вегасе» и «Ромовый дневник», персонажи которых неизменно пребывают под влиянием наркотических средств.


[^103]: Уильям Берроуз – американский писатель и эссеист, считается важнейшим представителем бит-поколения. Автор таких работ как «Джанки» и «Голый завтрак», в которых, основываясь на собственном опыте, детально знакомит читателя со всеми оттенками наркотической палитры. 


Словом, мужчина смотрелся адекватно и, кажется, и впрямь был в своем уме. Его глаза выражали одно лишь спокойствие. Заметив девушку, Молния улыбнулся, и Норе понадобилась всего доля секунды, дабы узнать в стоявшем перед ней мужчине того самого незнакомца с кладбища.  

Мужчина ничего не сказал. Он посторонился, жестом приглашая гостей в квартиру. Позже выяснилось, что обшарпанная двухкомнатка была жилищем одного из товарищей Молнии, – того самого, что организовал сделку по перевозке голландских семян в протезах глазных яблок – и именно здесь занимались взращиванием товара.

Гек подмигнул своей спутнице, прошел по крохотному коридорчику и скрылся за дверью кухни. Было слышно, как он весело с кем-то болтает.  Тем временем Молния помог девушке снять шубку и провел её в дальнюю комнату, представлявшую собой что-то вроде плохо обставленной гостиной.

– Вот уж не думал так встретиться, – наконец, заговорил Молния.

У него был тот самый вампирский акцент.

Мужчина опустился на диван. Это оказалось единственной мебелью, на которой можно было сидеть, не считая лишившегося двух ножек стула, что был прислонен к противоположной стене, так что Норе пришлось опуститься рядом.

– Я бы предложил кофе, – произнес Молния, кладя книгу по другую сторону, так что девушка вновь не успела узнать название, – или зеленый чай, но из напитков тут только Метакса. Там где должна быть кухня у нас… Ну, ты понимаешь.

Нора кивнула.

– Всё в порядке, – сухо ответила она, хотя едва ли была согласна с собственным утверждением.

Они находились наедине от силы минуты три, но Нора то и дело ловила на себе взгляд Молнии. Теплый и, на удивление, уютный, учитывая окружающую обстановку. Девушка чувствовала, что краснеет.

– Вы продадите травку Геку? – неуверенно произнесла она, зная, что раскраснеется ещё больше, если продолжит молчать.

Молния ухмыльнулся, и девушка вновь поразилась его красоте.

– Естественно, я-то знаю, для кого этот корабль.

– Вы с Агатой знакомы?

– Мы *были* знакомы, – ответил Молния.

Это прозвучало странно. Нора решила повременить с расспросами. Повисла неловкая пауза. Первым её нарушил мужчина.

– А что ты вообще здесь делаешь? – спросил он, чётко выговаривая каждое слово. – В такое-то время…

– Присматриваю за мальчишкой, – соврала Нора. Она и сама толком не знала, что здесь делает. – Не хотела отпускать его одного.

Вскинув брови, её собеседник искренне расхохотался.

– Присматриваешь? За Геком-то? – сквозь смех произнес Молния. – Да в вопросах выживания он каждому из нас фору даст!

Он вновь рассмеялся, а затем сказал что-то ещё, чего наша героиня не расслышала. Да это и не было важно. Девушка на мгновенье забыла о стеснительности и теперь зачарованно разглядывала улыбку сидящего рядом мужчины, стараясь запомнить этот момент как можно чётче.

– Пойду всё же справлюсь насчет чая, – произнес мужчина.

Он поднялся со своего места и Элеонора, наконец, смогла разглядеть коричневый томик, оставшийся на диване. Им оказался «Вокзал потерянных снов»[^104].

[^104]: Второй опубликованный роман Чайна Мьевиля, написанный в жанре стимпанк.

Так наша героиня влюбилась.

## 65 {-#65}

Последний месяц зимы выдался в действительности странным. Не потому, что снега не было вплоть до наступления марта – этим как раз никого не удивишь. Дело было в том, что данный промежуток времени внес множество изменений в жизни обитателей «Маятника», из которых далеко не все были положительными, но большинство событий уж точно оказались неожиданностью.

Ближе к утру Норе удалось добраться до собственной постели. Никогда прежде подъем по ступеням не занимал у нее так много времени и, только зарывшись в одеяла, девушка осознала, что на самом деле не поднималась, а спускалась по лестнице, ведущей из апартаментов Агаты.

До рассвета было ещё далеко, чему наша героиня несказанно радовалась. Одному Берроузу известно, что могло бы случиться с её головой при контакте с дневным светом: черепушка и без того обещала расколоться при первом удобном случае. Нора постаралась убедить себя, что всё утрирует и нет у неё никаких мигреней. Вышло как-то не ахти. Она попыталась отвлечься и восстановить в памяти события последних часов…

Ну, насколько это в принципе казалось возможным.

## 66 {-#66}

– Я не наркоманка, – безразлично произнесла Агата, когда парой часов ранее Элеонора вернулась в её кабинет со спичечным коробком, полным голландской травки. – Курю только по четвергам…

В западной стене раздался глухой стук.

– … и каждую вторую субботу, – нехотя добавила Агата, отчего грохот тут же прекратился. – Временами соседство Ласло становится невыносимым. Словно живешь с детектором лжи.

– Сегодня как раз четверг, – заметила Нора.

Владелица похоронного бюро ничего не ответила. Она высыпала содержимое коробка на стол и принялась своими длинными ногтями водить по его поверхности. Элеонора минут пять наблюдала за подругой. Подобная картина ей быстро наскучила.

– Я, конечно, не спец, – начала Нора, указывая на траву, – но, по-моему, её не так принимают.

Агата медленно подняла голову. Очки, как обычно, не позволяли сказать наверняка, однако Нора могла поклясться, что подруга закатывает глаза. Иного ответа не последовало и на протяжении последующих минут.

– Почему ты отказалась, если дуешь так часто? – нарушила тишину Нора.

– Я бы не сказала, что это часто.

– Ну так?

– Мне не хотелось отвлекаться. Думала разобраться с делами, – размеренно произнесла Агата.

Несколько травинок случайно попали под ноготь, так что она пыталась исправить ситуацию.

– Но ты уже три недели не вылезаешь из кабинета! – не выдержала Нора. – Сидишь тут, рассказываешь о гниении тел, – а мне, знаешь ли, это не особо нужно, я вообще, если хочешь знать, предпочитаю кремацию – составляешь могильные надписи, а из проигрывателя вечно доносятся эти загробные голоса… – она перевела дыхание. – Да и вид у тебя чересчур трагический.

Агата пожала плечами.

– Работа у меня такая.

Нора обошла стол.

– А на прошлой неделе я нашла это, – она резко выдвинула верхний ящик. 

Тот оказался пуст. 

– Секунду, – попросила девушка, и выдвинула второй ящик.

Результат был тот же, но наша героиня не хотела сдаваться. 

– Это, – она попробовала третий ящик.

Также пуст. Их, кстати, было двенадцать.

Агата, которая прежде спокойно наблюдала за разыгравшимся действом, откинулась в кресле.

– Попробуй нижний, – посоветовала она.

За неимением иных вариантов, Элеоноре пришлось прислушаться. К глубочайшему облегчению девушки, последний ящик не был пуст. Его заполняли блокноты и бумажные папки, (чёрные, разумеется) поверх которых красовалась бумажка размером А4 – печатный бланк, большинство пробелов в котором заполнял знакомый Норе почерк.     

Выглядел бланк следующим образом.

<blockquote>

<p align=center>ПРЕДСМЕРТНАЯ ЗАПИСКА</p>

Я, <em><u>Агата Рахманинова</em></u>, далее именуемая как Составитель, ___ числа, ____________ месяца ____ года совершившая самоубийство путем <em><u>асфиксии</em></u> по причинам <em><u>слишком банальным, чтобы их называть</em></u>, подтверждаю, что упомянутое выше решение было принято мною самостоятельно, не под влиянием алкогольного, или наркотического опьянения и без постороннего вмешательства.

Ввиду вышесказанного, заблаговременно 

<p align=center>***Прошу правоохранительные органы***</p>

– избежать заведения уголовного дела об умышленном убийстве Составителя по ст. 115 УК Украины;

– опустить проведение уголовного следствия о доведении до самоубийства по ст. 120 УК Украины, а также исключить любые ссылки на этот и другие законы, которые могут быть использованы в целях привлечения к уголовной ответственности третьей стороны; 

– в ходе опроса свидетелей и осмотра места происшествия настоятельно рекомендую избежать разговора со следующими лицами:

<em><u>Владиславом Мирославским – по причинам слабого психического здоровья;</em></u>

_____________________________________________________________

_____________________________________________________________

_____________________________________________________________

– упразднить проведение вскрытия исходя из того, что смерть Составителя наступила ненасильственным путем, посредством <em><u>асфиксии</u></em> и по причинам, приведенным выше.

Для облегчения работы правоохранительных органов к данному документу также 

<p align=center>***Прилагаются:***</p>

– полная информация о Составителе;

– пакет документов Составителя;

– последние записи, сделанные Составителем, кои могут потребоваться для проведения почерковедческой экспертизы.

<p align=center>***В дополнение***</p>

– прошу утилизировать тело составителя путем (подчеркнуть нужный вариант)

погребения (по желанию указать кладбище) ______________________________

<u>кремации</u> (по желанию указать крематорий и дальнейшую судьбу праха Составителя) __________________________________________________________________
________________________________________________________________________

свой вариант ________________________________________________________

– \*прошу учесть, что по желанию Составителя в момент утилизации на нём/ней должно быть надето (здесь перечислить свои предпочтения) <em><u>что-нибудь чёрное, загляните в мой гардероб – проблем не будет;</em></u>

– \*в целях погребения/кремации Составителя, а также проведения церемонии прощанья, (не обязательно) прошу воспользоваться услугами (вписать название желаемого бюро ритуальных услуг) <em><u>вот это будет задачка не из легких;</em></u>

– \*прошу учесть пожелания Составителя относительно (подчеркнуть и вписать нужное)

материала и дизайна гроба ________________________________________________

материала и дизайна урны ________________________________________________

свой вариант ___________________________________________________________
_______________________________________________________________________

Больше информации можно узнать, ознакомившись с завещанием Составителя, оформленном в ________________________________________________________________
и заверенном __________________________________________________________________



___ числа __________________ месяца _____ года.

Составитель: <em><u>Агата Рахманинова</em></u> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Подпись: ___________г.




\* обозначенные сносками пункты не являются обязательными для заполнения


</blockquote>

Обратная сторона бланка оказалась разлинованной. «Для заметок» – так она была озаглавлена. Когда девушка впервые обнаружила странный документ, та его часть пустовала, но теперь Агата оставила на ней послание, несущее вот такую сомнительную информацию:

> *Хорошо быть кремированным. Больно надо, чтоб тобой черви питались. К тому же, всегда остаётся шанс превратиться в зомби, что тоже так себе вариант, я считаю. А тут, развеялся и летишь себе над океаном весь такой радостный, а потом в дыхательные пути всяким мудакам попадаешь и такой: «Вот вам, сучки!» и дальше летишь…*

Смеяться Нора, вроде как, не собиралась, но, прочитав последние строки, просто не смогла удержаться. Девушка опустила бланк на стол и, надеясь, что её лицо все же приняло серьёзно настроенный вид, взглянула на подругу.

– Как ты это прокомментируешь? 

Физиономия Агаты оставалась беспристрастной.  

– Ты рылась в моем столе? – произнесла она, скорее удивленно. – Раньше ты никогда не рылась в моих вещах…

Владелица «Маятника» задумчиво выдохнула и замолчала на половине фразы.

– У меня закончились сигареты, – выпалила Нора и тут же поняла, как неправдоподобно это звучит. – За окном стояла ночь. Мне не хотелось выходить из дома. Да и холод такой, сама знаешь.

Агата знала.

– Странно… – протянула она.

– Что странно?

– Странно, что я тебя не заметила, потому как по ночам я всегда здесь.

Нора растерянно шмыгнула носом: она никогда не умела врать.

– Ну хорошо, это было днём, – призналась девушка. – Я волновалась за тебя! Ты ведёшь себя странно, еще более странно, чем обычно. Спишь от силы часа три в сутки и постоянно – всё время – проводишь в этой долбанной комнате!

Агата указала на предъявленный ей бланк.

– Это для моих курсов, – беглая ухмылка. – Всего лишь шаблон посмертной записки. – Мне нужно было разобраться с кучей дел, я же говорила.

– И как, разобралась?

Драматическая пауза.

– Почти.

## 67 {-#67}

Часом спустя обе девушки полулежа развалились с кожаных креслах, которые располагались в гостиной Агаты и были точными копиями излюбленного седалища хозяйки «Маятника», что осталось этажом ниже. За всю свою жизнь Элеонора ни разу не баловалась с дурью и начинать не собиралась, а уж тем более не хотела спать в прокуренной травкой комнате, так что наши героини сочли апартаменты Агаты местом, более подходящим для текущей сцены.

Разглядывая драп, Агата пришла к выводу, что это «не какая-то там солома», и ей было бы жалко пускать такую травку на косяки. Не так уж давно Владислав разбил стеклянный бульбулятор, который был втрое старше его самого, – и Агата подозревала, что сделал он это вовсе не случайно – так что дамочка обзавелась бутылкой с фольгой и наскоро соорудила самодельный кальян, он же Дудка, он же Ферик, он же Утка, Бонг, Батл и многое другое.

Однако, кое-что наши персонажи всё-таки не учли. Драп оказался чрезмерно хорошим, да таким, что Нора, которая лишь хотела понаблюдать за процессом, внезапно оказалась пассивным курильщиком, но поняла это слишком поздно, дабы иметь хоть малейшую возможность что-либо изменить. Прихода девушка, конечно, не поймала, но густые испарения быстро заполнили комнату и настроили нашу героиню на всем известную волну смеха и юмора.    

Большую часть времени Нора, чей голос стал заметно выше, хохотала, останавливаясь только чтобы послушать, что ещё скажет её подруга, а потом продолжала надрывать живот.

Голос второй девушки вообще познал поразительные метаморфозы: его переполняли эмоции угара и, вместе с тем глубокого трагизма, так что речь Агаты теперь скорее походила на страсти актеров шекспировских времен. Элеонора не была уверена, было бы ей настолько весело без периодических повествований подруги, но полагала, что да.

За все время Агата лишь раз поднялась со своего места, но при этом всё время выполняла какое-то действие. Вернее сказать, чувствовала его у себя в голове, а потом пыталась донести увиденное до собеседницы. Наша героиня (ну, та, которая была более укуренная) также частенько не могла понять, смеется она, или плачет, о чём не прекращала спрашивать, но это уже другая история.

Кстати, она также постоянно повторяла три слова, каждое из которых почему-то начиналось на «Т»: трагически, тревожно и трогательно. Последнее так вообще вечно прилетало не к месту.

– Я… знаешь что… – мечтательно начала Агата. Говорила она медленно, чуть ли не по слогам, периодически срываясь на жуткий смех. – Сижу как в соломенном кресле…

– Круто тебе. 

– Не-не-не…

– А я сижу как в дерьме. У меня нога затекла.

Нора попыталась сменить позу. Сие действие отдалось проникновением тысячи невидимых иголок в вышеупомянутую ногу, и девушка завопила.

– Это не до конца, – заявила Агата. – Я сижу, как в соломенном кресле сидел бы мужик… – она почувствовала, что мысль вот-вот ускользнет, и попыталась ускориться, в итоге запуталась, отчего речь её стала ещё медленнее. – На улице… Сидел бы чувак… Такой… Высокий… – истерический смех. – Сидел бы такой… И ел грибы, а к нему подошел мальчик…

Тут Нора не выдержала и разразилась очередным приступом атонального смеха.

– Какие грибы, ты чё? Невесомые?

– Да-да-да! – подтвердила Агата. Сделала она это с такой яростной готовностью, словно всю жизнь ждала, пока кто-нибудь да спросит у неё о невесомых грибах. – Так вот… Мальчик подошел к нему… И такой… Я сплю с твоей сестрой… Случайно сказал… А тот должен был по сценарию разозлиться… На него накричать… А он такой: ммм, ммммммммм… та ты садись… Для начала присядь… И сиди… – Агата вдруг заплакала, что исказило её последующие слова. – Под грибами он был… Я себя как-то так и вот так… – тут её голос сорвался, вновь пропитавшись небывалыми эмоциями, достойными лучших артистов «Глобуса». – Трагически! Господи, как же трагически!

Нора в растерянности уставилась на подругу, не прекращая при этом смеяться.

– Чё у тебя все трагически да трагически? – наконец, заговорила она.

Издав странный возглас, который её собеседнице так и не удалось идентифицировать, Агата прекратила плакать так же внезапно, как и начала. 

– Ой-ой-ой-ой-ой! – заверещала она. – Не делай такой голос! Как у дедушки… Который повесился… В фильме… Советском…Но не умер…

## 68 {-#68}

– Я знаешь что… 

– Что?

– На крыше сижу… – сказала Агата, продолжая совершать свои таинственные перемещения. – С сигаретой в руках… Смотрю на закат… И голос у меня как у Джонни Кэша…

Мечтательность её тона резко сменилась всё тем же трагизмом.

– Но…Зачем сидеть на крыше, когда ты на самом деле сидишь взаперти? – печально спросила Агата. – Ох, волосы длиннее стали! Какие кто?

– Кто? – Нора непонимающе моргнула.

– Эти существа на «С». Ты их уже раз пять за ночь упоминала.

Элеонора принялась размахивать руками, словно пытаясь прогнать рвущийся наружу смех.

– Была речь, была, – просмеялась она. – Хотя нет… Таких не упоминала.

– Они вертикальные? – вдруг спросила Агата.

– Чё? Я такого не говорила.

– Нет, я сама увидела… Ты мне показала…

Ещё одна пауза.

– А они все идут и идут, – с тревогой сказала Агата.

– Кто?

– Ну, люди, которые слышат. 

Нора понимала, что это всего лишь действие травы, но тревога подруги необъяснимым образом настигла её саму. Девушка перестала смеяться. Она приподнялась на локтях и взволновано взглянула на собеседницу.

– Кто идет, Агата?

Та помедлила, вероятно, обдумывая ответ.

– Мне кажется, девять, – безразлично пояснила Агата. 


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

– Стало понятней, когда в музыке молния ударила, – оповестила Агата после десятиминутной тишины.

Лицо её приняло восторженное выражение.

– Я тебе говорила? – крикнула Агата. – Я с самого начала хотела сказать! Я сейчас так, знаешь, всё как будто бы быстро…

– Да чё ты свой нос так держишь?

Громкий смех. 

– Нет, не отпадет! – сквозь хохот продолжала Нора.

– А-а-а, он уйдет, – взвыла Агата. Она осознала, что и впрямь держит нос, но до этого момента мысль о том, что тот может сбежать в её голову как-то не приходила. А вот теперь пришла, и наша трагическая джанки вцепилась в него всеми пальцами левой руки. – Уйдет… Пускай будет!

– Чё ты несешь? – членораздельно произнесла Нора, уповая на то, что от этого суть сказанного лучше усвоится собеседницей, хотя и сама она никак не могла остановить поток истерического смеха. – Что пускай будет – нос? Как будто у тебя есть выбор…

– Слушай! – возбужденно прервала её другая девушка. – Не обращай… Не обращай внимания, на то, что я нос держу…

Но, у Норы уже разыгралась фантазия.

– Сейчас он улетит! – крикнула она и рассмеялась. – Н-о-о-о-с, иди сюда! Носик мой, носик, останься!

Агата еще крепче сжала свой бедный нос. Дышать теперь приходилось ртом. Однако, укуренная владелица «Маятника» чувствовала, что просто обязана поведать то, что собиралась.

– Постой! НЕ ОБРАЩАЙ, ПОЖАЛУЙСТА, ВНИМАНИЯ НА ТО, ЧТО Я НОС ДЕРЖУ!

– Но-о-о-с, – пропела Элеонора.

– Не-не-не, я должна сказать! – заявила она, а затем повторила эту же фразу для пущей информативности. – Я сейчас как будто бы стою на балконе… Ты только дослушай… Я сейчас стою на балконе таком…Античном… В греческом дворце…Может быть… Или нет…Стою на балконе.. Волосы у меня так красиво подобраны… Я держусь за перила… Белые…И со стороны вижу, как я стою и смотрю на то… Как я с тобой тут сижу…

– Да?

– Да! И поэтому всё такое… Тарахтит быстро так, быстро! А на самом деле… Всё очень медленно… Очень… Трагически… Мы так медленно думаем… – она устало вздохнула.

Нора тоже что-то призадумалась.

– Ну ничё себе, – ответила она.

Наступила длительная пауза. Когда Норе уже показалось, что подруга уснула, та вдруг подняла голову, чтобы неуверенно спросить:

– В каком дворце?

– В греческом, – тут же ответила девушка.

– Да-да-да-да-да… Или греческом…

Затем Агата пробубнила ещё что-то нечленораздельное и вновь смолкла. Спустя четверть часа она вяло махнула рукой в сторону проигрывателя.

– Включи мне Джой Дивижн, – поразительно трезвым голосом попросила Агата.

И тут же отключилась.

## 69 {-#69}

Солнце лишь начинало вставать, украдкой бросая на кладбище первые лучи своего света. Элеонора распахнула глаза и тут же пожалела о быстроте этого действия: затылок пронзила сильная головная боль, которая, казалось, и не утихала с прошлой ночи, а только дремала вместе с девушкой.

Нора болезненно застонала и осмотрела спальню, надеясь обнаружить здесь какую-нибудь жидкость. Пить хотелось жутко.

Её разбудил гулкий отзвук шагов, звучавших то ли из стен, то ли из её собственного воображения, причем, на этот раз наша героиня более склонялась к последнему варианту. Проспав всего-то пару часов, Нора чувствовала необъяснимую бодрость, так что вскоре ей пришлось оставить попытки вновь погрузиться в сон. Девушка с трудом добралась до душа: она ощущала мерзкую ломку во всём теле, какая бывает, когда встаешь после долгой болезни. 

«Маятник» ещё спал. 

Владислав всю ночь провел за просмотром первого сезона «Фарго», и теперь с чувством выполненного долго сопел на чердаке. Агата так и осталась дрыхнуть в своей гостиной и, вероятно, собиралась не открывать глаз до тех пор, пока не компенсирует все бессонные ночи последнего месяца. Станислав Эдуардович, дожидаясь своей очереди преобразиться к церемонии, отдыхал в морозильнике мастерской Ласло и, вроде как, не собирался просыпаться.

Какое-то время Нора бесцельно бродила пустыми комнатами похоронного бюро, совершенно не зная, чем себя занять. Её обуяла глубокая беспричинная тоска, – девушка понимала, что это, видимо, и есть отходняк, но ничего не могла с собой поделать – которая позже вылилась в пиццу и двойную порцию шоколадного латте.

Начала она с уже откупоренной кем-то (ну кто бы это мог быть?) бутылочки красного бургундского. 

В своих мыслях Элеонора вновь вернулась к пустующим апартаментам, – единственным запертым дверям во всём доме, – понимая, что сейчас никто не сможет помешать проведению её скромной экспедиции, но тут же отогнала эту затею: ничем необоснованное любопытство можно отложить и до лучших, лишенных мигрени времен. Но, было ещё кое-что, нарушающее её и без того шаткий покой.

Однажды, в стремлении повысить свои писательские навыки, девушка штудировала веб-пространство, просматривая статьи для начинающих авторов. *«У каждой написанной фразы*, – так начиналась одна из них, – *если книга достойная, у каждого свершенного действия должен быть смысл. Он не всегда лежит на поверхности и ввиду своей утонченности легко может затеряться среди похожих, искусственно выдуманных высказываний, или же событий, служащих всего лишь декорациями в среде обитания этого самого смысла. Читателю предоставляется возможность взглянуть на верхушку айсберга, дабы в дальнейшем иметь шанс расставить все точки над «і», но, откровенно говоря, к этому прибегает крохотный процент реципиентов. Хитрость умелого пера заключается в красноречивом намеке, сделать который нужно своевременно и без особого фарса, так, чтобы спустя n-ное количество страниц читатель мог вернуться к этому моменту и осознать суть написанного…»*[^105]        

[^105]: Цитата из моей же старой статьи. 

Несмотря на свою простоту, совет был дельный, и Нора собиралась непременно использовать его при создании своего романа, как только ей удастся откопать в собственной голове тот самый смысл, идейный посыл, который бы можно было передать читателю. 

Однако, сейчас речь шла вовсе не об этом.

Всё ещё затуманенное сознание нашей героини в принципе понимало, что Агата Рахманинова – вовсе не книга, а чертовски странная дамочка, к тому же накануне обкурившаяся крепче, нежели собиралась, но, как вы уже поняли, было тут ещё что-то…

«У каждой написанной фразы, – размышляла Элеонора, – должен быть смысл, и укуренный бред Агаты – не исключение».

Девушка давала себе отчет в том, что её нынешние думы является всего лишь попытками скрасить унылое утро капелькой приключений, но, вместе с тем, чувствовала, что наркотический монолог подруги, или какая-то его часть, в дальнейшем ну просто должна преобразиться в более осмысленные слова. Причем, скорее всего та, что так встревожила, если не сказать напугала, нашу героиню. 

Прикрыв глаза, Нора без устали перебирала в голове отрывки сказанных Агатой фразочек, пока не остановилась на…

«Они идут и идут. Люди, которые слышат… Слышат что – запах? – девушка затаила дыхание, словно процесс этот мог помешать ей думать. – Стоп. Ну, при чём здесь запахи?»

Но Элеонора чувствовала, что мыслит в правильном направлении. Хотя, возможно, это лишь вино давало о себе знать. Ни для кого не секрет: наша героиня всегда быстро хмелела.

«Хо-ро-шо, – глубокий вдох. – Они идут и идут. Люди, которые слышат запах. Они идут туда, откуда доносится запах, или уходят, потому что услышали запах? Нет, это всё не то…»

– Они идут и слышат запах! – воскликнула Нора, удивившись неожиданной громкости своего голоса. – Люди продолжают идти, несмотря на то, что слышат запах! Какой-то неприятный запах.

Воодушевившись на некий миг, девушка вновь приуныла. Эти слова показались слишком нелепыми после того, как она произнесла их вслух.     

– Ой, все, – устало процедила Нора. – Мне надо пройтись.

## 70 {-#70}

Элеонора покинула пределы кладбища без лишних раздумий. Пребывание на холодном воздухе действовало на неё благосклонно: в скором времени в голове прояснилось. 

Ступая по голой, местами покрытой изморозью, земле, Нора ещё не знала, куда держит путь, пока не увидела приближающийся к остановке трамвай. Она ускорила шаг и вскоре впрыгнула  в пустую кабину. Город просыпался и спустя несколько остановок трамвай постепенно начал наполняться людьми, спешащими на работу, или учебу. Нора же никуда не спешила. Уткнувшись в электронную книгу, она одиноко сидела в самом конце салона, изредка бросая взгляд на проплывающие за окном городские пейзажи.

Спустя минут двадцать, или около того, занятие это ей наскучило, так что девушка сошла на первой попавшейся остановке, успев вовремя опомниться и отскочить в сторону. Помедли Нора ещё секунду, и толпа граждан, что спешили захватить немногочисленные сидячие места, непременно внесла бы её обратно в трамвай.

Девушка осмотрелась. Всё вокруг выглядело так, как обычно обстоят дела во Львове под конец зимы: уютно, но сыро и пасмурно. Её силуэт мелькал в окнах кофеен и витринах уличных лавок, всё еще мокрых после недавнего дождя, пока девушка бесцельно шагала сквозь город. Утренняя ходьба успокаивала, предавала некий смысл начавшемуся дню. 

Со временем огни вывесок сменились более спокойными видами. Наша героиня не знала, куда идет. Ноги сами вели её вдоль кирпичных стен, прокладывая путь среди пастельных домиков с крохотными балконами. Улочки становились всё уже, оставляя позади суету и шум машин, когда девушка нырнула под вычурную арку и поняла, что наткнулась на тупик.

Это был небольшой квадратный дворик, окруженный чередой разноцветных пятиэтажек. Внутри было тихо – никакого ветра, а среди постояльцев были только кошки, сгрудившиеся на скамейке.

Девушка подустала. Прогулка длилась третий час и она чувствовала, что уже практически обрела былую бодрость духа. Нора плюхнулась на одну из лавочек, расположенных под сенью широкого дуба и тут же почувствовала, как на самом деле вымоталась: аукнулись ночные посиделки, подкрепленные до неприличия коротким сном. Смартфон – одно из чудес современной техники, благодаря которому в кармане можно было иметь всё, что душе угодно: музыку, фильмы и целую библиотеку. Не доставало, разве что, еды, но и это лишь вопрос времени.

Элеонора собиралась почитать, но вместо этого откинулась назад и принялась изучать серое небо, проглядывающее сквозь обнаженные ветви, гадая, успеет ли добраться домой до того, как хлынет дождь. В том, что ливню суждено быть девушка даже не сомневалась. 

Веки тяжелели. Держать глаза открытыми с каждым мигом становилась всё труднее. Нора бы так и уснула посреди пустующего дворика, если бы не мелодичный голос, внезапно вырвавший её из небытия. Поначалу девушка сочла, что он ей пригрезился: слишком уж окрыляющими были слова.

> *Ах, я вспоминаю ясно, был тогда декабрь ненастный,*
> *И он каждой вспышки красной тень скользила на ковер.*
> *Ждал я дня из мрачной дали, тщетно ждал, чтоб книги дали*
> *Облегченье от печали по утраченной Линор,*
> *По Святой, что там, в Эдеме, ангелы зовут Линор, –*
> *Безыменной здесь с тех пор.*[^106]

[^106]:  Строки из стихотворения Эдгара Алана По «Ворон».

Нора сладко улыбнулась и, – она ни с чем не могла перепутать этот голос, пускай и слышала его всего во второй раз – приоткрыв глаза, взволновано огляделась по сторонам. Голос тем временем продолжал.  

> *Обезумевший, уставший, ждал я утра, дня, иль ночи *
> *– в поисках бродил что мочи,*
> *Содрогаясь от волненья, по утраченной Линор…*[^107]

[^107]:  Попытки говорившего продолжить вышеупомянутое стихотворения. Вполне успешные, как по мне.

– А теперь вот, кажется, нашёл! – весело добавил голос, пронизанный пленительным вампирским акцентом.

## 71 {-#71}

С рассветом того же дня Молния в задумчивости мерил шагами пространство собственной кухни, периодически заглядывая в спальню, чтобы бросить встревоженный взгляд на стоявшую у постели фотографию. 

Он жаждал беседы с Норой. Понял это ещё тем декабрьским утром, увидев бредущую промеж могил девушку. Случайную встречу на кладбище едва ли принято считать удачным поводом для свидания, но мужчина в первое же мгновенье осознал, всей душой почувствовал, что должен был с ней заговорить. 

Но он не заговорил. Таким уж был Молния: какие бы чувства и переживания не таились в его душе, мужчина всегда погребал их под тоннами других, куда менее волнующих дел.

Сделал Кровавую Мери, но так к ней и не притронулся. От одной мысли об алкоголе начинало мутить. Молния вернулся в спальню и, обхватив голову руками, присел на край кровати. 

Страх и надежда бурлили в нём, не позволяя сосредоточиться. Мужчина перевёл взгляд на снимок – фотографию смеющихся влюбленных, запечатлевшую его последние любовные отношения, которые уже года два как прекратили своё существование. За это время он отрастил волосы, побывал в одиннадцати странах, написал семь песен и трижды представал перед судом за подозрение в хранении марихуаны, но так и не понял, почему однажды остался без неё, в безмолвном одиночестве. 

Боль утраты никуда не делась, а если и затихала на время, то лишь для того, чтобы ударить с новой силой. Его сердце не было просто разбито, оно разбивалось каждый раз, когда Молния вспоминал свою единственную истинную любовь. Мысли о счастье, которое однажды обрушилось на него с такой неожиданностью, теперь делались крайне болезненными, как, в общем-то, и все мысли касательно того, что было. Худшую боль приносили разве что думы о том, что могло бы быть, но так никогда и не произойдет.

Боль, печаль, тоска, уныние – существует много слов, относящихся к субъекту повествования, но ни одно из них не способно в точности описать агонию разбитого сердца, особенно если это состояние годами не сдает своих позиций. Молния оказался однолюбом и в полной мере прочувствовал своё одиночество, осознав, что так и не встретит человека, для которого смог бы приоткрыть ржавые створки собственной души. Было в этом и нечто положительное – никакой новой боли.

А затем он встретил Нору. Увидел её, отворив дверь затхлого наркопритона, и новая волна чувств охватила мужчину в самый неподходящий момент: всего минутой ранее он собирался ширнуться. Впервые за свои неполные тридцать.

Страх предстоящего разочарования (а он был убежден, что именно такое завершение обретут любые попытки стать счастливым) смешался с предательским душевным трепетом, когда Молния вновь увидел Элеонору. Последний, кажется, победил, потому как мужчина, который и раньше в равной степени верил и в судьбу, и в глубину собственных чувств, просто не мог поверить, что подобные совпадения случайны.

«Вот бы кто из знакомых умер… – с печальной ухмылкой подумал Молния. – Тогда я смог бы наведаться к Агате и встретить *её*, раз уж судьба вдруг решила быть ко мне благосклонна… Встреча непременно бы состоялась.»

Он рассмеялся то ли глупости, то ли наивности собственных суждений. Вновь взглянул на фотографию и поспешно убрал её в дальний ящик комода.


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Время протекало мучительно медленно. Где-то за хмурыми облаками пряталось полуденное солнце. Накинув поверх махрового халата пальто, Молния таки взял в руки свой коктейль.

Квартира, в которой он жил, находилась на последнем этаже и располагала мансардными окнами, занимавшими большую часть потолка спальни, которая, кстати, была единственной, но весьма просторной комнатой. В моменты обострения одиночества, мужчине казалось, что в доме даже слишком много места для него одного.

Молния относился к тому типа людей, которые курят исключительно на балконе. Зимой эта привычка была особенно неудобной: балкон в его квартирке не был застеклен. Мужчина подкурил и облокотился о перила, чувствуя как первые капли дождя касаются привыкшей к теплу кожи.

Нет, он определенно искал встречи с Элеонорой.

Однако, процесс этот не был долгим. Сама того не ведая, девушка нашла его первой. 


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Нашей героине никогда не нравилось её имя. Полная форма, считала она, ещё ничего, но вот сокращения звучали ужасно в своей простоте, но девушка всегда была слишком вежливой, чтобы требовать от окружающих обращения к себе по полному имени, опасаясь, что такой шаг будет расценен как высокомерие. Говоря об этом, общение с хозяйкой похоронного бюро приносило Норе облегчение: та вообще редко обращалась к ней по имени, но, если и делала это, то называла подругу исключительно Элеонорой, хотя девушка не помнила, чтобы хоть раз упоминала о раздражении, которое испытывала, слыша краткую форму своего имени.

– … содрогаясь от волненья по утраченной Линор… А теперь вот, кажется, нашёл!

Нора с трудом, но определила источник звука и, обернувшись, вновь запрокинула голову. На последнем этаже соседнего дома, пуская дымовые кольца, ей улыбался Молния. 

Она знала лишь одну Линор и то не была знакома с ней лично.

– Это разве не о мёртвой девушке? – спросила Нора, чувствуя что, сама не зная от чего, вот-вот зальется краской.

– О ней самой. Но лишь первое четверостишье. 

Вдали громыхнуло. Секундой позже девушка вздрогнула, ощутив на лице несколько ледяных капель. Одна из них повисла на кончике носа и никак не хотела убираться прочь. Нора поспешно смахнула её рукавом своей шубки. Заметив это, Молния тоже махнул рукой.

– Поднимайся, – улыбнулся он девушке. – Если в твоих планах на сегодня, конечно, не числится сон под проливным дождем.

Нора улыбнулась в ответ. 

Такого в её планах не было.    

## 72 {-#72}

За окнами похоронного бюро уже битый час бушевала гроза, что лишь усилилась с наступлением темноты. Владелица «Маятника» провела в блаженном забытьи около восемнадцати часов. Проснулась она вечером, – часам к десяти –  тем самым практически возобновив свой привычный распорядок дня. Точное время своего пробуждения Агата назвать не могла: она опомнилась, стоя на кухне за приготовлением чашки крепкого чая. Как поднялась и прошла на сюда девушка не помнила.

Владислав сидел за столом, нарезая ингредиенты для какого-то салата с курицей. За всё время он не проронил ни слова, только периодически одаривал подругу укоризненными взглядами, до которых последней, откровенно говоря, не было особого дела.

– Ты видел, как я поднялась? – нарушила тишину Агата.

Ласло отрицательно качнул головой.

– Видел, как ты спала, когда спускался к обеду.

– В гостиной?

Он кивнул.

– А потом?

– Потом обедал.

Эта фраза прозвучала без единой нотки цинизма, так что Агата не сразу поняла, злиться ей, или смеяться, но слишком усердно пыталась в этом разобраться, так что боль в висках начала предостерегающе пульсировать. Девушка прикрыла глаза и перефразировала свой вопрос.

– Что я делала, когда ты увидел меня в следующий раз?

– Спускался по своей лестнице, – не отрываясь от готовки, ответил Владислав, (тут стоит заметить, что своими он называл все скрытые тоннели, ходы и лестницы) – потому что услышал шаги в холе. Увидел, как ты выходишь из комнат.

– Из своих апартаментов? 

– Нет. Из закрытых.

Агата открыла глаза и вдумчиво оглядела комнату, в которой находилась. Она по-прежнему чувствовала себя слегка потерянной, но чай понемногу начинал окунать её в реальность, возвращая чувство времени. Солнцезащитные очки девушка сдвинула на лоб и теперь раздумывала, а не надеть ли их снова.

– А где Элеонора? – вдруг вспомнила Агата.

Владислав пожал плечами.

– Не видел её с прошлого вечера.

Опустившись за стол, Агата закусила губу. Происходящее нравилось ей все меньше и меньше.

– Тревожишься? – спросил Владислав. 

Это был первый вопрос, заданный молодым человеком за прошедшие двое, а то и трое суток. Девушка подняла голову и встретилась взглядом с глазами друга, но те не сказали ровным счетом ничего нового – в глазах Ласло уже давно царила спокойная атмосфера обреченности.

– Зима подходит к концу, – объяснила Агата.

Ее собеседник скорбно кивнул.

– Знаю, – он подвинул к ней тарелку. – Вот, поешь салатик.

## 73 {-#73}

Несмотря на недавно охватившее её спокойствие, Элеонору вновь увлекли тревожные видения, стоило ей лишь провалиться в глубокий сон. Молния развалился рядом, периодически поглаживая обнаженные плечи девушки. Та лежала к нему спиной и к тому же частенько ворочалась, так что, обнимая Нору, мужчина видел лишь часть её лишенного косметики личика, но выражение лица возлюбленной ему совсем не нравилось.    

– Мне приятно находиться рядом с тобой, – сонно произнесла Элеонора, когда страсть обоих поутихла и, расслабившись, девушка отдыхала на плече Молнии. – Так… спокойно.

Молния знал, что она имеет в виду, пускай и не мог выразить свои чувства словами. Вместо этого он впервые за долгое время изменил старой привычке и задымил прямо в постели.

Его также охватило спокойствие. Надежда, думал мужчина, вот что в итоге причиняет душевную боль. Как бы хорошо ты не знал жизнь, сколько бы раз не разбивали твоё сердце, стоит только подумать, допустить саму мысль о том, что можешь обрести счастливое будущее с другим человеком – и вот ты попал. Остальным займётся твоё подсознание. Именно это Молния и сделал, впервые увидев Элеонору.

Девушка ещё не успела переступить порог его квартиры, а Молния уже загадочно улыбался, разглядывая её кричаще красные глаза.

– Я думал, травка для Агаты, – заметил он, заставив Нору смутиться. 

Она, вроде как, не рассказывала стрёмных историй, в отличии от своей сожительницы, но, тем не менее, всю ночь смеялась чужим лошадиным хохотом, за что теперь и испытывала понятную неловкость.

Однако неловкости этой наши герои лишились с той же скоростью, с какой часом позже лишились одежды. 


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>


Заложив руку за голову, Молния лежал на широкой кровати посреди комнаты, единственным источником света в которой был прикроватный ночник. Возвышающееся над ним мансардное окно покрылось миллионами дождевых капель, сквозь которые не проглядывалось ничего, кроме зияющей темноты. Мужчина затушил сигарету в вышеупомянутом стакане с Кровавой Мери, так что теперь она стала ещё и никотиновой, и осторожно оторвался от подушки, стараясь не потревожить свою Линор. 

Скрипнула кровать. Девушка простонала что-то во сне, но не проснулась. Молния сполз со своего места и на носочках направился в дальний угол комнаты, где, как он помнил, остались его штаны. Тишину нарушила трель звонящего телефона. Мужчина подскочил от неожиданности.

Нора открыла глаза как раз вовремя, дабы в самом разгаре застать его за прогулкой с голой задницей.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Тело мужчины покрывали «цветы молнии», – бордовые следы ветвящихся электрических зарядов, что образуются под воздействием высокого напряжения – в медицине называемые фигурами Лихтенберга. Тонкие полосы иголок шли вдоль спины Молнии, устилая его широкие плечи.

У неё уже имелась прекрасная возможность вблизи ознакомиться с отметинами своего… Нора не была уверена, что может называть его своим молодым человеком. Так или иначе, она села на кровати и, прикрывшись одеялом, разглядывала следы на теле Молнии, пока тот, по-прежнему обнаженный, замер с трубкой у уха, объясняя какому-то новоиспеченному джанки, что больше не занимается транспортировкой некого Виктора Палыча.

– Нет, Гертруды тоже нет, – настаивал Молния. – Говорю же тебе, кроме пыли только джараш и диски, – он замолчал, вероятно, случая реплику собеседника. – Звони, если хочешь, но уверен, у него одна солома.

Мужчина выслушал ещё какую-то, по всей видимости, не особо лестную фразу, после чего отключился и устало потёр лоб. Он виновато взглянул на возлюбленную.

– Прости, – произнес Молния. – Не стоило тебе это слышать. У нас на Леннона припрятана упаковка ампул, а у торчков вроде этого просто нюх на такие вещи, – и он поспешно добавил, как бы оправдываясь: – Но я не кололся. Ни разу. Драг на крайний случай.

Нора удивленно взглянула на собеседника, забыв о том, что держит одеяло, так что то выскользнуло из руки девушки, обнажив её левую грудь.

Молния улыбнулся.

– Не бери в голову, – произнес он, приложив немалые усилия воли к тому, чтобы не отводить взгляд от глаз Элеоноры, и прежде, чем та успела что либо возразить, спросил:   – Ты голодна? 

После недолгих раздумий девушка кивнула.

– Мне нужно отлучиться минут на десять, максимум пятнадцать, – он уже натягивал штаны. – Только передам несколько кораблей старому клиенту, а потом сможем выбраться в город, если хочешь.

Прогулки под дождём – вполне себе романтичная вещь, но только не под проливным и не в феврале, когда на улице минус. К тому же, города Норе на сегодня хватило с лихвой.

– Давай просто закажем пиццу, – ответила она.

Мужчина улыбнулся.

– Две.

Он надел рубашку и, вернувшись к кровати, склонился, чтобы поцеловать девушку. Та поцеловала его в ответ, и Молния заключил Элеонору в крепких объятьях. Затем, не выпуская её ладоней из своих рук, мужчина слегка отстранился и мечтательно взглянул на девушку.

– О чём ты думаешь? – спросила она.

– Тебе не понравится, – тут же отозвался Молния.

Нора нахмурилась.

– Скажи мне, и мы узнаем наверняка.

На лице Молнии скользнула меланхолическая улыбка. Он произнес фразу, от которой наша героиня на мгновенье усомнилась в своей трезвости.

– Я думаю, что люблю тебя, – сказал Молния.

Вопрос о молодом человеке отпал как-то сам по себе.

## 74 {-#74}

В «Маятник» Нора вернулась лишь следующим утром. Прогуливаясь среди могил, девушка боялась, что вот-вот позабудет об уважении к усопшим и пустится в пляс прямиком на кладбище – так она была счастлива.

Молния сказал, что любит её. Нора поняла, что он собирается сказать ещё до того, как мужчина открыл рот, – всё и так просматривалось в его глазах – хотя до последней минуты не верила в то, что подобный исход событий имеет место быть в её жизни. Девушка думала, что сможет ответить Молнии тем же, но не смогла: времени прошло слишком мало.

Вороны кружили над крестовидным памятником, крикливо сражаясь за лучшие места. Тем утром их склока, сопровождаемая шумом дождя, казалась девушке самой сладкой песней на всём белом свете.

Свернув за угол, наша героиня увидела хозяйку «Маятника», глядящую в окно со сложенными на груди руками, и про себя отметила, что подруга, умышленно, или нет, но определенно вернула себе траурный вид. За спиной Агаты стоял худощавый молодой человек с невероятно бледной кожей и светлыми волосами. Лишь одно короткое мгновенье девушке удалось созерцать Владислава. Тот поспешно отступил назад и исчез в темноте похоронного бюро.

Элеонора приветственно махнула подруге. Та не ответила. Она тоже отступила вглубь комнаты и принялась спускаться по лестнице, судя по передвижениям темного пятна, мелькающего в окнах.

Когда раскрасневшаяся от холода и любви Нора закрыла за собой дверь, Агата уже стояла у края ведущей в спальни лестницы. Её лицо не выражало никаких эмоций.

Нора же почувствовала иглы ноющей боли где-то в лицевых мышцах и поняла, что уже долгое время улыбается во все зубы.           

– Где ты была? – спросила дама в чёрном низким, пугающе загробным голосом.

Девушка взвесила все «за» и «против» в течении каких-то пары секунд, а затем, так и не покидая холл, изложила события, случившиеся с ней за последние сутки, опустив, разве что, подробности полового акта.

Соблюдая каменное лицо, Агата слушала молча.

– … и единственное, что меня смутило, – рассказывала Нора, – так это его поспешное откровение. Я имею в виду, ну кто признается в любви во второй день знакомства, понимаешь? Пожалуй, я верю в то, что он и впрямь это чувствует, но, всё равно, это как-то дико.

Закончив свой местами даже слишком трогательный монолог, Элеонора в ожидании взглянула на подругу, чьё лицо в его застывшей невыразительности едва ли внушало воодушевление: прежде девушка видела такие лица лишь у клиентов похоронного бюро и то до того, как над ними поработал Владислав.

– Скажешь что-нибудь? – поникшим голосом произнесла Нора.

Девушка полагала, что её подруга была слишком демократична, дабы осуждать случившееся и, вероятно, слишком похуистична, чтобы в полной мере понять ту палитру чувств, что она теперь испытывала, так что Нора не надеялась на бурную, а уж тем более радостную реакцию, но ей, всё же, хотелось услышать хоть какое-нибудь подобие комментариев. 

– Сколько раз вы занимались сексом? – безучастно спросила Агата.

Таким тоном обычно говорили о погоде, или до чёртиков наскучившей песне, что в который раз транслируется по радио. 

– Четыре, – краснея, ответила Нора.

– А сколько раз говорили? Всерьёз, об отношениях, например. 

Нора удивленно подняла брови. Одновременно с этим действием в стенах здания раздался глухой удар, с помощью которого Ласло обычно оповещал других обитателей «Маятника».о своём недовольстве 

– Каких отношениях, Агата? Мы знакомы-то третий день.

Владелица «Маятника» пропустила это мимо ушей.

– Значит, не говорили?

Девушка покачала головой.

Агата кивнула, словно ждала именно такого ответа. Развернувшись, она начала молча подниматься по ступеням и вскоре исчезла из поля зрения подруги. 

## 75 {-#75}

Сменив мокрую одежду на пижаму, Элеонора выплыла из сладостных грез о Молнии и вспомнила, что до сих пор злится на то ли грубость, то ли дерзость своей подруги. Филантропия филантропией, но такое явное безразличие выглядело чересчур по-хамски, даже для Агаты, особенно после душевного рассказа и – главное – описания собственных чувств, которыми для Норы было и без того непросто с кем-либо поделиться… 

Короче говоря, девушка решила, что заварит себе зеленого чаю, а уж потом непременно разберется с этим дерьмом. 

Однако, долго ждать не пришлось: закинув ногу на ногу, Агата и так сидела на кухне, только пила она совсем не чай.

– Выкладывай, – с порога потребовала Нора.

Хозяйка похоронного бюро вопросительно подняла бровь, но особого интереса к диалогу не проявила. С зажатой в зубах сигаретой, она бездумно водила пальцем по ободку винного бокала.

Позабыв о чае, Элеонора опустилась за стол и теперь сидела напротив Агаты, чувствуя нарастающее раздражение в сторону поведения последней. 

– Мать твою, Агата! – впервые за долгое время Нора повысила голос, пытаясь привлечь внимание подруги. – Ты странно себя ведёшь! Объясни мне, наконец, что, чёрт возьми, вообще здесь происходит? 

Ответа не последовало.

– Почему ты ведёшь себя так странно? – настаивала Нора. – И почему у тебя лицо как у жертвы инфаркта.

– Ты заблуждаешься, – вдруг произнесла дамочка в чёрном. – Однажды я перенесла инфаркт и, тебе придется поверить мне на слово, но в тот момент у меня было совершенно другое лицо.

Элеонора помолчала, обдумывая услышанное. 

– Выкладывай, – повторила она, на этот раз с большим спокойствием. – Почему ты себя так ведёшь?

– Зима близится к концу, – Агата нервно затянулась сигаретным дымом. – Только тебе это мало о чём скажет, не так ли?

Девушка смерила так-себе-собеседницу подозрительным взглядом.

– Ах… – улыбаясь, протянула Нора. – Как же я сразу не догадалась: ты снова курила свою дурь? 

Лицо Агаты оставалось серьёзным.

– Я курю только по четвергам, – напомнила она. 

Затушив сигарету, Агата в один заход осушила бокал и поднялась со своего места. 

– Подумай о том, что я тебе сказала, – бросила она, выходя из кухни.


<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>


Нора так и сделала. Ей понадобилось секунды четыре, дабы обдумать и окончательно осознать полнейшую нелепость услышанного, а также придти к выводу о том, что подобный ответ её совсем не устраивает.

Смачно выругавшись, наша героиня подскочила из-за стола, намереваясь догнать вторую девушку, но надобность в этом сразу же отпала: Агата вновь ожидала её, стоя у края ступеней. Причем выглядела так, словно зависает здесь уже не первый час, а вот разогнавшейся Норе пришлось резко притормозить, чтобы не столкнуть подругу с лестницы и самой, вдобавок, не полететь следом.

– Всё в порядке? – поинтересовалась Агата, глядя на запыхавшуюся девушку.

Нору такой вопрос чуть более чем просто высадил.

– У меня такое чувство, что не всё… – переведя дыхание, ответила Элеонора. – Причём уже не первый день. 

– Так?

– Тебя давно что-то тревожит, но ты, почему-то, не горишь желанием посвящать меня в причины своего поведения. И вот сейчас, когда я практически счастлива, ты поверх всего ещё умудряешься игнорировать…

Где-то за зеркальными стеклами Агата в нетерпении закатила глаза. Нора это учуяла: когда начинаешь узнавать человека, тебе не обязательно видеть всю картину, чтобы понять, что он именно делает в момент речи. Так в темноте можно увидеть улыбку друга – услышать по изменившимся ноткам знакомого голоса, или, в случае с Агатой, понять, что та закатывает глаза, благодаря слегка вытянувшемуся лицу и, скажем, по приоткрытым губам, громко выдыхающим воздух. 

Заметив нетерпение хозяйки «Маятника», которое уже в конец переполняло и её саму, Нора решила перейти к сути дела.

– С Молнией? – спросила она. – Между вам что-то было… Ты поэтому за меня не рада?

Агата изумленно приоткрыла рот.

– О, дорогуша… – начала она и тут же печально рассмеялась.  

Словно аккомпанируя раскатам грома, а стенах похоронного бюро раздался стук, от которого Агата тут же отмахнулась.

– Пойдем, – позвала она и вскоре исчезла в темноте, увлекая Элеонору за собой.

В закрытые апартаменты. 

## 76 {-#76}

По мере их приближения к единственной в «Маятнике» запертой двери, стук в стенах нарастал, превращаясь в настоящий гул.

– Да уйми ты свою истерию! – гневно крикнула Агата. – Хуже уже не будет!

Ответив на это заявление ещё парочкой глухих постукиваний, Владислав в итоге затих. Довольствуясь тишиной, Агата окунула руку в карман, чтобы извлечь на свет немалых размеров ключ. Старомодный, с витиеватым кованым наконечником, предмет этот походил на те, что обычно фигурируют в сказках, только был довольно ржавым и не смог отпереть дверь с должной скоростью, что тут же обламывало всё волшебство. 

Со второй попытки замок-таки поддался и, толкнув преклонного вида дверь, владелица «Маятника» жестом пригласила подругу внутрь. 

Щелкнул выключатель. В первую очередь, Элеонора увидела, что перед ней не комнаты, а одно сплошное помещение, являвшее собой небывалых размеров спальню. Во-вторых, окружающая её обстановка оказалась завораживающей и ввиду своей изысканности могла бы послужить достойными декорациями к фильму о Дракуле. Гробов, конечно, не было, но ведь они находились всего двумя этажами ниже.

Норе понадобилось какое-то время, чтобы осмотреться и справиться с восхищением, а заодно и настойчивым желанием сделать как можно больше снимков окружающих её предметов.

– Что же ты сразу не сказала, что у тебя есть люкс? – весело спросила девушка.

От этих слов выражение лица Агаты обрело своё привычное ироническое спокойствие. Дамочка подошла к резному гардеробу и, замешкавшись лишь на мгновенье, отворила обе дверцы.

– В этой комнате я храню воспоминания, – произнесла Агата, разглядывая что-то, лежащее в шкафу. Плавным жестом руки она поманила подругу к себе. – Подойди и взгляни. 

Одолеваемая любопытством Элеонора была уже на половине пути, когда увидела, на что смотрит Агата. Заинтересованность на лице девушки сменилась удивлением, за которым последовал истинный шок, приправленный едва уловимой ноткой понимания. На одной из полок, среди стопок картонных ящиков, виднелись три портрета. Они не были идентичными, как не бывает идентичной подпись, но, неизменно повторяя друг друга, определенно носили одно авторство. Каждая из картин была улучшенным вариантом предыдущей, – результатом мастерства набитой руки – и вместе с тем негласной копией новогоднего подарка Агате – портрета, который уже второй месяц весел в гостиной второго этажа.

Девушка открыла рот, но так и не смогла ничего сказать. Встретившись с изумлением в её взгляде, Агата поняла, что ждать дальше бессмысленно.

– Ты уже в четвёртый раз приходишь в «Маятник» и каждый раз являешься с первым снегом, – вздохнув, произнесла Агата. – Я не давала объявления о сдаче комнат с октября две тысячи двенадцатого, но ты всё равно приходишь в опозданием на час, показываешь мне ту старую заметку и говоришь, что ожидала увидеть памятники вместо могил, а я отвечаю, что в сущности это одно и то же, потому как обычно людям не возводят памятники при жизни.


