---
output:
  html_document: default
  word_document: default
  pdf_document: default
  epub_document: default
---

# Часть III. Переломный Момент {-#chapter-3}

<div align=right>

*…и темнота вокруг нее шумела, *

*словно прибой сумрачного моря.*

*--- Эрих Мария Ремарк*

</div>

## 77 {-#77}

Молния ударила в окна пустующих апартаментов, словно желая усилить и без того гнетущий драматизм наступившего момента. Над похоронным бюро послышались мощные раскаты грома, укрепляющую атмосферу обречённости, что теперь царила в душе Элеоноры.  

К счастью, электрическое снабжение пока не спешило покидать «Маятник», и, пытаясь придти в себя, Нора пристально разглядывала окружающую её обстановку. Агата не торопила подругу с вынесением каких бы то ни было умозаключений, за что последняя была весьма благодарна.

– Войдя сюда, я ко многому была готова, – после длительного молчания выдохнула Нора. – Ожидала, что ты покажешь мне один из своих стеклянных гробов, или ещё что-нибудь в таком роде.

Она слабо улыбнулась и, завидев выражение лица так-себе-собеседницы, поспешно добавила:

– Только не говори, что я уже выдавала тебе эту шутку, когда…

– Трижды.

Тщётно силясь справиться с безысходностью во взгляде, девушка запустила руку в волосы, чувствуя, что на глаза вот-вот навернутся слёзы. Первая мысль, посетившая голову Норы, казалась ей до ужаса нелепой, но вместе с тем пугающе возможной. В итоге, наша героиня отважилась озвучить собственные опасения.

– Я что…

– Нет, – прервала её Агата. – Ты не умерла.

Услышав это, Нора издала вздох облегчения и даже сумела выдавить из себя некое подобие улыбки, но следом в её голову пришла ещё одна, едва ли воодушевляющая мысль.  

– Ты знаешь всё, что я скажу? – печально спросила девушка.

– Не всё, – тут же ответила Агата, заставив Нору склоняться к тому, что и этот вопрос не был для её подруги неожиданным. 

Углубившись в размышления, Элеонора приуныла ещё сильнее. Заметив это, Агата молча взяла девушку под руку и усадила на огромных размеров ложе.

– Ты не призрак, – повторила Агата, опускаясь рядом. – Мы вместе проверяли твои документы. С возрастом вышла небольшая несостыковка, но в целом всё в порядке, – заверила она.

– Несостыковка? 

Агата помедлила.

– С каждым годом говорить это становится всё труднее, – заметила она, – но тебе уже далеко не двадцать.

Элеонора ошарашено моргнула, и ощутила, как по разгоряченному от волнения лицу скатилась одинокая слеза. Девушка не знала, смеяться ей, или плакать, – дурной знак – но старательно подавляла в себе оба этих импульса. 

– Сколько же мне на самом деле? – боязно поинтересовалась Нора, то ли от волнения, то ли в поисках морщин исследуя пальцами свою шею.

– Расслабься, – наблюдая за ней, ухмыльнулась Агата. – Всего лишь двадцать четыре.

– А тебе сколько?

– Двадцать пять.

Нора собралась с мыслями, пытаясь переварить полученную информацию. С таким же успехом она могла бы выкурить вчерашнюю траву и отбить чечётку, ни разу при этом не рассмеявшись.

– Ты ведёшь себя старше, – решила Нора, – а выглядишь моложе. Иногда это сбивает с толку.

Агата согласно кивнула.

– В прошлом месяце мне не продали сигареты, когда я отказалась снимать очки, – вспомнила она.

– А почему ты отказалась?

Владелица похоронного бюро вздохнула и издала протяжный стон, который её подруга идентифицировала как выражение усталости, смешанное с явным нежеланием касаться темы таинственных очков.

– Вернемся к этому позже, – пообещала Агата. – Когда решим твою проблему.

– Ты говоришь это каждый раз? – догадалась Нора. – Только моя проблема никак не решается…

– Ну, если честно, да, – впервые (по крайней мере, за то время, которое помнила Элеонора) Агата улыбнулась как нормальный человек, показывая ровные зубы. – И получается, что я вроде как не лгу.

– И всё же?

– Давай для начала справимся с одной историей, – вновь вздохнула Агата. – В моей же нет ничего таинственного. Ничего такого, чего не следовало бы ожидать. Я не вампир, – при этих словах её губы скривились в саркастической ухмылке, – просто немного странная. Поверь, ты отнюдь не удивишься, получив ответ на свой вопрос. 

И Нора поверила. За неимением других вариантов.

## 78 {-#78}

Владислав заскучал, подслушивая диалог наших героинь. Растянувшись на полу одного из своих тоннелей, он лениво разглядывал потолок, жалея, что не прихватил с собой книгу, или хотя бы чашку чая.

Говорить с Норой – даже после того, как девушка узнала часть правды – ему не хотелось: как и хозяйка бюро ритуальных услуг, Ласло тщательно подбирал круг общения и болезненно переживал уход близких.

А девушка, в растерянности сидящая всего в нескольких метрах от него, всегда уходила. Она исчезала с наступлением весны, покидая «Маятник», друзей… и не только. Теперь она могла уйти, так и не попрощавшись с Молнией, и для последнего это вылилось бы жутким ударом, тогда как мужчина едва ли оправился от предыдущего. Конечно, он не знал о недуге возлюбленной, но проблема, как раз таки, и заключалась в том, что никто до конца не мог понять, что происходит с Элеонорой. 

Сделать это был под силу только самой девушке.

– Я какая-то ненормальная? – тем временем с горестью вопрошала Нора. – Сумасшедшая, бежавшая из психушки? Скажи мне, если это так! Я должна знать, – и она притихла в ожидании. 

– Не думаю, что ты сумасшедшая в традиционном понимании этого слова, – успокаивающим тоном ответила Агата. – Правда в том, что, так или иначе, все мы здесь душевно травмированы обществом, только сказывается это по-разному. Ласло ведёт затворнический образ жизни, я же, как ты могла заметить, одержима смертью, не желанием, а значением, идеей самой смерти, ну а ты… – она замолчала, подбирая слова. – Ты вынуждена снова и снова переживать один и тот же фрагмент.

– То письмо, – вдруг вспомнила девушка. – Это ведь я его написала?

– Боюсь, что так.

– Но почему я этого не помню?

Знатно отлежав спину, Владислав поднялся на ноги, от нечего делать, прислонился к стене и, отодвинув затвор, теперь наблюдал за девушками через пустые глазницы портрета неизвестного музыканта. 

– Вероятно, у тебя случаются моменты просветления, – говорила Агата; в знак поддержки она держала подругу за руку, – которые, вместе с тем, можно назвать и моментами помутнения.

Элеонора слушала её, периодически вытирая струящиеся по щекам слёзы.

– Как-то ты поинтересовалась, сколько человек нужно, чтобы нести гроб, – продолжала дамочка в чёрном. – Ума не приложу, зачем тебе потребовались такие знания, но, услышав ответ, ты начала вести себя странно. 

– Насколько странно? 

– Что ж, весьма странно: подвисла на долю секунды, а потом на лице отразился испуг и ты вдруг разрыдалась, выкрикивая несвязные фразы. Ты размахивала руками и повторяла, что «они идут», как обычно делают сумасшедшие в фильмах… – она запнулась. – Чёрт, прости за такое сравнение, я не нарочно. 

Улыбнувшись, Нора отмахнулась и попросила продолжить рассказ, лишь сильнее сжав руку своей собеседницы.

– Мне кажется, тут как с гипнозом. Существуют какие-то слова, или ключевые фразы, что напоминают тебе о пережитом. Из-за них на тебя резко обрушивается груз прошлого, но затем сознание вновь блокирует все нежелательные мысли. В тот раз ты уснула. Отключилась прямо на кухне, а с наступлением утра уже ничего не помнила.

Нора по-детски всхлипнула.

«Это было бы мило, если бы не было так печально», – отметил про себя Владислав. 

– Вот почему меня так напугало твоё последнее письмо, – продолжала Агата. – К тому же, есть ещё кое-что.

– Да? – горестно отозвалась Нора.

– Твой дом. Его больше нет.

Девушка на мгновенье забыла о том, что плачет, и с недоверием взглянула на подругу.

– Хочешь сказать, он продан? – предположила Элеонора.

– Не совсем так, но об этом тебе предстоит узнать не от меня.

Поднявшись со своего места, Агата направилась к шкафу, – тому самому, где хранились художественные творения её подруги – и вернулась с небольшой записной книжкой, покрытой тонким слоем пыли.

– Порой ты успокаивалась и успевала кое-что записать, – произнесла хозяйка «Маятника», протягивая блокнот Элеоноре. – Прочти это и найдешь ответы на многие из возникших вопросов.

Девушка повертела в руках книгу, чувствуя вполне объяснимый страх перед содержащимся в ней текстом.

– Так сколько нужно людей для того, чтобы нести гроб? – напомнила Нора, стараясь разрядить обстановку.

– Шесть, – ответила Агата. – Иногда восемь, если покойный был чрезмерно склонен к полноте, ну, и ещё один, чтобы придерживать дверь, – она ухмыльнулась, – так что, мне кажется, девять.

## 79 {-#79}

– Что это там у тебя? – поинтересовалась Элеонора.

Она застала Агату в гостиной. Та без особых эмоций перебирала утренние письма, о чём, собственно, так и сказала.

– Есть что-нибудь для меня?

– Одно, – Агата протянула подруге алый конверт. – Должно быть, очередное любовное послание от Молнии.

– Да будет тебе, – улыбнулась девушка.

– Не будет. Я узнаю его почерк. 

Краснеющая Нора прижала к груди заветное письмо и в предвкушении грядущего чтения осмотрела журнальный столик Агаты, на котором виднелся ещё без малого десяток писем.

– А остальные?

– Ну, половина – это коммунальные счета, – не отрываясь от дела, ответила Агата. – Кое-что – ответы с аукциона и галереи. Я там картины заказываю. Ещё одно от поставщиков гробов. А это, – она потрясла в воздухе небольшим конвертиком, – неугомонные предложения товарища Овсянникова.

– Что ещё за товарищ Овсянников? – спросила Нора.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Товарищ Овсянников был пухлым человеком среднего возраста, чей и без того невеликий рост подрезал радикулит, так что вышеупомянутая личность едва ли доставала до хрупкого плеча нашей траурной героини. Носил он исключительно лакированные туфли и парадно-выходной костюм, оставшийся, казалось, ещё со времен Екатерины II. Всё это, в совокупности со щедро сдобренными гелем волосами, коих было не так уж много, и болезненно жёлтым цветом лица придавали товарищу Овсянникову вид покойника, внезапно решившего прогуляться комнатами похоронного бюро.

Именно таким Элеонора нашла товарища Овсянникова, когда одним из последующих вечеров тот покидал кабинет Агаты. Представлялся, кстати, этот человек только как товарищ Овсянников. Подписывался также, а потому имени-отчества его уже давно никто не помнил.

– Боевая, однако-с! – говоря сам с собой, произнес товарищ Овсянников, а завидев в холле Элеонору, соизволил объясниться. – Живым велела не возвращаться.

– Это очень кстати, – заметила девушка, дивуясь внезапно появившемуся красноречию. – В этом месяце у нас мало клиентов.

Так вот, товарищ Овсянников показал себя личностью прагматичной и крайне настойчивой, а предложения его и впрямь были неугомонными. Мужчина писал каждый месяц, (иногда сразу по несколько писем) а также под конец каждого сезона являлся в «Маятник», желая как бы лично засвидетельствовать выраженные намерения. 

История эта длилась уже третий год.  

Несмотря на откровенно странное поведение, предложение товарища Овсянникова не несло в себе ничего романтического. Он не просил ни руки, ни сердца Агаты, ни других составляющих супового набора. Желание пухлого человечка имели чисто деловой характер: он хотел купить «Маятник». Товарищ Овсянников спал и видел как заполучает землю, на которой возвышалось бюро ритуальных услуг. Он работал агентом по недвижимости, но в один прекрасный вечер переквалифицировался в похоронных дел курьера. 

Это случилось, когда один из его престарелых клиентов изъявил желание быть погребенным именно на том месте, где уже не одну сотню лет располагалось крыльцо «Маятника». По известным одному господу богу причинам старик хотел возвести свой посмертный мемориал аккурат на этом куске кладбищенской земли и, не имея наследников, был готов выложить за свой внезапный каприз целое состояние, пятнадцать процентов которого обещались товарищу Овсянникову, если тот сумеет всё устроить.

И вот погребальный агент забрасывал Агату настойчивыми предложениями, каждый раз извергая всё больше аргументов и увеличивая обещанный гонорар. Сумму он обещал большую.

– Насколько большую? – уточнила Нора.

– Неприлично большую, – безразлично ответила Агата. 

## 80 {-#80}

Наступившим утром двери похоронного бюро оставались открытыми для проведения очередной прощальной церемонии, а это значило, что события последующего часа в стенах «Маятника» будут происходить по старому сценарию: тоскливая музыка, плачущие над усопшим люди и Агата, прикуривающая около проигрывателя. Тогда-то Элеонора и поинтересовалась, кому принадлежали пустующие апартаменты.    

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Над городом сгустились поздние сумерки, что, однако, практически не сказывалось на погоде. Последний день лета подходил к концу, и когда остатки солнечного света коралловыми лучами проглядывались сквозь стены Старого города, температура воздуха превышала тридцать пять градусов. 

Ввиду подвального расположения, в баре было заметно прохладней. Здесь работали до последнего клиента, и стоявшая за стойкой девушка довольно наблюдала толпу, стремительно заполняющую зал, в душе надеясь, что закроет бар не ранее чётырех утра: в тому времени за стенами должно стать хоть немного прохладней. Она ненавидела лето сколько себя помнила – просто физически не могла находиться в духоте, в этих краях неизменно сопутствующей жаркую пору года.      

Щегловатого вида официантик, пыхтя, взгромоздил на стойку новый поднос с посудой, которую девушка тут же принялась расставлять по местам. Она делала это автоматически, мыслями находясь где-то в просторах Исландии и изредка бросая взгляд на пьющую публику, чтобы прикинуть, когда ждать следующих заказов.    

Пили в основном водку и пиво. Её раздражало и даже слегка задевало, что из всех возможных вариантов люди предпочитали столь банальные вещи, да ещё и в чистом виде. Если не считать молчаливого иностранца, который каждый вечер заходил сюда, чтобы пропустить несколько стаканчиков бренди-колы, за смену девушка продала от силы тринадцать коктейлей, семь из которых были Лонг-Айлендами.

Кто-то попросил убавить холод кондишина, но барменша сделала вид, что не расслышала это непристойное предложение.

Без пяти одиннадцать (она знала это наверняка потому, что по возможности отлучалась покурить в завершении каждого часа) в зал спустился молодой человек в круглых солнцезащитных очках. Он тут же направился к барной стойке, и девушка раздосадовано швырнула сигаретную пачку обратно в ящик.

Вошедший был не на много выше самой девушки, густые каштановые волосы небрежно ложились на плечи, а бровь украшала стальная штанга; вдобавок к очкам на нём были красные джинсы и рубаха, надетая поверх рваной футболки, ну, и, конечно же, борода – подобная картина превращала молодого человека в представителя андерграундного поколения прошлого века.

Он умостился за стойкой и барменша, вопреки упорным просьбам начальства, всегда игнорирующая приветствия, вопросительно подняла бровь.

– Плесни мне Джека, детка, – голос был мягким.

– Ты часом не рок-н-ролльщик конца семидесятых? – спросила девушка, на этот раз недовольно вскидывая обе брови.

– Не совсем…

– Тогда не стоит звать меня деткой, чувак.

– Я тебе не чувак, – обиженно отозвался молодой человек.

Барменша приоткрыла рот, но тут же закрыла его, вспомнив, где находится. Она наполнила стакан льдом и потянулась за виски.   

– И колу в стекле.

Девушка кивнула.

– Можно мне пепельницу? – вновь напомнил о себе клиент.

– У нас не курят, – отрезала барменша.

Возвратившись с перекура, она увидела, как посетитель растерянно вертит в руках свои очки. Глаза его, хоть и были покрасневшими, чертовски напомнили девушке её собственные. Заметив приближение барменши, молодой человек поспешно водрузил предмет на место.

Его стакан пустовал.

– Повторить? – спросила девушка и, не дожидаясь ответа, потянулась за бутылкой: вид молодого человека говорил о том, что это будет далеко не последний бокал за сегодняшний вечер.

Гость кивнул.

Подрагивающая рука, красные глаза, подведенные красноречивыми синяками, и скользящая улыбка, то и дело сменявшаяся растерянностью – всё это было ей знакомо.

– Переборщил с дурью? – спросила барменша, протягивая собеседнику новую порцию виски. – Хлебни крепкого чаю, это должно…

– Мой отец умер, – вдруг произнес молодой человек.       

Девушка молча протянула ему пепельницу.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

– Снял бы ты очки, – заметила барменша тремя часами позже, когда подливающий себе колы мужчина в очередной раз промахнулся мимо стакана. – У нас и без того слабое освещение.

Адам, так его звали, и оказался тем самым последним клиентом. Между тем, вскоре предстояло выяснить, что он вообще оказался тем самым. 

– Не хочу, чтобы кто-то это видел, – ответил молодой человек, указывая на свои глаза. – Никто не должен видеть твою боль, понимаешь? Лучше уж сойти за торчка.

– Здесь никого нет.

Адам удивленно обернулся, разглядывая тёмный зал. Помещение пустовало: официанты, на пару с работниками кухни, покинули его более часа назад. Тусклый свет озарял лишь барную стойку.

– Не уверен в том, что я чувствую, – произнес Адам; речь его была поразительно чёткой как для человека, опустошившего с дюжину бокалов. –  Сегодня я возвращался с кладбища и видел парней с лопатами. Думаю, они шли закапывать отца. И они говорили о том, что сейчас идет в кино. Один из них смеялся, делясь впечатлениями от просмотра «Ученика чародея»… когда шёл закапывать моего отца, ты понимаешь? 

Девушка кивнула. Она приготовила себе выпить и закурила, опустившись напротив собеседника. Тот снял очки, и барменша вновь поразилась заметному сходству.  

– Это было дико, но вместе с тем так естественно, – продолжал Адам. – Я хочу сказать, они ведь даже не знали его. Жизнь продолжается – так все говорят. На улицах сновали толпы. Все куда-то спешили. А я ждал трамвай и надеялся, что он никогда не приедет, потому как мне некуда идти. И эта музыка… Весёлые песни о радостях и летней любви, звучащие отовсюду – меня они просто сводили с ума. А затем я увидел как солнце исчезает за небосводом. Небо окрасилось пастельными тонами, как на той картине Ван Гога, с оранжевой рощей, и я подумал, что происходящее мне только снится. Это был самый прекрасный закат, какой я только видел, но ведь подобной красоте просто не место в такой день, рядом со смертью… И эта чёртова музыка! Думаешь, это когда-нибудь прекратится?

– Думаю, музыка никогда не перестанет играть, – сказала девушка, которая спустя месяц стала обладательницей похоронного бюро.

## 81 {-#81}

До встречи с Адамом Агата и представить не могла, как много способно почувствовать человеческое сердце. Жизнь нашей героини сложилась далеко не счастливо, но в свои девятнадцать она не была особенно грустной, как, в общем-то, и радостной. Ей было просто… нормально.

Не нужно быть экспертом в любовных делах, дабы понять, как больно бывает, однажды поднявшись на небеса, свалиться обратно. Прямиком на дно. Но прежде, чем мы дойдем до этого…

Первой вещью, поразившей девушку, стало удивительное состояние душевного спокойствия. Позже, когда с улиц Львова сошел последний снег, Агата перечитывала письма, которые писала своей дальней подруге в те счастливые дни, но больше не узнавала себя. Откровенно говоря, она с трудом верила мысли о том, что в принципе могла быть *такой*.

> *Этой ночью я практически не спала, волнение было столь сильным, что у меня (впервые в жизни!) тряслись коленки. Однако, утром меня охватило странное спокойствие и сейчас, сидя за этим письмом, я всё так же спокойна.*

> *Знаешь, что я люблю больше всего? Наши разговоры. Когда мы добираемся, скажем, до магазина, но так и продолжаем сидеть в машине – просто не можем наговориться. Адам рассказывает о вещах, которые, кажется, всё эти время таились на самой поверхности моего подсознания. Невозможно описать, что я при этом чувствую. Серьёзно! Это так чудесно – понимать, что рядом сидит человек, который знает содержимое твоей головы лучше тебя самой, просто знать, что ты больше не одна во Вселенной.*

> *Однако, как ни странно, он ничего не говорил, когда я поняла это. Однажды Адам вернулся в «Маятник», промокший от вечернего дождя, он вошёл в спальню, взглянул на меня этими карими глазами, которые я люблю больше всего на свете, и молча поднес с губам мою руку. Никогда бы не подумала, что такой шаблонный жест сделается столь трогательным и дорогим моему сердцу. В этот самый момент я в полной мере осознала собственные чувства. Думаю, это всегда будет моим самым счастливым воспоминанием. *   

> *Это далеко не всё, что меня поражает. Естественно, я помню твой скептицизм в данном вопросе, но, чёрт возьми! В сентябре я начала работать над картиной, о которой не рассказывала даже тебе. Она странная. Я имею в виду, странная для меня, потому что так не похожа на то, что я обычно пишу. Да, ты и сама сейчас это поймешь. В общем, мною задумывалось изображение открытого космоса; в центре просторы Вселенной пересекал горизонтальный луч лилового цвета, на котором виднелись крохотные домики пастельных цветов. Такие, знаешь, из 50-х. И все это на фоне невозможно близко расположившейся Луны.*

> *Как это всегда бывает, финальный образ тут же засел в моей голове, но на самом деле до завершения работы было ещё далеко. Более того, в день, о котором я говорю, не было даже черновика. Только изображение в моей голове, о котором я непрестанно думала. Так вот, следующим утром Адам рассказал мне свой сон. Ты догадываешься, к чему я клоню? Он детально описал всё то, что я только собиралась нарисовать. Все аспекты картины, включая цвета и их оттенки.*

## 82 {-#82}

> *Только что осознала, что, зайдя в вагон, почувствовала, что вернулась домой. Все поезда для меня одинаковы и в каждом я ощущаю себя дома. Подумать только, сколько эмоций я пережила за эти годы, находясь в дороге. У меня так много воспоминаний, но я знаю одно: я никогда ещё не была так спокойна и счастлива как сейчас.*

> *В моем городе невыносимый холод и совершенно отсутствует золотая осень, чего не скажешь о местах, которые видны из окна. Слева замерзшее поле, а по правую сторону раскинулся лес, он невероятно прекрасен. Кое-где мелькают небольшие домики – это то, о чём я мечтаю, милая. Все эти осенние цвета, я так влюблена в них, приятный холод и шуршание листьев… *

> *Вся моя жизнь прошла бы осенью, будь это возможно.* 

> *Я почему-то вспомнила Джоуэла и Клементину[^108]. Ту сцене в осеннем лесу. Снова-таки, впервые в жизни, я чувствую, что  встретила того самого и это изменило меня, сделала той, кем мне всегда стоило бы быть. *

[^108]: Главные персонажи романтической драмы «Вечное сияние чистого разума», режиссера Мишеля Гондри.

> *Подумываю сделать себе кофе и закурить. Последнее, правда, вряд ли возможно, кажется, курение в поездах запретили окончательно, хотя когда меня это, собственно, останавливало?*

> *В моих наушниках любимая музыка и я думаю о тебе, о нашей дружбе и о том, что, наконец, увижу тебя, ведь ты мой самый близкий друг и я безумно тебя люблю, не забывай об этом.*

> *Конечно, я к тому же думаю о своем мужчине, но, для твоей же пользы, не стану вдаваться в подробности касательно моих мыслей, тебе ли не знать, какой я похотливый романтик?*

> *Только что выяснила, что курить в поезде уже совсем нельзя, очень жаль, ведь, зная свою удачу, я обещала Адаму не сходить на перрон до конечной остановки. Увидев мой трагический взгляд, проводник дала мне вафель. Чёрт возьми, я перечитала предыдущее предложение и просто не могу остановить смех! Шикарно! Я даже не буду его убирать. Надеюсь, ты улыбнешься, прочитав «Увидев мой трагический взгляд, проводник дала мне вафель» – хорошее предложение. Такое можно диктовать деткам в школе, как пример сложноподчиненного, чертовски смешно.*

> *Знаю, тебе сложно в это поверить, но я ни разу не чувствовала того, что чувствую сейчас, ни к чему и ни к кому. И это чудесно.*

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

> *Ох, я, всё же, не удержалась и пару часов назад вышла прогуляться. Удивительное место, названия которого я не запомнила. Станция находится прямиком около леса. Восхитительная осенняя погода: свежий ветер, нежаркое солнце, а вокруг – сплошная осень. Сейчас я проезжаю места, подобные тому, но погода здесь уже не так дружелюбна. Представляю, что ждет меня дома, но главное ведь, кто ждет меня там, правда?*

> *B вагоне шумно, а я так устала, чувствую себя жутко вымотанной, это и не удивительно.  К слову, я дочитала  последнюю книгу Кристи, которая у меня была. Думаю, перейду к Ф. К. Дику – никогда не могла оценить его по общепризнанному достоинству. Почитаю с часик в наушниках и постараюсь уснуть.*

> *Зря я не взяла те таблетки.*

> *И всё же, меня весьма удивляет, что я совсем не волнуюсь, думаю, я начну переживать в самый  последний момент, хотя  я знаю, всё в порядке, всё в абсолютном полном порядке.*

> *Переключаю своё внимание на «Доктора Бладмани, или как мы стали жить после бомбы». Не стану окончательно с тобой прощаться, думаю, я ещё напишу  пару строк, прежде чем  вручить тебе это письмо. К тому же, мы с тобой совсем скоро встретимся.*

> *Подумать только… В общем, ты и сама знаешь.* 

> *И это делает меня счастливой.*

<div align=right>

> *С любовью,*

> *Агата*

</div>

Вышеуказанному спокойствию понадобилось менее трёх месяцев, дабы вместе с Адамом навсегда исчезнуть из жизни нашей героини. Осень закончилась, и Агате казалось, что и сама её жизнь подошла к концу.

Было непросто поверить, что девушка, писавшая столь воодушевляющие строки и та, что читала их следующей весной, допивая n-ный бокал вина, являлись одним и тем же лицом.

«Я ведь даже имя свое теперь полностью не пишу» – мысленно отметила Агата, и откупорила следующую бутылку.  

Осень закончилась, и её сознание напрочь пропиталось грустными британскими песнями.

## 83 {-#83}

– Агата? – взволнованно позвала Нора, возвращая подругу в «здесь и сейчас».

– Элеонора? – медленно отозвалась Агата.

– Отойди в сторону! Гроб же несут!

Владелица похоронного бюро, временно позабывшая о собственных обязанностях, подняла голову, и увидела с полсотни пар глаз, что удивленно уставились на неё, на мгновенье откинув пелену скорби. С особенным колоритом из толпы выделялись нетерпеливые лица носильщиков. 

– Соболезную вашей утрате, – глухо произнесла Агата, обращаясь к заплаканной женщине, что стояла ближе остальных. – Красивое платье. 

Она кивнула толпе и вышла в холл. 

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

– Там от силы десять листов, – заметила Нора, с надеждой взглянув на подругу. – Быть может, мне удастся это обойти?

Содержимое записной книжки по-прежнему вселяло в девушку ужас, пугая своей неизвестностью. Её не покидало гнетущее ощущение неминуемой беды. Нора понятия не имела, что скрывается на этих злополучных страницах. 

По всей видимости, она не раз возвращалась к собственным тайнам, переживать которые приходилось снова и снова. И пускай она не могла вспомнить случившегося, на каком-то уровне Элеонора помнила о душевной боли, следующей за проникновением в эти самые тайны. 

– Не выйдет. Для того чтоб вернуться к жизни, нужно принять её, ясно осознать прошлое, и только тогда идти дальше, – заметила владелица «Маятника». – Иначе, встретимся следующей зимой.

– А что, если я не смогу принять прошлое?

– Хуже уже не будет, – Агата пожала плечами.



Это было за месяц до того, как она решила затянуть петлю вокруг шеи.

## 84 {-#84}

Времени оставалось всего ничего.

Радости это, как можно догадаться, обескураженной Элеоноре не добавляло, да ещё и Агата не менее двух раз в день атаковала её своими «Ну что, ты прочла?», делая это с безразличной настойчивостью, свойственной исключительно молодым авторам, вручившим друзьям драгоценную рукопись.

Гонимая попытками подбодрить себя, Нора выбралась в город. Она собиралась наведаться к Геку, дабы выпить горячего шоколада и, возможно, послушать какой-нибудь новый (а так ли это?) отрывок его приключений. Девушка также пыталась вытащить в свет Агату, но та упорно пустила корни, ссылаясь на предстоящую встречу с клиентами и подготовку к тем своим странным курсам.

Агата то ли не смогла, то ли не захотела рассказывать подруге о том, кто являлся единственным (за годы, что она провела здесь) обладателем закрытых апартаментов. Вместо этого хозяйка «Маятника» снабдила Нору стопкой мятых писем и ретировалась в свой кабинет ещё до того, как девушка успела прочесть хотя бы строчку.

Для Норы же чтение писем началось бессонной ночью и закончилось проливными слезами – слишком уж она была чуткой.

– Это и есть Адам? – поинтересовалась Нора, указывая на одну из фотографий, висевших над письменным столом, в дальней комнате «Ретроспективы».

Гек, который уже вовсю хлопотал над излюбленным напитком, прервался и заинтересованно взглянул на девушку.

– О-о-о, – протянул малец. – Так вона тобі нарешті розповіла?[^109]

[^109]:  Так она тебе, наконец, рассказала? 

Элеонора водила взглядом по снимкам.

– Да, – ответила девушка. – И мне хотелось бы знать, в который раз?

– Што в который раз? – переспросил Гек, чьё чересчур изумленное выражение лица выдавало тот факт, что он отлично понял суть вопроса.

– Я все помню, Гек, – мягко улыбнулась Элеонора. – Точнее, я ничегошеньки не помню, но меня тут просветили, что я довольно частый гость в «Маятнике».

Малец нервно проглотил стоявший в горле ком.

– Ну так? – напомнила о себе девушка.

Гек решил, что претворяться дурачком бесполезно.

– Она рассказала тебе это впервой, – возвращаясь к приготовлению шоколада, ответил мальчик. – Мои поздравления. Такой себе левел-ап.[^110]

[^110]: Level-up (англ.) – повышение уровня. 

Нора расхохоталась.

– А я знала, что ты говоришь по-русски?

– Не-е-е, – Гек ухмыльнулся, довольный собой. – Это чисто для праздничных нагод[^111].

[^111]: Нагода (укр.) – случай.

Лицо Норы вытянулось в непонимании.

– Что *на год*? 

Теперь пришла очередь Гека смеяться.

– Та, в смысле случаев, – сквозь хохот ответил малец, наблюдая недоумение собеседницы.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Нора с удовольствием выслушала ещё один отрывок о путешествии Гека, после чего мальчик традиционно поинтересовался ее мнением.

– Увлекательно, а главное – каждый раз как новый, – с печальной улыбкой ответила девушка.

Время было позднее, за покрытыми изморозью окнами царил бешенный холод – последняя попытка зимы продлить собственное существование. Улицы пустовали, так что тем вечером Элеонора стала единственным в «Ретроспективе» покупателем. 

Вернее, могла бы стать, но малец отказался от денег, и настойчиво выпроводил нашу героиню прежде, чем та успела оспорить его решение.

Прогуливаясь магазинчиком, Нора вспомнила о пишущей машинке, которую присмотрела во время первого визита в «Ретроспективу». С того дня прошло значительное количество времени, но волею судьбы предмет оказался на месте. Чёрный с позолотой корпус, утонченные кругляши клавиш – живя в двадцать первом веке, девушка осознавала непрактичность своего выбора, но просто влюбилась в эту вещицу.

– Щитай это подарком к прошедшим праздникам, – прокомментировал свой жест Гек.

Элеонора была вовсе не против. Под Новый год у неё бывали и более неожиданные подарки, например, полный пакет ритуальных услуг от Агаты, а также предварительная бронь места на кладбище.

«Только выбери сама, какое больше понравится» – предложила тогда Агата.

Относительно же машинки у Норы были большие планы. Она оказалась красивой, думала девушка, такие, должно быть, были у Ремарка и Хема. К тому же, ей непременно захочется провести за печатью какое-то время, так всегда бывает с полюбившимися вещами, а это должно поспособствовать творчеству.

Радуясь внезапному приобретению, Элеонора вернулась в «Маятник».

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

На самом деле, ей хотелось вовсе не этого, ведь, несмотря на сложившуюся ситуацию, мысли девушки в основном занимал Молния. Пока Норе удавалось избегать встреч с возлюбленным, ссылаясь на вымышленную простуду, которую она, якобы, подхватила следующим после их ночи утром, но, как и страсть, болезнь не может длиться вечно. Вскоре они увидятся, и тогда Молния непременно затронет тему отношений, задаст вопросы, ответов на которые Элеонора не знала. 

Волны тепла окутывали сердце нашей героини, когда она думала о нём. Этим вечером Норе не хотелось торчать в «Маятнике», не хотелось копаться в пугающем прошлом. Единственным искренним желанием Элеоноры оказалась жажда новых встреч с возлюбленным. Не терпелось вновь пережить те самые волнительные чувства, ощутить эмоции, которые, по всей видимости, настигали её уже не в первый раз. Она знала, где именно сейчас желает оказаться, но вместе с тем, понимала, что нельзя пускать всё на самотек. Девушка всей душой стремилась к Молнии, но не могла признаться ему в собственном безумии. 

Более того, сама она всё ещё не была в силах это осознать.    

Как бы там ни было, вспоминать прошедшие месяцы для Норы было сродни повторному просмотру фильма с неожиданной развязкой, когда большая часть предшествующих финалу событий кажется странной в своей монотонности, а затем – БАЦ! – ты начинаешь по-новому понимать действия и диалоги ключевых персонажей, и всё невещественное становится вдруг существенным. 

Элеонора вздохнула. Она вновь подумала о Молнии, – мальчике с глазами из самого синего льда[^112] – водрузила на колени пишущую машинку, подле которой уложила свою старую тетрадь.

[^112]: Аллюзия на песню Сплин «Выхода нет».

До наступления весны оставалось менее трёх часов, когда девушка взялась за чтение.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Читать собственные записи оказалось непросто. Местами даже слишком сложно: почерк её тянулся вверх, или вниз, а кое-где просто прыгал, меняя размер и наклон, но наибольшую трудность являл, конечно же, сам текст. Норе не единожды приходилось его перечитывать, подолгу задерживаться на одной и той же странице в попытках вместить в голове увиденное.

Откровенно говоря, девушка ожидала от себя совершенно другой реакции. Думала, что будет плакать, может быть, даже истерически кричать, да с такой силой, что в её спальню ворвутся встревоженные обитатели «Маятника»…

Но Нора молчала.

Её сковал ступор, и девушка просто механически перечитывала содержимое тетради.

В какой-то момент, правда, Нора всё же тихонько вскрикнула, прикрывая рот рукой. Её зрачки расширились, как это бывает при выбросе окситоцина, или контакте с психотропными веществами, и девушка резко подскочила с кровати, заставив ни в чём не повинную машинку свалиться на пол. Та перевернулась, открывая Норе вкладыш, приклеенный к обратной стороне. На бумажке был перечень имен – вероятно, бывших владельцев вещицы. 

Что ж, наша героиня едва ли изумилась, увидев последним в списке собственное имя.  

Пару дней назад Элеонора всё-таки не выдержала и ответила на бесконечные просьбы возлюбленного о встрече. Это был прекрасный вечер: счастливые, они укутались в наушники и слонялись по ярмаркам, раздражая окружающих своим влюбленным видом, а позже, вернувшись в спальню мужчины, Нора заметила небольшое изменение в обстановке – на прикроватном столике появилась фотография, запечатлевшая её саму, смеющуюся в объятьях Молнии.

Снимок момента, о котором Нора ничегошеньки не помнила. Тогда-то она и поняла, что с дальнейшим развитием отношений стоит повременить до лучших, более светлых для её памяти времен.

## 85 {-#85}

Группка усталых мужчин самоотверженно долбила застывшую землю, периодически прерываясь на перекур. До полудня оставались считанные секунды, а яма была готова лишь наполовину.

К бюро ритуальных услуг уже начинали подтягиваться люди.

– Бесполезно! – крикнул один из могильщиков, с яростью отшвыривая своё орудие. – Мы всё равно не успеем!

Лопата ударилась о замерзшую почву, издавая звенящий стук.

– Підітри шмарклі[^113], – усмехаясь, ответил второй могильщик. 

[^113]: Утри сопли.

Он был слишком стар, чтобы кидаться лопатами, но тоже остановился и облокотился о многострадальный инструмент.

– Не зверху ж його ховати[^114]. 

[^114]: Не поверх же его хоронить.

Третий мужчина ничего не сказал: он предпочитал нытью усердную работу и, к тому же, был немым.

Могильщики продолжили старое доброе дело, которому сегодняшняя погода никак не желала способствовать.

Шел первый день марта.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Стоя у окна в холле третьего этажа, Агата с тоской наблюдала обстановку внизу: траурная процессия уже заполняла крыльцо «Маятника», неся с собой букеты цветов и убогие венки, которые дамочка терпеть не могла, а вот могила ещё явно не была готова. Обычно копателей было четверо, – Евгений, Борис, Леонид и Яков – но Лёня подхватил какой-то вирус, а эти трое явно не справлялись с работой.

Евгений – первоклассный нытик – бросил лопату и закурил, в четвертый раз за минувший час, так что лишь с помощью неземного усилия воли Агата смогла подавить в себе настойчивое желание запустить в идиота одной из пустых винных бутылок, которые с вечера так никто и не убрал.

Двое могильщиков, вероятно, будут работать ещё медленнее, думала Агата. Придется потерпеть. 

Поначалу она намеревалась провести церемонию по стандартному расписанию, но положение вещей изменилось, и прощанье с усопшим пришлось продлить. В поисках чего-нибудь воистину трогательного, Агата мысленно перебирала названия музыкальных исполнителей пока, наконец, не остановилась на…

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Бон Ивер сделал своё дело. 

Содрогающая стены толпа горожан ревела не один час, оглушая своим плачем Владислава, удручая Элеонору и раздражая Агату, и успешно продолжала бы реветь дальше, если бы владелица похоронного бюро не свернула лавочку. 

Могильщики, в конце концов, покончили с работой, и вскоре шестеро галантно разодетых мужчин по команде Агаты подняли гроб и медленно зашагали к выходу. Люди, казалось, вовсе не собирались прерывать своих рыданий, но, всё же, были вынуждены потянуться за покойником.

– Подбери что-нибудь динамичное, – попросила Агата, когда помещение опустело. Она обвела рукой церемониальный раз. – Без метёлки тут явно не обойтись.

И она отправилась в кладовую – прощанье оказалось слишком плаксивым, так что пол был усыпан использованными бумажными салфетками, пластиковыми стаканчиками, в которых раньше были успокаивающие пилюли, и прочими признаками истерии.

Покопавшись среди пластинок, Элеонора сделала свой выбор и спустя мгновенье в стенах «Маятника» Фаллон спрашивал, какую же песню сыграют, когда мы умрем?

## 86 {-#86}

Небеса затянуло серым цветом. Витражи похоронного бюро мерно целовал ледяной дождь. Стояла последняя суббота ноября и в «Маятнике» впервые проводили прощальную церемонию с наступлением сумерек.

Зал переполняли скорбные лица, а воздух был пропитан запахом роз. Никто не перешептывался, не рвался произносить речь, казалось, люди были слишком поражены случившимся, и только Фаллон продолжал задавать свои бесконечные вопросы. 

<div align=center>

*Well, I wonder which song they’re gonna play when we go.*

*I hope it’s something quiet and minor and peaceful and slow.*

*When we float out into the ether, into the Everlasting Arms…*[^115]

</div>

[^115]: Текст песни «The 59’ Sound» группы The Gaslight Anthem: (англ.) что ж, мне интересно, какую песню сыграют, когда мы умрём? Надеюсь, это что-то тихое, грустное, спокойное и медленное. Когда мы выходим в эфир, в Вечные Объятья…

Пластинка вращалась без остановки. Песня уже в который раз начиналась с начала, но едва ли кто-нибудь обратил на это внимание. Агата стояла у самого проигрывателя, разглядывая пластинку, но не решалась её сменить – руки девушки непрерывно дрожали как, собственно, и она сама.

Слёзы уже вторые сутки бесшумно струились по лицу нашей героини, и вокруг её зрачков начинала проступать кровавая сетка лопнувших сосудов. Агата плакала без звука, как в старых фильмах. Дела и при желании не могли бы обстоять иначе: девушка потеряла голос. Она открывала рот, шевелила губами, но слова застревали в горле. Где-то в глубине сознания скользнула мысль о том, что такое бывает при резких душевных травмах, и при хорошем лечении голос может вернуться, но сейчас это отнюдь не имело никакого значения.

Церемонией руководил брат покойного, так что, Агата просто стояла у выхода, периодически переводя застывший взгляд с пластинки на лицо усопшего.

«При жизни он не был таким… Бледным…» – пронеслось в голове Агаты. – «Это как-то… Неправильно…Ласло должен был… Больше тона…»

Она осознала, что мыслит отрывочно. 

<div align=center>

*And I wonder were you scared when the metal hit the glass?*

*See I was playing a show down the road*

*When your spirit left your body.*[^116]

</div>

[^116]: И мне интересно: ты испугался, когда металл ударил по стеклу? Видишь ли, я разыгрывал шоу на дороге, когда дух покидал твоё тело.

Тоскливые лица участников толпы сделались для девушки одинаковыми. Они сливались с чёрными одеждами и, подобно пластинке, начинали вращаться по кругу, стоило Агате поднять голову. Причиной этому вряд ли была одна лишь пелена слёз, устлавшая ее глаза.

И только образ покойного оставался чётким. 

…хотя, Агата допускала вероятность того, что на самом деле видит его исключительно в своей голове. Тем вечером владелица «Маятника» поняла, что внутри неё что-то оборвалось. Прежде она воспринимала слова о разбитом сердце как красивые метафоры, но в этот самый миг, в одиночестве стоя у разрывающегося проигрывателя, Агата в полной мере чувствовала давящую боль под ребрами – буквально ощущала тяжесть зияющей в груди дыры и знала, что вне зависимости от того, как в дальнейшем сложится её жизнь, она, Агата, уже никогда не будет прежней. 

<div align=center>

*Young boys, young girls,*

*Young boys, young girls,*

*Young boys, young girls,*

*Young boys, young girls,*[^117]

</div>

[^117]: Юноши и девушки…

Она знала, что боль не отступит.

Так и произошло.

<div align=center>

*Ain’t supposed to die on a Saturday night,*

*Ain’t supposed to die on a Saturday night,*

*Ain’t supposed to die on a Saturday night,*

*Ain’t supposed to die on a Saturday night.*[^118]

</div>

[^118]: … не собирались умирать субботним вечером.

Мотив в сотый раз принялся набирать обороты. Внезапно чёрно-белая толпа в молчании расступилась. Бледные руки подняли гроб, чтобы плавно нести его к выходу и дальше – в сырую землю.

Тогда внутри Агаты вновь что-то оборвалось. А затем ещё раз. И ещ ё. Словно её грудь поразило тонкое лезвие невидимого кинжала. Дышать становилось всё сложнее.

Девушка вздрогнула от неожиданности, почувствовав на своей талии чью-то теплую руку.

– Надень их, – ласково произнес Молния.

Не оборачиваясь, Агата узнала его по голосу. Молния, который сам только что потерял брата, приобнял подругу, с безмолвной скорбью глядя в её истерзанные слезами глаза. Это было очень кстати: девушку затрясло сильнее, и она чувствовала, что вот-вот упадет. 

Тем временем Молния протягивал ей солнцезащитные очки.

«Никто не должен видеть твою боль…» – вспомнила Агата, и новые ручейки слёз оросили её щёки.

Агата Рахманинова надела очки как раз в тот момент, когда мимо неё проносили гроб с преждевременно усопшим.  

*Его очки.* 

## 87 {-#87}

Минуло пять с лишним лет. Держа в руках инструменты для уборки, владелица «Маятника» вновь стояла у входа в церемониальный зал. Комната была пуста, если не считать Элеонору, которая деловито расставляла по местами хаотично разбросанные стулья. Агата с усердием пыталась заставить себя уяснить, что это в действительности так, но больное сознание диктовало ей иную сцену.

Изображения накладывались друг на друга: безлюдная комната и толпа, плывущая за гробом.

Виной всему была музыка.

*«Ain’t supposed to die on a Saturday night!»* – настаивал на своем Фаллен.

В этот момент Агата могла бы поклясться, что уловила в воздухе запах роз, смешавшийся с формалином, хотя последний был здесь вполне ожидаем.

Элеонора не была из тех, кто мог с лёгкостью ощутить чужое присутствие, особенно если то было бесшумным. Она никогда не чьего-либо на спине чужого взгляда, а потому, обернувшись, подпрыгнула от неожиданности – девушка застала подругу за тем самым взором в бесконечность.

– В чем дело? – встревожилась Нора: лицо Агаты сделалось бледнее обычного.

Девушка чуть было не добавила: «Кто-нибудь умер?», но вовремя спохватилась.

Тем временем Агата, казалось, приоткрыла рот, но вместо ответа с её губ сорвался лишь усталый выдох.

– Что стряслось? – на этот раз громче спросила Нора.

Она уже направлялась к подруге.

– Ничего нового, – ровным голосом произнесла Агата. – Всего лишь воспоминания.

Элеонора вопросительно взглянула на хозяйку похоронного бюро.

– Под эту музыку хоронили Адама, – объяснила Агата, вручая девушке метёлку. – А теперь давай разгребем всё это дерьмо. 

## 88 {-#88}

Официально шёл двадцать первый день марта, но истинная весна укрыла город лишь с наступлением следующего месяца, а пока крыльцо похоронного бюро, как и окружающие его надгробия, купалось в белоснежных хлопьях. Несмотря на метель, особого холода не ощущалось, и вороны по обыкновению кружили по дворику, изредка покидая его пределы.

Густой дым струился сразу из нескольких стальных дымоходов. Ввиду своего мрачного вида и громоздкой, слегка зауженной верхушки, издали «Маятник» напоминал траурный орган. Только вместо музыки из его труб лился пар.

Именно об органной мелодии подумал Молния, приближаясь к похоронному бюро. Он едва ли успел осознать эту мысль: ассоциативный ряд вступил в действие и в голове мужчины тут же заиграла старая митлофовская мелодия.[^119] В руках его был утонченный букет фиолетовых лилий, в сердце – любовь и огонь воспламеняющейся надежды.

[^119]:  I’d do anything for love – (с анг. *Я бы сделал все ради любви*) песня Meat Loaf.

За прошедшее время он видел свою Линор не менее дюжины раз. Последние зимние дни насторожили Молнию: казалось, девушка опять спасовала, но прошло какое-то время, и если Нора и впрямь в чём-то сомневалась, то, по всей видимости, разрешила этот вопрос, потому как в дальнейшем вела себя естественно. 

…ну, насколько это вообще возможно, для влюбленных, ещё находящихся на той стадии отношений, когда принято не портить друг при друге воздух и делать вид, что на некоторых участках тела волосы и вовсе никогда не росли. 

Однако, говоря о бюро ритуальных услуг, этот визит стал для Молнии первым за долгое время. Мужчина ударил по дереву увесистой ручкой, тем самым чуть не изувечив собственные пальцы.

Безрезультатно.

Дверь как всегда оказалась открытой: вряд ли кто-то в здравом уме пожелает проникнуть в эту обитель смерти. Ну, а клиентам тут всегда рады.

Внутри также мало что изменилось. Окликнув Агату, мужчина несколько минут провел в холле, прислушиваясь к тишине здания в надежде уловить в ней шаги, голоса, или, быть может, отдаленные звуки музыки, но ничего из этого не последовало…

(Разумеется, живя в веке социальных сетей, он мог просто позвонить Норе, или скинуть парочку сэлфи, выходя из дому, но так уж вышло, что наш герой был любителем сюрпризов.)

… и Молния поднялся в единственную хорошо знакомую ему комнату. 

Впервые за долгое время та оказалось незапертой, но Молния, конечно, не мог этого знать.

## 89 {-#89}

В те дни, повествовал Гек, хоть и стояла холодная весна, погода заметно отличалась от нынешней. Снегопад обратился проливным дождем и дорога, по которой плёлся дрожащий мальчик, представляла собой дряблую кашицу из грязи, небесной воды и талого снега.

Температура вновь поднялась, и пускай в душе нашего персонажа зародился относительный покой, (он наконец-то осел во Львове) Гек изнывал от хорошо знакомого ему недуга. Первое время он ночевал где придётся, пару раз даже снимал комнату в хостеле, а затем начал подрабатывать то тут то там: расклеивал листовки, подметал парадную и разносил газеты. Последней работой стала уборка подземного барчика, где Гек драил полы, переворачивал стулья, чтобы отлепить от них застывшие жвачки, выносил мусор и выполнял прочие пыльные поручения. Платили хорошо, в сравнении с предыдущими вакансиями, и чаще всего мальчику удавалось перекусить бесплатно, но полученные деньги уходили на оплату жилья, (малец арендовал плохо меблированную комнату у одной барыжащей самогоном старушки, которую встретил на вокзале; та не задавала лишних вопросов взамен на молчание мальчика) а он вдруг возьми и сляг с простудой недели на две.

Трудиться в таком состоянии ему не позволяли, особенно в питейном заведении. На бирже труда Гек не состоял ввиду возраста, а акциями не владел ввиду бедности, словом, средства его отнюдь не прибавлялись, так что наступившим утром наш герой очутился на улице.

Не имея багажа и определенных жизненных перспектив, изнуренный тоской и болезнью, он бродил серыми улицами, не зная куда себя деть, пока наконец не остановился у единственного места, которое счел подходящим убежищем – всё  у того же бара. Работа при высокой температуре и впрямь виделась ему малоприятным времяпрепровождением, однако особых вариантов всё равно не было, но ребёнок был рад любой возможности побыть в тепле.

Бар, по всей видимости, не разделял его чувств, потому как дверь была заперта.

«Слишком рано» – с грустью подумал мальчик.

Он всхлипнул и, убедившись, что поблизости никого нет, позволил соплям смешаться со слезами. 

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

К обеду малец намотал ещё несколько кругов, ошиваясь около Старого города, от чего ему стало только хуже. Заручившись поддержкой бешеной усталости, сон приложил все усилия, дабы поймать Гека в свои объятья, но тот понимал, что нельзя просто упасть посреди грязной улицы: он мог замерзнуть насмерть, или того хуже – быть пойманным блюстителями порядка.

Пришлось взять себя в руки. Темнота близилась, а путь до вокзала казался слишком долгим, так что мальчик не придумал ничего лучше кроме как…

Прямиком через улицу от всё ещё закрытого бара находилась антикварная лавка. Посетителей там было немного, а содержимого – как раз наоборот, – Гек не раз прогуливался мимо, разглядывая сквозь витрины сгрудившийся на старой мебели хлам – так что вскоре в мальчишеской голове созрел не больно-то и хитрый план и, дождавшись, пока владелец «Ретроспективы» отправится обедать в дальнюю комнату, Гек пробрался внутрь.

В магазинчике из каждого уголка веяло стариной. Здесь было невероятно уютно, а главное – тепло. Играла музыка, но на входе Гек всё же с ловкостью опытного воришки придержал хрустальные колокольчики, подвешенные над дверью, опасаясь, что те могут выдать его присутствие. Он прокрался в укромный уголок образованный антресолью и парочкой стеллажей, которые оказались напрочь заставлены диковинными вещами, чьи владельцы (а не исключено, что и их дети) уже давно почили в земле. По дороге мальцу встретился целый сундук тряпья, поверх которого лежали пледы ручной работы. Одолжив парочку, он умостился на полу.

Синатра предлагал начинать распускать сплетни, когда Гек благополучно погрузился в сон.[^120]

[^120]: Start spreading the news – первые строки песни Фрэнка Синатры под названием «New York, New York».

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Накануне малец прикончил последний пузырек таблеток, но, очнувшись от глубокого сна, почувствовал улучшение и в кои-то веки нашёл себя отдохнувшим. Он тут же зажал рот рукой, пытаясь скрыть рвущийся наружу кашель, но сделал это слишком поздно.

– Значит, проснулся уже… – донеслось откуда-то из-за стеллажа.

Малец испуганно подскочил…

(стыдясь того, что влез сюда, своего внешнего вида, положения, да и вообще всего, что только может быть на этом свете)

… но запутался в одеялах и плюхнулся обратно на задницу.

– Не мельтеши, – прокомментировал сие действие неизвестный голос.

– Как вы меня нашли? – тихо спросил мальчик, стараясь выиграть время.

Он вспоминал планировку помещения и мысленно уже начинал прокладывать путь к отступлению. Из-за стеллажа, наконец, показался обладатель на удивление спокойного голоса.

– Ты оставил грязные следы – это раз, – с теплой улыбкой ответил Валерий, – не просто кашлял, ревел во сне – это два. К тому же, и это три, я прожил здесь не одно десятилетие, – он указал на перепачканные мальчиком пледы, что валялись на полу. – Ты и впрямь думал, что я не замечу пропажи?

Гек не нашелся с ответом. Вместо этого он предпринял новую попытку подняться.

– Да не мельтеши ты, – мужчина махнул рукой.

При других обстоятельствах Гек едва ли прислушался бы к такому совету, (тогда он совершенно не доверял взрослым) но глаза его собеседника лучились добром и вдобавок ко всему совсем не казались взрослыми, они скорее выдавали мальчика, по каким-то страшным причинам заключенного в теле средних лет мужчины.  

Тем временем хозяин антикварной лавки окинул взглядом незваного гостя.

– Не мельтеши, – в третий раз повторил Валерий. – Я приготовлю тебе горячего шоколада.

## 90 {-#90}

Стрыйский парк Элеонора нашла очаровательным и полагала, что он оставался таковым в любое время года. Место оказалось старое, в правильном понимании этого слова: вековые деревья, широкие заснеженные аллеи, заброшенные тропинки и водоёмы прекрасно гармонировали со всевозможной архитектурой, и Нора с восхищением разглядывала каждый уголок парка.  

Местами, разгуливая укрытыми снегом дебрями, девушка чувствовала себя так, словно оказалась в настоящем лесу. Агата, вероятно, ощущала то же самое: вид у неё, в большинстве своем оставался довольный.

Приятно было, наконец, сменить обстановку. Вместо эдгарпошных птиц мимо наших героев то и дело проносились белки. Одна бесстрашная красотка прыгнула прямиком на плечо мальчика, а затем без малейших противоречий умостилась на его ладони, чтобы отправиться в руки Элеоноры.

– Посунься трошки правіше![^121] – Гек деловито махнул головой.

[^121]: Подвинься немного правее!

– Это обязательно? – отозвалась Агата, но, всё же, послушно подвинулась в сторону Норы.

– Может, хотя бы уберешь сигарету? – предложила та, обхватывая подругу за талию.

– Ну, что за нонсенс! – отозвалась дамочка в чёрном.

Под конец прогулки они поднялись по пешеходной дорожке, на месте которой когда-то протекал ручей. Девушки стояли у края верхней террасы. За их спинами виднелись бесконечные заснеженные просторы.

Нора улыбнулась, и вскоре её инстаграм пополнился ещё одной фотографией. 

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Бюро ритуальных услуг окутывали звуки музыки. Отдаваясь звонким эхом, трогательные и вместе с тем тоскливые ноты заполняли немногочисленные комнаты третьего этажа, неся в себе дивную силу – умение забираться прямо в глубь человеческой души. Музыка нарастала и потухала чтобы стать ещё громче и ударить в самое сердце.

Возвратившись в «Маятник» прямиком из морозного дня, Агата Рахманинова, казалось, сначала почувствовала, а уже затем услышала льющуюся из пустующих апартаментов музыку. Она узнала мелодию с первых секунд. Просто не могла не распознать её. Узнала и вздрогнула, но, к счастью, Элеонора была слишком увлечена шутками Гека, а потому ничего не заметила.

Оба, мальчик и девушка, весело переговариваясь, чистили обувь от налипшего на неё снега, когда Агата устремилась вверх по лестнице, собираясь ни то разрыдаться, ни то отругать Владислава, а, может быть, и всё сразу. Она убавила шаг лишь достигнув своего этажа. Поняла, что Ласло нет дома: он ещё вчера уехал на один из этих своих кулинарных конкурсов.

Приглушенный плотным стеклом свет падал сквозь синие витражи третьего этажа, создавая призрачную иллюзию тумана. Агата пересекла холл и медленно следовала по коридору, с благоговейным страхом глядя на слегка прикрытую дверь.

Сердце девушки обратилось натянутой струной, обещавшей порваться в любую минуту. По мере её приближения музыка становилась все громче. Сомнений не возникало. Это была она – музыка Адама.

– Призраков не существует, – шепотом напомнила себе Агата и тут же добавила с ироничной улыбкой на губах: – К сожалению…

Она вошла в комнату, отказавшись от дальнейших раздумий.

Да, это определенно была музыка Адама, а у изножья широкого ложа сидел сам Адам. Он расположился лицом к проигрывателю и, опустив глаза, в задумчивости разглядывая свои пластинки, так что девушке были видны лишь очертания его профиля. Одет гость был как всегда в чёрное, с высокого лба струились пряди густых волос, что казались светлее в теплом свете лампы, и, думая об этом, Агата не совсем поняла, почему до сих пор не лишилась чувств.

Словно во сне, Агата сделала несколько неуверенных шагов по направлению к мужчине, но тут же остановилась, чувствуя, что затылок её вот-вот поцелует половицы. Владелица «Маятника» громко выдохнула. Адам обернулся, и тогда девушка поняла, кого приняла за покойного возлюбленного.

Прежде она не замечала их сходства.

«Похожи, но не одинаковы, – устало подумала Агата. – Скулы не такие высокие, да и глаза у Адама были карие».

– Я напугал тебя, – с извиняющимся видом произнес Молния.

– Вовсе нет, – машинально соврала дама в чёрном, но лицо говорило за неё.

– Прости, просто воспоминания вдруг нахлынули…

Отнюдь не жаждущая откровенной болтовни Агата вновь предприняла попытку отвертеться.

– Ты отпустил бороду.

Но и Молния не сдавал позиций.

– И волосы, – безразлично добавил он. – Я знаю, что так тебя напугало, ведь я и сам теперь не могу со спокойной душой смотреться в зеркало.

– Всего на одно мгновенье… – начала Агата, но так и не нашла в себе сил окончить фразу.

Они помолчали.

– Это странно, – нарушила тишину Агата.

Молния согласно кивнул.

– Да я и сам никогда не осознавал, как сильно мы похожи, а сейчас…

– Нет, – оборвала его девушка. – Я вдруг поняла, что совсем недавно стала старше него. Это странно, – повторила Агата. – Я имею в виду, любить мёртвых.

В этот момент на лестнице раздались шаги. За ними послышался голос Элеоноры. Та звала подругу по имени.

– Наверное, нашла цветы, – предположил Молния.

– Фиалковые лилии?

– Как всегда, – ответил мужчина, силясь выдавить из себя улыбку.

–  Иди, – произнесла Агата, которая также пыталась улыбнуться.

У обоих вышло не ахти.

## 91 {-#91}

Тем вечером в «Маятнике» собралась уже известная нам компания. Их было лишь пятеро, (Владислав вернулся наступлением темноты) но число это всё же превышало привычное количество ошивающихся в похоронном бюро людей, если, конечно, учитывать только живых.

Какое-то время Гек ещё самоотверженно пытался занять Элеонору своими россказнями, но внимание мечтательной девушки всецело принадлежало возлюбленному. Застенчивая и вместе с тем любвеобильная парочка смотрелась так, словно её составляющие знакомы между собой от силы месяц.

Что ж, в каком-то смысле так оно и было.

Нора стеснялась пить при молодом человеке, зная о том, как быстро хмелеет, а Молния, по всей видимости, также не собирался крутить косяки: едва ли это вообще было им нужно. Геку не наливали ввиду возраста, (хотя разок малец всё же воспользовался тем, что любующимися друг другом голубки не особо-то обращали внимание на происходящее вокруг, и пригубил красного полусладкого) так что всё веселье досталось Агате, которая вряд ли согласилась бы с таким утверждением, потому как большую часть вечера дамочка провела в своем кресле, в молчании потягивая винишко.

Посиделки вышли незапланированными и, что ещё хуже, какими-то консервативными. За все месяцы, которые помнила и не помнила Элеонора, хозяйка похоронного бюро впервые проиграла – буквально слила – партию в шахматы. Норе это совсем не понравилось. Её подруга, конечно, выглядела тем, что называют absent-minded, (а в нашем случае лучше сказать ‘wine-minded’)[^122] но вместе с тем Агата сильнее других не любила проигрывать, делая это гораздо ярче остальных. Дамочка была бомбой замедленного действия, и лучше чем Норе об этом было известно разве что Владиславу. Агата не раз запускала в подругу колодой карт, делая это со всей мировой яростью, и однажды разошлась настолько, что девушка в слезах выбежала из «Маятника», чтобы затем ещё долгое время бродить заснеженными тропинками кладбища в поисках менее бесноватой компании.

[^122]: Игра слов: absent-minded (англ.) – рассеянный. Первое слово созвучно с «absinthe» (абсент), так что, ослышавшись, или не зная правописания высказывания, его можно буквально перевести как «тот, чей ум поглощен абсентом»; wine – вино.  

Так вот, Элеонора с недоверием воззрилась на подругу, ожидая от неё характерных резких движений, взмывающих в воздух шахматных фигур и предвидя картину раскуроченной доски, летящей в бесконечность.

Однако, ничего такого не последовало. Физиономия мастерицы похоронного дела не выражала признаков исступления и вскоре Агата уже расставляла по местам павшие в бою фигурки, предложив гостям сыграть новую партию, но на сей раз без её участия.

«Сама не своя!» – мысленно изумилась Нора, но отсутствие неврастенического припадка подруги безусловно не могло испортить чьего-либо настроения.

Игра продолжалась.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Наступившим утром завтрак между собой разделила лишь часть вышеупомянутой компании – её объятая любовью половина. Гек, который уснул уже после того, как встало солнце, всего на минутку выбрался из своего диванного убежища. Он иронично хрюкнул при виде целующейся на кухне парочки и поспешил вернуться в царство сна, прихватив в собой парочку клубничных круассанов.

Мальчик продолжал спать, когда Молния покинул бюро ритуальных услуг для встречи с очередным клиентом.

Солнце плавно скрывалось за кладбищем. Его лучи ещё держали в своих объятьях каменные надгробия, что уже понемногу лишались снежного покрова. Отдаленно теплый свет укрыл и лицо стоявшей у окна девушки, и Агата сняла очки, желая в полную силу насладиться закатом. В спальне раздавались печально вдохновляющие звуки музыки «Облачного атласа».

Впервые за долгие, мучительные годы её лицо выражало воистину решительное умиротворение. Агата слегка улыбнулась, – и это непременно сделало бы её моложе, если бы не сочные синяки, издавна поселившиеся под глазами – выкурила шуршащую сигарету, запивая её всё тем же вином, вкус которого вдруг сделался (хотя, казалось бы, куда ещё?) лучше.

Солнце совсем село. Вскоре за задернутыми шторами раздалось неуверенное постукивание.

«Дождь пошёл, – мимоходом подумала Агата. – И я пойду».           
Она сделала музыку громче, выкурила ещё одну сигарету, которую также запила вином, поднялась на древнюю бархатную табуретку о трёх ножках, продолжая держать винный бокал, свободной рукой накинула на шею петлю, затянула её, прикрыла глаза и всё с той же легкой улыбкой на лице шагнула в вечность.  

## 92 {-#92}

Наслаждаясь тихой погодой, вечерней чашкой кофе и чарующей музыкой, доносившейся откуда-то сверху, Элеонора сидела над антикварной машинкой, перепечатывая записи из собственного дневника, о котором ещё месяц назад не имела ни малейшего понятия. Она толком не знала, зачем это делает, но в тайне от себя самой всё же надеялась, что в процессе удастся вспомнить ещё какие-нибудь детали, события… Да что угодно!

Настроение у нашей героини было лежательное. Вовсе не хотелось идти куда-нибудь, встречаться с людьми, вступать в диалоги, или, боже упаси, самой вести разговоры. 

Однако, тем не предвещавшим беды вечером Норе всё же предстояла одна неожиданная встреча.

Девушка сладко потянулась и взялась за дело. Хвала небесам, для этого вовсе не было необходимым покидать пределы постели.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

> *С чего мне вообще стоит начать? Я не знаю, но нужно что-нибудь писать. Хер его знает, как долго может продлиться это чёртово озарение… *

> *Лучше бы его и вовсе не было. *

> *Мне не так уж давно исполнился двадцать один год, *

> *(и я собираюсь начинать с этой фразы все последующие записи, если таковым суждено появиться на свет, потому как оказалось, что чаще всего я бываю не в курсе собственного возраста)*

> *Сейчас канун Нового года. Я сижу на кухне Агаты, в «Маятнике». Его хозяйка испуганно носится вокруг меня с коробкой успокоительного. Ещё одна аптечка лежит на столе. В ней сплошные пилюли для шизанутых и неврастеников. Замеченные мной препараты можно разделить на три группы:*



> *Психотропные: аминезин, голопередом, амитриптилин;*

> *Транквилизаторы: феназепам, гидазепам;*

> *Седативные: персен, новопасит, фитосет и целая куча валерьяны.*



> *Все это – лишь часть запасов. Интересно, откуда у Агаты такой широкий выбор? *

> *Седативные оказались совершенно бесполезными. Транки, в отличие от своих предшественников, кое-как заработали. Подавили выброс адреналина, чем, собственно, и привели меня в чувства. Записывая это, я не ощущаю особых эмоций и в холодности своей скорее похожу на Агату. Такое чувство, что мы поменялись местами, ведь она выглядит на удивление взволнованной, даже чувствительной.*

> *Как парадоксально.*

> *Ну вот, как я и думала, подруга тычет мне пластинку амитриптилина. *

> *Я не хочу принимать психотропные. Это слишком. Такое дерьмо даже не продается по рецепту, а выдается исключительно по государственным бланкам розового цвета и подавляет в человеке всё, что только можно подавить. Я-то знаю.  *      

> *Я провела в клинике восемь паршивых месяцев, мысля слогами и ощущая себя как персонаж Николсона после лоботомии.[^123] Такое медицинское вмешательство собьёт с толку любого, не позволит думать, а уж тем более записывать свои думы. Но я должна это сделать. Должна, если не хочу придти сюда одним декабрьским утром в теле дряхлой старухи, которая думает, что ей всё ещё двадцать и ровным счетом ничего не помнит.*

[^123]: Имеется в виду Рэндл Макмёрфи – один из героев романа Кена Кизи под названием «Пролетая над гнездом кукушки»,  в одноименной экранизации которого основную роль исполнил Джек Николсон.

> *Так что, нахер психотропные! Пора признать это. Я схожу с ума.*

> *Я СХОЖУ С УМА.*

> *Как там говорилось: «Схожу с ума, иль восхожу к высокой степени безумства».*[^124]

[^124]: Цитата из стихотворения Беллы Ахмадулиной «Прощание».

> *Удивительно, (ох, если бы только я могла сейчас удивляться) когда я сняла комнату в «Маятнике» всё шло к тому, что моя домовладелица не дружит с головой, а оказалось, что это я.*

> *Я тронутая.*

> *Ещё вчера я унывала из-за того, что я самая обычная и мне не о чем писать книги, а теперь этот вопрос вдруг отпал сам собой. Разве самые обычные девушки проводят по три сезона в психиатрической лечебнице, чтобы затем вернуться в свой старый дом и не помнить об этом? Не помнить вообще о том, что уже были здесь?*

> *Сомневаюсь.*

> *Новость о том, что однажды я уже зимовала в «Маятнике» в более спокойное для своей психики время, стала воистину ошеломительной, но сегодня я узнала не только это. Сегодня я узнала о так званых первопричинах, приведших меня в объятья безумия.*

> *Впервые я появилась на ступенях похоронного дома в конце ноября позапрошлого года. Тем днем первый снег выпал раньше обычного. Я была предельно счастлива, с тремя чемоданами тряпья, желанием обустроиться и отсутствием видимых горестей.* 

> *Незадолго до этого я рассталась с молодым человеком, имени которого упоминать не стоит. Отношения между нами были не иначе как странными. Они продлились четыре года, но на деле оказались неэмоциональными и чертовски затяжными. Иначе не скажешь.*

> *Нет, возможно в самом начале, будучи школьницей я и любила его той самой наивной детской любовью, когда говоришь метафорами, помышляешь о раннем замужестве и ссоришься из-за ерунды, впоследствии чего разыгрываешь настоящую трагедию. Естественно, всё это делается неосознанно, но участники таких вот мелодрам почему-то всегда уверены в собственной правоте и яро убеждены в том, что знают жизнь.*

> *Ну, а в итоге заблуждаются оба*.

> *Помню как тряслась из-за пустяков. По ним же и страдала, ревела. Сейчас мне трудно поверить в собственную причастность ко всем тем вещам. Ещё труднее осознать, что чувства вообще имели место быть… Думаю, так со всеми бывает.*

> *Что ж, тот период моей жизни (когда думаешь, что уже вовсю такой взрослый, а нихера подобного) можно описать всего одной фразой: типичная, подростковая, но зачем-то слишком затянувшаяся связь.*

> *На самом деле первые отношения редко бывают настоящими. Я имею в виду, что они едва ли связаны с любовью и, главное, тем, что она с собой несёт, так что счастлив тот, у кого вовремя не сложилось.*

> *Став старше, я поняла это, но по ряду причин (включавших в себя такие штуки как боязнь одиночества и чувство сострадания в сторону других людей) не могла просто взять и разорвать всё. Тот парень был, мягко говоря, нелюдимым. Делал покупки в полном молчании, а затем возвращался домой и красноречиво описывал в своём бложике пожелания мучительной смерти всем встреченным за день ребятам: от водителя автобуса до кассирши из супермаркета, но он не был плохим человеком. Он был никакущим.*

> *И я его не любила.*

> *Он тоже меня не любил, хотя не забывал ежедневно ломать комедию перед целым миром, (которому, правда, было глубоко насрать) показательно выставляя свои ко мне чувства, что выражалось, конечно же, только на словах. Ему нравилось делать вид, что он меня любит так же сильно, как нравилось притворяться словно у него уйма злостных врагов, тогда как на самом деле у него не было даже друзей.*

> *Несмотря ни на что, я всегда оставалась верной этому человеку. Даже в мыслях. Бог свидетель, я терпела многое и не единожды пыталась помочь его могзам встать на место, но силы мои иссякли, и сколько бы сопереживания во мне не было, так больше не могло продолжаться. Вдобавок ко всему вышесказанному и куче других подробностей, которые мне приводить не хочется не столько из-за экономии времени, сколько от нежелания вторично вникать во всё это, было здесь кое-что ещё.*

> *Пожалуй, самое главное. Я так опасалась одиночества, думала, что просто не смогу найти того, кто оказался бы лучше, но  с ним я не просто не чувствовала себя любимой – я в принципе не ощущала, что состою в каких бы то ни было отношениях, а в таком вопросе нет ничего хуже, чем быть с человеком, который заставляет тебя чувствовать себя одинокой.*

> *Итак, став старше и осознав это, я окончательно утвердилась в правильности мысли о том, что эти отношения давно себя исчерпали.*

> *Наш, с позволения сказать, разрыв состоялся незадолго до моего двадцатилетия и, по сути, вовсе не был разрывом как таковым. Общение в очередной раз сошло на «нет», и я просто отошла от привычной модели поведения, то есть не стала пытаться что-либо изменить. В общем, я отпраздновала свой двадцатый день рождения и поспешила убраться из и без того ненавистного города. Наскоро собрала вещи и успела прыгнуть в поезд ещё до того, как начала волноваться и, вопреки здравому смыслу, побежала к нему во зло себе самой.*

> *Я прекрасно помню своё первое утро во Львове. Снежное и спокойное. Тогда я ощущала небывалый прилив сил, вызванный ничем иным кроме как обретением долгожданной свободы. Помнила я это и вчера, ясно и отчетливо, за тем только исключением, что думала, будто описываемые мной события произошло не год, а от силы месяц назад. *   

> *Пожалуй, на сегодня достаточно предыстории.* 

> *Оба моих родителя родились весной, и если я ещё могла позволить себе обойти стороной именины отца, то мамины – ни за что на свете. Я никогда не пропускала дней её рождения и отнюдь не собиралась начинать. Указанной датой было третье марта. Я собиралась сесть в поезд первого, прибыть второго и вечером явиться с сюрпризом. Так и поступила. Выехала налегке, с одной только дорожной сумкой, что в размерах своих незначительно превосходит дамскую. Сошла с поёзда следующим днем и, прежде чем взять такси, (дом мой находился за городской чертой) решилась зайти ещё в одно место.*

> *Вероятно, во многом я просто желала убедиться, что он жив-здоров и пришёл в норму после нашего расставания, потому как, вопреки всем законам логики, где-то в глубине души я всё ещё чувствовала себя виноватой перед этим человеком… Себе же я сказала, что всего-навсего хочу забрать книги, которые он одалживал почитать, но никогда толком не возвращал (так что за минувшие годы их накопилось не менее двух десятков).*

> *То же сказала и ему, показавшись на пороге захудалой квартирки, которую арендовал мой бывший молодой человек. За всё время, проведенное вместе, я была здесь лишь раз – вот вам ещё один образец странности наших отношений. Всего раз за целых четыре, мать их, года! Обычно мы встречались в парках, кафешках и торговых центрах. Короче говоря, на нейтральной территории. И слава богу! Находиться в его жилище сделалось задачей не из легких. Представьте себе чердак заброшенного дома, куда лет эдак десять не проникал никто кроме смачно гадящих голубей. Представили? А теперь пустите туда пожить семейство наркозависимых бездомных, и в общих чертах картина готова.*

> *К слову, открывший мне дверь человек являл собой всё и сразу. Он выглядел и как наркозависимый бездомный, и как покинутый грязный чердак, и, в конце концов, как лоснящийся от жира и пота голубь, этот самый чердак оскверняющий.*

> *К тому же, он, кажись, температурил.* 

> *Мне было предложено войти. Делать этого совсем не хотелось, но проклятая вежливость взяла свое, и я перешагнула порог. Невольно подпрыгнула при хлопке закрывающейся за моей спиной двери, и тут же, с опозданием на четыре секунды, решила зачем-то добавить, что очень спешу.*

> *«Ты никуда не пойдешь, пока мы не поговорим!» – внезапно заявил он,*

> *(и это мне совсем не понравилось)*

> *а затем принялся запирать дверь на ключ,*

> *(это мне понравилось ещё меньше)*

> *а потом широко открыл рот и… проглотил тот самый ключ.*

> *(Это был пиздец.)*

> *Как и все героини историй с подобным началом, я повиновалась зову инстинкта, и сделала несколько молчаливых шагов назад. Батарейка моего сотового приказала долго жить ещё в поезде, (видимо, вот откуда однажды во мне появилось настойчивое желание приобрести не одну, а целых три переносных зарядки) соседей за стеной грязной квартирки давно не было, а единственным живым существом поблизости, как мне помнилось, числилась глухая бабка, живущая этажом ниже, о которой совсем не известно, жива ли она. *

> *Савелий, завидев моё поведение, принялся тараторить о том, что ничего мне не сделает. Никакого вреда, но разве не это обычно убийцы втолковывают своим жертвам? Я тихонько застонала и продолжила пятиться, размышляя, что делать дальше. В итоге, спина моя уткнулась в обшарпанную стену, а подходящих мыслей всё не было.*

> *Тогда меня, конечно же, обуял ужас и все его друзья, ведь, вдобавок ко всему, Савелий выглядел чертовски помешанным, (щит[^125], только сейчас поняла, что таки спалила его имя, но хер с ним, так тому и быть) но не стану лишний раз тянуть кота за яйца. Он не бил меня и не насиловал. Пальцем не тронул.*

[^125]: Shit (англ.) – дерьмо.

> *Савелий сделал кое-что гораздо хуже. Сам того не замышляя, (по крайней мере мне хотелось бы на это надеяться) он воплотил в жизнь куда более изощренный план мести…*

В этот момент новообращённую машинистку прервали. За стенами спальни раздался приглушенный топот, сопровождаемый сильными ударами, издаваемыми по всей видимости соприкосновением кулаков со внутренней стороной стены. Шум нарастал. Гремело так, словно коридорами несся не один человек, а целое стадо ошалелых Владиславов.

Мгновение спустя в комнату влетел белобрысый парнишка, ярко контрастирующий с тёмного цвета стенами, из которых он и явился. Как и при их первой (во время нынешнего визита в «Маятник») встрече, таинственный таксидермист застал Элеонору чутка растрепанной, в одной футболке возлежавшую на шёлковых простынях.

– Влад… – начала девушка.

Глаза её в изумлении расширились. 

– Быстрее! – воскликнул внезапный гость, в нетерпении размахивая руками.

Ошарашенная Нора отреагировала не сразу. В уголок её подсознания уже закралась тревожная мысль о том, что Владислава так просто из убежища не выманишь, разве что стряслась какая-то беда…

Но девушка ещё несколько секунд зачарованно разглядывала пришельца. Особое внимание нашей героини приковали большие и на редкость светлые глаза, окаймлённые такого же цвета ресницами.

– Скорее! – настаивал Владислав. – Давай за мной!

Его переполненный испуга голос привел девушку в чувства и мгновенье спустя оба уже неслись вверх по лестницам тёмных стенных коридоров.

## 93 {-#93}

Тем временем этажом выше медленно умирала Агата. Но делала она это духовно, угасала мнимой, как Остап Бендер[^126], смертью, отделавшись лишь несколькими царапинами, тогда как кое-каким предметам окружения мрачной дамочки посчастливилось куда меньше.

[^126]: Остап Бендер – персонаж книг Ильи Ильфа и Евгения Петрова, который был однозначно убит в конце «Двенадцати стульев», но необъяснимо продолжил жить на страницах «Золотого телёнка», следующей работы писателей.

Так перед глазами Элеоноры, ворвавшейся в покои подруги, предстали останки хрустального бокала и бархатный табурет, обезглавленный жестокой случайностью. Завершал картину треснувший надвое карниз, что ввиду преклонного возраста оказался слишком ветхим, а посему свершено непригодным для самоубийства.

Виновница торжества тёмным пятном растянулась на полу. Петля, уже кем-то заботливо ослабленная, по-прежнему обрамляла фарфоровую шейку. Агата лежала лицом вниз, и это напугало Нору больше всего остального, но, услышав топот друзей, хозяйка похоронного бюро, вероятно чересчур преданная своему делу, медленно подняла голову. Передние пряди волос хаотично устлали бледное лицо. Спешащая к подруге Нора вдруг замерла и мимо воли отпрянула, когда Агата приподнялась на локтях. Её волосы отхлынули, и взгляды девушек впервые встретились без стеклянной преграды.

Это были глаза поэта, с отчаяньем отшлифованные болью и глаукомой. Последняя всё же преуспела меньше и была всего лишь производным последствием первой. Нора как-то читала, что заболевание это получило своё название в честь лазурной воды, но пока ничего подобного на физиономии Агаты не проглядывалось. А было вот что: правый глаз девушки испещряла алая сетка лопнувших сосудов, не выдержавших злостной судьбы, повышенного давления и моря пролитых слёз; левый же (если не учитывать зрачка и карей радужки) и вовсе был красным, без видимых признаков уцелевшего белка.  

– Отдыхаешь? – поинтересовался Владислав.

Агате такой подход к сложившейся ситуации более чем пришелся по душе. Она попыталась рассмеяться, но вместо этого из горла чуть было не окочурившейся девушки вырвался лишь хриплый стон, скорее походящий на карканье какого-нибудь издыхающего ворона.

Этот жуткий звук вернул Нору к реальности. Она опустилась на колени рядом с подругой, пытаясь одновременно обнять несчастную и помочь ей встать на ноги.

– Мои очки… – попросила Агата пугающе потусторонним голосом.

Не видя теперь в этом особого смысла, Элеонора всё же протянула суициднице запрашиваемый предмет. За её спиной Ласло осмотрел место происшествия и, уверившись в том, что цель достигнута, с наивысшей степенью, увы, никем не замеченного артистизма скрылся в стене.

Девушке без особых усилий удалось поднять на ноги Агату. Ведя исхудавшую подругу к кровати, Элеонора ощутила вязкую влагу на собственных пальцах, но она не чувствовала боли, а потому тут же перевела взгляд на Агату. Вдоль запястья второй девушки хлестала кровь.

– Ты поранилась! – охнула Элеонора. – Здесь есть аптечка? 

– Пустяки, – просипела Агата. Вышло что-то вроде «ус…м…к».

– Что? – с быстротой медсестёр военного госпиталя Элеонора уже выдвигала ящики комода в поисках заветной коробки.

– Пустяки… По сравнению с тем… Что я собиралась… Сделать… – медленно и с придыханием объяснила мастерица похоронного дела, усаживаясь на незаправленную постель.

– Ну, об этом позже, – бросила Элеонора.

Аптечка нашлась под кроватью. Однако, внутри не оказалось ничего, хоть издали напоминавшего бинт. Сплошные седативные, транки и хорошо знакомые Норе психотропные.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Взмыленные постояльцы «Маятника» напрочь забыли о Геке. Его разбудил грохот, издаваемый падением Агаты, которое, в свою очередь, продлилось топотом Владислава. Наш герой поспешил наверх, но представший перед ним таксидермист строго-настрого запретил мальчику проникать в эпицентр внезапной суеты. Будучи личностью упрямой и чертовски изворотливой, Гек, всё же, озадачился появлением таинственного Владислава, да настолько, что так и не решился его ослушаться.

Какое-то время мальчик обиженно бродил по дому, разглядывая гробовые обивки и сокращая запас провианта до минимума, после чего занятие это ему наскучило и малец удалился, прихватив с собой бутылочку всё того же красного полусладкого.     

## 94 {-#94}

За неудавшимся самоубийством последовало новое утро. Туманное, голубое и очень красивое. 

Агата Рахманинова очнулась от глубокого, лишенного видений сна, когда стрелка старинных напольных часов приближалась к отметке с цифрой девять. Утонувшая в полумраке спальня оказалась чистой, без виденных признаков битого стекла, или карниза, погибшего в неравном бою с гравитацией. Руку ей забинтовали минувшим вечером, петлю с шеи сняли и, досыта накормив голопередоном, отправили в длительное плаванье по царству забвения.  

Дамочка не имела ни малейшего понятия, в котором часу она в последний раз принимала психотропное. Она с тоской взглянула на бутылку, хранившую в себе останки вчерашнего вина, но так и не отважилась её опустошить.

И оказалась права. Эффект от пилюль ещё не прошел полностью: пытаясь читать, Агата то и дело проваливалась в сон.

Нора показалась в начале одиннадцатого. Она принесла завтрак, к которому так никто и не притронулся, а также печатную машинку и старый дневник, над которыми принялась трудиться, то и дело одаривая подругу жалостливым взглядом.

– Ты прочитала? – наконец, не выдержала Агата.

Она задала этот вопрос рефлекторно, просто потому, что привыкла, и вовсе не ожидала положительного ответа, так что глаза хозяйки «Маятника» комично расширились, а лицо удивленно вытянулось, когда Элеонора произнесла:

– Прочитала.

Агата несколько раз моргнула, с недоверием воззрившись на собеседницу. На мгновенье она забыла и о своем разбитом сердце, и о широкой синей полоске, которая теперь обрамляла её тонкую шею, подобно уже успевшему всем надоесть чокеру. Словом, наша траурная дамочка оживилась.

– Серьёзно?

Элеонора спокойно кивнула.

– Ты *всё* прочла? – допытывалась Агата. 

– Всё.

По-прежнему не веря своим ушам, Агата приподнялась на локтях и в недоумении взглянула на подругу.

– Но почему ты всё ещё здесь? – тихо спросила она.

– Ну, как я могла уйти? – ласково произнесла девушка.

– Ты… Ты осталась из-за меня?

Элеонора отложила машинку. Её лицо осветила широкая улыбка.

– Конечно, я осталась из-за тебя. Как бы мне не хотелось вернуться в дурку… Нет, на самом деле мне совершенно туда не хочется, но я ни за что не стала бы оставлять тебя в таком состоянии. Я же уже не первый день вижу, что тебе становится только хуже, – она вздохнула и вновь улыбнулась. – Я не виню тебя за такую реакцию. Раньше я всегда уходила, узнав о собственном безумии. Вроде как жертвовала собой во благо других – так я, по крайней мере, думала. Но, как оказалось, я здесь не единственная, у кого проблемы с головой, так что нельзя и дальше думать только о себе. В конце концов, мне меньше всего хочется уходить от тебя.

– И от Молнии, – напомнила Агата.

– И от Молнии, – согласилась Нора, застенчиво закусывая нижнюю губу. – Знаешь, думаю, на этот раз у нас всё может сложиться…

– А если нет, у тебя всегда есть шанс начать с чистого листа, – прохрипела владелица похоронного бюро.

Воцарилось секундное молчание, ну а далее…

Обе девушка заливисто рассмеялись.

## 95 {-#95}

– Можно мне взглянуть? – спросила Агата.

Она указала на стопку отпечатанных страниц, лежавших около Элеоноры. Та согласилась без лишних раздумий, и дамочка в чёрном халате тут же углубилась в чтение небольшой истории. 

Здесь же, во избежание повторения, приводится только вторая часть записей Элеоноры.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

> *Он не бил меня и не насиловал. Пальцем не тронул.*

> *Савелий сделал кое-что гораздо хуже. Сам того не замышляя, (по крайней мере мне хотелось бы на это надеяться) он воплотил в жизнь куда более изощренный план мести…*

> *Роста в нём было где-то сто восемьдесят, хотя сам Савелий зачем-то любил говаривать, что там не меньше ста девяноста двух. Веса своего он наоборот не разглашал. В этом, в принципе, и так не было нужды. Мой бывший был необычайно тучным человеком,  а за три с лишним месяца, что мы не виделись, сделался ещё шире. Короче, спорить я с ним не собиралась и ни о каком побеге не помышляла. Закрытая дверь, девятый этаж.*

> *Квартира та была двухкомнатной. Он проводил меня в дальнюю спальню, а сам замер в дверном проёме, без преувеличений перекрывая собой путь к возможному отступлению. В совокупности с его потрепанным видом и проглоченным (!!!) ключом, забыть о котором было бы сложно, это не сулило ничего хорошего. Я опустилась на залитый бог знает чем диван,*

> *(постели на нем не было, но плешивый плед и лишенная наволочки подушка – с пятнами в тон диванных – свидетельствовали о том, что именно здесь спал мой бывший)*

> *и приготовилась к мучительно долгому разговору. Возможно, даже скандалу.*

> *Его не последовало.*

> *Как я уже сказала, Савелий меня и пальцем не тронул.* 

> *– Ты вообще когда-нибудь любила меня? – начал он.*

> *Я не поднимала глаз. Промямлила что-то о том, что всё слишком затянулось, мы были совсем детьми и только думали, что знаем друг друга, мол, я старалась понять его, но он никогда не шёл навстречу, что, кстати, так и было – это и ещё кучку невнятной чепухи.*

> *Савелий прервал меня на полуслове. Он ударил по дверному косяку так, что тот дал трещину, и повторил свой вопрос, на этот раз срываясь на поразительно высокий для его внешности крик.*

> *Я испугалась. Даже не так. В моей душе ожил первобытный страх. Перед глазами пронеслись все виденные раннее киноленты о маньяках. Я подумала, что должна подыграть. Солгать, чтобы успокоить его. Логично. Но затем я вспомнила, кто стоит передо мной. Человек, с которым я провела четыре года, за которого так волновалась, и о ком, наверное, когда-то так тосковала, чьи губы не раз целовала в покрытых сумерками парках… *

> *Подумала и сказала правду.*

> *Я сказала «нет».*

> *Савелий не ответил. Никогда. Я подняла голову, и увидела, что он тоже смотрит на меня. Глаза его расширились. Слово, которое, кажется, должно было начинаться на «с», застыло в горле. Он посмотрел куда-то сквозь невидимую пелену, сделал неуверенный полушаг в мою сторону и оглушительным громом рухнул лицом вниз.*

> *По природе своей я та ещё впечатлительная трусишка. Однако, в по-настоящему стрессовых ситуациях не начинаю орать, несясь сквозь пространство и время. Обычно, я просто впадаю в ступор.*

> *На этот раз реакция моя была всё той же. Мне понадобилась добрая четверть часа дабы сообразить, что нужно проверить его пульс. Тяжело дыша, я склонилась над распростертым на полу телом. Рука его всё ещё оставалась тёплой, но пульс отсутствовал.*

> *Как и дыхание.*

> *Я убедилась в том, что и так уже знала.*

> *Нужно было размышлять о том, как выбраться из помещения, но я беззвучно отползла от трупа. В голове как загнанные лошади бились безрадостные мысли. Меня одолевало чувство вины и отвращения, в равной степени смешавшихся. Страшило осознание того, что человек, такой же как и я по факту, просто взял и превратился в гору тухнущего мяса. Я имею в виду, он технически был разумным существом, вне зависимости от того, нравился мне его разум, или нет. *

> *А теперь стал мясом. Его могут жрать черви, крысы, каннибалы… Пройдет какое-то время, (совсем немного, учитывая силу отопления) и можно будет отрывать куски. Сознания-то в нём нет. <ins>Больше</ins> нет. *

> *Естественно, в итоге эти мысли свелись к тому, что рано или поздно так же будет и со мной. Со всеми, кого я люблю, и теми, кого едва знаю.*

> *«Не стану же я его есть!» – пронеслась истерическая мысль. Я разразилась чужим, холодящим кровь смехом. Это заставило меня разрыдаться. *

На этой неопределенной ноте запись обрывалась, но тут же начиналась следующая.

## 96 {-#96}

> *Прошлой осенью мне исполнилось двадцать два. Сейчас двадцать девятое января и я вновь сижу на кухне в «Маятнике», где меня по-прежнему отпаивают успокоительным. Всё по тем же причинам.*

> *Боюсь, эта запись будет совсем короткой, ибо рука моя дрожит, а под слипающиеся веки впору вставлять спички, как в тех старых диснейевских мультфильмах. В общем, дела у меня складываются не очень. Ну, а теперь о том, что повергло меня в это состояние.*

> *Сегодняшним вечером мне явился очередной из недостающих пазлов. Новый отрывок описанной выше истории.*

> *За проведённое во Львове время я перевидала уйму прощальных церемоний, но за ужином вдруг поняла, что никогда не обращала внимания на то, сколько человек обычно несут гроб. Не знаю, почему мои мысли вообще коснулись подобной темы, неужели мне было <ins>настолько</ins> скучно? Энивей,[^127] путём несложных логических умозаключений я пришла к выводу о том, что носильщиков должно быть парное количество, но сколько именно не помнила. Вот и спросила у той, кто не мог не знать ответ. Агата сказала, что при желании это могут быть и четыре человека, но обычно гроб несут шесть мужчин, ну, или восемь, если покойник оказался особенно крупных размеров.*

[^127]: Anyway (англ.) – в любом случае.

> *И тогда я вспомнила.*

> *Вскрытия не проводили. Мне это показалось как минимум странным, ведь 

> *А) Савелий просто упал замертво, без каких-либо предупреждений;*

> *Б) Я была в его квартире в тот самый момент и после, а брюшная полость покойного в итоге оказалась… Не хочу об этом думать;*

> *В) По украинским законам вскрытие обязательно даже для смертельно больных, стоявших на учёте у онколога.*

> *Короче, всё это было и остаётся необъяснимо непрофессиональным шагом со стороны полиции. Сложилось впечатление, что и патологам, и судмедэкспертам было попросту лень заниматься установлением причин смерти этого несчастного. Как было, так и запихнули в землю. Я нашла это ужасным, но не настолько, чтобы бить тревогу. Ужасов мне к тому времени уже хватало, хотя, как оказалось следующим днём, они и не собирались заканчиваться.*

> *Полиции, как и мне, по всей видимости, хотелось поскорей расправиться с этой историей.*

> *Хоронили Савелия в закрытом гробу. Вечером того же дня, которым его обнаружили. Но это едва ли помогло. Проститься с ним пришло человек двадцать. Все бывшие коллеги, которым происходящее, по-моему, было безразлично. Их пригнал большой босс, преданный идее team-building-а.*[^128]

[^128]: Team-building (с англ. team – команда, building – строительство) – сплочение рабочего коллектива. 

> *Похоронное бюро оказалось крохотным, а зал прощаний – так вообще стесняющим в размерах. Приходилось стоять слишком близко к гробу. Тот был закрыт, но запахи разложения всё равно умудрялись просочиться наружу. Священник, одетый по всем канонам современной церковной моды, держал в руках потрёпанный томик и бубнил что-то  своём, о вечном. Местами ему вторила юная бабонька, внешний вид который говорил о том, что она не первый год страдает ПГМ.[^129] На протяжении всего времени действия я трижды выходила проветриться, а, возвратившись, видела, что эти ребята и не думают заканчивать. *

[^129]: Православие головного мозга.

> *И вот, когда я в четвёртый раз намеревалась покинуть тесное помещение, в дверях возникло восемь молодых людей, одетых во всё чёрное, разумеется. Поднять гроб им удалось не с первой попытки, но, в конце концов, мужчины водрузили на плечи свою тягостную ношу и тут…*

> *Я увидела, как преобразились их лица. Отсутствующее выражение сменилось отвращением, к которому примешивалась просьба избежать происходящего. В ноздри носильщиков с новыми силами ударило трупное зловоние, ведь те находились совсем близко к его источнику. Я смотрела в глаза бедолагам и понимала их лучше, чем кто-либо другой, а они лишь продолжали идти, несмотря на запах, влекущий за собой тошноту, головокружение и страх перед тем днём, когда и они сами превратятся в нечто подобное.*

> *Думаю, в описываемый момент, я была не единственной, кто осознал, что предпочитает быть кремированным.*

Остаток страницы был пуст, а под конец записи почерк Элеоноры сделался столь размашистым, что читавшей всё это дело Агате не единожды пришлось прибегнуть к расшифровкам самого автора.

К облегчению нашей траурной героини, последующая запись выглядела куда аккуратней. По крайней мере, в начале.

> *Мне не так уж давно исполнилось двадцать три. Только до недавнего времени я думала, что двадцать.*

> *Зима близится к концу. Я лежу в своей постели, в «Маятнике». Закинулась всё теми же упомянутыми выше пилюлями. Прочитав предыдущую запись. Всё так же отказываюсь принимать психотрпные, чтобы иметь возможность её продолжить. Должно быть, это удобно: львиная доля моей истории уже записана, а я даже не помню, как это делала.*

> *Энивей, я чувствую себя так, будто описываемые события произошли совсем на днях, так что могу продолжить. Воспоминания о тех днях подобно раковой опухоли засели в моем мозгу.*

> *Первое время я боялась… Просто не могла заставить себя перешагнуть его… Его тело. Подтянув к подбородку колени, я сидела на заляпанном диване. То роняла в отчаянье голову, то разглядывала распластавшегося на ковре мужчину.*

> *Савелий свалился параллельно дверному проёму. В какой-то мере мне даже повезло: – если подобное слово может быть применимо в такой ситуации – часть его головы скрывалась под антресолью, так что лица совсем не было видно. Как я уже говорила, при жизни Савелий был неимоверно толстым человеком, и смерть ничего не изменила, посему вскоре я столкнулась с вполне ожидаемой проблемой. Я подступалась со всех сторон и, хотя рост мой довольно сложно назвать маленьким, перешагнуть покойника никак не выходило. Во время очередной попытки голова моя закружилась от страха, что ни на мгновенье не ослаблял своих оков, и тошнотворного запаха, которые уже вовсю начинали источать исходившие от трупа испарения. Это значило, что прошло много времени. Гораздо больше, чем мне казалось. Я едва не упала, балансируя на одной ноге, но в последний момент рука моя успела опереться о шкаф, и я устояла на ногах.*

> *Само собой разумеется, я кричала. Не от ужаса, но желания позвать на помощь. Вопила что было мочи, барабанила по батарее и избивала стены.*

> *Безрезультатно.*

> *Думать о нём как о теле – гниющей груде мяса – всё ещё было сложно. Не знаю, как долго я пробыла в той комнате, всё происходило как во сне, но, видимо, я провела там немало времени, потому как с каждым моим вдохом трупные испарения становились всё яростней. Я перерыла всю комнату в поисках ключа, или мобильника – чего угодно, что могло бы пригодиться.*

> *Нихера.*

> *Запасной ключ. Он должен был где-нибудь быть. Я попыталась набраться сил. Силы никак не приходили, но ждать с моря погоды ещё дольше виделось мне бессмысленным, и, превозмогая рвотные порывы, я наступила на тело. Рассчитывала, что оно будет твёрдым, однако трупное окоченение уже отступило. Почва под моей ногой оказалась дряблой и какой-то липкой. Отвратительно, неестественно мягкой. Новый ком ужаса подобрался к моему горлу, и, неистово взмахнув руками, я вновь забалансировала на одной ноге. В итоге, всё равно упала лицом вниз, и теперь лежала в той же позе, что и покойник.*

> *Я обшарила каждый уголок пыльной квартирки. Где-нибудь непременно должен был найтись второй ключ. Но его не было. Нигде.*

> *Как и стационарного телефона. Его так вообще никогда и в помине здесь не устанавливали. За интернет хозяин квартиры также давненько не платил, посему от компьютера не было никакого толку. Я зажгла во всех комнатах свет и тщетно пыталась распахнуть окна. Старые деревянные ублюдки оказались наглухо заклеенными на зиму.*

> *Изголодавшись по свежему воздуху, я схватила первый угодивший под руку предмет, (им оказался доисторический стул) и яростно молотила по кухонному окну до тех пор, пока практически всё стекло не оказалось у моих ног. То же я проделала и с другими окнами. Швыряла в них всё подряд, выкрикивая ругательства и мольбы о помощи, в ответ на которые какой-то старый скряга, наконец, пригрозил вызвать полицию.*

> *Однако, за окнами сгущалась ночь, а стражей порядка так никто и не потревожил. Думаю, район, в котором находилось вышеупомянутое жилище, слыл слишком неблагополучным, чтобы хоть кто-нибудь обратил внимание на одинокие крики и мебель, галантно выбрасываемую из окон.*

> *Несмотря на разбитые стекла, здесь по-прежнему царила духота. Дышать было трудно. Стоявший в помещении дурман не раз вынуждал мой желудок опорожниться. Котелок вскипал от боли, а я всё думала и думала, но оставим позади глупые россказни о смельчаках, что в таких ситуациях сплетают тросы из штор и простыней, чтобы выбросить из окна и спуститься по ним на волю.*

> *Выход был только один. Я знала так с самого начала. Потому так испугалась. Знала, что Савелий был слишком ленив и неосмотрителен, чтобы иметь проклятый запасной ключ.*

> *«Иголка в яйце, яйцо в утке, утка в зайце, заяц где-то там ещё…» – бездумно прошептала я, подбирая на кухне наименее тупой нож».*

## 97 {-#97}

– Как много деталей, – произнесла Агата. – Транки сделали тебя поразительно хладнокровной. 

– Да прекрати, – отмахнулась Нора так, словно ей отвесили комплимент.

– Нет, я серьёзно, – владелица похоронного бюро ткнула ногтем в открытую страницу старого блокнота, оставляя в ней вмятину. – Это – достойное чтиво. Ты не знаешь прозекторского дела и об анатомии, видно, располагаешь лишь общими сведеньями… Словом, ты не штудировала учебников, дабы это написать. Ты сама свой учебник, и от этого написанное становится реальным.

– Потому что это и впрямь реально.

– Для тебя – да. А теперь становится реальным и для читателя.

Нора задумалась. Неужто Агата вела к тому, что даже сложившаяся ситуация имеет положительные стороны. Не очень-то похоже на Агату. Особенно сегодняшнюю. Но, в конце концов, разве не этого она – Нора – так долго жаждала: писать достойные вещи?

– Не вижу ничего о твоём доме, – заметила тем временем Агата, листая блокнот. – Почему? Ты не вспомнила?

– Я вспомнила, – отозвалась девушка. – Но только вчера. – Она указала на стопку отпечатанных листов. – Всё здесь.

– И что там?

– Все сгорело. Когда я, наконец, сбежала с похорон и добралась до дома, всё сгорело, – она помолчала, а затем с горечью добавила. – И все сгорели.

– Хорошо…

– Хорошо?

– Хорошо, что ты это вспомнила, – объяснила Агата.

– Жаль, я не могу быть в этом столь уверенна.

Пауза.

– Давай сюда продолжение.  

## 98 {-#98}

– Ну, а теперь касательно тебя, – уверенно начала Нора.

Агата к тому моменту уже покончила с чтением старого дневника подруги и его отпечатанной версии. Особого впечатления на неё записи не произвели: Агата и без того предполагала что-то подобное, хотя тем, как излагались события, дамочка не могла не гордиться. Дневник, безусловно, прояснял многое, но, расправившись с ним, владелица похоронного бюро вновь раскисла. Она откинулась назад и теперь безмолвно лежала, зарывшись лицом в подушки, и, если бы Элеонора заботливо поинтересовалась, что ей принести, Агата непременно заказала бы новую жизнь.

Но Нора сказала вовсе не это.

– Эй ты, страдалица! – позвала девушка. – Подними-ка свою тощую задницу и откушай немного чаю!

Не привыкшая к такому обращению Агата медленно поднялась и с тоской посмотрела на подругу своими измученными глазами. Довольная произведенным эффектом Нора продолжила излагать речь.

– Мне понятны твои чувства, – девушка взяла подругу за руку. – Больше чем ты думаешь. 

Агата приоткрыла рот, но так ничего и не сказала.

– У тебя случаются периоды эмоциональных срывов, – говорила Нора. – У нас обеих. По понятным причинам. Я не виню тебя, не приуменьшаю твоей боли, но Агата… – она помолчала, размеренно взвешивая слова. – В такие моменты, правильно говорят, ты должна вспоминать счастливые моменты. Я имею в виду, общие…

Агата в нетерпении махнула рукой.

– У меня больше нет счастливых воспоминаний. Когда он ушёл…

– Смерть не отменяет того, что он сделал при жизни, – ласково заметила Нора.

– Я не сказала «умер». Я сказала «ушел», – мрачно объяснила хозяйка похоронного бюро. – Он ушел от меня за несколько недель до собственной смерти. Так вот, он ушёл, и это стерло все счастливые воспоминания. Ты понимаешь?

Элеонора кивнула.

– Думаю, да.

Воцарилось молчание.

– Но почему? – наконец, решилась Нора. – Мне думалось, вы были счастливы.

– Мне тоже так думалось. Я уж точно была, да и он, наверное, какое-то время. По крайней мере, мне бы очень хотелось думать, что был.

– Тогда почему он ушёл?

Агата не стала спешить с ответом. Она отпила успевшего остыть чаю, подкурила сигарету и только потом заговорила.

– Что ж, версий оказалось много. Адам был личностью… М-м-м, переменчивой, и каждый раз менял свой ответ. Он говорил банальную ерунду, вроде той, что обычно вскармливают пустоголовым девицам, мол, у нас разные цели в жизни, все дела. Говорил, что ушёл из-за того, что я не хочу детей и потому, что я слишком мрачная. Хотя ничего из этого, как бы, не было новостью, а последним я так вообще стала из-за него. Ещё он говорил, что я слишком сильно выражала свои чувства, а затем что он бросил меня, потому как боялся, что в один прекрасный день попросту мне изменит… – она тяжело вздохнула. – Короче, он одарил меня кучей безобразной чепухи, но, знаешь, кое-что из его слов всё-таки было правдой.

Элеонора вопросительно воззрилась на подругу.

– Он сказал, что никогда не любил меня, – просто сказала Агата.

## 99 {-#99}

Солнце садилось и поднималось над кладбищем, а заставить Агату Рахманинову встать на ноги всё никак не представлялось возможным. Новообращенная самоубийца продолжала отказываться от завтраков и даже вина, которые Элеонора настойчиво носила в спальню подруги.

Очередной раз с подносом в руках пересекая коридор третьего этажа, Элеонора машинально рассматривала украшающие его стены картины. Они не были авторства Агаты, но всё же вряд ли принадлежали предыдущему владельцу похоронного бюро. 

Хотя… Как знать, думала девушка.

Она без стука проникла в укрытые мраком покои, и с порога заявила:

– Ты и впрямь слишком мрачная!

Ответом ей была лишь тишина.

Девушка зажгла свет, желая убедиться, что её траурная подруга не успела покончить с собой за те четыре часа, что они не виделись. Удостоверившись, что Агата на месте, наша героиня завела старую волынку.

– Взгляни на все это, – Нора обвела рукой комнату. – Круг твоих интересов сводится к смерти во всех её проявлениях.

– К чему ты ведешь? – безрадостно спросила Агата, чей тон как бы подтверждал произнесенное Элеонорой утверждение.

– Помнишь классический разбор произведения?

– Какой к чёрту разбор? – переспросила Агата, падая обратно на подушки. – Женщина, дай мне умереть спокойно.

– Нет, не дам, – чуть ли не кокетливо возразила Нора, и тут же продолжила свою тираду. – Я говорю об обычном разборе произведения. Такой тысячу раз расставляют делать в школке. Ну, знаешь, там цель, тема, объект, субъект, что всем этим хотел сказать автор…

– Ну?

– Вчера я сортировала скопившиеся в ящике письма. Кстати, для тебя там ещё штуки три от товарища Овсянникова. Так вот, сортировала я письма, – говорила девушка, – и забавы ради решила разобрать наши собственные жизни по этому самому плану.

– Это ещё зачем? – Агата презрительно хмыкнула.

– Говорят же тебе: забавы ради. Люблю, знаешь ли, поиграть в филологическую деву.

Сие заявление осталось без ответа.

И слава богу.

– Энивей, в итоге я добралась до скрытых образов, и, знаешь, что поняла?   

– Удиви меня, – бросила Агата в манере, говорившей о том, что её уже едва ли что может удивить.

– Все очень просто, – ответила Нора, которая, кажется, не уловила сарказма в тоне собеседницы. – Я поняла, что «Маятник», со всем свои темным величием – это образ горя, тоски и печали, которые, подобно старому зданию, нерушимо возвышаются над жизнями мрачных героев. Моей, твоей и даже Владислава.

– Матерь божья, – зевнула Агата. – Вот так и напишешь в своей книге. А потом добавишь: услышав это слова, героиня номер два зевнула и отвернулась к стене.

И она отвернулась к стене.

– Нет, я не шучу, – настаивала Нора, а затем сыграла запретной картой. – Вспомни, чего ты хотела до встречи с Адамом?

Агата села на кровати. Впервые за долгое-долгое время на лице дамочки отразилась неуверенность.

– Присмотрись, – не сдавалась Нора. – Бюро – не просто символ смерти. Для тебя это ещё и образ скорби по человеку, который не просто ушёл, а ещё и позволил себе заявить, что, несмотря на твои глубокие чувства, никогда не любил тебя. Этим он забрал последнее, разве ты не видишь? Игра не стоит свеч, моя дорогая.

Агата молчала, тогда как глаза её делались всё более печальными.

– Так чего ты хотела до встречи с ним? – повторила свой вопрос Нора.

– Мне было всего девятнадцать…

– Ну, а сейчас тебе всего двадцать пять.

Вновь никакого ответа.

– Как бы там ни было, – подытожила Нора, – не думаю, что ты хотела всего этого. Оглянись! Тебя сплошь и рядом окружает смерть. Ты знаешь это, но продолжаешь лелеять её как Владислав свою социофобию. Твоя работа, книги, картины, даже твой внешний вид – всё пропитано духом смерти!   

– Не правда, – сонно возразила Агата. – У меня полно пейзажей!

– Это пейзажи *кладбищ*, – напомнила Нора и, вопреки протестам собеседницы, раздвинула шторы, карниз для которых уже успели заменить.

Та закатила глаза. Учитывая их плачевное состояние, зрелище вышло воистину жутким.

Пытаясь не выдать охватившей её к этому жесту неприязни, Элеонора перебирала в голове всё картины, имеющиеся в «Маятнике», ну, или, вернее, их большую часть – ту, что смогла вспомнить.

– Хотя, всё же есть одна… – припомнила Нора. – Висит в самом конце твоего коридора. У двери в гостиную. 

– Да?

– На ней нет ни кладбищ, ни мертвых людей. Что это? – спросила Нора, протягивая подруге стопку конвертов.

Агата взяла её и без особого интереса изучала письма, пока не добралась до последнего. При взгляде на небольших размеров бумажку глаза владелицы похоронного бюро удивленно расширились.

– Thorsmörk. 

– По-русски, если не затруднит.

– Исландия, – зачарованно ответила Агата.

Тут-то всё и решилось. 

## 100 {-#100}

Близился полдень восемнадцатого мая. 

Агата обосновалась прямиком перед входом во дворик бюро ритуальных услуг, в котором провела последние пять с лишним лет. Она сидела на одном из безымянных надгробий, зажав между пальцев сигарету и изредка затягиваясь. Несмотря на стремительно приближавшееся лето, в воздухе ещё витала приятная свежесть, оставшаяся после ночного дождя. Термометр показывал всего семнадцать градусов тепла – любимая погода нашей траурной героини.

Слегка опустив очки, она взглянула на здание, возвышающееся впереди, среди тонких ветвей и старых памятников. Многие из последних были настолько прекрасны, что Агате не составляло труда вообразить каждое из них, закрыв глаза: (пара примеров). Сквозь покрытые листвой деревья то тут то там пробивались жаркие лучи солнца, а трава к тому времени уже полностью позеленела, что не просто завершало картину – делало её идеальной.

Затянувшись, Агата медленно выдохнула табачный дым и ещё какое-то время наблюдала за тем, как он растворяется в пастельных красках поздней весны. Сейчас ей определенно нравилось это время года, гораздо больше обычного. Хотя бы потому, что товарищ Овсянников больше не донимал обитателей «Маятника» своими письменами.

Вскоре Агата услышала за спиной шаги, слегка приглушенные мокрой травой, но не стала оборачиваться, прекрасно зная, кто стоит позади.

– Пора, – сказала Элеонора, ненавязчиво касаясь плеча подруги.

– Ещё один момент, – отозвалась та.

Ленивым, но вполне уверенным движением, Агата стянула с лица солнцезащитные очки, к которым уже давно успела более чем привыкнуть, после чего швырнула их на землю и раздавила одним из своих тяжелых ботинок. Сделав это, она почувствовала нарастающую тревогу, но вместе с тем теплом расплывающееся по телу спокойствие, о котором так много слышала за последние дни.

Наконец обернувшись, Агата встретилась с удивленным взглядом зелёных глаз.

– Говорят, надо начинать с мелочей, – с намеком на веселье в голосе произнесла бывшая владелица похоронного бюро, и зеленые глаза улыбнулась.

Агата тоже улыбнулась краем губ. В её голове вдруг заиграл задорный мотивчик, о котором она не вспоминала на протяжении пары лет.

– Такое чувство… – начала Нора, но затормозила, пытаясь правильно подобрать слова. – Чувствуется словно…

– Чувствуется, словно начало новой эры, – закончила Агата.

Элеонора удовлетворительно кивнула. В мыслях девушки, как оказалось, играла та же что и у подруги же песня. 

А потом началось.

<p style="margin-top: 2em; margin-bottom: 2em"> &ast; </p>

Владислав притаился за широким каменным постаментом в виде почившего льва, опрометчиво надеясь остаться незамеченным. Всё бы ничего, но и без того высокий юноша периодически выглядывал из-за надгробия. Он наблюдал за девушками. Обнявшись, те стояли в нескольких метрах от «Маятника».

Агата сказала что-то о наступлении новой эры. Несмотря на теплую погоду, от этих слов по телу Владислава скользнул приятный холодок. Бывшие обитатели похоронного бюро – все трое – мысленно напевали одну и ту же песню, даже не догадываясь об этом.

Тем временем Элеонора махнула рукой – подала знак рабочим, нанятым товарищем Овсянниковым, чей богатый клиент накануне дал дуба.

«Feels like… Feels like it’s coming…»[^130] – пронеслось в голове Ласло.

[^130]: Текст песни группы Foster the People под названием Coming of Age: чувствуется, словно это наступает… 

Словно в такт этим обнадеживающим строкам, подъёмный кран, все утро дожидающийся своей очереди выйти на сцену, загудел, поднимая в воздух чугунный дробильный шар. Подобно маятнику, тот заколебался в пространстве и принялся ходить по кругу, набирая обороты, а затем нанёс сокрушительный удар по тёмному кирпичу бюро ритуальных услуг. Как ни странно, первой комнатой, одержавшей поражение, стали закрытые апартаменты. 

За этим ударом последовал ещё один, и вот с лица Земли исчезла гостиная Агаты Рахманиновой, которая по-прежнему думала о себе исключительно как о владелице похоронного дома, но уже начинала осознавать, что вскоре таким мыслям придётся покинуть её сознание, вне зависимости от того, хочется ей этого, или нет.

А ей, кажется, очень хотелось.

– Feels like… feels like it’s coming, – пропела дамочка в черной шляпе. – It feels like… It’s like a coming of age.[^131]

[^131]: Чувствуется, словно это начало новой эры. 
















